# N103 アマゾネスの部族（Amazon）画像データ。登場人物は全員20歳以上。女性のみ（女装なし）。全員褐色の肌・引き締まった長身（筋肉は描かない）。
# 挿入はシャマラの木彫りの張り型（豊穣の張り型）だけ。戦化粧は洗えば落ちる顔料の線（刺青・傷ではない）。
ST = {"pen": "strapon"}      # シャマラの黒檀色の木彫りの張り型（赤い革の腰帯）
PAINT = "red clay and white ash paint lines drawn on his chest"
NEG_AMA = "muscular female, abs, six pack, tattoo, scar, bodybuilder"

DATA = {
 "code": "Amazon",
 "world": "tribal village of amazon warrior women deep in a southern jungle, thatched huts, bonfire, hanging vines, tropical plants, warm light, detailed background",
 "bg": "amazon village plaza in the jungle at dusk, big crackling bonfire in a circle of logs, thatched huts, leopard fur rugs, hanging vines, torches, drum tower silhouette, tropical trees",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "オルテア",
         "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, tall, long legs, toned slender body, dark-skinned female, tan skin, red hair, very long braided hair, gold eyes, leopard fur bikini top, leopard fur loincloth, gold armlets, gold bracelets, amazon chieftain, huge breasts, confident grin",
         "name": "the red-braided amazon chieftain in a leopard fur top",
         "pose": "standing with hands on her hips, hearty wide grin, looking down at viewer",
         "neg": NEG_AMA},
   "e1": {"type": "woman", "jp": "ネレア",
          "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, long legs, slender toned body, dark-skinned female, tan skin, black hair, high ponytail, feather hair ornament, green eyes, brown leather chest wrap, leather loincloth, bow and quiver, amazon huntress, large breasts, quiet expression",
          "name": "the black-ponytailed huntress with a feather ornament",
          "pose": "holding a bow at her side, finger to her lips, quiet half-lidded look, looking at viewer",
          "neg": NEG_AMA},
   "e2": {"type": "woman", "jp": "ウルア",
          "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, long legs, dark-skinned female, tan skin, purple hair, long single braid, amber eyes, cream cloth chest wrap, patterned wrap skirt, holding a soft grass brush, small pot of red pigment, amazon body painter, large breasts, gentle smile",
          "name": "the purple-braided body painter with a grass brush",
          "pose": "holding a soft brush and a pigment pot, gentle droopy-eyed smile, looking at viewer",
          "neg": NEG_AMA},
   "e3": {"type": "woman", "jp": "ティカ",
          "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, toned slender body, dark-skinned female, tan skin, orange hair, short hair, brown eyes, leather sports chest wrap, short leather loincloth, anklets with small bells, amazon warrior, large breasts, energetic grin",
          "name": "the orange-haired amazon wrestler with bell anklets",
          "pose": "crouching forward ready to pounce, arms open, energetic grin, looking at viewer",
          "neg": NEG_AMA},
   "boss": {"strap": "carved ebony wooden strap-on on a red leather belt", "type": "woman", "jp": "シャマラ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, tall, long legs, dark-skinned female, tan skin, white hair, very long hair, feather headdress, crimson eyes, red ceremonial robe with open sides, bead necklaces, amazon priestess, huge breasts, mysterious smile",
            "name": "the white-haired amazon priestess in a red ceremonial robe",
            "pose": "holding a smoking stone dish of herbs, exhaling a thin sweet smoke, mysterious half-lidded smile, looking at viewer",
            "neg": NEG_AMA},
 },
 "places": {
   "hiroba": "village plaza at night, crackling bonfire, leopard fur rug before the fire, circle of log seats, smoke, torches",
   "tent": "chieftain's great tent, leopard fur rugs, golden bowls, tallow lamps, drum-shaped shadows on the cloth walls",
   "road": "jungle trade path, damp moss and earth, hanging vines, dappled sunlight through huge leaves",
   "watch": "wooden lookout platform high in a great tree, plank floor, rustling leaves, hide mat",
   "paint": "body painter's hut, shelves of clay pigment pots in red white and black, bowls of herb oil, grass brushes, water basin",
   "ring": "wrestling training ground, ring of trampled earth, hay strewn on the ground, wooden fence, jungle around",
   "altar": "smoky cave altar, stone dish burning herbs, sweet drifting smoke, carved wooden spirit statue, flower offerings, candle glow",
   "falls": "jungle waterfall pool, cold spray, wet black rocks, ferns, roaring water",
   "wedding": "wedding tent, bed of flower petals, jars of mead, hanging bell ornaments, warm lamp light, flower garlands",
   "furs": "fur drying yard in the sun, rows of hanging animal furs, soft fur piles on the ground, wooden racks",
   "drum": "drum tower on a thatched roof at sunset, huge wooden drum, orange sky over the jungle",
   "store": "fruit storehouse, piles of ripe tropical fruit, cool earthen walls, baskets, dim light",
   "bridge": "foot of a vine rope bridge over a deep valley, creaking wooden planks, wind, mossy stones",
   "spring": "jungle spring at night, moonlight on the water, fireflies, smooth flat rocks, ferns",
 },
 "atk": {
   "m1": ("ring", "he lies on his back pinned in the hay, the tall chieftain kneels over him holding his wrists, her knee pressing and rolling his penis, grinning down, his legs twitching", ),
   "m2": ("tent", "the tall chieftain lifts him off his feet in a tight hug, his face buried in her cleavage, his legs dangling, her hand stroking his back, rocking him, " + PAINT),
   "m3": ("wedding", "the tall chieftain holds him up in her arms and kisses him deeply, tongues, saliva trail, her thumbs rubbing both his nipples, flower petals around, blush"),
   "e1": ("road", "he lies on the moss, the huntress lies behind him with her lips at his ear, whispering and licking inside his ear, her finger to her own lips, his back arched, trembling"),
   "e2": ("paint", "he sits on a low stool, the body painter kneels before him drawing red circles around his nipple with a soft grass brush, the brush tip touching his nipple, pigment pot in her hand, trembling"),
   "e3": ("ring", "the amazon wrestler pins him down in the hay and squeezes his face between her breasts, shaking them side to side, her legs locked around his, bell anklets, his arms flailing weakly"),
   "boss": ("altar", "he kneels in the sweet smoke, the priestess cups his chin and exhales thick herb smoke into his open mouth, pinching his nipple with her other hand, hazy smoke around them, drool"),
 },
 "atk_desc": {
   "m1": "the chieftain wins the contest of strength by pinning him under her knee.",
   "m2": "the chieftain lifts him up and locks him in her embrace.",
   "m3": "the chieftain performs the wedding kiss while toying with his nipples.",
   "e1": "the huntress stalks his ear with whispers.",
   "e2": "the body painter draws war paint circles around his nipple.",
   "e3": "the wrestler pins him and smothers him between her breasts.",
   "boss": "the priestess breathes spirit smoke into his mouth.",
 },
 "lose": {
   # オルテア 技1（力比べ＋抱擁）
   "btl_m1":     ("ring", "he lies on his back in the hay at the center of the ring, the tall chieftain kneels beside him painting a red line on the center of his chest with her finger, her knee resting on his crotch, cum on his belly, " + PAINT),
   "onani_m1":   ("hiroba", "sitting alone by the bonfire wrapped tightly in a blanket, the blanket squeezed between his knees, a heavy cushion on his chest, fingers rubbing his own nipple, penis untouched, the chieftain watches from beyond the fire"),
   "inochi_m1":  ("bridge", "he lies on his back at the foot of the rope bridge, the tall chieftain kneels over him pressing and rolling his penis with her knee, holding his wrists above his head, grinning, cum splashing, " + PAINT),
   "onedari_m1": ("tent", "he lies on the leopard fur rug with arms opened in surrender, the tall chieftain kneels over him, her knee rolling his penis, her hand pinching his nipple, laughing, cum on his belly, " + PAINT),
   # オルテア 技2（族長の抱擁）
   "btl_m2":     ("tent", "the tall chieftain holds him up in her arms, his face buried deep in her cleavage, his legs dangling, her hand stroking his back, her breasts rubbing his nipples, cum dripping down his thighs, " + PAINT),
   "onani_m2":   ("furs", "lying alone on his back in the sunny fur yard, a heavy fur pile pressing down on his chest, his fingers under the fur rubbing his own nipples, penis untouched, the chieftain watches from between the hanging furs"),
   "inochi_m2":  ("spring", "sitting in the chieftain's lap by the moonlit spring, wrapped in her arms against her warm chest, the chieftain strokes his nipple and whispers in his ear, wet skin, fireflies, cum on his thighs"),
   "onedari_m2": ("wedding", "he lies on the petal bed held tight in the chieftain's arms, his face in her cleavage, the chieftain rocks him to sleep, stroking his hair, his body limp and melting, cum on the petals"),
   # オルテア 技3（婚礼の儀＝口づけ＋乳首）
   "btl_m3":     ("wedding", "the tall chieftain holds him up in her arms and kisses him deeply, tongues, saliva trail, pinching both his nipples, his legs dangling, cum dripping onto the petal bed, " + PAINT),
   "onani_m3":   ("hiroba", "sitting alone by the bonfire wrapped in a blanket, sucking two of his own fingers as if kissing, the other hand rubbing his own nipple, penis untouched, the chieftain watches from beyond the fire"),
   "inochi_m3":  ("drum", "on the drum tower at sunset, the tall chieftain lifts him in her arms and kisses him deeply, tongues, pinching his nipple, the huge drum behind them, his legs dangling, cum dripping, " + PAINT),
   "onedari_m3": ("tent", "the tall chieftain holds him in her lap on the leopard fur and kisses him deeply, saliva trail, rolling both his nipples between her fingers, his arms around her neck, cum on his belly"),
   # ネレア（狩りの囁き／弓を引く手で）
   "btl_e1":     ("road", "he lies on the moss on his side, the huntress lies behind him whispering into his ear with her lips at his earlobe, her archer's fingers stroking his penis, cum splashing on the moss, " + PAINT),
   "onani_e1":   ("watch", "lying alone curled on the hide mat of the dark lookout platform, holding his breath, fingertips tracing behind his own ear toward the ear hole, trembling, penis untouched, the huntress watches from a branch far away"),
   "inochi_e1":  ("store", "he sits against baskets of ripe fruit in the dim storehouse, the huntress leans behind him licking his ear, her archer's fingers stroking his penis, a feather ornament tied to his ankle, cum dripping"),
   "onedari_e1": ("spring", "he lies on a flat rock by the moonlit spring, the huntress lies beside him with her lips against his ear, whispering, her finger on her own lips, fireflies, his back arched, cum on his belly"),
   # ウルア（戦化粧の筆／顔料を塗り広げる）
   "btl_e2":     ("paint", "he lies on a mat in the painter's hut, the body painter leans over him licking a dried red line on his chest, her soft brush circling his nipple, her pigment-wet breasts pressed on his side, cum on his belly, " + PAINT),
   "onani_e2":   ("hiroba", "sitting alone in the shadow of the bonfire, drawing lines around his own nipple with a soft grass brush, tip of the brush on his nipple, trembling, penis untouched, the body painter watches from the circle of log seats"),
   "inochi_e2":  ("falls", "he sits on a wet rock by the waterfall pool, the body painter kneels before him drawing red lines on his wet chest with a brush, her pigment-covered breasts pressed against him, spray, cum on the rock"),
   "onedari_e2": ("paint", "he sits on a low stool with his chest thrust out, the body painter kneels before him painting a red line onto his nipple with the brush tip, pots of red white and black pigment beside her, cum dripping, " + PAINT),
   # ティカ（組み打ち／足を絡めて）
   "btl_e3":     ("ring", "the amazon wrestler pins him face-up in the hay, his face squeezed between her breasts, her bare sole with bell anklets rubbing his penis, his arms limp, cum on her foot, " + PAINT),
   "onani_e3":   ("furs", "lying alone face down on a fur pile with his face buried in a cushion, a heavy rolled fur on his back, one hand under his chest rubbing his nipple, penis untouched, the amazon wrestler watches from the fur racks"),
   "inochi_e3":  ("bridge", "at the foot of the rope bridge, the amazon wrestler sits on his chest pinning him, his face squeezed between her breasts, her legs wrapped around his, bell anklets, his hands limp, cum on his belly"),
   "onedari_e3": ("tent", "in a corner of the great tent, he lies asleep buried face-first in the amazon wrestler's breasts, the wrestler hugs him tight with her legs locked around his, happy grin, cum on the fur bedding"),
   # シャマラ（精霊の煙／豊穣の張り型）
   "btl_boss":   ("altar", "from side, he lies on his back on the altar furs with legs lifted, the priestess kneels between his legs pegging his anus with a carved dark wooden strap-on on a red leather belt, anal, exhaling smoke onto his face, pinching his nipple, his own penis separate, cum on his chest", ST),
   "onani_boss": ("hiroba", "kneeling alone before the bonfire, a bundle of herbs burning, inhaling deep sweet smoke, pinching both his own nipples as he exhales, penis untouched, the priestess watches from beyond the smoke"),
   "inochi_boss":("spring", "from side, he lies on his back on a flat rock by the moonlit spring holding his knees, the priestess pegging his anus with her carved wooden strap-on, anal, blowing smoke onto his lips, his own penis separate, fireflies, cum on his belly", ST),
   "onedari_boss":("altar", "from side, he lies on his back in the drifting smoke with legs spread, the priestess over him pegging his anus with her carved wooden strap-on, anal, kissing smoke into his mouth, pinching his nipple, his own penis separate, a flower necklace on his chest", ST),
 },
 "lose_desc": "takes him as the husband of the tribe, with war paint lines redrawn every morning.",
 "onanie": {
   "master": ("tent", "wrapped tightly in a fur blanket on the rug, a heavy cushion on his chest, fingers rubbing his own nipples, penis untouched"),
   "e1": ("watch", "curled up on the hide mat in the dark, fingertips creeping from behind his own ear into the ear hole, penis untouched"),
   "e2": ("paint", "sitting on a stool, drawing circles around his own nipple with a soft grass brush, penis untouched"),
   "e3": ("furs", "lying face down with his face buried in a cushion, a heavy rolled fur on his back, rubbing his own chest, penis untouched"),
   "boss": ("altar", "kneeling before the burning herb dish, inhaling the sweet smoke, pinching his own nipples, hazy look, penis untouched"),
 },
 "magic": {
   "1": ("m", "drum", "the chieftain beats the huge war drum with both fists, hair flying, the drum echoing over the jungle, fierce joyful grin"),
   "2": (None, "road", "a thick column of white signal smoke rising from a small fire of green leaves in a jungle clearing, spear planted beside it"),
   "3": (None, "road", "a hunting net of woven vines hanging hidden above the jungle path, trigger rope and bent sapling, dappled light"),
   "4": ("e2", "wedding", "the body painter holds up a colorful flower necklace with both hands, offering it, gentle smile, flower petals falling"),
   "5": (None, "hiroba", "the amazon village at dusk seen from its entrance, bonfire in the plaza, thatched huts, torches, flower garlands on the gate"),
 },
}
