# N87 アトリエの画家（Atelier）画像データ。登場人物は全員20歳以上。女性＋NH（彫刻家カミーユ・画商ラファエラ）・女装あり。
# 敗北28本・技CGは主人公が白い女神のドレス（片肩の一枚布・金の細紐・白い花冠・素足・ウィッグなし）のまま。画布・スケッチ帳は白紙で描く。
DRESS = "a white draped one-shoulder goddess dress made of a single cloth with a thin gold cord at the waist, a white flower crown, barefoot, no wig"
DRESS_CHEST = DRESS + ", the cloth slipped off his shoulder baring his flat chest"
DRESS_OPEN = DRESS + ", the hem lifted up"
DRESS_BOTH = DRESS + ", the cloth slipped off his shoulder baring his flat chest, the hem lifted up"
DATA = {
 "code": "Atelier",
 "world": "painter's atelier in an old art district, white skylight light, easels with blank canvases, smell of turpentine, red velvet, detailed background",
 "bg": "painter's atelier under a large skylight, white daylight, several easels with blank canvases, a model stand draped in red velvet, an hourglass, jars of brushes, stacked empty gold frames",
 "josou": "white draped one-shoulder goddess dress made of a single cloth, thin gold cord at the waist, white flower crown, barefoot, no wig",
 "chars": {
   "m":    {"type": "woman", "jp": "アデライード", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, voluptuous, long legs, chestnut hair, long hair pinned up with a paintbrush, green eyes, paint-stained off-white blouse, long maroon skirt, huge breasts",
            "name": "the chestnut-haired painter in a paint-stained blouse",
            "pose": "holding a paintbrush up to measure proportions, one eye narrowed, sultry smile, looking at viewer"},
   "e1":   {"type": "woman", "jp": "ミュゲ", "canon": False,
            "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, bob cut, brown eyes, deep green painter's smock, beret, large breasts",
            "name": "the pink-bobbed apprentice in a green smock and beret",
            "pose": "holding a white flower crown in both hands, sweet eager smile, looking at viewer"},
   "e2":   {"type": "nh", "jp": "カミーユ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, slender, elegant, feminine body, long legs, gray hair, long hair in a single ponytail, amber eyes, black apron dress smudged white with plaster, large breasts",
            "name": "the gray-haired sculptor in a plaster-smudged black apron dress",
            "pose": "standing quietly with plaster-dusted hands, calm reserved expression, looking at viewer"},
   "e3":   {"type": "woman", "jp": "シエナ", "canon": False,
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, orange hair, wavy hair, gold eyes, ochre dress, brown apron, small paint bottles without labels at her waist, large breasts",
            "name": "the orange-haired paint seller in an ochre dress",
            "pose": "holding up a small paint bottle without label, teasing grin, looking at viewer"},
   "boss": {"type": "nh", "jp": "ラファエラ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, very tall, elegant, feminine body, long legs, blonde hair, long wavy hair, red eyes, black velvet evening dress, fur stole, gold jewelry, large breasts",
            "name": "the tall blonde art dealer in a black velvet evening dress",
            "pose": "holding a wine glass, fur stole on her shoulders, appraising sweet smile, looking at viewer"},
 },
 "places": {
   "street":   "gallery street at dusk, cobblestones, a frame shop display window with empty gold frames, a fluttering blank poster without text",
   "atelier":  "painter's atelier under a white skylight, easels with blank canvases, blank sketchbook, charcoal sticks, turpentine jars",
   "stand":    "model stand draped in red velvet, easels with blank canvases around it, an hourglass",
   "costume":  "costume room, dress forms, piles of white cloth, fresh white flowers, tall standing mirror",
   "sculpture":"sculpture room, white plaster dust in the air, marble blocks, headless plaster torsos, chisels",
   "paintshop":"paint shop counter after closing, rows of small pigment bottles without labels, mortar and pestle, colored powder",
   "salon":    "art dealer's salon, chandelier, red walls hung with gold-framed blank canvases, wine glasses",
   "framing":  "framing room, stacks of empty gold frames, glue pots, wood shavings",
   "attic":    "attic nap room, narrow bed, moon through a small skylight, creaking floorboards",
   "fountain": "courtyard fountain at night, stone goddess statue, splashing water, night air",
   "wash":     "brush washing area, stone sink, soap foam, brushes in jars dripping water",
   "store":    "art supply storeroom, bundles of blank canvases, dust, lamp light, barrels",
   "gallery":  "exhibition hall after closing, white walls with framed blank canvases, small blank title cards without text",
   "bedroom":  "art dealer's mansion bedroom, canopy bed, black velvet, fur throw",
 },
 "atk": {
   "m1": ("stand", "he stands still on the red velvet model stand, the painter stands close brushing the soft tip of a dry paintbrush in circles around his bare nipple, watching his face, blank canvas on the easel", {"hero_outfit": DRESS_CHEST}),
   "m2": ("atelier", "he stands frozen in a pose on the model stand, the painter sits behind an easel with a blank canvas staring at him intently, charcoal in hand, no hands on him, trembling, flushed", {"hero_outfit": DRESS}),
   "m3": ("framing", "the painter holds his face buried between her huge breasts, her lips at his ear whispering critique, her hands framing his face like a picture frame, empty gold frames behind", {"hero_outfit": DRESS}),
   "e1": ("costume", "he stands before the tall mirror, the pink-bobbed apprentice stands behind him tying the gold cord at his waist, smoothing the white cloth over his chest and hips, placing a flower crown", {"hero_outfit": DRESS}),
   "e2": ("sculpture", "the gray-haired sculptor hugs him tightly from behind, wrapping warm plaster-soaked cloth strips around his arms, her cheek against his hair, calm face, plaster dust", {"hero_outfit": DRESS}),
   "e3": ("paintshop", "he sits on a stool at the counter, the orange-haired paint seller leans in licking the rim of his ear, her tongue at his ear, teasing grin, pigment bottles without labels", {"hero_outfit": DRESS}),
   "boss": ("salon", "under the chandelier, the tall art dealer holds his chin and kisses him deeply, tongues, her other hand pinching his bare nipple, fur stole, appraising", {"hero_outfit": DRESS_CHEST}),
 },
 "atk_desc": {
   "m1": "the painter strokes his nipple with the tip of her paintbrush.",
   "m2": "the painter pins him in place with her gaze, don't move.",
   "m3": "the painter frames his face within her breasts.",
   "e1": "the apprentice dresses him as a goddess.",
   "e2": "the sculptor takes a plaster cast of him in her embrace.",
   "e3": "the paint seller names colors with her tongue on his ear.",
   "boss": "the art dealer appraises him with her kiss.",
 },
 "lose": {
   # アデライード 技1（絵筆の穂先＋動かないで）
   "btl_m1":     ("stand", "he stands still on the red velvet model stand, the painter sweeps a flat brush left and right over his bare nipples, staring at him, blank canvas on the easel, his knees shaking, cum dripping down his thigh", {"hero_outfit": DRESS_BOTH}),
   "onani_m1":   ("attic", "standing alone by the narrow bed frozen in a pose, staring at a dry paintbrush on the pillow, chest thrust out, no hands, penis untouched, the painter sketches in a blank sketchbook from the doorway", {"hero_outfit": DRESS_CHEST}),
   "inochi_m1":  ("wash", "he stands by the stone sink, the painter dabs his bare nipple with the wet tip of a round brush, water dripping, a blank sheet of paper without text beside, his knees trembling, cum dripping", {"hero_outfit": DRESS_BOTH}),
   "onedari_m1": ("atelier", "he stands in the white skylight light pushing out his bare chest, the painter touches the brush tip to his nipple and looks into his face, blank canvas, cum dripping down his thigh", {"hero_outfit": DRESS_BOTH}),
   # アデライード 技2（★動かないで）
   "btl_m2":     ("atelier", "he stands frozen in a pose on the model stand, the painter sits behind an easel with a blank canvas staring at his crotch, charcoal in hand, no hands on him, cum dripping under the lifted hem", {"hero_outfit": DRESS_OPEN}),
   "onani_m2":   ("costume", "standing alone before the tall mirror frozen in a pose, arms held still, no hands, hips trembling, penis untouched, the painter sketches in a blank sketchbook behind him, visible in the mirror", {"hero_outfit": DRESS}),
   "inochi_m2":  ("store", "he stands among bundles of blank canvases under lamp light holding a blank paper without text, the painter sits on a barrel staring at him with charcoal in hand, no hands on him, cum dripping", {"hero_outfit": DRESS_OPEN}),
   "onedari_m2": ("gallery", "he stands on a low pedestal in front of an empty gold frame, the painter sits before him staring intently, a blank title card without text on the wall, no hands on him, cum dripping", {"hero_outfit": DRESS_OPEN}),
   # アデライード 技3（額縁の抱擁＋動かないで）
   "btl_m3":     ("framing", "the painter holds his face buried between her huge breasts before stacks of empty gold frames, her lips at his ear, her hands framing his face, his hips trembling, cum dripping under the hem", {"hero_outfit": DRESS_OPEN}),
   "onani_m3":   ("attic", "lying face down alone on the narrow bed with his face buried in a pillow, hands flat on the sheet, hips trembling, penis untouched, the painter sketches from the doorway", {"hero_outfit": DRESS}),
   "inochi_m3":  ("fountain", "on the edge of the fountain beside the stone goddess statue, the painter holds his face in her cleavage, lips at his ear, moonlight, water splashing, cum dripping", {"hero_outfit": DRESS_OPEN}),
   "onedari_m3": ("atelier", "the painter makes a frame with her hands around his face and sinks it between her huge breasts, blank canvas on the easel, skylight, his knees trembling, cum dripping", {"hero_outfit": DRESS_OPEN}),
   # ミュゲ（★衣装合わせ／絵具を溶く手）
   "btl_e1":     ("costume", "he stands before the tall mirror with a flower crown, the pink-bobbed apprentice stands behind him tying the gold cord, her paint-smeared hand stroking his penis under the lifted hem, cum on the white cloth", {"hero_outfit": DRESS_OPEN}),
   "onani_e1":   ("store", "standing alone among canvas bundles, a white cloth wrapped around himself, stroking his own thighs and chest over the cloth, penis untouched, the pink-bobbed apprentice sketches in a blank sketchbook far behind", {"hero_outfit": DRESS}),
   "inochi_e1":  ("wash", "by the stone sink, the pink-bobbed apprentice places a white flower crown on his head and smooths the cloth over his chest and hips, a blank paper without text on the sink, trembling, cum dripping", {"hero_outfit": DRESS}),
   "onedari_e1": ("street", "he stands before the frame shop display window at dusk, the pink-bobbed apprentice smooths the white cloth over his hips and chest from behind, his reflection in the glass, cum dripping", {"hero_outfit": DRESS}),
   # カミーユ（★石膏の型取り／大理石の脚・NH、挿入なし）
   "btl_e2":     ("sculpture", "the gray-haired sculptor hugs him tightly from the front, plaster cloth strips wrapped around his arms, his penis clamped between her thighs, calm face, plaster dust, cum on her thighs", {"hero_outfit": DRESS_OPEN}),
   "onani_e2":   ("attic", "lying alone on the narrow bed wrapped tightly in a wool blanket up to his chest, stroking his own chest, lips counting, penis untouched, the gray-haired sculptor watches from the doorway", {"hero_outfit": DRESS}),
   "inochi_e2":  ("framing", "among empty gold frames, the gray-haired sculptor hugs him tightly from behind, warm plaster cloth wrapped around his chest and arms, her cheek on his hair, a blank paper without text on the bench, trembling", {"hero_outfit": DRESS}),
   "onedari_e2": ("gallery", "he stands on a statue pedestal, the gray-haired sculptor hugs him tightly from behind, plaster cloth on his arms, a plaster torso beside, a blank title card without text, trembling, cum dripping", {"hero_outfit": DRESS}),
   # シエナ（★色見本の舌／パレットの上で）
   "btl_e3":     ("paintshop", "he sits on the counter, the orange-haired paint seller licks deep into his ear, her bare foot stroking his penis under the lifted hem, colored powder, cum on her foot", {"hero_outfit": DRESS_OPEN}),
   "onani_e3":   ("street", "standing alone in a narrow alley of the gallery street, tracing the rim of his own ear with a wet fingertip, eyes hidden, penis untouched, the orange-haired paint seller sketches in a blank sketchbook far away", {"hero_outfit": DRESS}),
   "inochi_e3":  ("store", "he sits on a barrel in the storeroom, the orange-haired paint seller sucks his earlobe, holding a blank paper without text, lamp light, trembling, cum dripping", {"hero_outfit": DRESS}),
   "onedari_e3": ("salon", "in the corner of the salon, the orange-haired paint seller licks deep into his reddened ear, holding his head, his knees buckling, cum dripping under the hem", {"hero_outfit": DRESS_OPEN}),
   # ラファエラ（★品評会／買い上げの夜・NH）
   "btl_boss":   ("salon", "from side, he lies on his back on a velvet chaise under the chandelier, the tall art dealer over him penetrating his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate", {"pen": "penis", "hero_outfit": DRESS_BOTH}),
   "onani_boss": ("bedroom", "sitting alone on the edge of the canopy bed sucking two of his own fingers as if kissing, the other hand pinching his own bare nipple, penis untouched, the tall art dealer watches from the doorway", {"hero_outfit": DRESS_CHEST}),
   "inochi_boss":("framing", "from side, he lies on his back on a worktable among empty gold frames, the tall art dealer over him penetrating his anus with her own penis, anal, kissing him deeply, his own penis separate", {"pen": "penis", "hero_outfit": DRESS_BOTH}),
   "onedari_boss":("gallery", "among framed blank canvases, the tall art dealer holds his chin and kisses him deeply, tongues, flicking his bare nipple, a blank red card without text on the wall, cum dripping", {"hero_outfit": DRESS_BOTH}),
 },
 "lose_desc": "keeps him as her goddess model in the white dress forever.",
 "onanie": {
   "master": ("atelier", "standing frozen in a pose on the model stand, arms still, no hands, hips trembling, blank canvas nearby, penis untouched"),
   "e1": ("costume", "a white cloth wrapped around himself like a dress, stroking his own thighs and chest over the cloth before the mirror, penis untouched", {"hero_outfit": DRESS}),
   "e2": ("attic", "lying wrapped tightly in a wool blanket up to his chest, stroking his own chest, lips counting, penis untouched"),
   "e3": ("paintshop", "sitting on a stool tracing the rim of his own ear with a wet fingertip, penis untouched"),
   "boss": ("bedroom", "sitting on the canopy bed sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "stand", "turning over an hourglass on the model stand with a paintbrush in her hair, sultry smile"),
   "2": (None, "paintshop", "a blank order form without text on the counter beside small pigment bottles without labels and a quill pen"),
   "3": ("e3", "atelier", "peeking out from behind an easel with a blank canvas, finger to her lips, mischievous grin"),
   "4": ("e1", "costume", "holding up a white draped goddess dress and a white flower crown, sweet smile"),
   "5": (None, "gallery", "an exhibition hall being prepared, empty gold frames leaning on white walls, blank title cards without text, a ladder"),
 },
}
