# N98 夏の海の家（Beach）画像データ。登場人物は全員20歳以上。女性＋NH（ルカ・ソレイユ）。挿入はソレイユの「満ち潮」（btl/inochi/onedari_boss）だけ。
# 日焼けは tan / tanlines まで（sunburn はネガ）。看板・貼り紙・瓶に文字なし。主人公の首には貝殻の首飾り。
PEN = {"pen": "penis"}
SUN_NEG = "sunburn, red skin, peeling skin"
NECK = "a seashell necklace on a hemp cord around his neck"
DATA = {
 "code": "Beach",
 "world": "summer seaside beach with a wooden beach hut, bright sunlight, white sand, sparkling sea, coconut sunscreen oil sheen on wet skin, detailed background",
 "bg": "wooden seaside beach hut on white sand in bright summer daylight, reed screens, tatami seating area, blank signboard without text, beach parasols, sparkling sea, no humans",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "カイリ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 29 years old, adult proportions, beautiful detailed eyes, tall, long legs, auburn hair, long wavy hair, amber eyes, tan skin, tanlines, white bikini, open red aloha shirt, straw hat, huge breasts",
         "name": "the auburn-haired tanned manager in a white bikini and red aloha shirt",
         "pose": "one hand on her hip, the other holding a white sunscreen bottle, confident generous grin, looking at viewer",
         "neg": SUN_NEG},
   "e1": {"type": "woman", "jp": "サーヤ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, tall, athletic slender body, long legs, blonde hair, high ponytail, green eyes, light tan, red competition swimsuit, whistle on a cord around her neck, large breasts, lifeguard",
          "name": "the blonde lifeguard in a red competition swimsuit",
          "pose": "holding the whistle near her lips, serious caring expression, looking at viewer",
          "neg": SUN_NEG},
   "e2": {"type": "nh", "jp": "ルカ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, slender, feminine body, long legs, pink hair, bob cut, purple eyes, white frilled bikini, yellow apron, medium breasts, shaved ice stall clerk",
          "name": "the pink-bobbed shaved ice clerk in a white frilled bikini and yellow apron",
          "pose": "holding a bowl of strawberry shaved ice with both hands, earnest shy smile, looking at viewer",
          "neg": SUN_NEG},
   "e3": {"type": "woman", "jp": "ペルル",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, light green hair, long single braid, brown eyes, seashell bikini top, flowing pareo, basket of seashells, large breasts, dreamy",
          "name": "the green-braided shell seller in a seashell bikini and pareo",
          "pose": "holding a conch shell to her ear, dreamy sleepy smile, looking at viewer",
          "neg": SUN_NEG},
   "boss": {"type": "nh", "jp": "ソレイユ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, black hair, long wavy hair, gold eyes, black one-piece swimsuit, sheer long pareo, sunglasses on head, large breasts, bar owner",
            "name": "the black-haired bar owner in a black one-piece swimsuit and sheer pareo",
            "pose": "hand on her hip with the sheer pareo flowing, embracing warm smile, looking at viewer",
            "neg": SUN_NEG},
 },
 "places": {
   "nightbeach": "sandy beach after closing time at dusk, warm lights of the beach hut behind, gentle waves",
   "daybeach":   "bright white sand beach at noon, blazing sunlight, hot sand, sparkling waves",
   "zashiki":    "beach hut tatami seating area, woven goza mats, electric fan, low tables",
   "backkitchen":"shady back of the beach hut kitchen, wooden crates of empty glass bottles without labels, ice bucket",
   "kakigori":   "shaved ice stall, ice shaving machine, red strawberry syrup bottles without labels, cold mist, wooden crates",
   "lifeguard":  "under a tall wooden lifeguard tower, striped shadow of the wooden legs, dry sand, lifebuoy",
   "changing":   "beach changing room, light through reed blinds, wet wooden floorboards",
   "shower":     "wooden outdoor shower hut, lukewarm water spray, light through gaps in the plank walls",
   "parasol":    "under a striped beach parasol, striped shade, beach towel on the sand, red and white striped swim ring",
   "tidepool":   "rocky tide pool at sunset, warm shallow seawater, seaweed, orange sky",
   "shellstall": "small seashell stall on the beach, baskets full of seashells, hanging shell wind chimes",
   "pier":       "wooden pier at sunset, orange sea, creaking planks, two glass soda bottles without labels",
   "shore":      "moonlit shoreline at night, waves lapping in and out, wet sand shining in the moonlight",
   "bar":        "open-air beach bar at night, rattan chairs, hanging lanterns, bottles of rum without labels",
   "upstairs":   "live-in room upstairs in the beach hut at night, mosquito net over a futon, window screen, sound of waves",
 },
 "atk": {
   "m1": ("nightbeach", "he kneels on the warm sand, the tanned manager kneels before him squeezing his penis between her oiled huge breasts in her white bikini top, sunscreen oil dripping, glossy skin, his hips trembling"),
   "m2": ("nightbeach", "he sits on the sand, the tanned manager hugs him from behind rubbing her oiled breasts across his back, her oily hands spreading sunscreen over his chest, glistening skin, trembling"),
   "m3": ("pier", "at the end of the sunset pier, the tanned manager holds him close kissing him deeply, tongues, her oily fingers rolling his nipples, orange sea behind, trembling"),
   "e1": ("lifeguard", "he lies on his back in the sand under the lifeguard tower, the lifeguard kneels over him pinching his nose, sealing his lips with a long mouth-to-mouth kiss, blowing breath into him, his chest rising"),
   "e2": ("kakigori", "he sits on a wooden crate behind the stall, the shaved ice clerk draws a circle around his nipple with an ice cube, meltwater running down his chest, cold mist, trembling"),
   "e3": ("shellstall", "he lies beside baskets of seashells, the shell seller presses a conch shell to his ear and whispers, her lips close to his other ear, hips twitching"),
   "boss": ("shore", "on the moonlit shore, the bar owner hugs him from behind rocking with the waves, pinching both his nipples, waves washing over their feet, his head fallen back"),
 },
 "atk_desc": {
   "m1": "the manager squeezes him in her oiled cleavage instead of a swim ring.",
   "m2": "the manager spreads sunscreen on him with her breasts.",
   "m3": "the manager kisses him on the sunset pier and rolls his nipples.",
   "e1": "the lifeguard gives him mouth-to-mouth again and again.",
   "e2": "the shaved ice clerk traces his nipples with melting ice.",
   "e3": "the shell seller whispers through a conch shell into his ear.",
   "boss": "the bar owner rocks him with the waves on the night shore.",
 },
 "lose": {
   # カイリ 技1（浮き輪の代わりに）
   "btl_m1":     ("nightbeach", "he kneels on the warm sand, the tanned manager squeezes his penis between her oiled huge breasts in her white bikini top, sunscreen oil glistening, " + NECK + ", cum in her cleavage"),
   "onani_m1":   ("backkitchen", "sitting alone behind the crates of bottles, hugging a red and white striped swim ring to his chest, oily fingertips rubbing his own nipple, penis untouched, the tanned manager watches far away by the kitchen door"),
   "inochi_m1":  ("parasol", "he kneels in the parasol shade blowing into a striped swim ring, the tanned manager presses her oiled breasts against his back, her hands spreading sunscreen over his chest, glistening skin, trembling"),
   "onedari_m1": ("zashiki", "he lies on the goza mat with a striped swim ring as a pillow, the tanned manager kneels over him squeezing his penis between her oiled huge breasts, electric fan, cum on her breasts"),
   # カイリ 技2（★日焼け止めの塗り合い）
   "btl_m2":     ("nightbeach", "he kneels on the warm sand, the tanned manager hugs him from behind, her oiled breasts sliding over his back, her oily hands on his chest and sides, " + NECK + ", cum on the sand, trembling"),
   "onani_m2":   ("upstairs", "lying alone face down on the futon inside the mosquito net, rubbing his oiled chest against a towel, hips twitching, penis untouched, the tanned manager watches far away at the doorway"),
   "inochi_m2":  ("shower", "he stands with both hands on the plank wall of the shower hut, the tanned manager presses her oiled breasts against his back, sunscreen and water dripping, a shell-shaped tanline on his chest, trembling"),
   "onedari_m2": ("parasol", "he lies face down on a beach towel under the striped parasol, the tanned manager lies on his back sliding her oiled breasts over him, white sunscreen bottle beside, glistening skin"),
   # カイリ 技3（夕暮れの桟橋）
   "btl_m3":     ("pier", "at the end of the sunset pier, the tanned manager kisses him deeply, tongues, her oily fingers rolling his nipples, her breasts pressed to his chest, waves below, " + NECK + ", cum on the planks"),
   "onani_m3":   ("tidepool", "sitting alone in the shadow of a rock by the tide pool at sunset, two of his own fingers in his mouth, oily fingertips of the other hand rolling his own nipple, penis untouched, the tanned manager watches far away"),
   "inochi_m3":  ("pier", "they sit side by side at the end of the pier at sunset, two soda bottles without labels beside them, the tanned manager kisses him deeply, tongues, her oily fingers rolling his nipple"),
   "onedari_m3": ("pier", "he lies on the planks of the sunset pier, the tanned manager leans over him kissing him deeply, her oiled breasts on his chest, her fingers rolling his nipple, orange sky, trembling"),
   # サーヤ（★人工呼吸）
   "btl_e1":     ("lifeguard", "he lies on his back in the sand under the lifeguard tower, the lifeguard kneels beside him pinching his nose and kissing him mouth-to-mouth, her sandy bare foot pressing his penis, cum on her foot"),
   "onani_e1":   ("changing", "sitting alone on the wet floorboards behind the reed blind, cheeks puffed holding his breath, two of his own fingers in his mouth, penis untouched, the lifeguard watches far away at the entrance"),
   "inochi_e1":  ("daybeach", "he lies at the water's edge with waves washing his legs, the lifeguard kneels over him pinching his nose and giving a long mouth-to-mouth kiss, his chest rising, blazing sunlight"),
   "onedari_e1": ("lifeguard", "he lies in the tower's striped shadow offering his lips, the lifeguard leans over him sealing his lips with a long mouth-to-mouth kiss, her bare foot on his penis, cum on the sand"),
   # ルカ（★溶けた氷）
   "btl_e2":     ("kakigori", "he sits on a wooden crate at the back of the stall, the shaved ice clerk circles his nipple with an ice cube, her cold fingers stroking his penis, meltwater on his chest, cum dripping"),
   "onani_e2":   ("backkitchen", "sitting alone beside the ice bucket, tracing his own nipple with an ice cube, meltwater running down his chest, penis untouched, the shaved ice clerk watches far away at the doorway"),
   "inochi_e2":  ("kakigori", "he stands at the stall counter, the shaved ice clerk stands close tracing his nipple with melting ice, then warming it with her fingertip, cold mist, strawberry shaved ice bowls, trembling"),
   "onedari_e2": ("zashiki", "he sits on the goza mat with his chest thrust out, the shaved ice clerk kneels beside him tracing both his nipples with an ice cube until it melts, meltwater dripping, trembling"),
   # ペルル（★貝殻の囁き）
   "btl_e3":     ("shellstall", "he lies beside baskets of seashells, the shell seller presses a conch shell to one ear, licking his other ear, his penis clamped between her thighs under her pareo, cum on her thighs"),
   "onani_e3":   ("tidepool", "sitting alone on a rock by the tide pool, holding a seashell to his ear, wet fingertips tracing the rim of his other ear, mouth open, penis untouched, the shell seller watches far away"),
   "inochi_e3":  ("shore", "he lies on the moonlit wet sand, the shell seller lies beside him holding a seashell to his ear, whispering into his other ear, waves lapping at their feet, his body limp"),
   "onedari_e3": ("shellstall", "he sits leaning against the stall, the shell seller covers his ear with a big conch shell and whispers into it, her lips close, his head tilted, trembling, drool"),
   # ソレイユ（★夜の波打ち際／満ち潮）
   "btl_boss":   ("shore", "from side, on the moonlit shore, he lies on the wet sand with legs lifted, the bar owner leans over him penetrating his anus with her own penis, anal, pinching his nipple, waves washing over them, his own penis separate, cum on his chest", PEN),
   "onani_boss": ("bar", "sitting alone in a rattan chair wrapped tightly in a wet bath towel, fingers slipped under the towel pinching his own nipple, penis untouched, the bar owner watches far away by the lanterns"),
   "inochi_boss":("shore", "from side, on the moonlit shore, he kneels on all fours in the shallow waves, the bar owner kneels behind him penetrating his anus with her own penis, anal, her hand reaching around pinching his nipple, his own penis separate, cum in the water", PEN),
   "onedari_boss":("shore", "from side, at the moonlit water's edge, he lies on his back holding his knees, the bar owner kneels between his legs penetrating his anus with her own penis, anal, " + NECK + ", his own penis separate, cum on his stomach", PEN),
 },
 "lose_desc": "keeps him at the beach hut as a live-in worker in an endless summer.",
 "onanie": {
   "master": ("nightbeach", "lying face down on a beach towel, rubbing his oiled chest against the towel, one hand under his chest rubbing his own nipple, penis untouched"),
   "e1": ("lifeguard", "sitting in the tower's shadow, cheeks puffed holding his breath, two of his own fingers in his mouth, penis untouched"),
   "e2": ("kakigori", "sitting on a crate, tracing his own nipple with an ice cube, meltwater running down his chest, penis untouched"),
   "e3": ("shellstall", "sitting by the baskets, holding a seashell to his ear, wet fingertips tracing the rim of his other ear, penis untouched"),
   "boss": ("bar", "wrapped tightly in a wet bath towel in a rattan chair, fingers slipped under the towel pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": (None, "zashiki", "a chilled glass marble soda bottle without label beaded with water droplets on a low wooden table, ice cubes, summer light"),
   "2": (None, "backkitchen", "a blank paper notice without text pinned to a wooden post of the beach hut, fluttering in the sea breeze"),
   "3": (None, "daybeach", "blazing summer sun over the white sand beach, heat shimmer, an empty beach towel and parasol, glaring light"),
   "4": ("m", "parasol", "pouring white sunscreen oil into her palm from a white bottle without label, glossy tanned skin, inviting grin"),
   "5": (None, "nightbeach", "the wooden beach hut glowing with warm lights at dusk, reed screens, a blank signboard without text, striped swim rings hanging"),
 },
}
