# N69 ギャンブルカジノ（Cammy）画像データ。登場人物は全員20歳以上。すべて女性。
# キャミー・酔いどれバニー・爆乳バニー・宝石サキュバスは本編キャラ（立ち絵を見ずに本文から作った見た目。canon_img と見比べて直す）。
# 主人公の貞操帯（股間だけの平たい金属の器具）は {"cage": True}。カード・チップ・帳面には文字や数字を描かない。
CHIP = "blank red casino chips without numbers"
CARDS = "blank playing cards without text"
DATA = {
 "code": "Cammy",
 "world": "luxurious fantasy casino at night, red carpet, gold chandeliers, green felt gaming tables, glittering lights, detailed background",
 "bg": "interior of a luxurious fantasy casino at night, green felt card tables with blank playing cards, roulette wheel, stacks of blank red chips without numbers, gold chandeliers, red carpet, no people",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "キャミー", "canon": True, "canon_img": "F17.png",
            "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, tall, blonde hair, long twintails, red eyes, smug grin, red lipstick, red and black strapless casino dress with gold trim, deep cleavage, black thighhighs, high heels, gigantic breasts, huge breasts, curvy",
            "name": "the blonde-twintailed gambler in a red and black dress",
            "pose": "leaning forward with her arms pushing her huge breasts together, flipping a blank gold coin with her thumb, mocking grin, looking down at viewer"},
   "e1":   {"type": "woman", "jp": "酔いどれバニー", "canon": True, "canon_img": "EU50.png",
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, auburn hair, long wavy hair, green eyes, drunk blush, rabbit ears, black playboy bunny suit, white wrist cuffs, bowtie, black fishnet pantyhose, high heels, holding a wine bottle without label, large breasts",
            "name": "the tipsy auburn-haired bunny hostess with a wine bottle",
            "pose": "sitting on a bar stool with legs crossed, raising a wine bottle, tipsy flushed smile, looking at viewer"},
   "e2":   {"type": "woman", "jp": "爆乳バニー", "canon": True, "canon_img": "EU51.png",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, very long hair, droopy eyes, brown eyes, gentle smile, rabbit ears, black playboy bunny suit, white wrist cuffs, bowtie, black pantyhose, high heels, gigantic breasts, huge breasts, soft body",
            "name": "the pink-haired busty bunny hostess",
            "pose": "holding her gigantic breasts together with both arms, sleepy gentle smile, head tilted, looking at viewer"},
   "e3":   {"type": "woman", "jp": "ディーラー クラブ",
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, tall, silver hair, metallic hair, short hair, purple eyes, expressionless, casino dealer uniform, black vest, white collared shirt, black bow tie, white gloves, black slacks, slender, medium breasts",
            "name": "the silver-haired dealer in a black vest and white gloves",
            "pose": "standing straight, fanning a deck of blank playing cards without text in one white-gloved hand, expressionless, looking at viewer"},
   "boss": {"type": "woman", "jp": "宝石サキュバス", "canon": True, "canon_img": "EU61.png",
            "tags": "adult woman, mature female, mature face, 30 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, black hair, very long straight hair, gold eyes, glowing jewel-like eyes, small black horns, black bat wings, purple and black low-cut gown, layered jeweled necklaces over her chest, jeweled rings on her fingers, gem earrings, arrogant smile, large breasts",
            "name": "the black-haired jewel succubus in layered jeweled necklaces",
            "pose": "seated elegantly with legs crossed, stroking the jeweled necklaces on her chest with ringed fingers, arrogant smile, looking down at viewer"},
 },
 "places": {
   "vip":      "VIP card table with green felt, " + CARDS + ", " + CHIP + ", gold chandelier, dim luxurious light",
   "roulette": "roulette table with a spinning red and black wheel without numbers, green felt, " + CHIP + ", casino crowd lights blurred in the background",
   "lounge":   "casino lounge, red velvet sofa, low marble table with two dice, gold lamps",
   "bar":      "casino bar counter with high stools, bottles without labels on the backbar shelves, cocktail glasses, warm light",
   "slots":    "row of glittering slot machines with blank reels, colorful lights, round stool",
   "blackjack":"blackjack table with green felt, " + CARDS + " dealt in a row, " + CHIP + ", card shoe",
   "jewel":    "jewel room at the top floor of the casino, white marble floor, glass display shelves full of glowing colorful gems",
   "stage":    "casino show stage under a spotlight, red velvet curtain, dark audience seats",
   "private":  "gambler's private bedroom in the casino, canopy bed with red silk, vanity mirror, " + CHIP,
   "poker":    "poker room, green felt table, " + CARDS + ", " + CHIP + ", dim hanging lamp",
   "salon":    "bunny hostesss' rest salon, big soft sofa with round cushions, mirrors, pink light",
   "cashier":  "casino cashier counter at night after closing, small hourglass, thick ledger without text, " + CHIP,
   "cellar":   "wine cellar under the casino, wooden barrels, bottle racks, blank blackboard without text on the wall, dim warm light",
   "inspect":  "small card inspection room, desk stacked with sealed decks of blank cards, record book without text, desk lamp",
   "entrance": "grand casino entrance hall, red carpet, gold doors, chandeliers",
 },
 "atk": {
   "m1": ("vip", "he sits on the edge of the green felt table, the gambler kneels before him pressing his erection between her gigantic breasts, paizuri, pushing her breasts together with both hands, mocking grin, precum"),
   "m2": ("roulette", "he kneels by the roulette table with a small red chip glowing at his throat, the gambler dangles a tiny silver key on a chain above her deep cleavage, lowering it between her breasts, teasing grin, trembling", {"cage": True}),
   "m3": ("lounge", "he lies on his back on the red velvet sofa, the gambler lies on top of him crushing him under her gigantic breasts, her lips at his ear mocking him, his face flushed, trembling, two dice on the table"),
   "e1": ("bar", "he sits on a high bar stool, the bunny hostess holds his face in both hands and kisses him mouth to mouth pouring sweet wine into his mouth, tongues, wine dripping from his chin, wine bottle in her hand"),
   "e2": ("slots", "he sits slumped on the round stool, the bunny hostess hugs his head and buries his face deep between her gigantic breasts, paizuri-style hug, swaying her breasts, slot machine lights"),
   "e3": ("blackjack", "he stands leaning on the blackjack table with his chest bare, the dealer holds a blank playing card and presses its corner against his nipple, the other white-gloved hand dealing cards, expressionless, trembling"),
   "boss": ("jewel", "he kneels on the white marble floor with small gem clips pinching both his nipples, the jewel succubus stands over him as her jeweled necklaces glow brightly into his eyes, his mouth open, back arched, hips twitching"),
 },
 "atk_desc": {
   "m1": "the gambler squeezes him between her gigantic breasts.",
   "m2": "the gambler makes him wager the key of his chastity cage.",
   "m3": "the gambler crushes him under her breasts and whispers insults.",
   "e1": "the tipsy bunny hostess pours wine into his mouth with a kiss.",
   "e2": "the busty bunny hostess buries his face in her breasts.",
   "e3": "the dealer deals cards whose corners touch his nipples.",
   "boss": "the jewel succubus dazzles him with her necklace and clips gems on his nipples.",
 },
 "lose": {
   # キャミー 技1（ズリズリ）
   "btl_m1":     ("vip", "he kneels up on the green felt offering his hips, the gambler holds her gigantic breasts squeezed around his penis without moving, paizuri, cum splattered over her cleavage and collarbone, mocking grin, blank chips scattered"),
   "onani_m1":   ("stage", "kneeling alone on the stage under the spotlight, pinching his own nipples with both hands, back arched, hips twitching, penis untouched, the gambler watches from a chair far behind holding her breasts together"),
   "inochi_m1":  ("vip", "he kneels on the floor with a red leather collar on his neck, the gambler lifts her gigantic breasts with both hands and sways them before him without touching, his hips thrusting into the air, cum dripping, a blank registration paper without text on the table"),
   "onedari_m1": ("private", "he kneels on the canopy bed with a red collar, thrusting his hips into the gambler's gigantic breasts, paizuri, the gambler pinching his nipple, cum overflowing from her cleavage, a leather betting ledger without text beside"),
   # キャミー 技2（首輪のチップ＝貞操帯の鍵）
   "btl_m2":     ("roulette", "he kneels on the floor by the roulette wheel with a red collar, his penis locked in the chastity cage, the gambler slowly pushes a tiny silver key on a chain down into her deep cleavage, cum leaking from the cage, trembling", {"cage": True}),
   "onani_m2":   ("private", "kneeling alone on the carpet with a cord hanging around his neck, pinching his own nipple, the other hand reaching under from behind pressing his own perineum, his penis locked in the cage, the gambler watches from the canopy bed", {"cage": True}),
   "inochi_m2":  ("roulette", "he kneels with his hands on the floor after closing time, his penis locked in the chastity cage leaking, the gambler sits on the roulette table sinking the silver key into her cleavage, teasing grin, blank paper without text glowing gold", {"cage": True}),
   "onedari_m2": ("cashier", "he stands before the cashier counter with a red collar, his penis locked back in the chastity cage, cum dripping, the gambler leans on the counter sinking a wet silver key into her cleavage, a small hourglass with all the sand fallen, ledger without text", {"cage": True}),
   # キャミー 技3（押しつぶし）
   "btl_m3":     ("lounge", "he lies on his back on the red velvet sofa pinned under the gambler, the gambler presses her whole weight and gigantic breasts on his chest, her lips at his ear mocking, cum spreading between their bellies, dice on the table"),
   "onani_m3":   ("entrance", "sitting alone like a dog on the red carpet at the casino entrance, a red collar on his neck, hugging himself and pressing his chest against his own knees, flushed, trembling, penis untouched, the gambler laughs far away by the gold doors", {"cage": True}),
   "inochi_m3":  ("poker", "he lies on his back on the green poker table, a red collar with blank chips, the gambler sits apart not touching him and leans to his ear mocking him, his hips lifting by themselves, cum on his belly"),
   "onedari_m3": ("stage", "he lies face down on a crimson velvet cushion on the stage under the spotlight, the gambler lies on his back crushing him with her gigantic breasts, her lips at his ear, a small glowing crystal beside, cum soaking the cushion"),
   # 酔いどれバニー（口移しの酒）
   "btl_e1":     ("bar", "he sits on a bar stool, the bunny hostess holds his face and kisses him mouth to mouth pouring sweet wine, tongues, her other hand stroking his penis, cum on her palm, wine bottle on the counter"),
   "onani_e1":   ("lounge", "sitting alone under a glittering champagne tower of glasses, sucking his own fingers deeply with sweet drink in his mouth, drink dripping from his lips, penis untouched, the bunny hostess watches from the sofa with a wine bottle"),
   "inochi_e1":  ("bar", "he leans against the bar counter with his chin raised, the bunny hostess lets a single drop of wine fall from her lips onto his tongue, a red collar on his neck, cum dripping, wine glass on the counter"),
   "onedari_e1": ("cellar", "he stands between the knees of the bunny hostess sitting on a barrel, the bunny hostess kisses him mouth to mouth pouring amber liquor, her hand stroking his penis, cum on her palm, blank blackboard without text"),
   # 爆乳バニー（ぱふぱふ）
   "btl_e2":     ("slots", "he kneels by the slot machines with his face buried deep between the bunny hostess's gigantic breasts, the bunny hostess hugs his head and sways her breasts, her hand on his penis, cum on her belly and thighs, slot lights"),
   "onani_e2":   ("salon", "sitting alone on the big sofa pressing two round cushions against both sides of his face, swaying them, dreamy expression, penis untouched, the bunny hostess watches from across the salon smiling"),
   "inochi_e2":  ("salon", "he lies asleep on the big sofa with his face nestled between the bunny hostess's gigantic breasts, the bunny hostess lies with him hugging his head, cum on her belly, a red collar on his neck, peaceful"),
   "onedari_e2": ("salon", "he sits on a large bed in the mirrored room with his face buried in the bunny hostess's gigantic breasts, the bunny hostess hugs him and strokes his penis, a few blank white tags without text tucked in her cleavage, cum on her hand"),
   # ディーラー クラブ（カードの角で）
   "btl_e3":     ("blackjack", "he stands thrusting his hips at the blackjack table, the dealer presses the corner of a blank card against his nipple, her white-gloved thumb on the underside of his penis, cum splattered on the dealt blank cards"),
   "onani_e3":   ("vip", "sitting alone at a baccarat table with his shirt open, touching the corner of a blank playing card to his own nipple, counting under his breath, penis untouched, the dealer watches expressionless from across the table"),
   "inochi_e3":  ("blackjack", "he lies with his upper body on the blackjack table, blank red chips placed on his chest, the dealer holds a blank card corner a hair above his nipple without touching, expressionless, cum in her white glove"),
   "onedari_e3": ("inspect", "he sits on a chair in the inspection room, the dealer presses a blank card corner to his nipple and strokes his penis with her white-gloved hand, expressionless, cum in her glove, record book without text open on the desk"),
   # 宝石サキュバス（宝石の首飾り）
   "btl_boss":   ("jewel", "he kneels on the white marble with gem clips on both nipples, his legs turning into clear glowing crystal from the knees down, the jewel succubus strokes his penis with ringed fingers while her necklaces shine into his eyes, cum on her rings, peaceful sleepy face, no pain"),
   "onani_boss": ("jewel", "kneeling alone and perfectly still on the marble between jewelry showcases, small gem clips pinching both his own nipples, hands resting on his knees, dazed dreamy face, penis untouched, the jewel succubus watches from a throne far away"),
   "inochi_boss":("jewel", "he kneels at the feet of the jewel succubus, gem clips glowing on his nipples, the jewel succubus touches only her own necklace and it shines, his body sparkling with soft light, blissful sleepy face, no pain, cum dripping"),
   "onedari_boss":("jewel", "he sits before a black ebony high-stakes table, the jewel succubus strokes his penis with ringed fingers, a pearl on his fingertip, ruby clips on his nipples, her necklaces glowing, a silk thread strung with four gems in her other hand, cum on her rings"),
 },
 "lose_desc": "wins him at the casino and keeps him as a collared pet.",
 "onanie": {
   "master": ("private", "kneeling on the carpet with a cord around his neck, pinching his own nipple, the other hand reaching under from behind pressing his own perineum, his penis locked in the chastity cage", {"cage": True}),
   "e1": ("bar", "sitting on a bar stool with sweet drink in his mouth, sucking two of his own fingers deeply as if kissing, drink dripping from his lips, penis untouched"),
   "e2": ("salon", "sitting on the sofa pressing two big round cushions against both sides of his face, swaying them, penis untouched"),
   "e3": ("blackjack", "sitting at the blackjack table with his shirt open, touching the corner of a blank playing card to his own nipple tip, penis untouched"),
   "boss": ("jewel", "kneeling still on the marble floor, small gem clips pinching both his own nipples, hands resting on his knees, dreamy face, penis untouched"),
 },
 "magic": {
   "1": ("m", "vip", "flipping a shining blank gold coin high into the air with her thumb, mocking grin, blank red chips flying"),
   "2": (None, "entrance", "a black and gold invitation card without text with a red wax seal lying on a silver tray, scattered blank red chips"),
   "3": ("e3", "blackjack", "sliding a hidden blank card out from her white-gloved sleeve, expressionless, cards dealt on the felt"),
   "4": ("e2", "salon", "leaning forward and hugging her gigantic breasts together with a wink, bunny ears, sparkles"),
   "5": (None, "roulette", "the grand casino floor glittering with gold light, a spinning roulette wheel without numbers, towers of blank red chips, falling gold coins"),
 },
}
