# N84 草原の騎馬の民（Centaur）画像データ。登場人物は全員20歳以上。女性（ケンタウロス2人・巫女）＋ふたなり（馬の獣人2人）。女装なし。
# ケンタウロスは上半身が成人女性・下半身は艶のある馬体で、蹄は柔らかい革の蹄覆い（踏む痛みは描かない）。
CENTAUR_NEG = "human legs, human feet, two legs on the centaur, horse head, bare hooves, horseshoes"
DATA = {
 "code": "Centaur",
 "world": "vast green steppe of nomadic horse riders, felt yurts with embroidered hangings, wind over the grass, wide sky, detailed background",
 "bg": "vast green steppe under a wide sky, a ring of round felt yurts with embroidered door hangings, a campfire pit, leather saddles on a rack, distant hills, wind over the grass",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "サラントヤ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, tall, very tall, centaur, human upper body of a woman, glossy chestnut horse body below the waist, soft leather hoof covers on all four hooves, long black hair in a thick braid, gold eyes, embroidered red breastplate, fur shoulder mantle, bow on her back, small leather saddle with carved marks hanging at her waist, huge breasts",
            "name": "the black-braided centaur chieftain in a red breastplate",
            "pose": "standing tall on her four horse legs, one hand on her hip, bold hearty grin, looking down at viewer",
            "neg": CENTAUR_NEG},
   "e1":   {"type": "woman", "jp": "ナラン", "canon": False,
            "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, tall, centaur, human upper body of a woman, dapple gray horse body below the waist, long flowing horse tail, soft leather hoof covers on all four hooves, orange hair, short hair, brown eyes, white riding vest with a decorative sash, large breasts",
            "name": "the orange-haired gray centaur rider",
            "pose": "standing on her four horse legs, swishing her long tail forward, energetic grin, one hand waving, looking at viewer",
            "neg": CENTAUR_NEG},
   "e2":   {"type": "woman", "jp": "オユン", "canon": False,
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, horse girl, horse ears, horse tail, human legs, chestnut brown hair, ponytail, amber eyes, long green robe with a sash, leather riding boots, large breasts",
            "name": "the chestnut-ponytailed horse-eared stable keeper in a green robe",
            "pose": "standing quietly holding a bridle, calm half-lidded eyes, soft small smile, looking at viewer"},
   "e3":   {"type": "woman", "jp": "ツェツェグ", "canon": False,
            "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, very long braided hair with red cords, green eyes, white shaman robe, beaded forehead ornament, holding a flat frame drum, large breasts",
            "name": "the purple-braided shaman with a frame drum",
            "pose": "standing holding a flat frame drum and a drumstick, mysterious smile, swaying, looking at viewer"},
   "boss": {"type": "woman", "jp": "アルタナ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, long legs, horse girl, horse ears, horse tail, human legs, blonde hair, very long hair, red eyes, crimson long robe with gold thread, soft braided lasso on her hip, huge breasts",
            "name": "the blonde horse-eared vice-chieftain in a crimson robe",
            "pose": "standing with a soft braided lasso looped in one hand, confident big-sister grin, looking at viewer"},
 },
 "places": {
   "steppe":  "center of the vast green steppe, endless grass swaying in the wind, distant hoofbeat dust, wide blue sky",
   "chief":   "chieftain's large yurt interior, thick felt walls, fur rugs, hearth smoke, embroidered hangings, low guest bed",
   "women":   "women's yurt interior, colorful hanging cloths, dried herbs, low beds with cushions",
   "spring":  "clear spring in the steppe, wet flat stones, water splashes, grass at the water's edge",
   "hill":    "trade road hill, dirt road with wheel ruts, a stone cairn on the hilltop, grassland below",
   "dusk":    "steppe at dusk, red sky, long shadows, cooling wind",
   "stable":  "horse stable, hay piles, leather saddles and bridles on the wall, water bucket, straw floor",
   "festival":"festival square at night, large bonfire, drums, circle of dancers far away, roasted meat skewers",
   "shaman":  "shaman's yurt interior, herbal smoke, hanging bells and red cords, flat drums, dim lamp",
   "camp":    "night camp on the steppe, starry sky, crackling campfire, wool blankets, night dew",
   "track":   "racing track of trampled grass, finish post with a plain cloth flag without text",
   "workshop":"saddle workshop, tanned leather, a small knife, bundles of red cords, beeswax, small leather saddle on a stand",
   "moon":    "hill under a huge full moon, silver grass swaying, quiet night",
 },
 "atk": {
   "m1": ("steppe", "he sits on the grass looking up, the tall centaur chieftain stands over him stroking his thighs with a soft leather-covered front hoof, pressing his penis gently between the soft leather covers, grinning down"),
   "m2": ("steppe", "the tall centaur chieftain carries him lifted in one arm while galloping, his face buried in her cleavage, his legs dangling off the ground, her braid flying, hair and grass swaying"),
   "m3": ("spring", "he sits on a wet stone at the spring looking up, the tall centaur chieftain bends down from above kissing him deeply, tongues, her hand stroking his penis, her braid hanging over him"),
   "e1": ("track", "he sits on the grass, the gray centaur rider stands beside him sweeping his nipples with the tip of her long horse tail, teasing circles, his back arched"),
   "e2": ("stable", "he lies on his back on the straw, the stable keeper lies beside him whispering into his ear, licking the rim of his ear, her horse ears perked, trembling, blush"),
   "e3": ("shaman", "he lies with his head on the shaman's lap, the shaman beats the flat frame drum above his face, his body swaying to the rhythm, dazed, hips floating, no hands on him"),
   "boss": ("camp", "by the campfire, the vice-chieftain hugs him with his face buried deep in her huge breasts, both her hands pinching his nipples, the lasso loosely around them, his breath shallow"),
 },
 "atk_desc": {
   "m1": "the centaur chieftain strokes him with her soft leather hoof covers.",
   "m2": "the centaur chieftain gallops with him held against her breasts.",
   "m3": "the centaur chieftain bends down from high above to kiss him.",
   "e1": "the gray centaur sweeps his nipples with the tuft of her tail.",
   "e2": "the stable keeper whispers words of the steppe into his ear.",
   "e3": "the shaman shakes his mind with the rhythm of her drum.",
   "boss": "the vice-chieftain buries his face in her breast pillow.",
 },
 "lose": {
   # サラントヤ 技1（蹄覆いの足＋馬上の抱擁）
   "btl_m1":     ("steppe", "he sits collapsed on the grass with red cords tied around his waist, the tall centaur chieftain stands over him pressing his penis between her soft leather hoof covers, grinning down, cum on the leather, the small carved saddle at her waist"),
   "onani_m1":   ("chief", "sitting alone on the low bed hugging a cushion to his chest, rocking back and forth, stroking his own thighs with a soft leather glove, penis untouched, the centaur chieftain watches from the lifted door hanging"),
   "inochi_m1":  ("hill", "he sits on the rutted dirt road on the hilltop looking up, the tall centaur chieftain pins his penis gently between her soft leather hoof covers, the stone cairn behind, cum on the leather, flushed"),
   "onedari_m1": ("track", "he sits at the finish post of the racing track begging with arms reaching up, the tall centaur chieftain rubs his penis between her soft leather hoof covers, laughing, cum on the grass"),
   # サラントヤ 技2（★馬上の抱擁）
   "btl_m2":     ("dusk", "the tall centaur chieftain holds him in both arms against her huge breasts, standing still in the red dusk, his face buried in her cleavage, twelve red cords swaying at his waist, his legs dangling, cum dripping"),
   "onani_m2":   ("women", "kneeling alone on a low bed hugging a large cushion tightly, pressing his face into it, rocking his hips back and forth, penis untouched, the centaur chieftain watches from the tent entrance"),
   "inochi_m2":  ("moon", "the tall centaur chieftain walks under the huge full moon carrying him in her arms, his face rubbing into her cleavage, his legs dangling, distant town lights on the horizon, trembling, cum dripping"),
   "onedari_m2": ("workshop", "the tall centaur chieftain lifts him high in a tight embrace against her huge breasts, a small leather saddle with carved marks on the stand, red cords at his waist, his arms around her neck, cum dripping"),
   # サラントヤ 技3（草原の口づけ＋馬上の抱擁）
   "btl_m3":     ("spring", "he sits on a wet stone at the spring with his face turned up, the tall centaur chieftain bends down from high above kissing him deeply, tongues, saliva trail, her hand stroking his penis, cum on the stone"),
   "onani_m3":   ("chief", "lying alone on his back on the low bed hugging a cushion, staring up at the embroidered ceiling with his lips parted, rocking his hips, penis untouched, the centaur chieftain peeks in from behind the hanging"),
   "inochi_m3":  ("hill", "on the hilltop by the stone cairn he stands on tiptoe looking up, the tall centaur chieftain bends down kissing him deeply, tongues, her hand stroking his penis, saliva trail, cum dripping"),
   "onedari_m3": ("festival", "by the bonfire the tall centaur chieftain holds him up in her arms and bends her face down kissing him deeply, tongues, his arms around her neck, his legs dangling, cum dripping"),
   # ナラン（★尾の房）
   "btl_e1":     ("track", "he lies on the trampled grass, the gray centaur rider stands over him sweeping his nipples with the tuft of her long tail, grinning, her large breasts swaying, cum on his belly"),
   "onani_e1":   ("stable", "sitting alone on the straw, brushing his own nipples with a soft wide brush, back arched, penis untouched, the gray centaur rider watches from the stable door"),
   "inochi_e1":  ("dusk", "he rides on the gray centaur's horse back holding her sash, the gray centaur rider turns her long tail forward brushing his nipples, red dusk sky, trembling, cum on her gray coat"),
   "onedari_e1": ("women", "he lies on a low bed begging, the gray centaur rider stands beside the bed sweeping both his nipples left and right quickly with the tuft of her tail, cum on his chest"),
   # オユン（★草原の囁き／天幕の中で・ふたなり）
   "btl_e2":     ("stable", "from side, he lies on his back on the straw with legs lifted, the stable keeper lies over him penetrating his anus with her own penis, anal, whispering into his ear, his own penis separate, cum on his belly", {"pen": "penis"}),
   "onani_e2":   ("women", "lying alone on a low bed, tracing the rim of his own ear with a wet fingertip, mouth open, hips twitching, penis untouched, the stable keeper watches from the next bed"),
   "inochi_e2":  ("camp", "he lies wrapped in a wool blanket by the campfire, the stable keeper lies behind him whispering into his ear, her lips at his ear, starry sky, trembling, drool"),
   "onedari_e2": ("stable", "from behind, he lies on his side on the straw, the stable keeper hugs him from behind penetrating his anus with her own penis, anal, lips at his ear whispering, his own penis separate, cum on the straw", {"pen": "penis"}),
   # ツェツェグ（★太鼓の響き／巫女の膝枕）
   "btl_e3":     ("shaman", "he lies with his head on the shaman's lap, the shaman beats the flat frame drum above him, her thighs pressing his penis, his body swaying to the rhythm, cum dripping, dazed"),
   "onani_e3":   ("festival", "standing alone at the dark edge of the festival square, humming a rhythm with his hands at his sides, swaying his body, hips floating, penis untouched, the shaman watches far away with her drum"),
   "inochi_e3":  ("moon", "he kneels on the moonlit hill with red prayer cords around his wrists, the shaman stands beside him beating the flat frame drum, his body swaying, no hands on him, trembling, cum on the grass"),
   "onedari_e3": ("festival", "he lies with his head on the shaman's lap in front of the bonfire, the shaman beats the flat frame drum over him, his hips floating to the rhythm, cum dripping, no hands on his penis"),
   # アルタナ（★副族長の胸枕／夜営の契り・ふたなり）
   "btl_boss":   ("camp", "from side, he lies on his back on a wool blanket by the campfire, the vice-chieftain over him penetrating his anus with her own penis, anal, his face pressed into her huge breasts, pinching his nipple, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("chief", "lying face down alone on the bed with his face buried in a pillow, both hands pinching his own nipples, breath shallow, penis untouched, the vice-chieftain watches from the entrance"),
   "inochi_boss":("camp", "he lies on a wool blanket under the stars with his face buried deep in the vice-chieftain's huge breasts, the vice-chieftain hugs his head to her chest, gentle smile, cum on the blanket"),
   "onedari_boss":("women", "from side, he lies on a low bed with a soft lasso loop around his chest, the vice-chieftain over him penetrating his anus with her own penis, anal, his face in her huge breasts, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the steppe herd as her rider forever.",
 "onanie": {
   "master": ("chief", "sitting on the low bed hugging a cushion to his chest, rocking his body back and forth, stroking his own thigh with a soft leather glove, penis untouched"),
   "e1": ("stable", "sitting on the straw, sweeping his own nipples with a soft wide brush, back arched, penis untouched"),
   "e2": ("women", "lying on a low bed, tracing the rim of his own ear with a wet fingertip, lips moving, penis untouched"),
   "e3": ("shaman", "kneeling with hands on his knees, humming a drum rhythm, swaying his body, hips floating, no hands, penis untouched"),
   "boss": ("camp", "lying face down on a blanket with his face buried in a pillow, both hands pinching his own nipples, penis untouched"),
 },
 "magic": {
   "1": ("m", "chief", "holding up a leather pouch of white mare's milk wine, pouring it into a wooden cup, hearty laugh"),
   "2": (None, "hill", "an old hand-drawn map of the steppe without text spread on a flat stone, held down by a knife and a leather pouch"),
   "3": ("boss", "steppe", "swinging a soft braided lasso overhead in a wide loop, wind in her blonde hair, confident grin"),
   "4": ("m", "chief", "holding open the embroidered door hanging of her yurt with one hand, beckoning with the other, warm inviting smile"),
   "5": (None, "workshop", "a small leather saddle with carved notches on a wooden stand, red cords hanging from it, a small knife beside, lamp light"),
 },
}
