# N96 時計塔の魔女（Clock）画像データ。登場人物は全員20歳以上。女性＋NH（ギアリス・ゼロア）。挿入はゼロアの「零時の針」（btl_boss・inochi_boss）だけ。文字盤に数字は描かない。
PEN = {"pen": "penis"}
DATA = {
 "code": "Clock",
 "world": "old clock tower of a fantasy european town at night, brass gears, clock oil, blank clock faces without numbers, moonlight, detailed background",
 "bg": "machine room behind a giant translucent clock face without numbers, walls of huge interlocking brass gears, moonlight shining through the clock face, brass floor, no humans",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "セクンダ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, long legs, blonde hair, very long hair, pocket watch hair ornament, red eyes, red lipstick, black and gold witch dress, deep neckline, halo of golden gears behind her back, hourglass pendant on her chest, hourglass figure, huge breasts, witch",
         "name": "the blonde time witch in a black and gold dress",
         "pose": "holding an open pocket watch in one hand, elegant teasing smile, looking at viewer",
         "neg": "numbers on clock, roman numerals"},
   "e1": {"type": "woman", "jp": "ペンデュラ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, loose wavy hair, green eyes, sleepy droopy eyes, maroon dress with pendulum ornaments, gold pendulum on a long chain, large breasts",
          "name": "the pink-haired pendulum keeper in a maroon dress",
          "pose": "dangling a gold pendulum on a long chain from her fingers, dreamy sleepy smile, head tilted, looking at viewer"},
   "e2": {"type": "nh", "jp": "ギアリス",
          "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, slender, feminine body, long legs, orange hair, short bob, amber eyes, leather work apron, work gloves, white shirt with open collar, oil can at her waist, medium breasts, artisan",
          "name": "the orange-bobbed gear artisan in a leather apron",
          "pose": "one gloved hand on her hip, holding a small brass oil can, smug smile, looking at viewer"},
   "e3": {"type": "woman", "jp": "カリヨン",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, red hair, medium hair, brown eyes, white blouse, black corset skirt, thick bell rope over her shoulder, large breasts, cheerful",
          "name": "the red-haired bell ringer in a white blouse and corset skirt",
          "pose": "hugging a thick bell rope, bright cheerful grin, leaning forward, looking at viewer"},
   "boss": {"type": "nh", "jp": "ゼロア",
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, silver hair, very long hair, metallic hair sheen, gold eyes, black tailcoat dress with cinched waist, blank clock face brooch without numbers on her chest, black elbow gloves, large breasts, calm expressionless",
            "name": "the silver-haired timekeeper in a black tailcoat dress",
            "pose": "standing straight with gloved hands folded, cold calm gaze, looking at viewer",
            "neg": "numbers on clock, roman numerals"},
 },
 "places": {
   "machine":  "machine room behind a giant translucent clock face without numbers, walls of interlocking brass gears, moonlight through the clock face, brass floor",
   "belfry":   "bell tower top, huge silent bronze bell overhead, open arches, night wind, moonlit town rooftops",
   "stairs":   "spiral stone staircase inside the clock tower, iron handrail, pendulum clocks without numbers lining the wall",
   "pendulum": "pendulum hall, a huge golden pendulum hanging from the high ceiling, moving shadow on the floor, flickering candelabras",
   "workshop": "gear workshop, oily workbench, bundles of mainsprings, brass cogs, bench vise, oil lamp",
   "witch":    "witch's bedroom, black and gold canopy bed, shelves lined with hourglasses, sweet scented oil lamp",
   "hourglass":"hourglass room, many hourglasses big and small with falling golden sand, warm light through glass",
   "corridor": "frozen corridor where time has stopped, glittering dust suspended in midair, candle flames frozen mid-flicker",
   "zero":     "midnight chamber, black stone floor with a huge inlaid clock face without numbers at the center, cold clear air, long shadows of clock hands",
   "guest":    "clock tower guest room, soft bed, small mantel clock without numbers, warm lamp",
   "bellroom": "bell ringer's tiny room, hanging bell rope, hay bed, window showing the great bell",
   "ledge":    "narrow ledge outside the giant clock face without numbers, night wind, town lights far below",
   "hall":     "clock tower entrance hall, heavy wooden door, dusty stone floor, dim quiet",
   "plaza":    "town clock square at night, cobblestones, small clock tower with a blank clock face without numbers, fountain",
   "inn":      "small inn room, wall clock without numbers, thin blanket on a bed, the dark clock tower silhouette in the window",
 },
 "atk": {
   "m1": ("machine", "he lies on his back on the brass floor, the time witch kneels over him squeezing his penis between her huge breasts in her deep neckline, hourglass pendant dangling, kissing his lips, golden gears turning behind"),
   "m2": ("corridor", "he stands frozen mid-motion with one arm raised, dust suspended in the air, the time witch holds his face and kisses him deeply, tongues, saliva trail, an open pocket watch in her hand"),
   "m3": ("stairs", "he sits on the spiral stone steps, the time witch sits behind him whispering into his ear, her fingertips flicking both his nipples, pendulum clocks on the wall, trembling, blush"),
   "e1": ("pendulum", "he kneels before the huge swinging golden pendulum, head tilted following it, mouth open, the pendulum keeper stands beside him dangling a gold pendulum before his face, whispering, no hands on him"),
   "e2": ("workshop", "he sits on the oily workbench, the gear artisan stands before him pinching and twisting both his nipples with gloved fingers like winding a spring, oil can on the bench, back arched"),
   "e3": ("belfry", "under the silent giant bell, the bell ringer hugs his head against her large breasts, his face buried in her cleavage, pafupafu, her hands pressing her breasts to his cheeks, his hips twitching"),
   "boss": ("zero", "he stands frozen stiff on the giant clock face floor, the tall timekeeper stands behind him holding him still, rolling both his nipples with her long-gloved fingertips, his body rigid, trembling"),
 },
 "atk_desc": {
   "m1": "the time witch squeezes him in her hourglass cleavage inside a stopped second.",
   "m2": "the time witch kisses him again and again inside one stopped second.",
   "m3": "the time witch counts the seconds into his ear, one flick per second.",
   "e1": "the pendulum keeper stops his mind with two swings of the pendulum.",
   "e2": "the gear artisan winds his nipples like a mainspring.",
   "e3": "the bell ringer lets him hear her heartbeat like a bell.",
   "boss": "the timekeeper freezes his whole body and rolls his nipples.",
 },
 "lose": {
   # セクンダ 技1（砂時計の谷間）
   "btl_m1":     ("machine", "he lies on his back on the brass floor, the time witch kneels over him squeezing his penis between her huge breasts, cum pooling in her cleavage, her lips on his, dust frozen in the moonlight, his hips floating"),
   "onani_m1":   ("inn", "sitting alone on the thin blanket, pressing his own flat chest together with both arms, two of his own fingers deep in his mouth, cheeks puffed holding his breath, penis untouched, the time witch watches far outside the window"),
   "inochi_m1":  ("hourglass", "he lies among rows of hourglasses with golden sand falling, the time witch leans over him with his penis squeezed between her huge breasts, kissing him, cum on her cleavage, his hips lifted"),
   "onedari_m1": ("belfry", "under the silent giant bell, he lies on the stone floor with his lips parted begging, the time witch kneels over him squeezing his penis between her huge breasts, her lips hovering above his, moonlit night wind"),
   # セクンダ 技2（★止まった一秒）
   "btl_m2":     ("corridor", "he stands frozen with one arm still raised, dust suspended in the air, candle flames frozen, the time witch holds his face kissing him deeply, tongues, saliva trail, his knees buckling, cum dripping to the floor"),
   "onani_m2":   ("guest", "sitting alone on the soft bed beside the mantel clock, sucking two of his own fingers deeply as if kissing, cheeks puffed holding his breath, other hand stroking his own neck, penis untouched, the time witch watches from the far doorway"),
   "inochi_m2":  ("plaza", "he kneels on the cobblestones by the fountain, the blank clock face without numbers glowing behind, the time witch bends down holding his chin and kissing him deeply, tongues, saliva trail, cum on the cobblestones"),
   "onedari_m2": ("ledge", "he sits leaning against the giant clock face with town lights far below, the time witch presses him to the glass kissing him deeply, tongues, a long saliva thread, his lips parted begging for more, trembling"),
   # セクンダ 技3（秒針の刻み）
   "btl_m3":     ("stairs", "he slumps against the iron handrail on the spiral steps, the time witch sits behind him whispering seconds into his ear, her fingertips flicking both his nipples, cum on the stone steps, pendulum clocks on the wall"),
   "onani_m3":   ("inn", "lying alone on the thin blanket under the wall clock, one fingertip flicking his own nipple in rhythm, two fingers of his other hand in his mouth, penis untouched, the time witch watches far outside the window"),
   "inochi_m3":  ("witch", "he lies on the black and gold canopy bed, the time witch lies beside him whispering into his ear, her fingertip flicking his nipple, her lips on his cheek, shelves of hourglasses, cum on his stomach"),
   "onedari_m3": ("machine", "he kneels among huge turning brass gears begging, the time witch stands behind him whispering into his ear and flicking both his nipples, a small clock face mark without numbers on his chest, trembling"),
   # ペンデュラ（★振り子の催眠）
   "btl_e1":     ("pendulum", "he kneels on a cushion before the huge swinging golden pendulum, head tilted following it, mouth open, drool, the pendulum keeper stands beside him whispering, no hands on him, cum dripping on the cushion"),
   "onani_e1":   ("inn", "sitting alone on the bed dangling a ring on a string before his own face, head swaying following it, mouth open, other hand on his knee, penis untouched, the pendulum keeper watches far outside the window"),
   "inochi_e1":  ("corridor", "in the frozen corridor with dust suspended in the air, he kneels limp, the pendulum keeper stands before him swinging a gold pendulum on a long chain before his face, drool, cum on the floor"),
   "onedari_e1": ("guest", "he lies on the soft bed, a gold pendulum swinging above him, the pendulum keeper lies beside him with his penis clamped between her thighs under her lifted maroon skirt, swaying in rhythm, cum on her thighs"),
   # ギアリス（★ゼンマイ巻き）
   "btl_e2":     ("workshop", "he sits on the oily workbench with his back arched, the gear artisan stands before him twisting both his nipples with gloved fingers like winding a spring, oil can on the bench, cum on the workbench"),
   "onani_e2":   ("guest", "sitting alone on the soft bed, pinching and slowly twisting both of his own nipples like winding a spring, back arched, mouth open, penis untouched, the gear artisan watches from the far doorway"),
   "inochi_e2":  ("machine", "he leans back against a brass gear frame, the gear artisan pinches and twists his nipple with gloved fingers, her other oily gloved hand stroking his penis, oil can at her waist, cum dripping"),
   "onedari_e2": ("pendulum", "he sits on a round stool before the swinging pendulum with his chest thrust out begging, the gear artisan stands behind him winding both his nipples one twist at a time, drool, trembling"),
   # カリヨン（★鐘楼の胸）
   "btl_e3":     ("belfry", "under the silent giant bell, the bell ringer sits on the stone floor hugging his face into her large breasts, pafupafu, squeezing his cheeks with her breasts, his hips twitching, cum on the floor"),
   "onani_e3":   ("bellroom", "lying alone face down on the hay bed, face buried in a pillow, one hand stroking his own chest, hips twitching, penis untouched, the bell ringer watches from the far doorway"),
   "inochi_e3":  ("stairs", "on a landing of the spiral stairs, the bell ringer sits on a step hugging his head against her large breasts, his face buried, his body limp against her, cum on the step"),
   "onedari_e3": ("hall", "by the heavy door of the entrance hall, he kneels gripping a thick bell rope with both hands, the bell ringer hugs his face into her large breasts, pafupafu, his hips twitching, cum on the floor"),
   # ゼロア（★永遠の一秒／零時の針）
   "btl_boss":   ("zero", "from side, he lies on his back on the giant clock face floor with legs lifted, the timekeeper kneels between his legs penetrating his anus with her own penis, anal, rolling his nipple with long-gloved fingers, his own penis separate, cum on his chest", PEN),
   "onani_boss": ("guest", "lying alone on his back on the bed perfectly still, arms at his sides, only his fingertips slowly rolling his own nipples, body rigid, penis untouched, the timekeeper watches from the far corner"),
   "inochi_boss":("corridor", "from side, among dust frozen in the air, he kneels on all fours, the timekeeper kneels behind him penetrating his anus with her own penis, anal, her gloved hand reaching around rolling his nipple, his own penis separate, cum on the floor", PEN),
   "onedari_boss":("machine", "behind the translucent giant clock face, he lies motionless on a black bed, the timekeeper lies beside him holding him in her arms, rolling his nipple with long-gloved fingertips, a clock face mark without numbers on his chest, moonlight"),
 },
 "lose_desc": "keeps him frozen forever inside one endless second of the clock tower.",
 "onanie": {
   "master": ("machine", "kneeling with two of his own fingers deep in his mouth, cheeks puffed holding his breath, other hand stroking his own neck, penis untouched"),
   "e1": ("pendulum", "sitting before the huge swinging pendulum with hands on his knees, head swaying following it, mouth open, drool, penis untouched"),
   "e2": ("workshop", "sitting on the workbench, pinching and twisting both of his own nipples like winding a spring, back arched, penis untouched"),
   "e3": ("bellroom", "lying face down with his face buried in a hay pillow, one hand stroking his own chest, hips twitching, penis untouched"),
   "boss": ("zero", "lying perfectly still on his back on the giant clock face floor, only his fingertips slowly rolling his own nipples, penis untouched"),
 },
 "magic": {
   "1": ("m", "hourglass", "turning over the hourglass pendant on her chest, golden sand flowing upward, glowing golden gears around her, teasing smile"),
   "2": (None, "hall", "an ornate old brass key with a gear-shaped bow lying on a velvet cloth, soft light, dust"),
   "3": (None, "corridor", "a closed silver pocket watch floating in midair, dust and a candle flame frozen around it, silent stopped time"),
   "4": ("m", "machine", "pressing one fingertip against a giant clock hand to stop it, golden magic circle, gears halted behind her, calm smile"),
   "5": ("e3", "belfry", "pulling the thick bell rope under the huge bronze bell, the bell ringing with golden sound waves over the night town, cheerful grin"),
 },
}
