# N71 学園の特別講義（Eiraira）画像データ。登場人物は全員20歳以上。すべて女性（エルフ・ハーピーを含む）。
# エイライラ・ガンナーハーピー・ヒーラーハーピー・ファルコンハーピーは本編キャラ（立ち絵を見ずに本文から作った見た目。canon_img と見比べて直す）。
# 学園ものなので制服・生徒の語は使わず academy / lecture と書く。本・書類・答案・黒板には文字を描かない。
# 主人公の鎖骨の下には赤点の赤い丸が浮かぶ（RED）。
RED = "small glowing red circle marks below his collarbone"
DATA = {
 "code": "Eiraira",
 "world": "grand fantasy magic academy for card masters, gothic stone architecture, tall arched windows, warm lamplight, detailed background",
 "bg": "empty grand tiered lecture hall of a fantasy magic academy, wooden desks in rising rows, large blackboard without text, tall arched windows with evening light, no people",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "エイライラ", "canon": True, "canon_img": "F19.png",
            "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, tall, elf, long pointy ears, silver hair, very long straight hair, green eyes, calm scholarly expression, elegant white and gold academy lecturer robe with a deep neckline, black pencil skirt, thighhighs, large breasts",
            "name": "the silver-haired elf lecturer in a white and gold robe",
            "pose": "standing with one hand holding a closed blank book without text, the other hand adjusting a lock of hair behind her pointy ear, calm faint smile, looking at viewer"},
   "e1":   {"type": "woman", "jp": "ガンナーハーピー", "canon": True, "canon_img": "EU43.png",
            "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, harpy, red hair, spiky ponytail, orange eyes, cocky grin, large red and brown feathered wings, feathers on her forearms, bird legs with sharp talons, holding a long flintlock rifle, leather bandolier, black crop top, short shorts, perky large breasts",
            "name": "the red-haired gunner harpy with a flintlock rifle",
            "pose": "resting the long rifle on her shoulder, pinching a single red feather between two fingers like a bullet, cocky grin, looking at viewer"},
   "e2":   {"type": "woman", "jp": "ヒーラーハーピー", "canon": True, "canon_img": "EU44.png",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, harpy, light pink hair, long fluffy hair, droopy eyes, soft brown eyes, gentle smile, large fluffy white feathered wings, soft down feathers on her forearms, bird legs with talons, white healer robe with pink trim, soft body, huge breasts",
            "name": "the pink-haired healer harpy with fluffy white wings",
            "pose": "spreading her fluffy white wings wide as if to embrace, gentle smile, head tilted, looking at viewer"},
   "e3":   {"type": "woman", "jp": "研究助手 セシル",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, loose side braid, green eyes, glasses, academy researcher robe, white blouse, long skirt, holding a blank book without text, polite smile, medium breasts",
            "name": "the blonde researcher with glasses and a braid",
            "pose": "holding a blank book without text to her chest, pushing up her glasses with one finger, polite smile, looking at viewer"},
   "boss": {"type": "woman", "jp": "ファルコンハーピー", "canon": True, "canon_img": "EU46.png",
            "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, tall, harpy, brown hair, long hair tied back, sharp gold eyes, confident warrior smile, huge dark brown and cream barred falcon wings, feathers on her forearms, bird legs with sharp talons, sleeveless dark leather warrior top, short feathered skirt, slender toned body, large breasts",
            "name": "the brown-haired falcon harpy with huge barred wings",
            "pose": "spreading her huge barred wings mid-landing, arms crossed under her breasts, confident smirk, looking down at viewer"},
 },
 "places": {
   "hall":      "grand tiered lecture hall, rows of wooden desks rising behind, large blackboard without text, lectern, warm light",
   "court":     "stone dueling stage in the academy courtyard at dusk, orange sky, gothic arches, old trees",
   "lab":       "elf lecturer's research room, tall bookshelves with blank books, alchemy glassware, leather armchair, low desk with papers without text",
   "range":     "shooting range behind the academy, wooden targets with blank faces, stone pillars, hay bales",
   "infirmary": "academy infirmary, white bed surrounded by white curtains, soft afternoon light",
   "library":   "academy library reading room after closing, tall bookshelves, long reading desk, green desk lamps",
   "tower":     "rooftop flight training ground on top of the academy clock tower, stone floor, wide bright sky and clouds",
   "observatory":"academy observatory at night, large brass telescope, open dome showing the starry sky, lamp",
   "classroom": "small classroom at night, a few wooden desks, lamp light, blackboard without text",
   "lounge":    "dormitory lounge at night, fireplace, big sofa with a feather duvet",
   "arena":     "circular training arena of the academy, sand floor, stone spectator stands with cushions",
   "office":    "faculty office after school, heavy wooden desk, bulletin board with blank papers without text, bookshelves",
   "greenhouse":"academy greenhouse, blooming flowers, green lawn, glass roof with sunlight",
   "exam":      "exam hall at dusk, rows of desks with blank answer sheets without text",
   "meadow":    "grassy hilltop meadow behind the academy used for flight practice, bright sky, wind",
 },
 "atk": {
   "m1": ("hall", "he stands before the lectern, the elf lecturer kneels in front of him squeezing his erection between her large breasts, paizuri, calm smile, looking up at him, precum"),
   "m2": ("court", "he kneels on the stone stage staring with an empty dazed expression, the elf lecturer stands before him slowly swaying her large breasts side to side, hypnosis, no hands on him, mouth open, hips twitching"),
   "m3": ("lab", "he sits naked in the leather armchair, the elf lecturer leans over from behind the chair, her lips at his ear lecturing softly, tongue in his ear, her fingers pinching both his nipples, trembling"),
   "e1": ("range", "he stands against a wooden target with his chest out, the gunner harpy flicks his nipples rapidly with the tip of a red feather, fast feather strikes, cocky grin, trembling"),
   "e2": ("infirmary", "he sits limp on the white bed, the healer harpy wraps him in her fluffy white wings in a warm embrace, his face pressed into her huge breasts, every muscle relaxed, feathers floating"),
   "e3": ("library", "he sits in a chair at the long reading desk, the researcher with glasses holds his face and kisses him deeply, tongues, saliva trail, blank answer sheets without text on the desk"),
   "boss": ("tower", "he lies on his back on the stone rooftop, the falcon harpy dives onto him and buries his face between her large breasts, her wings spread wide, stroking his nipple with a feather"),
 },
 "atk_desc": {
   "m1": "the elf lecturer squeezes him between her breasts.",
   "m2": "the elf lecturer hypnotizes him with the sway of her breasts.",
   "m3": "the elf lecturer gives him a private lesson at his ear.",
   "e1": "the gunner harpy rapid-fires feathers at his nipples.",
   "e2": "the healer harpy wraps him in a fluffy feather embrace.",
   "e3": "the researcher grades him with a kiss.",
   "boss": "the falcon harpy dives down and hugs his face into her breasts.",
 },
 "lose": {
   # エイライラ 技1（エルフの胸）
   "btl_m1":     ("hall", "he kneels before the lectern, the elf lecturer holds his penis in her cleavage and kisses its tip, paizuri, pinching his nipple, cum overflowing from her cleavage onto her pale skin, " + RED),
   "onani_m1":   ("hall", "sitting alone at a front desk of the tiered hall with both hands on his knees, rocking his hips while staring forward, flushed, penis untouched, the elf lecturer stands far away at the blackboard watching"),
   "inochi_m1":  ("hall", "he kneels before the lectern, the elf lecturer holds her large breasts together over his penis, paizuri, calm smile, cum on her chest, a glowing blank parchment without text on the floor, " + RED),
   "onedari_m1": ("office", "he sits in a chair before the heavy desk, the elf lecturer opens her large breasts as he cums, cum splashing onto her chest and collarbone, a blank application form without text on the desk, " + RED),
   # エイライラ 技2（揺れる講義）
   "btl_m2":     ("court", "he kneels on the stone stage at dusk staring blankly, the elf lecturer sways her breasts before his eyes and strokes his penis in the same rhythm, cum spurting, empty eyes, mouth open"),
   "onani_m2":   ("observatory", "sitting alone by the telescope with his hands on his knees, eyes following a small silver pendulum swinging before him, blank expression, mouth open, penis untouched, the elf lecturer watches from across the dome"),
   "inochi_m2":  ("lab", "he sits limply in a chair in the research room, the elf lecturer stands before him swaying her breasts, hypnosis, no hands on him, cum spurting, blank eyes, a pendulum clock on the wall, " + RED),
   "onedari_m2": ("classroom", "he stands at the front desk under the lamp, the elf lecturer sways her breasts up, down and in circles before him, hypnosis, no hands on him, his face empty, cum on the floor below the blackboard, " + RED),
   # エイライラ 技3（個人指導）
   "btl_m3":     ("lab", "he sits in the leather armchair with his back arched, the elf lecturer behind him whispers into his ear with her lips touching it, pinching both his nipples, no hand on his penis, cum splashing on the floor"),
   "onani_m3":   ("classroom", "sitting alone at a desk at night with his fists on his knees, eyes closed as if listening, hips twitching, nipples erect, penis untouched, the elf lecturer walks between the desks far away watching"),
   "inochi_m3":  ("library", "he sits slumped at a reading desk, the elf lecturer stands behind him with her lips at his ear, pinching his nipples, reading from a blank book without text, cum under the desk"),
   "onedari_m3": ("lab", "he sits on the elf lecturer's lap on the leather sofa, the elf lecturer licks his ear and pinches his nipple, her other hand stroking his penis, cum on his chest, a blank form without text on the low table"),
   # ガンナーハーピー（羽根の早撃ち）
   "btl_e1":     ("range", "he kneels against a wooden target, the gunner harpy squeezes his penis between her perky breasts, paizuri, flicking his nipple with a red feather, cum up to her chin"),
   "onani_e1":   ("exam", "sitting alone at an exam desk with his shirt open, flicking his own nipple rapidly with the tip of a quill pen, blank answer sheet without text, penis untouched, the gunner harpy watches from the back of the hall"),
   "inochi_e1":  ("range", "he stands before a target with his hands behind his head and chest out, the gunner harpy flicks his nipples with a red feather, no hand on his penis, cum dripping, " + RED),
   "onedari_e1": ("arena", "he sits on the gunner harpy's lap in the front row of the stands, his penis pressed under her breasts, the gunner harpy flicks both his nipples with red feathers, cum splashing up her cleavage"),
   # ヒーラーハーピー（ふわふわの）
   "btl_e2":     ("infirmary", "he lies limp inside a cocoon of the healer harpy's fluffy white wings, sucking her breast, his penis squeezed between her soft thighs, cum between her thighs, feathers everywhere"),
   "onani_e2":   ("lounge", "lying alone on the sofa by the fireplace wrapped in a thick feather duvet, completely relaxed, slowly stroking his own chest, dreamy face, penis untouched, the healer harpy watches from a chair far away"),
   "inochi_e2":  ("infirmary", "he lies limp on the white bed, the healer harpy wraps him in her fluffy wings, his face in her huge breasts, his penis between her thighs, cum soaking her white feathers, " + RED),
   "onedari_e2": ("greenhouse", "he lies on the lawn among flowers wrapped in the healer harpy's fluffy wings, sucking her breast, the healer harpy slowly strokes his penis and brushes his nipple with a wingtip, cum on her hand"),
   # セシル（採点の口づけ）
   "btl_e3":     ("library", "he sits in a chair, the researcher with glasses sits sideways on his lap kissing him deeply, sucking his tongue, her hand stroking his penis under the desk, cum on her fingers"),
   "onani_e3":   ("classroom", "sitting alone at a desk in the afternoon light, pressing his lips to the back of his own hand again and again, counting, penis untouched, the researcher with glasses watches from the teacher's desk"),
   "inochi_e3":  ("exam", "he sits at a desk piled with blank answer sheets without text, the researcher with glasses kisses him deeply, tongues, pinching his nipple, stroking his penis, cum on the answer sheets"),
   "onedari_e3": ("exam", "he sits on a chair in the empty exam hall, the researcher with glasses kneels between his legs kissing the tip of his penis, pinching his nipple, cum on her lips and glasses"),
   # ファルコンハーピー（急降下の抱擁）
   "btl_boss":   ("tower", "he lies on his back on the rooftop, the falcon harpy lies on him burying his face between her large breasts, stroking his nipple with a feather, her knee pressing his penis, cum on her knee, wings spread"),
   "onani_boss": ("arena", "sitting alone in the stands pressing a cushion against his own face, stroking his own nipple with a fallen brown feather, penis untouched, the falcon harpy watches from the arena sand"),
   "inochi_boss":("tower", "he lies on his back on the rooftop with his arms spread, the falcon harpy presses his face between her breasts, her knee rubbing his penis, feather on his nipple, cum on his belly, " + RED),
   "onedari_boss":("meadow", "he is lifted into the air hugged by the falcon harpy, his face buried in her large breasts, his penis between her thighs, her huge wings beating, cum dripping onto the grass below"),
 },
 "lose_desc": "keeps him in the academy as her research subject.",
 "onanie": {
   "master": ("classroom", "sitting with both hands on his knees, eyes following a silver pendulum swinging before him, empty expression, mouth open, hips twitching, penis untouched"),
   "e1": ("range", "standing with his shirt open, flicking his own nipple rapidly with the tip of a red feather, penis untouched"),
   "e2": ("lounge", "wrapped in a thick feather duvet, completely relaxed, slowly stroking his own chest, penis untouched"),
   "e3": ("library", "sitting at the reading desk, pressing his lips to the back of his own hand again and again, penis untouched"),
   "boss": ("tower", "lying on his back pressing a cushion against his own face, stroking his own nipple with a brown feather, penis untouched"),
 },
 "magic": {
   "1": ("m", "hall", "holding out a sheet of blank paper without text with a glowing red circle stamp, calm smile, magic sparkles"),
   "2": (None, "tower", "a folded blank letter without text carried on the wind with swirling feathers above the academy rooftops"),
   "3": ("boss", "meadow", "beating her huge wings to create a powerful tailwind gust, grass and feathers blowing, confident smile"),
   "4": ("e2", "infirmary", "spreading her fluffy wings to release a gentle glowing healing breeze, soft green and white light, floating feathers"),
   "5": (None, "hall", "the grand tiered lecture hall glowing with magic light, floating blank books, chalk dust sparkling in the sunbeams"),
 },
}
