# N62 格下のF級マスター（Eruru）画像データ。登場人物は全員20歳以上（学園の上級課程・成人の学生）。全員女性。ノート・札・判・掲示は文字なし。
# 本編キャラ（エルル・生意気キャロル・怪盗サキュバス）は本編の立ち絵を見ずに、本文の手がかり（制服の胸元のリボン・黒い革のグローブ等）と役から決めた見た目。
SEAL = "small red seal marks on his forehead"

DATA = {
 "code": "Eruru",
 "world": "fantasy magic academy for adult students next to an adventurers guild, stone corridors, wooden classrooms, warm lamplight, detailed background",
 "bg": "empty classroom of a fantasy magic academy after class, rows of wooden desks pushed together, blank blackboard without text, sunset light through tall arched windows",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "エルル", "canon": True, "canon_img": "F6_Eruru.png",
         "tags": "adult woman, mature female, mature face, 20 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long hair, twintails, red hair ribbons, violet eyes, academy uniform for adults, white blouse, red ribbon tie, black pleated skirt, black thighhighs, rogue, tsundere smirk, large breasts",
         "name": "the blonde-twintailed senior in an academy uniform",
         "pose": "arms crossed under her chest, chin raised, smug tsundere smirk, looking down at viewer"},
   "e1": {"type": "woman", "jp": "生意気キャロル", "canon": True, "canon_img": "EU17_Carol.png",
          "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, gyaru, orange hair, long wavy hair, pink eyes, tanned skin, off-shoulder crop top, short denim skirt, rogue, smug teasing grin, huge breasts",
          "name": "the tanned orange-haired gyaru in a crop top",
          "pose": "leaning forward pushing her huge breasts together with her arms, tongue out, mocking grin, looking at viewer"},
   "e2": {"type": "woman", "jp": "同級生 マリベル",
          "tags": "adult woman, mature female, mature face, 20 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, bob cut, green eyes, academy blazer uniform for adults, knee-length skirt, black pantyhose, holding a notebook and a pen, teasing smile, medium breasts",
          "name": "the pink-bobbed classmate holding a notebook",
          "pose": "hugging a notebook to her chest, tapping her lips with a pen, polite teasing smile, looking at viewer"},
   "e3": {"type": "woman", "jp": "同級生 ティナ",
          "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, black hair, side ponytail, red eyes, academy uniform for adults, beige cardigan, knee-length skirt, black pantyhose, chatty grin, medium breasts",
          "name": "the black-haired classmate in a beige cardigan",
          "pose": "one hand cupped beside her mouth as if whispering a secret, winking, chatty grin, looking at viewer"},
   "boss": {"type": "woman", "jp": "怪盗サキュバス", "canon": True, "canon_img": "EU70.png",
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, phantom thief, wine red hair, long hair, gold eyes, black domino mask, small black horns, black bat wings, black leather gloves, black tailcoat over a black leotard, black thighhighs, confident alluring smile, large breasts",
            "name": "the masked red-haired phantom thief succubus in black leather gloves",
            "pose": "one gloved finger on her lips, the other hand twirling a pink jewel, alluring smile, looking at viewer"},
 },
 "places": {
   "yard": "training yard behind the adventurers guild, packed dirt ground, wooden target dummies, stone wall",
   "classroom": "empty academy classroom after class, desks pushed together as a card table, blank blackboard without text, teacher's desk, sunset light",
   "locker": "guild changing room, wooden lockers, long wooden bench, lamplight",
   "rooftop": "academy rooftop at noon, tall fence, water tower, blue sky",
   "lecture": "academy lecture hall, long wooden desks in rows, back row seat, notebooks without text",
   "corridor": "academy stone corridor corner at dusk, arched windows, long shadows",
   "clocktower": "inside a stone clock tower at night, huge gears, moonlight through the clock face window",
   "library": "academy library reading desks in the back, tall bookshelves, lamplight, quiet",
   "tavern": "adventurers guild tavern at night, wooden tables, card table, mugs, lamplight",
   "courtyard": "academy courtyard with a wooden bench, flower beds, noon sunlight",
   "exhibit": "academy treasure exhibition hall at night, glass display cases, moonlight",
   "storage": "guild storage room, stacked old wooden crates, dust in the lamplight",
   "guildroof": "guild building rooftop at night, stone floor, bright full moon",
   "breakroom": "guild staff break room behind the reception, worn leather sofa, lamp",
   "dorm": "adult student dormitory room, bed with a pink blanket, rug on the floor, shelf with trophies, desk lamp",
   "vault": "guild treasure vault at midnight, wooden chests full of gold coins, jewels, candlelight",
 },
 "atk": {
   "m1": ("yard", "he stands with his back to the guild wall, the senior stands close stroking his penis with her bare hand, teaching gesture, smug smirk, his hips pulling back, trembling"),
   "m2": ("classroom", "he leans back against the teacher's desk, the senior holds his chin and kisses him deeply, purple magic glow flowing from her lips into his, tongues, saliva trail"),
   "m3": ("locker", "he sits on the long bench, the senior kneels between his legs with her blouse open, sandwiching his penis in her cleavage, pinching his nipple, smug smirk"),
   "e1": ("rooftop", "he sits against the fence, the gyaru straddles his legs and smothers his face between her huge breasts, bouncing them, mocking grin, his hands limp"),
   "e2": ("lecture", "he sits in the back row, the classmate beside him pokes his nipple through his shirt with the corner of her notebook, calm teasing smile, his hands gripping the desk"),
   "e3": ("corridor", "he stands against the corridor wall, the classmate leans in whispering into his ear, one hand cupped by her mouth, no hands on his body, his knees trembling, blush"),
   "boss": ("clocktower", "he sits on the stone floor, the phantom thief succubus kneels over him kissing him deeply, her black leather gloved fingers circling both his nipples, pink sparkles"),
 },
 "atk_desc": {
   "m1": "the senior gives her junior a hands-on lesson.",
   "m2": "the senior drains his magic with a kiss.",
   "m3": "the senior locks him inside her cleavage.",
   "e1": "the gyaru disciplines him as a breast masochist.",
   "e2": "the classmate pokes him with the corner of her notebook.",
   "e3": "the classmate whispers a rumor that rewrites his common sense.",
   "boss": "the phantom thief steals his desire with gloves and lips.",
 },
 "lose": {
   # エルル 技1（格下への手ほどき・手コキ）
   "btl_m1": ("yard", "he kneels on the packed dirt, the senior stands before him slowly opening and closing her empty hand, his hips pulling back, cum soaking his trousers, " + SEAL),
   "onani_m1": ("courtyard", "sitting alone on the ground, sucking two of his own fingers, the other hand rubbing his own nipple under his shirt, penis untouched, the senior watches from a far bench with a smirk"),
   "inochi_m1": ("yard", "he sits against the stone wall, the senior crouches before him stroking his penis with her bare hand, smug smirk, cum on her fingers, " + SEAL),
   "onedari_m1": ("breakroom", "he sinks into the leather sofa, the senior sits beside him stroking his penis with her bare hand, teasing smile, cum on her palm, his hands clutching the cushion"),
   # エルル 技2（魔力の口づけ）
   "btl_m2": ("classroom", "he slumps against the teacher's desk, the senior holds his face and kisses him deeply, purple magic glow drawn from his lips, tongues, saliva trail, cum soaking his trousers"),
   "onani_m2": ("library", "sitting alone at a reading desk, pressing two of his own fingers to his lips and sucking them, the other hand on his own nipple, penis untouched, the senior watches from between the shelves"),
   "inochi_m2": ("classroom", "he leans against the teacher's desk in the sunset, the senior kisses him deeply sucking his tongue, purple glow on her fingertips, his knees buckling, cum soaking his trousers"),
   "onedari_m2": ("rooftop", "he sits in the shadow of the water tower, the senior blows a kiss from a few steps away with a purple heart of magic, no hands on him, his back arched, cum stain"),
   # エルル 技3（谷間に閉じ込めて）
   "btl_m3": ("locker", "he kneels on the floor, the senior sits on the bench with her ribbon untied and blouse open, sandwiching his penis in her cleavage, pinching his nipple, cum on her breasts"),
   "onani_m3": ("tavern", "kneeling alone beside the card table, staring up, sucking his own fingers, the other hand pinching his own nipple, penis untouched, the senior leans over the far table showing her cleavage"),
   "inochi_m3": ("storage", "he sits against the old crates, the senior kneels between his legs with her blouse open, trapping his penis in her cleavage, arms crossed under her breasts, cum spurting, dust in the lamplight"),
   "onedari_m3": ("dorm", "he kneels on the rug, the senior sits on her bed with her blouse open, his penis trapped deep in her cleavage, smug smile, cum between her breasts"),
   # キャロル（おっぱいマゾの躾）
   "btl_e1": ("rooftop", "he sits against the fence, the gyaru hugs his head deep into her huge cleavage, mocking grin, his hips jerking, cum soaking his trousers"),
   "onani_e1": ("courtyard", "kneeling alone on the grass, his face pressed into his own rolled-up jacket, stroking his own chest, breath shallow, penis untouched, the gyaru watches from the bench laughing"),
   "inochi_e1": ("tavern", "he lies on a long bench in the dim back of the tavern, the gyaru lies on top of him smothering his face in her huge breasts, mocking grin, cum stain"),
   "onedari_e1": ("locker", "he kneels before the long bench, the gyaru sits on the bench pulling his face into her huge wet cleavage, bouncing her breasts, his hips jerking"),
   # マリベル（ノートの端で）
   "btl_e2": ("lecture", "he slumps in the back-row chair with his shirt open, the classmate touches his nipple with the corner of her notebook, writing tally marks with her pen, cum dripping on the chair"),
   "onani_e2": ("lecture", "sitting alone at a long desk, poking his own nipple through his shirt with the back end of a pen, a notebook corner rubbing the other nipple, penis untouched, the classmate watches from the far end of the row"),
   "inochi_e2": ("lecture", "he sits on the floor against a long desk, the classmate kneels beside him poking his bare nipple with the back end of her pen, notebook open without text, cum on the floor"),
   "onedari_e2": ("library", "he sits beside the classmate at a back reading desk, the classmate pokes his nipple with her notebook corner, finger on her lips for silence, his shirt open, cum stain"),
   # ティナ（耳打ちの噂）
   "btl_e3": ("corridor", "he sinks down against the corridor wall, the classmate leans to his ear whispering, hand cupped by her mouth, no hands on him, cum soaking his trousers"),
   "onani_e3": ("lecture", "sitting alone at an empty desk with his hands flat on the desk, whispering words to himself, flushed, hips twitching, penis untouched, the classmate watches from the doorway grinning"),
   "inochi_e3": ("corridor", "he is cornered against the corridor wall, the classmate whispers into his ear, blowing softly, no hands on him, his knees buckling, cum stain, dusk light"),
   "onedari_e3": ("dorm", "he sits curled on the edge of the bed in the dormitory at night, the classmate leans on his shoulder whispering into his ear, no hands on him, trembling"),
   # 怪盗サキュバス（欲望の盗み取り）
   "btl_boss": ("clocktower", "he sits on the stone floor, the phantom thief succubus kisses him deeply, her black leather gloves circling both his nipples, pink light drawn from his chest, cum on the floor"),
   "onani_boss": ("exhibit", "sitting alone on the floor between glass cases wearing a single black leather glove, circling his own nipple with the gloved fingers, sucking the fingers of his other hand, penis untouched, the phantom thief watches from atop a display case"),
   "inochi_boss": ("guildroof", "he lies on his back on the stone roof, the phantom thief succubus straddles his chest, her gloved fingers circling his nipples, kissing him, bright full moon, " + SEAL),
   "onedari_boss": ("vault", "he leans against a chest of gold coins, the phantom thief succubus holds a glowing pink jewel to his lips, her other gloved hand circling his nipple, cum stain, candlelight"),
 },
 "lose_desc": "keeps him forever as her low-rank errand boy.",
 "onanie": {
   "master": ("classroom", "sitting at a desk, sucking two of his own fingers deeply as if kissing, the other hand tracing his own nipple, penis untouched"),
   "e1": ("rooftop", "face pressed into his own rolled-up jacket, breath shallow, stroking his own chest with both hands, penis untouched"),
   "e2": ("lecture", "sitting at a long desk, poking his own nipple with the back end of a pen and rubbing it with the corner of a notebook without text, penis untouched"),
   "e3": ("corridor", "leaning on the corridor wall with his hands pressed flat against it, whispering to himself, flushed, hips twitching, penis untouched"),
   "boss": ("exhibit", "wearing a black leather glove on one hand, circling his own nipple with it, sucking two fingers of his other hand, penis untouched"),
 },
 "magic": {
   "1": ("m", "yard", "the senior stands with her arms crossed looking down with a smug smile, golden aura of superiority around her, wind blowing her twintails"),
   "2": (None, "corridor", "a folded note without text pinned to a wooden locker door in the academy corridor, sunset light"),
   "3": ("boss", "clocktower", "the phantom thief succubus beckons with a gloved finger from swirling dark purple mist, glowing gold eyes, alluring smile"),
   "4": ("m", "classroom", "the senior tugs the collar of her white blouse open with one finger showing her cleavage, loosened ribbon tie, blushing smug look"),
   "5": (None, "classroom", "an empty academy classroom after class, desks pushed together, a single chair in the middle, blank blackboard without text, long sunset shadows"),
 },
}
