# N63 昇格試験・再試験（Exam）画像データ。登場人物は全員20歳以上。全員女性。採点表・書類・申込書・採点板は文字なし。
# 本編キャラ（試験官・アーチャー・大剣使いの守護傭兵・サキュバススナイパー）は本編の立ち絵を見ずに、本文の手がかり（弓・鎧・大剣・赤い瞳・ブーツ等）と役から決めた見た目。
SHEET = "a blank grading sheet without text with red seal marks"

DATA = {
 "code": "Exam",
 "world": "fantasy adventurers guild hall used for rank promotion exams, wooden counters, stone walls, lamplight, detailed background",
 "bg": "interior of a fantasy adventurers guild exam room, long wooden desk with a blank grading sheet without text, wall clock without numbers, bookshelves, stone walls, lamplight",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "試験官", "canon": True, "canon_img": "F07_Stand.png",
         "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, tall, blonde hair, medium hair, side braid, amber eyes, hunter, guild examiner, short green jacket, white shirt, brown shorts, belt with pouches, knee boots, cheerful smile, large breasts",
         "name": "the blonde examiner in a short green jacket",
         "pose": "waving one hand cheerfully, the other hand on her hip, bright playful smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "アーチャー", "canon": True, "canon_img": "EU19_Stand.png",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, auburn hair, short ponytail, green eyes, archer, brown leather hunter outfit, short cape, quiver of arrows with white feathers, longbow on her shoulder, playful smile, medium breasts",
          "name": "the auburn-haired archer with a longbow",
          "pose": "longbow resting on her shoulder, twirling a white arrow feather between her fingers, playful smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "大剣使いの守護傭兵", "canon": True, "canon_img": "EU18_Stand.png",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, very tall, athletic curvy body, black hair, long hair, dark red eyes, mercenary, silver breastplate and pauldrons, dark red cloth, armored skirt, huge greatsword, bold smirk, huge breasts",
          "name": "the tall black-haired mercenary in silver armor",
          "pose": "the huge greatsword planted in the ground beside her, one hand on its hilt, bold smirk, looking down at viewer"},
   "e3": {"type": "woman", "jp": "試験補佐 ミント",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, light green hair, short bob, brown eyes, guild staff vest, white blouse, black pencil skirt, black pantyhose, holding a blank clipboard, serious expression, medium breasts",
          "name": "the light-green-bobbed exam assistant with a clipboard",
          "pose": "holding a blank clipboard against her chest, pen raised, serious businesslike expression, looking at viewer"},
   "boss": {"type": "woman", "jp": "サキュバススナイパー", "canon": True, "canon_img": "EU20_sniper.png",
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, sniper, silver hair, long hair, glowing red eyes, small black horns, black bat wings, black bodysuit, long black coat, thigh boots, long rifle, cool expression, large breasts",
            "name": "the silver-haired succubus sniper with glowing red eyes",
            "pose": "long rifle held upright at her side, two fingers pointing at viewer like a gun, cool narrow-eyed stare, looking at viewer"},
 },
 "places": {
   "examroom": "guild basement practical exam room, long wooden bench, desk with " + SHEET + ", stone walls, lamplight",
   "infirmary": "guild infirmary, white bed, white curtain, medicine shelf, bright window",
   "interview": "small guild interview room, hard wooden chair, desk, two-seat sofa, lamplight",
   "range": "archery range behind the guild at sunset, straw targets, wooden fence, orange sky",
   "training": "night training ground of sand, burning bonfire, weapon racks",
   "records": "guild records room on the third floor, tall bookshelves, long desk, ink bottles, blank papers without text",
   "tower": "top floor of a stone watchtower at night, moonlight through a wide window, sniper platform",
   "hall": "guild great hall with an exam table in the middle, big wall clock without numbers, empty benches",
   "arena": "night stone arena with empty stone seats, torches",
   "library": "guild library, study desk deep between the bookshelves, wall clock without numbers, answer sheets without text",
   "classroom": "guild written-exam classroom, single desk, lectern, blank blackboard without text",
   "lodge": "small guild lodging room at night, simple bed with two pillows, window with moonlight",
   "locker": "guild changing room with a wall-sized mirror, wooden lockers, bench",
   "counter": "guild reception counter after closing, wooden counter, papers without text, lamp",
   "forest": "forest clearing at night, campfire, fallen log, quiver of arrows on the ground",
   "merc_room": "room above a tavern, single wooden bed, a greatsword leaning on the wall, candlelight",
 },
 "atk": {
   "m1": ("examroom", "he sits on the long bench, the examiner sits beside him slowly stroking his penis with her hand then stopping just before he cums, checking a pocket watch, cheerful smile, his hips shaking"),
   "m2": ("infirmary", "he sits on the edge of the white bed with his shirt open, the examiner leans in rolling only his nipples with her fingertips, a pocket watch in her other hand, timing him, trembling"),
   "m3": ("interview", "he sits on the hard chair, the examiner behind him whispers into his ear and licks it, her hand slowly stroking his penis and stopping, edging, his toes curled"),
   "e1": ("range", "he stands with his back against a straw target, the archer brushes the white feather of an arrow over his bare nipples, playful smile, his chest arching"),
   "e2": ("training", "he lies on the sand, the mercenary in armor sits and pulls his face deep into her huge cleavage, hugging his head, bonfire light, his arms limp"),
   "e3": ("records", "he sits at the long desk, the exam assistant holds his chin and kisses him, clipboard held in her other hand, serious face, his lips trembling"),
   "boss": ("tower", "he sits frozen on the moonlit floor, the succubus sniper stares into his eyes with glowing red eyes, pink heart-shaped crosshair light on his chest, her fingers pinching his nipples"),
 },
 "atk_desc": {
   "m1": "the examiner gives him the endurance test with her hand.",
   "m2": "the examiner times how long he lasts with only his nipples.",
   "m3": "the examiner grades him by whispering into his ear.",
   "e1": "the archer tickles his nipples with arrow feathers.",
   "e2": "the mercenary buries his face in her chest.",
   "e3": "the exam assistant gives him a grading kiss.",
   "boss": "the succubus sniper locks her charm sight on him.",
 },
 "lose": {
   # 試験官 技1（我慢テスト・手コキ）
   "btl_m1": ("examroom", "he slumps on the long bench, the examiner holds her open palm just above his penis without touching, thin cum leaking, " + SHEET + " on the desk, his breath ragged"),
   "onani_m1": ("hall", "standing alone at the exam table, both hands pinching his own nipples under his shirt, glancing at the wall clock, penis untouched, the examiner watches from across the table laughing"),
   "inochi_m1": ("examroom", "he leans with his hands on the desk, the examiner waves her open hand close to his penis without touching, cum dripping, cheerful smile, " + SHEET),
   "onedari_m1": ("counter", "he leans on the reception counter panting, the examiner reaches her open hand toward his face from behind the counter, his breath ragged, a blank application form without text"),
   # 試験官 技2（実技指導・乳首）
   "btl_m2": ("infirmary", "he lies on the white bed with his shirt open, the examiner pinches both his nipples, a pocket watch hanging from her finger, thin cum leaking, " + SHEET + " on the side desk"),
   "onani_m2": ("arena", "sitting alone on the arena floor, a pocket watch in one hand, rolling his own nipple through his shirt with the other, counting minutes, penis untouched, the examiner watches from the stone seats"),
   "inochi_m2": ("infirmary", "he lies on the white bed with his chest bare, the examiner points one finger at his nipple without touching, his nipples erect, his body frozen waiting, cheerful smile"),
   "onedari_m2": ("interview", "he sits with his shirt open, three hourglasses on the shelf behind, the examiner flicks his nipple with her fingernail, an hourglass running on the table, blush, trembling"),
   # 試験官 技3（耳元の採点）
   "btl_m3": ("interview", "he sits on the hard chair, the examiner leans from behind whispering into his ear, her hand stopped just before his penis, cum leaking, trembling"),
   "onani_m3": ("library", "sitting alone at a study desk deep between the shelves, one hand pinching his own nipple, whispering to himself, penis untouched, the examiner peeks from the end of the shelf"),
   "inochi_m3": ("records", "he collapses from his chair at night, the examiner catches him from behind whispering into his ear, desk lamp, cum stain, a blank form without text on the desk"),
   "onedari_m3": ("interview", "he sits on the two-seat sofa, the examiner with her arm around his shoulders licks his right ear and whispers, her hand stroking his penis and stopping, edging"),
   # アーチャー（矢羽根）
   "btl_e1": ("range", "he stands against a straw target at sunset with his shirt open, the archer brushes a white arrow feather across his nipple, cum dripping, playful smile"),
   "onani_e1": ("classroom", "sitting alone at the single desk, brushing the feather end of a quill pen over his own nipple through his open shirt, a blank answer sheet without text, penis untouched, the archer watches from the lectern"),
   "inochi_e1": ("range", "he kneels before the straw targets with his shirt open, the archer brushes a white arrow feather over both his nipples, no hands on him, cum dripping"),
   "onedari_e1": ("forest", "he sits on a fallen log by the campfire with his shirt open, the archer kneels beside him circling his nipple with a long tail feather, a quiver full of feathers beside"),
   # 大剣使いの守護傭兵（胸の中で）
   "btl_e2": ("training", "he lies limp on the sand, the armored mercenary hugs his face into her huge cleavage, bonfire light, cum dripping, his arms hanging"),
   "onani_e2": ("lodge", "lying alone on the bed at night, his face pressed between two stacked pillows, stroking his own chest, penis untouched, the mercenary watches from the open door"),
   "inochi_e2": ("arena", "he sits on the arena steps by the torches, the mercenary hugs his face deep into her huge cleavage, her armor loosened, his knees trembling, cum stain"),
   "onedari_e2": ("merc_room", "he kneels on the wooden bed with his face buried from the front in the mercenary's huge cleavage, the mercenary hugs him tight, greatsword against the wall, candlelight"),
   # ミント（採点のキス）
   "btl_e3": ("records", "he sits at the long desk, the exam assistant kisses him deeply while holding the blank clipboard, her serious face, cum stain, ink bottles"),
   "onani_e3": ("interview", "sitting alone in a small waiting room, kissing the back of his own hand again and again, a finger tracing his own lips, penis untouched, the exam assistant watches from a corner desk"),
   "inochi_e3": ("records", "he sits on the floor against the file shelves, the exam assistant kneels and kisses him softly, clipboard under her arm, his body trembling, cum stain"),
   "onedari_e3": ("classroom", "he slumps over an exam desk in the empty evening classroom, the exam assistant leans over and kisses him, clipboard in hand, calm face"),
   # サキュバススナイパー（魅了の照準）
   "btl_boss": ("tower", "he sits frozen on the moonlit floor, the succubus sniper points two fingers at him like a gun, glowing red eyes, pink crosshair on his chest, no hands on him, cum dripping"),
   "onani_boss": ("locker", "standing alone before the wall-sized mirror, staring into his own reflection, pinching his own nipples at a steady rhythm, penis untouched, the succubus sniper watches in the mirror from behind with red eyes"),
   "inochi_boss": ("tower", "he lies on his back on the sniper platform, the succubus sniper stands over him pointing a finger, glowing red eyes, pink crosshair on his chest, his body frozen, moonlight"),
   "onedari_boss": ("training", "he kneels bare-chested in front of a wooden target at night, the succubus sniper stares down with glowing red eyes, her fingers pinching both his nipples, moon behind her"),
 },
 "lose_desc": "keeps him at the guild forever as a permanent exam failure.",
 "onanie": {
   "master": ("infirmary", "sitting on the bed, glancing at a pocket watch, rolling only his own nipples under his shirt, counting minutes, penis untouched"),
   "e1": ("classroom", "sitting at a desk, brushing the feather end of a quill pen over his own nipple like sweeping, penis untouched"),
   "e2": ("lodge", "face pressed between two stacked pillows, pushing them together harder, stroking his own chest, penis untouched"),
   "e3": ("records", "sitting at the long desk, kissing the back of his own hand repeatedly, tracing his own lips with a finger, penis untouched"),
   "boss": ("locker", "staring into his own eyes in the wall mirror, pinching his own nipples at a steady interval, penis untouched"),
 },
 "magic": {
   "1": (None, "counter", "a sealed envelope without text with a red wax seal on the guild counter, a stamp and a red ink pad beside it"),
   "2": ("m", "hall", "the examiner raises a hunting horn and blows it, calling hunters, cheerful smile, cape of her jacket fluttering"),
   "3": ("e3", "examroom", "the exam assistant suddenly appears holding up a blank clipboard with a stern face, pointing a pen, surprise inspection"),
   "4": ("m", "examroom", "the examiner holds up a large hourglass and turns it over with a playful wink, the sand flowing, extra time"),
   "5": (None, "hall", "the guild great hall set up as a promotion exam venue, exam table in the center, empty benches, big wall clock without numbers, banners without text"),
 },
}
