# N76 西の鉱山の守護者（Gemini）画像データ。登場人物は全員20歳以上。女性のみ（挿入はルベリアの紅玉の張形＝ペニバンだけ）。女装なし。
# マスターのジェミニは本編キャラ（70024・F24.png）。本編の立ち絵は見られないので、brief の手がかり（重たい胸・宝石の首飾り・垂れ目・肘置き）＋役に合う見た目。
ST = {"pen": "strapon"}   # ルベリアの紅玉の張形（赤い宝石飾りのペニバン）

DATA = {
 "code": "Gemini",
 "world": "fantasy gem mine in the western mountains, oil lanterns, glowing crystal veins in the rock, detailed background",
 "bg": "interior of a gem mine tunnel, glowing crystal veins on the rock walls, mine cart rails, hanging oil lanterns, wooden support beams, dripping water",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ジェミニ", "canon": True, "canon_img": "F24.png",
         "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, tall, long legs, light brown hair, long wavy hair, droopy eyes, hazel eyes, gentle smile, gold necklace with many gemstone settings, off-shoulder white blouse, brown corset vest, long skirt, boots, deep cleavage, huge breasts, heavy breasts",
         "name": "the light-brown-haired guardian with huge breasts and a gem necklace",
         "pose": "resting her heavy breasts on a padded armrest cushion held in her arms, gentle droopy-eyed smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "ルチル",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long braid, amber eyes, magnifying loupe hanging on a cord around her neck, leather apron over a white shirt, rolled-up sleeves, polishing cloth, large breasts",
          "name": "the blonde gem polisher in a leather apron",
          "pose": "holding a polishing cloth between her fingers, peering through her loupe, focused smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "ベリル",
          "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, green hair, short hair, brown eyes, miner's helmet with a lamp, soot-stained tank top, work pants, thick thighs, curvy, plump body, large breasts",
          "name": "the green-haired miner forewoman in a helmet and tank top",
          "pose": "hands on her hips, a pickaxe on her shoulder, bold grin, looking at viewer"},
   "e3": {"type": "woman", "jp": "アメシア",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, very long straight hair, crystal hair tips, purple eyes, sheer layered crystal-like dress, barefoot, mineral spirit, dreamy expression, medium breasts",
          "name": "the purple-haired crystal spirit in a sheer crystal dress",
          "pose": "holding up a small glowing crystal, half-closed dreamy eyes, looking at viewer"},
   "boss": {"strap": "ruby red strap-on on a red leather harness", "type": "woman", "jp": "ルベリア",
            "tags": "adult woman, mature female, mature face, 32 years old, adult proportions, beautiful detailed eyes, tall, long legs, crimson hair, long curly hair, red eyes, large ruby gem on her chest, red velvet gown, long red gloves, elegant, large breasts",
            "name": "the crimson-haired ruby lady in a red velvet gown",
            "pose": "one long-gloved hand on the ruby at her chest, elegant smile, looking at viewer"},
 },
 "places": {
   "patrol": "narrow mine tunnel patrol path, swaying oil lanterns, damp rock walls, dripping water, wooden support beams",
   "vein": "large cavern hall of ore veins, glowing gemstone veins pulsing on the rock walls, warm rock floor",
   "crevice": "cramped side tunnel barely wide enough for one person, rough earthen walls, low ceiling, one small lantern",
   "barracks": "miners' break room, soot-stained long bench, pickaxe rack, a single oil lamp at night",
   "polish": "gem polishing workshop, spinning grinding wheel, fine sparkling stone dust, wooden workbench with a large magnifying lens",
   "crystal": "crystal cave, large crystals hanging from the ceiling, flickering prismatic light",
   "lake": "shore of an underground lake, mirror-like still water, glowing moss",
   "sort": "gem sorting table at the end of mine cart rails, piles of raw gemstones",
   "hut": "guard hut at the mine entrance, wooden desk with a patrol map without text, blank calendar without text on the wall, oil lamp",
   "ruby": "ruby chamber, red velvet walls and floor, red velvet chaise longue, many candles, large open jewelry box with gold trim",
   "atelier": "gem artisan's atelier, shelves lined with raw gemstones, wooden workbench, sparkling window light",
   "window": "atelier window seat at sunset, a glass bead on the windowsill, sparkling gems on the shelves",
   "bed": "bed in the atelier, fluffy feather duvet, soft pillows, a padded armrest cushion by the pillow",
   "engawa": "sunny wooden veranda of the atelier, warm wooden floor, sunlight, a wooden pillar",
   "plaza": "village square at night after a festival, empty cobblestones, wooden bench, a jewelry shop window glowing",
   "closet": "inside a cramped wooden closet, folded thick blankets, dim light through the door gap",
 },
 "atk": {
   "m1": ("bed", "he lies on his back on the feather duvet, the guardian kneels over his hips resting her huge heavy breasts on his crotch, paizuri, his penis buried deep in her cleavage through her open neckline, her weight pinning his hips, trembling"),
   "m2": ("vein", "he lies on his back on the warm rock floor, the guardian lies over him dropping her huge breasts onto his face, breast smother, his nose and mouth covered, swaying her breasts, glowing veins, his hands limp"),
   "m3": ("crystal", "he sits against a crystal pillar, the guardian stands over him pulling her deep cleavage open with two fingers, her knee grinding his crotch, kneejob, his face fixed on her cleavage, trembling"),
   "e1": ("polish", "he lies on the workbench, the gem polisher leans over him peering through her loupe, polishing his nipple in small circles with a cloth-wrapped fingertip, her other hand stroking his penis, handjob, sparkling dust"),
   "e2": ("crevice", "he is pinned against the earthen wall of the cramped tunnel, the miner forewoman presses her whole body against him, her big breasts crushing his face, her strong arms locking his shoulders, hug, helmet lamp light, sweat"),
   "e3": ("crystal", "he kneels in the crystal cave looking up, dazed, the crystal spirit sways her crystal-tipped hair before his eyes, whispering, ceiling crystals flashing, no hands on him, mouth open, trembling"),
   "boss": ("ruby", "he lies on the red velvet chaise longue, the ruby lady leans over him kissing him deeply, tongues, her long-gloved fingers rolling his nipple, the ruby on her chest glowing, saliva trail"),
 },
 "atk_desc": {
   "m1": "the guardian gives him her thank-you paizuri.",
   "m2": "the guardian smothers his face with her heavy breasts.",
   "m3": "the guardian spreads her cleavage open and grinds her knee.",
   "e1": "the gem polisher polishes his nipples like a gemstone.",
   "e2": "the miner forewoman squeezes him into a narrow tunnel.",
   "e3": "the crystal spirit whitens his mind with glittering light.",
   "boss": "the ruby lady drinks his magic with a ruby kiss.",
 },
 "lose": {
   # ジェミニ 技1（お礼のパイズリ）
   "btl_m1": ("bed", "he lies on his back on the feather duvet, the guardian kneels over his hips pressing his penis between her huge heavy breasts, paizuri, cum spilling from her cleavage, twelve small glowing dots on his collarbone, the gold necklace full of gems"),
   "onani_m1": ("patrol", "sitting alone against the damp rock wall, burying his face in a rolled-up cloak, one hand stroking his own chest, hips twitching, penis untouched, the guardian sits far away on a rock pushing up her cleavage with her elbows, watching"),
   "inochi_m1": ("hut", "he sits on a chair in the guard hut, the guardian kneels before him with her huge breasts resting on a padded armrest, squeezing his penis between her breasts, paizuri, holding still at the edge, blank calendar without text"),
   "onedari_m1": ("engawa", "he lies on his back on the sunny veranda, the guardian leans over his hips squeezing his penis between her sun-warmed huge breasts, paizuri, cum on her cleavage, a blank schedule paper without text pinned on the pillar"),
   # ジェミニ 技2（★守護者のぱふぱふ）
   "btl_m2": ("vein", "he lies on his back on the warm rock floor, the guardian lies over him pressing her huge breasts down on his face, breast smother, her hand gently stroking his penis, cum on his belly, glowing veins"),
   "onani_m2": ("barracks", "lying alone face down on the soot-stained bench, his face buried between two stacked pillows, one hand stroking his own chest, hips twitching, penis untouched, the guardian stands far away in the doorway watching"),
   "inochi_m2": ("lake", "he lies with his head on the guardian's lap by the still lake, the guardian bends forward smothering his face with her huge breasts, breast smother, his arms limp, a row of small pebbles on the shore, glowing moss"),
   "onedari_m2": ("bed", "he lies on the feather duvet, the guardian lies on him with her huge breasts covering his whole face, swaying them, breast smother, his arms limp at his sides, hips raised, cum on his belly"),
   # ジェミニ 技3（谷間くぱぁと膝）
   "btl_m3": ("crystal", "he sits collapsed against a crystal pillar, the guardian stands over him pulling her cleavage open with two fingers, her knee grinding his crotch, kneejob, cum on her knee, crystals reflecting her cleavage"),
   "onani_m3": ("atelier", "kneeling alone at the workbench, parting two stacked pillows with his fingers and burying his face between them, one hand stroking his own chest, penis untouched, the guardian watches far away from behind the shelf"),
   "inochi_m3": ("sort", "he sits on the edge of the gem sorting table, the guardian stands before him spreading her cleavage open with her fingers, her knee held just short of his crotch, his hips pushing forward toward her knee, one raw gem on the table"),
   "onedari_m3": ("plaza", "he sits on a wooden bench in the empty night square, the guardian leans over him smothering his face with her huge breasts, her knee grinding his crotch, kneejob, a plain armband on his arm, cum dripping"),
   # ルチル（★磨き上げ）
   "btl_e1": ("polish", "he lies on the polishing workbench, the gem polisher peers through her loupe polishing his swollen nipple with a cloth-wrapped fingertip, her other hand stroking his penis, handjob, cum on his belly, sparkling dust"),
   "onani_e1": ("hut", "sitting alone on a chair, a polishing cloth wrapped around his fingertip, rubbing his own nipple in small circles, chest pushed out, penis untouched, the gem polisher watches far away from the doorway"),
   "inochi_e1": ("sort", "he sits on the gem sorting table, the gem polisher kneels before him licking his nipple to a gloss, her cloth-wrapped finger circling his other nipple, his nipples glossy and swollen, a blank notebook without text"),
   "onedari_e1": ("atelier", "he sits before the shelves of raw gemstones, the gem polisher kneels beside him licking his glossy nipple, her hands resting on her knees, cum on his thigh, a blank tag without text on the shelf"),
   # ベリル（★狭い坑道）
   "btl_e2": ("crevice", "he is pinned against the earthen wall of the cramped tunnel, the miner forewoman presses her full body against him, her big breasts crushing his face, her thick thighs clamping his penis, thighjob, cum dripping, lantern light"),
   "onani_e2": ("closet", "sitting alone inside the cramped closet tightly wrapped in a thick blanket, one hand stroking his own chest inside it, trembling, penis untouched, the miner forewoman looks in far away from the opened door"),
   "inochi_e2": ("barracks", "he sits on the soot-stained bench held tight in the miner forewoman's arms, his face pressed into her big breasts, her thick arms locking his shoulders, hug, trembling, pickaxe rack, a single oil lamp"),
   "onedari_e2": ("vein", "he is squeezed into a narrow rock crevice in the vein cavern, the miner forewoman presses against him blocking every way out with her breasts and arms, her thick thighs clamping his penis, thighjob, cum dripping"),
   # アメシア（★煌めきの暗示）
   "btl_e3": ("crystal", "he kneels in the crystal cave with his back arched, dazed, the crystal spirit sways her crystal-tipped hair before his eyes, whispering, all the ceiling crystals shining, no hands on him, cum dripping"),
   "onani_e3": ("window", "sitting alone at the window staring at a glass bead on the sill, hands resting on his thighs, mouth open, hips twitching, penis untouched, the crystal spirit peeks in far outside the window"),
   "inochi_e3": ("lake", "he lies on the lake shore, the crystal spirit kneels beside him with her hands on her knees, shimmering purple reflections from the water on his face, dazed, no hands on him, cum on his belly"),
   "onedari_e3": ("plaza", "he sits on the cobblestones before the glowing jewelry shop window at night, dazed, purple, red and clear gems glittering in the window, the crystal spirit kneels beside him, no hands on him, cum dripping"),
   # ルベリア（★紅玉の口づけ／紅玉の張形）
   "btl_boss": ("ruby", "from side, he lies on his back on the red velvet chaise longue with legs lifted, the ruby lady kisses him deeply, pegging his anus with a red jeweled strap-on, anal, her long-gloved fingers rolling his nipple, his own penis separate", ST),
   "onani_boss": ("barracks", "sitting alone on the bench at night, sucking two of his own fingers deeply as if kissing, the other hand pinching his own nipple, penis untouched, the ruby lady stands far away in the lamp shadow watching"),
   "inochi_boss": ("vein", "from side, he lies on his back on the warm rock floor, the ruby lady over him pegging his anus with her red jeweled strap-on, anal, kissing him deeply, the ruby on her chest glowing, his own penis separate, cum on the rock", ST),
   "onedari_boss": ("ruby", "from side, he is on all fours on the red velvet rug, the ruby lady kneels behind him pegging his anus with her red jeweled strap-on, anal, turning his face to kiss him, his own penis separate, open jewelry box", ST),
 },
 "lose_desc": "keeps him in the western mine, all his magic turned into gems on the guardian's necklace.",
 "onanie": {
   "master": ("bed", "lying face down with his face buried between two stacked pillows, pressing them against his face until his breath is shallow, one hand stroking his own chest, penis untouched"),
   "e1": ("polish", "sitting at the workbench, a polishing cloth wrapped around his fingertip, polishing his own nipple in small circles, chest pushed out, penis untouched"),
   "e2": ("closet", "sitting inside the cramped closet tightly wrapped in a thick blanket, unable to move, one hand stroking his own chest inside it, penis untouched"),
   "e3": ("window", "sitting at the window staring at a glittering glass bead, hands resting on his thighs, no hands on his body, mouth open, hips twitching, penis untouched"),
   "boss": ("barracks", "sitting on the bench, sucking two of his own fingers deeply as if kissing, tongue around them, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "vein", "holding up a freshly mined glowing raw gemstone above her cleavage, gentle droopy-eyed smile, glowing veins behind her"),
   "2": (None, "hut", "a patrol map of the mine without text spread on a wooden desk, an oil lamp, a brass compass"),
   "3": (None, "vein", "a rock wall of glittering gemstone veins flashing with dazzling light"),
   "4": ("m", "bed", "sitting on the bed resting her huge breasts on a padded armrest cushion, beckoning with one finger, droopy-eyed smile"),
   "5": (None, "atelier", "a gold necklace with twelve gem settings, most of them filled with glowing gems, on a velvet cushion on the workbench"),
 },
}
