# N90 魔王軍の女幹部（General）画像データ。登場人物は全員20歳以上（人外は見た目の年齢・成人）。
# 女性＋ふたなり（ヴェルローザ・ブラッカ・ドラクミラ＝ふたなりの魔族。type は woman、挿入の本だけ pen=penis）。女装なし。
# 黒薔薇の紋は口づけで浮かぶ黒い薔薇の模様（焼印・刺青・痛みではない）。流血・死体・王国の紋章なし。
ROSE = "small black rose marks glowing faintly on his skin"
DATA = {
 "code": "General",
 "world": "dark fantasy demon army fortress camp at night, black banners without emblems, bonfires, black roses, detailed background",
 "bg": "interior of a demon general's black command tent, bonfire glow, silver vase of black roses, fur rug, dark silk cushions, black banners without emblems",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "ヴェルローザ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, very tall, long legs, voluptuous, demon woman, black hair, very long hair, curved black horns, red eyes, red lipstick, black and crimson dress armor decorated with black roses, open chest plate, cleavage, black cape, huge breasts",
            "name": "the tall black-horned demon general in black rose dress armor",
            "pose": "standing with one hand on her hip, cape flowing, confident alluring smile, looking at viewer"},
   "e1":   {"type": "woman", "jp": "ネフェル",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, succubus, purple hair, twintails, gold eyes, small bat wings, thin demon tail, black military-style bodysuit, short cropped coat, large breasts",
            "name": "the purple-twintailed succubus corporal",
            "pose": "leaning forward with a finger to her lips, playful grin, looking at viewer"},
   "e2":   {"type": "woman", "jp": "リゼット",
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, human mage, blonde hair, very long hair, green eyes, white mage robe dyed black, holding a staff, large breasts",
            "name": "the blonde mage in a black-dyed robe",
            "pose": "standing holding a staff, gentle big-sister smile, looking at viewer"},
   "e3":   {"type": "woman", "jp": "ブラッカ",
            "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, tall, long legs, slim toned body, demon woman, red hair, wolf cut, short horns, amber eyes, crimson-black light armor, loincloth, sergeant, large breasts",
            "name": "the red-haired demon sergeant in light armor",
            "pose": "standing with arms crossed, hearty grin, looking at viewer"},
   "boss": {"type": "woman", "jp": "ドラクミラ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, very tall, long legs, demon woman, silver hair with metallic sheen, very long hair, dragon horns, purple eyes, black full plate armor with a curved feminine breastplate, no helmet, dark knight commander, huge breasts",
            "name": "the tall silver-haired dark knight in black plate armor",
            "pose": "standing straight with both hands resting on a sheathed sword, stern calm face, looking at viewer"},
 },
 "places": {
   "command":  "demon general's black command tent, bonfire glow, silver vase of black roses, fur rug",
   "captive":  "rough canvas prisoner tent, straw bedding, a draft through the flaps, a lantern",
   "prison":   "fortress cell, cold stone walls, iron bars, wall torch",
   "lab":      "magic laboratory, glowing magic circle on the floor, stacks of grimoires, glass vessels, herbs",
   "barracks": "soldiers' barracks, rows of simple cots, spear racks on the wall, leather and oil",
   "knights":  "black knights' guardroom, weapon racks lined with black armor, stone floor, fireplace",
   "drill":    "night training ground, rows of bonfires, damp earth, fortress walls looming",
   "wall":     "top of the fortress wall at night, night wind, black flags without emblems, distant camp lights on the horizon",
   "council":  "war council room, long ebony table with a spread map, candlesticks, tall dark thrones",
   "hall":     "investiture hall, black rose tapestries without text, long red carpet, high ceiling",
   "bedchamber": "general's bedchamber, canopy bed with black and crimson silk sheets, black rose petals, warm incense burner",
   "medical":  "medical tent, white cloth partitions, examination table, blank record book without text",
   "bath":     "stone bath with steaming water, black rose petals floating, wet stone",
   "field":    "misty dawn field between two armies, a trodden road, the fortress behind and distant camp lights ahead",
 },
 "atk": {
   "m1": ("command", "he kneels on the fur rug with his face buried in the demon general's open cleavage, the demon general squeezes her huge breasts around his cheeks, her cape around him, trembling"),
   "m2": ("hall", "he kneels on the red carpet, the demon general bends down kissing his neck, black rose marks blooming on his skin where her lips touched, her hand holding his chin, blush"),
   "m3": ("hall", "from side, he kneels on all fours on the red carpet, the demon general kneels behind him penetrating his anus with her own penis, anal, reaching around pinching his nipples, a bladeless ceremonial sword on the carpet, his own penis separate", {"pen": "penis"}),
   "e1": ("captive", "he lies on the straw bedding, the succubus corporal lies over his shoulder whispering into his ear, her tongue in his ear, her tail swaying, trembling"),
   "e2": ("lab", "he sits in the middle of the glowing magic circle, the blonde mage stands before him with two fingers on his forehead chanting, soft light swirling around his head, no hands on his body, mouth open, trembling"),
   "e3": ("barracks", "he stands at attention beside the cots, the demon sergeant pinches his nipples and flicks them, a record book without text in her other hand, flushed"),
   "boss": ("knights", "he stands before the fireplace, the dark knight hugs him tightly from behind in her black plate armor, her ungauntleted fingers pinching his nipples, her armored arms locking him, trembling"),
 },
 "atk_desc": {
   "m1": "the demon general recruits him into her bosom.",
   "m2": "the demon general marks him with a black rose kiss.",
   "m3": "the demon general knights him in the investiture ceremony.",
   "e1": "the succubus corporal whispers betrayal into his ear.",
   "e2": "the fallen senior mage casts a spell into his mind.",
   "e3": "the demon sergeant gives the recruit a physical inspection.",
   "boss": "the dark knight embraces him in black armor.",
 },
 "lose": {
   # ヴェルローザ 技1（勧誘の胸）
   "btl_m1":     ("command", "he lies on the fur rug with his face buried in the demon general's cleavage, the demon general lifts his chin and kisses him, twelve black rose marks glowing on his skin, cum on his belly"),
   "onani_m1":   ("captive", "lying alone on the straw bedding hugging a rolled-up coat to his chest and burying his face in it, tracing a black rose mark on his collarbone with one finger, penis untouched, the demon general watches from the tent flap"),
   "inochi_m1":  ("field", "he stands in the dawn mist wearing a black envoy cloak with a black rose clasp, the demon general hugs his face to her cleavage and kisses him, distant camp lights ahead, cum on his thigh"),
   "onedari_m1": ("council", "he sits on the demon general's lap on the tall throne with his face in her cleavage, pressing his lips onto a blank black parchment without text, black rose marks glowing on his skin"),
   # ヴェルローザ 技2（黒薔薇の口づけ）
   "btl_m2":     ("hall", "he kneels on the red carpet, the demon general kisses the middle of his chest, a large black rose mark blooming there, twelve black rose marks glowing across his neck, chest and thighs, cum on the carpet"),
   "onani_m2":   ("captive", "sitting alone on the straw bedding, sucking two of his own fingers, tracing the black rose marks on his chest with his other hand, penis untouched, the demon general watches from the tent flap"),
   "inochi_m2":  ("wall", "he stands on the fortress wall at night, the demon general draws a black cloak over his shoulders and kisses him deeply, tongues, distant camp lights far behind, " + ROSE),
   "onedari_m2": ("bedchamber", "he sits on the black silk sheets hugging a blank black parchment without text to his chest, the demon general strokes one black rose mark on his thigh, lips hovering at his, " + ROSE + ", cum on the sheets"),
   # ヴェルローザ 技3（叙任式・ふたなり）
   "btl_m3":     ("hall", "from side, he kneels on all fours on the red carpet, the demon general behind him penetrating his anus with her own penis, anal, pinching his nipples, the bladeless ceremonial sword laid on his shoulder, his own penis separate, " + ROSE, {"pen": "penis"}),
   "onani_m3":   ("captive", "kneeling alone on the straw bedding, pinching his own nipple, sucking two fingers of his other hand, black rose marks on his chest, penis untouched, the demon general watches from the tent flap"),
   "inochi_m3":  ("bath", "from side, he kneels in the rose petal bath gripping the stone edge, the demon general behind him in the water penetrating his anus with her own penis, anal, kissing his neck, pinching his nipple, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("bedchamber", "from side, he lies on his back on the black silk sheets holding his knees, the demon general over him penetrating his anus with her own penis, anal, pinching both his nipples, his own penis separate, black rose petals", {"pen": "penis"}),
   # ネフェル（寝返りの囁き）
   "btl_e1":     ("captive", "he lies pinned on the straw bedding, the succubus corporal lies on him whispering into his ear and nibbling his earlobe, her bare foot pressing his penis, cum on her foot, her tail curling"),
   "onani_e1":   ("captive", "lying alone on the straw bedding, tracing both his own ears with his fingertips, lips moving in a whisper, penis untouched, the succubus corporal watches from the tent flap grinning"),
   "inochi_e1":  ("field", "he walks beside the succubus corporal along the misty dawn road, the succubus corporal leans on his shoulder whispering into his ear, distant camp lights ahead, flushed, " + ROSE),
   "onedari_e1": ("drill", "he kneels before the bonfires, the succubus corporal bites his earlobe and whispers, her foot on his thigh, a blank parchment without text in his hands, " + ROSE),
   # リゼット（堕ちた先輩の魔法）
   "btl_e2":     ("lab", "he sits in the glowing magic circle with his face against the blonde mage's chest under her black robe, the blonde mage holds two fingers on his forehead chanting, light swirling in his head, cum on the circle, no hands on his crotch"),
   "onani_e2":   ("captive", "sitting alone on the straw bedding with both hands on his knees, whispering a spell, faint light flickering around his head, hips twitching, penis untouched, the blonde mage watches from the tent flap"),
   "inochi_e2":  ("medical", "he lies on the examination table, the blonde mage stands beside him with two fingers on his forehead, soft light melting around his head, a blank record book without text, mouth open, trembling"),
   "onedari_e2": ("lab", "he sits in the glowing magic circle with his face buried in the blonde mage's chest, the blonde mage chants over his head, a blank black parchment without text beside them, " + ROSE),
   # ブラッカ（新兵の身体検査／新兵の洗礼・ふたなり）
   "btl_e3":     ("barracks", "from side, he lies on a simple cot with his legs lifted, the demon sergeant kneels between his legs penetrating his anus with her own penis, anal, pinching his nipple, his own penis separate, a record book without text on the cot", {"pen": "penis"}),
   "onani_e3":   ("captive", "standing alone at attention in the tent, pinching and flicking both his own nipples, penis untouched, the demon sergeant watches from the tent flap laughing"),
   "inochi_e3":  ("medical", "from side, he lies on the examination table with his knees up, the demon sergeant penetrating his anus with her own penis, anal, pinching his nipple, a blank form without text with a thumbprint, his own penis separate", {"pen": "penis"}),
   "onedari_e3": ("drill", "from side, he is bent over a wooden barricade by the bonfires, the demon sergeant behind him penetrating his anus with her own penis, anal, reaching around flicking his nipple, his own penis separate", {"pen": "penis"}),
   # ドラクミラ（黒鎧の抱擁）
   "btl_boss":   ("knights", "he sits before the fireplace held from behind inside the dark knight's black armored arms, the dark knight pinches his nipples with bare fingers, her armored thighs clamping his legs, cum on the stone floor"),
   "onani_boss": ("captive", "kneeling alone on the straw bedding with a heavy blanket draped over his back, pinching both his own nipples, motionless, penis untouched, the dark knight watches from the tent flap"),
   "inochi_boss":("field", "he rides a black horse in the misty dawn, the dark knight sits behind him in black armor holding him tightly, her bare fingers pinching his nipple, the horse turning back from distant camp lights"),
   "onedari_boss":("knights", "he stands before racks of black armor, the dark knight hugs him from behind tightening her armored arms, pinching his nipples, her armored thigh between his legs, a blank parchment without text on the floor, cum dripping"),
 },
 "lose_desc": "makes him a loyal soldier of the demon army, covered in black rose marks.",
 "onanie": {
   "master": ("command", "kneeling on the fur rug, sucking two of his own fingers, tracing black rose marks on his chest with his other hand, penis untouched"),
   "e1": ("captive", "lying on the straw bedding, tracing both his own ears with his fingertips, whispering to himself, penis untouched"),
   "e2": ("lab", "sitting in the magic circle with both hands on his knees, whispering a spell, faint light around his head, no hands on himself, penis untouched"),
   "e3": ("barracks", "standing at attention by the cots, pinching and flicking both his own nipples, penis untouched"),
   "boss": ("knights", "kneeling before the fireplace with a heavy blanket over his back, pinching both his own nipples, penis untouched"),
 },
 "magic": {
   "1": ("m", "wall", "standing on the fortress wall raising one hand in command, cape and black flags streaming in the wind, bonfires below"),
   "2": (None, "council", "a blank black parchment summons without text sealed with a black rose wax seal on the ebony table, candlelight"),
   "3": (None, "lab", "a glowing purple magic circle trap on the stone floor, sparks rising, grimoires around"),
   "4": ("e1", "captive", "leaning in with a hand cupped by her mouth as if whispering a secret, beckoning with one finger, tail swaying"),
   "5": (None, "drill", "dark purple miasma creeping over the night training ground, bonfires dimmed, black flags without emblems"),
 },
}
