# N78 口づけの魔女（Kiss）画像データ。登場人物は全員20歳以上（人外は見た目の年齢・成人）。女性＋ふたなり（ミストラ・オスクラ＝人外のふたなり、type は woman）。女装なし。
# 口紅の筒・目録・台帳・名札は文字なし。ふたなりの挿入の絵は口づけしたままの構図。
FP = {"pen": "penis"}   # ミストラ・オスクラのふたなり逆アナル（指でほぐした後だけ）

DATA = {
 "code": "Kiss",
 "world": "gothic mansion of a kiss witch on the edge of a fantasy town at night, red velvet, candlelight, rose scent, detailed background",
 "bg": "parlor of a gothic mansion at night, red velvet long sofa, vanity table with a lit mirror and rows of small gold lipstick tubes, candlelight, heavy red curtains",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ベーゼリア",
         "tags": "adult woman, mature female, mature face, 31 years old, adult proportions, beautiful detailed eyes, tall, long legs, succubus, small horns, thin tail, purple hair, long wavy hair, gold eyes, glossy deep red lipstick, wine red mermaid dress, black lace long gloves, seductive smile, large breasts",
         "name": "the purple-haired kiss witch in a wine red mermaid dress",
         "pose": "blowing a kiss with one gloved hand, half-lidded eyes, seductive smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "カルミナ",
          "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, red hair, hime cut, green eyes, red lipstick, black artisan jacket, bundle of lip brushes at her waist, neat composed expression, large breasts",
          "name": "the red-haired rouge artisan in a black jacket",
          "pose": "holding a fine lip brush up between her fingers, composed polite smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "ミストラ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, succubus, small horns, thin tail, pink hair, long wavy hair, purple eyes, pale purple sheer misty robe, languid half-lidded eyes, pink lips, large breasts",
          "name": "the pink-haired breath succubus in a pale purple sheer robe",
          "pose": "blowing a soft sweet breath from her lips, languid half-lidded eyes, looking at viewer"},
   "e3": {"type": "woman", "jp": "シェリ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, orange hair, high ponytail, brown eyes, red dancer costume with an open chest, sheer sash, gold bells on her ankles, barefoot, cheerful smile, large breasts",
          "name": "the orange-haired kiss dancer with ankle bells",
          "pose": "dancing on one foot with arms open for a hug, ankle bells jingling, cheerful smile, looking at viewer"},
   "boss": {"type": "woman", "jp": "オスクラ",
            "tags": "adult woman, mature female, mature face, 34 years old, adult proportions, beautiful detailed eyes, very tall, long legs, demon, black horns, black hair, very long straight hair, gold eyes, dark red lipstick, black and crimson tailcoat dress, black gloves, suave smile, large breasts",
            "name": "the black-haired kiss duchess in a black and crimson tailcoat dress",
            "pose": "bowing slightly with one gloved hand on her chest, suave smile, looking at viewer"},
 },
 "places": {
   "parlor": "mansion parlor, red velvet long sofa, vanity mirror lights, candlelight",
   "bedroom": "luxurious bedroom, canopy bed with deep crimson silk sheets, heavy drapes, incense burner by the pillow",
   "vanity": "vanity room, three-panel mirror, rows of small gold lipstick tubes without text, face powder",
   "portrait": "portrait room, rows of framed portraits of men with painted lips, one empty frame, quiet fireplace, leather armchair",
   "workshop": "rouge artisan's workshop, mortar for mixing rouge, bundles of lip brushes, beeswax, cold workbench",
   "bath": "steamy marble bathroom, marble bath edge, sweet-scented steam, wet sheer cloth",
   "ballroom": "dance hall, polished floor, moonlight through tall windows, a small stage",
   "hall": "mansion entrance hall, spiral staircase, cold stone floor",
   "window": "small room by a window, night street below, curtains swaying in the night wind",
   "study": "duchess's study, ebony desk, sealing wax, red candles, old papers",
   "greenhouse": "greenhouse at night, roses and night flowers, damp soil, moonlight through the glass",
   "wardrobe": "wardrobe room, rows of velvet dresses, perfume in the air",
   "cellar": "underground wine cellar, wine barrels, cool air, a single lamp",
   "balcony": "mansion balcony at night, starry sky, hedges around the mansion, distant town lights",
 },
 "atk": {
   "m1": ("hall", "he kneels at the foot of the spiral staircase with his knees buckling, the kiss witch stands on the stairs blowing him a kiss from afar, glowing red lip marks stuck on his chest, no hands on him, trembling"),
   "m2": ("bedroom", "he lies sunk in the crimson silk sheets, the kiss witch leans over him kissing him deeply, tongues, letting a string of her saliva drip into his mouth, red lipstick smeared on his lips"),
   "m3": ("parlor", "he lies on the red velvet sofa with his shirt opened, the kiss witch sucks his right nipple leaving a red lipstick mark, her gloved fingers rolling his left nipple, trembling"),
   "e1": ("workshop", "he sits on the workbench, the rouge artisan leans to his ear kissing his earlobe leaving a red lipstick mark, licking the rim of his ear, a lip brush in her other hand, trembling"),
   "e2": ("bath", "he sits on the marble bath edge in the steam, the breath succubus presses her lips to his and blows a sweet misty breath into his mouth, dazed, flushed"),
   "e3": ("ballroom", "he sits collapsed on the polished floor, the kiss dancer hugs him tightly raining kisses on his cheek and neck, many lipstick marks on his face, ankle bells jingling"),
   "boss": ("study", "he sits on the ebony desk, the kiss duchess kisses down from his neck to his collarbone, her gloved fingers pinching his nipple, a trail of dark red lipstick marks, trembling"),
 },
 "atk_desc": {
   "m1": "the kiss witch blows him a kiss from afar.",
   "m2": "the kiss witch gives him her deep witch's kiss.",
   "m3": "the kiss witch leaves red suck marks on his nipples.",
   "e1": "the rouge artisan kisses his earlobes in rouge.",
   "e2": "the breath succubus passes sweet breath mouth to mouth.",
   "e3": "the kiss dancer hugs him with a rain of kisses.",
   "boss": "the kiss duchess traces a path of kisses down his neck.",
 },
 "lose": {
   # ベーゼリア 技1（投げキッス）
   "btl_m1": ("hall", "he sits collapsed on the cold stone floor at the foot of the spiral staircase, the kiss witch on the stairs blows him a kiss from afar, glowing red lip marks stuck on his chest and neck, no hands on him, cum on the floor"),
   "onani_m1": ("portrait", "sitting alone before an empty picture frame, sucking two of his own fingers deeply, red lipstick on his lips, the other hand tracing his own lips, penis untouched, the kiss witch watches far away beside a portrait, blowing a kiss"),
   "inochi_m1": ("balcony", "he leans on the balcony railing, glowing red lip marks on his neck, chest and inner thighs, the kiss witch stands a step away blowing a kiss toward him, his lips parted, trembling, cum dripping"),
   "onedari_m1": ("parlor", "he sits on the red velvet sofa holding an open catalog book without text, the kiss witch across the room blows him a kiss, a red lip mark flying onto his chest, his mouth open, cum on his thigh"),
   # ベーゼリア 技2（★魔女の深い口づけ）
   "btl_m2": ("bedroom", "he lies sunk in the crimson silk sheets, the kiss witch kisses him deeply, tongues, a string of her saliva dripping into his open mouth, deep red lipstick on his lips, cum on his belly"),
   "onani_m2": ("vanity", "sitting alone before the three-panel mirror, sucking two of his own fingers deeply, drool on his chin, swallowing, penis untouched, the kiss witch watches far away reflected in the mirror"),
   "inochi_m2": ("wardrobe", "he stands among the velvet dresses, the kiss witch holds his chin and kisses him deeply, tongues, saliva trail, a small silver hand bell in his hand, his knees weak"),
   "onedari_m2": ("bedroom", "he lies under the canopy with his mouth open begging, the kiss witch leans over him kissing him deeply, tongues, saliva trail, an open catalog book without text on the sheets"),
   # ベーゼリア 技3（紅の吸い跡）
   "btl_m3": ("parlor", "he lies on the red velvet sofa with his shirt opened, the kiss witch sucks his left nipple, her gloved fingers rolling his right nipple, red lipstick suck marks on both nipples, cum on his belly"),
   "onani_m3": ("greenhouse", "sitting alone among the roses, sucking two fingers of one hand, the other wet fingers rolling his own nipple, penis untouched, the kiss witch watches far away from behind the roses"),
   "inochi_m3": ("cellar", "he sits on a wine barrel with his shirt opened, the kiss witch sucks his nipple with wine-stained lips, her fingers rolling the other nipple, red suck marks on both nipples, cum dripping"),
   "onedari_m3": ("bedroom", "he lies on the crimson sheets with a thin sheer shirt opened, the kiss witch sucks his nipple and kisses him in turn, red suck marks on both nipples, saliva trail, cum on his belly"),
   # カルミナ（★耳たぶの口づけ）
   "btl_e1": ("workshop", "he sits on the cold workbench, the rouge artisan kisses his red-marked earlobe and pushes her tongue into his ear, her fingers stroking his penis, handjob, cum on the workbench, lip brushes"),
   "onani_e1": ("vanity", "sitting alone before the mirror with red lipstick on his lips, pinching his own earlobe with wet fingers, tracing it, penis untouched, the rouge artisan watches far away by the door"),
   "inochi_e1": ("wardrobe", "he sits among the velvet dresses, red color swatches painted on his wrist and neck, the rouge artisan kisses his earlobe, a lip brush in her hand, trembling, flushed"),
   "onedari_e1": ("workshop", "he sits on the workbench, the rouge artisan whispers into his red-marked ear, her fingers stroking his penis, handjob, cum dripping, a blank ledger without text on the bench"),
   # ミストラ（★口移しの吐息／吐息の後で・ふたなり）
   "btl_e2": ("bath", "from side, he lies on his back on the marble bath edge with legs lifted, the breath succubus penetrates his anus with her own penis, anal, kissing him and blowing breath into his mouth, his own penis separate, steam", FP),
   "onani_e2": ("window", "sitting alone by the window, breathing into his own cupped palms and inhaling it back, dazed, hands away from his body, penis untouched, the breath succubus watches far away outside the window"),
   "inochi_e2": ("greenhouse", "he lies among the night flowers, the breath succubus hovers her lips just above his, blowing a sweet misty breath over his face and chest, not touching him, dazed, cum on his belly"),
   "onedari_e2": ("bath", "from side, he lies on his back on the marble bath edge, the breath succubus penetrates his anus with her own penis, anal, kissing him mouth to mouth passing her breath, his own penis separate, steam", FP),
   # シェリ（★口づけの雨）
   "btl_e3": ("ballroom", "he lies on the polished floor, the kiss dancer hugs him raining kisses on his neck and chest, lipstick marks all over his face, her belled foot stroking his penis, footjob, cum on her foot"),
   "onani_e3": ("portrait", "sitting alone in the leather armchair hugging a long pillow, pressing his lips to the back of his own hand, the other fingers rubbing his own nipple, penis untouched, the kiss dancer watches far away by the fireplace"),
   "inochi_e3": ("balcony", "he sits on the balcony floor, the kiss dancer hugs him tightly kissing him just beside his lips, countless lipstick marks all over his face and chest, trembling, cum dripping"),
   "onedari_e3": ("ballroom", "he sits at the edge of the small stage, the kiss dancer jumps on him in a tight hug raining kisses on his cheeks, her ankle bells jingling, a blank name tag without text on his chest"),
   # オスクラ（★公爵の接吻／接吻しながら・ふたなり）
   "btl_boss": ("study", "from side, he lies on his back on the ebony desk with legs lifted, the kiss duchess penetrates his anus with her own penis, anal, kissing his neck, pinching his nipple, his own penis separate, dark red lipstick marks down his neck", FP),
   "onani_boss": ("wardrobe", "standing alone among the velvet dresses, tracing a wet finger down from his own neck to his chest, pinching his own nipple, penis untouched, the kiss duchess watches far away between the dresses"),
   "inochi_boss": ("portrait", "from side, he lies on his back on the leather armchair, the kiss duchess penetrates his anus with her own penis, anal, kissing down his neck but not his lips, his own penis separate, dark red lipstick marks", FP),
   "onedari_boss": ("bedroom", "from side, he lies on his back on the crimson silk sheets, the kiss duchess penetrates his anus with her own penis, anal, kissing his neck and collarbone, pinching his nipple, his own penis separate", FP),
 },
 "lose_desc": "keeps him in the kiss witch's mansion with his lips painted in twelve shades of rouge.",
 "onanie": {
   "master": ("vanity", "sitting before the mirror, sucking two of his own fingers deeply, swallowing his saliva, red lipstick on his lips, the other hand tracing his own lips, penis untouched"),
   "e1": ("vanity", "sitting before the mirror with red lipstick on his lips, pinching his own earlobe between wet fingers and tracing it, penis untouched"),
   "e2": ("window", "breathing into his own cupped palms and inhaling it back, dazed, hands away from his body, penis untouched"),
   "e3": ("bedroom", "hugging a long pillow, pressing his lips to his own arm and shoulder, the free fingers rubbing his own nipple, penis untouched"),
   "boss": ("wardrobe", "tracing a wet finger from his own neck down to his chest, pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "vanity", "holding a small gold lipstick tube without text, painting her lips deep red before the mirror, seductive smile"),
   "2": (None, "hall", "an invitation letter without text sealed with a red lip-shaped wax seal on a silver tray"),
   "3": (None, "parlor", "many glowing red lip marks fluttering in the air like butterflies"),
   "4": ("m", "bedroom", "sitting on the canopy bed, pressing a gloved fingertip to her lips for a goodnight kiss, half-lidded eyes"),
   "5": (None, "vanity", "a vanity table with a three-panel mirror and twelve small gold lipstick tubes without text in a row, candlelight"),
 },
}
