# N61 師匠の再修行（Konoha）画像データ。登場人物は全員20歳以上。全員女性。修行帳・札・紙は文字なし。
# 本編キャラ（コノハ・サキュバスメイド・サムライガール・シズク）は本編の立ち絵を見ずに、本文の手がかり（着物・袴・エプロン・白手袋・琥珀の瞳など）と役から決めた見た目。
BOOK = "a blank training notebook without text"

DATA = {
 "code": "Konoha",
 "world": "quiet rural japanese-style village house of a magic mentor, wooden engawa veranda, tatami rooms, bamboo grove and hills around, warm light, detailed background",
 "bg": "interior of a rural japanese-style house, tatami training room with wooden pillars, open shoji facing a garden and engawa veranda, bamboo grove beyond, afternoon light",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "師匠 コノハ", "canon": True, "canon_img": "F1_Shisyo.png",
         "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, tall, black hair, long hair, loose low ponytail, red eyes, purple haori over a white kimono, dark red obi, sorceress, mentor, teasing smile, large breasts",
         "name": "the black-haired mentor in a purple haori",
         "pose": "one hand on her hip, the other raising a finger as if giving a lesson, teasing big-sister smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "サキュバスメイド", "canon": True, "canon_img": "EU01_maid.png",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, pink hair, long wavy hair, maid headdress, purple eyes, small black horns, small bat wings, thin demon tail, black maid dress, white apron, white gloves, huge breasts",
          "name": "the pink-haired succubus maid in a white apron",
          "pose": "hands folded politely in front of her apron, slight bow, gentle seductive smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "サムライガール", "canon": True, "canon_img": "EU02_samurai.png",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, red hair, high ponytail, gold eyes, samurai, red kimono top, black hakama, katana at her waist, confident grin, large breasts",
          "name": "the red-haired samurai in a black hakama",
          "pose": "hand resting on the katana hilt at her waist, bold grin, chest out, looking at viewer"},
   "e3": {"type": "woman", "jp": "姉弟子 ヒワ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, ponytail, amber eyes, white training gi, dark red hakama, confident smile, medium breasts",
          "name": "the brown-ponytailed senior disciple in a training gi",
          "pose": "arms crossed, slightly leaning forward, cheerful mischievous smile, looking at viewer"},
   "boss": {"type": "woman", "jp": "サムライ師範 シズク", "canon": True, "canon_img": "EU03_wear.png",
            "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, tall, silver hair, very long hair, loose braid over shoulder, green eyes, droopy eyes, samurai instructor, loose light pink kimono with a wide open collar, white hakama, gentle smile, huge breasts",
            "name": "the silver-haired samurai instructor in a pink kimono",
            "pose": "hands clasped under her chest, head tilted, soft droopy-eyed smile, looking at viewer"},
 },
 "places": {
   "keiko": "tatami training room of a village house, wooden pillars, sliding shoji doors, morning light",
   "shinshitsu": "mentor's bedroom, one futon on tatami, andon paper lamp light, night",
   "engawa": "wooden engawa veranda at sunset, open shoji, garden with a stone lantern, orange sky",
   "kyakuma": "japanese guest room, zabuton cushions, low table with tea cups, pendulum clock on the wall, afternoon light",
   "chikurin": "bamboo grove on the hill behind the village, fallen leaves, morning mist",
   "dojo": "village dojo with a wooden floor and tatami mats, wooden practice swords on the wall rack",
   "okuzashiki": "inner tatami parlor on a rainy night, andon lamp, rain outside the shoji",
   "irori": "wooden-floored room with a sunken irori hearth, iron kettle hanging, zabuton cushions, firelight",
   "kawara": "riverbank with round stones at dusk, village far behind, evening glow",
   "jinja": "small village shrine grounds, stone steps, red torii, noon sunlight",
   "okunoma": "back room with a futon spread on tatami, paper lamp, night",
   "kaya": "detached guest room with a mosquito net hung over a futon, dim lantern, summer night",
   "yudono": "wooden bathhouse washing area, wooden bucket and stool, steam",
   "miharashi": "hilltop lookout with a wooden bench under a starry night sky, village lights far below",
   "futonbeya": "futon storage room piled with freshly sun-dried futons, sunlight through a small window",
   "kagura": "wooden kagura stage behind a shrine at a summer festival night, paper lanterns, festival lights far away",
 },
 "atk": {
   "m1": ("keiko", "he kneels on the tatami holding a card, the mentor sits behind him pinching both his nipples through his shirt, whispering into his ear, flushed, trembling"),
   "m2": ("shinshitsu", "he is wrapped in the mentor's arms on the futon, the mentor presses his face deep into her cleavage and hugs his whole body, his arms hanging limp, blush"),
   "m3": ("engawa", "he sits on the veranda, the mentor holds his chin and kisses him deeply, tongues, both her fingers pinching his nipples under his open shirt, saliva trail"),
   "e1": ("kyakuma", "he lies with his head on the succubus maid's lap, the maid bends over licking deep into his ear, white-gloved hand stroking his hair, his toes curled, trembling"),
   "e2": ("chikurin", "he sits on the fallen leaves, the samurai kneels over him holding his cheeks and kissing him roughly, sucking his tongue, saliva trail, katana on the ground"),
   "e3": ("dojo", "he lies on the tatami, the senior disciple holds him from behind in a grappling hold with her legs locked around his waist, rolling both his nipples with her fingers, trembling"),
   "boss": ("okuzashiki", "he kneels on the tatami, the samurai instructor hugs his head into her huge cleavage while pinching his nipple with her fingertips, soft smile, his hands dropping cards"),
 },
 "atk_desc": {
   "m1": "the mentor teaches him the woman's way of fighting, part one.",
   "m2": "the mentor wraps his whole body in her embrace, part two.",
   "m3": "the mentor ends the lesson with a kiss and fingertips.",
   "e1": "the succubus maid cleans his ears with her tongue.",
   "e2": "the samurai steals his lips with a warrior's kiss.",
   "e3": "the senior disciple pins him in a grappling lesson.",
   "boss": "the samurai instructor embraces him in her soft chest.",
 },
 "lose": {
   # コノハ 技1（その一・乳首責め）
   "btl_m1": ("keiko", "he lies on his back on the tatami with his shirt open, the mentor kneels beside him blowing softly on his erect nipples without touching, cum dripping on his stomach, " + BOOK + " beside"),
   "onani_m1": ("keiko", "sitting alone on the tatami, both hands pinching his own nipples through his shirt at a command, back arched, penis untouched, the mentor sits far away on the veranda bench watching"),
   "inochi_m1": ("engawa", "he sits on the sunset veranda, the mentor leans to his ear whispering, no hands on him, his nipples standing out under his shirt, trembling, cum stain, " + BOOK + " on the floor"),
   "onedari_m1": ("irori", "he sits on a zabuton by the hearth offering his bare chest, the mentor pinches and pulls his nipples, teasing smile, firelight, " + BOOK + " by the hearth"),
   # コノハ 技2（その二・ぱふぱふ）
   "btl_m2": ("shinshitsu", "he lies on the futon, the mentor holds his head against her cleavage with her kimono loosened, he breathes her scent, his body limp, cum on the sheets"),
   "onani_m2": ("irori", "lying alone by the hearth hugging a folded zabuton to his face like breasts, stroking his own chest, breath shallow, penis untouched, the mentor watches from across the hearth"),
   "inochi_m2": ("shinshitsu", "he sleeps on one futon with his face buried in the mentor's cleavage, the mentor holds him and writes in " + BOOK + " by the pillow, andon lamp light"),
   "onedari_m2": ("yudono", "he kneels on the steamy washing floor, the mentor in a wet white bathing robe presses his face between her breasts and hugs him, wooden bucket, flushed"),
   # コノハ 技3（修行の締め）
   "btl_m3": ("engawa", "he sits on the sunset veranda, the mentor holds his face in both hands and kisses him softly, lips pressed, cum soaking his trousers, trembling"),
   "onani_m3": ("kawara", "sitting alone on a riverbank stone, pressing his lips to the back of his own hand, the other hand under his shirt pinching his own nipple, penis untouched, the mentor watches from a distance"),
   "inochi_m3": ("dojo", "he kneels in seiza on the moonlit dojo floor with his shirt open, the mentor kisses him deeply while pinching both his nipples, tongues, saliva trail, cum on the floor"),
   "onedari_m3": ("miharashi", "he sits on the bench under the stars, the mentor kisses him deeply, tongues, her fingers pinching his nipples under his open shirt, village lights far below"),
   # サキュバスメイド（耳掃除）
   "btl_e1": ("kyakuma", "he lies with his head on the succubus maid's lap, the maid licks deep into his ear with only her tongue, no hands on him, cum soaking his trousers, pendulum clock"),
   "onani_e1": ("irori", "sitting alone on the wooden floor, a wet fingertip in his own ear, head tilted, murmuring, knees trembling, penis untouched, the succubus maid watches from the doorway"),
   "inochi_e1": ("kyakuma", "he lies on the succubus maid's lap, the maid licks deep into his ear, her tail curling, " + BOOK + " on the low table, cum stain, trembling"),
   "onedari_e1": ("kyakuma", "he lies on the succubus maid's lap in the maid's room, the maid licks into his ear, her white-gloved hands holding his head, a cold teacup on the tray, flushed"),
   # サムライガール（口吸い）
   "btl_e2": ("chikurin", "he sits on the fallen leaves in the bamboo grove, the samurai holds his cheeks and kisses him deeply, sucking his tongue, no hands on his body, cum soaking his trousers"),
   "onani_e2": ("jinja", "sitting alone on the shrine stone steps, sucking two of his own fingers hard, the other hand pinching his own nipple, penis untouched, the samurai watches from the torii"),
   "inochi_e2": ("chikurin", "he kneels in the misty bamboo grove, the samurai lifts his chin and kisses him deeply, sucking his tongue, his swollen lips, " + BOOK + " on the ground"),
   "onedari_e2": ("kawara", "he sits on a round riverbank stone, the samurai holds his face and kisses him, sucking his tongue to the root, wooden practice sword beside, sunset"),
   # ヒワ（寝技の稽古）
   "btl_e3": ("dojo", "he lies on the tatami, the senior disciple holds him from behind with arms and legs locked around him, rolling both his nipples, cum on the mat, his body pinned"),
   "onani_e3": ("okunoma", "lying alone wrapped tightly in a futon like a cocoon, fingers slipped through a gap rolling his own nipple, penis untouched, the senior disciple watches from the sliding door"),
   "inochi_e3": ("okunoma", "at dawn he lies on the futon, the senior disciple holds him from behind, legs wrapped around his, pinching his nipples, his sleepy face, trembling"),
   "onedari_e3": ("futonbeya", "he lies sunk in a pile of sun-dried futons, the senior disciple lies on top of him pinning his wrists with her legs around his, rolling his nipples, sunlight"),
   # シズク（師範の抱擁）
   "btl_boss": ("okuzashiki", "he kneels on the tatami, the samurai instructor hugs his head into her cleavage and pinches both his nipples, no hand on his penis, cum on her kimono hem, rain outside"),
   "onani_boss": ("okuzashiki", "kneeling alone with his face buried in a large soft cushion, one hand pinching his own nipples in turn, penis untouched, the samurai instructor watches smiling from the far side of the parlor"),
   "inochi_boss": ("kaya", "he lies on the futon inside the mosquito net, the samurai instructor holds his face against her cleavage and pinches his nipple, dim lantern, " + BOOK + " by the pillow"),
   "onedari_boss": ("kagura", "he lies across the samurai instructor's lap on the kagura stage, his face buried in her cleavage, she pinches his nipple and strokes his head, festival lanterns far away"),
 },
 "lose_desc": "keeps him in the village forever as a lifelong disciple.",
 "onanie": {
   "master": ("shinshitsu", "lying alone on the futon with his face buried in a pillow pressed like breasts, both hands stroking his own chest, breath shallow, penis untouched"),
   "e1": ("kyakuma", "sitting on a zabuton, wet fingertip tracing the rim of his own ear and slipping into it, head tilted, penis untouched"),
   "e2": ("chikurin", "sitting on the fallen leaves, sucking hard on two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched"),
   "e3": ("okunoma", "wrapped tightly in a futon, unable to move, fingers slipped through the gap rolling his own nipple, penis untouched"),
   "boss": ("okuzashiki", "face buried in a large soft cushion, one hand pinching his own nipples left and right in turn, penis untouched"),
 },
 "magic": {
   "1": ("e1", "kyakuma", "the succubus maid kneels and offers a cup of steaming green tea on a lacquered tray, polite smile"),
   "2": (None, "kyakuma", "a folded letter in a paper envelope without text sealed with a red wax seal, lying on a low wooden table beside a teacup"),
   "3": ("e2", "chikurin", "the samurai leaps out from behind the bamboo with a wooden practice sword raised, surprise attack, fallen leaves swirling"),
   "4": ("m", "shinshitsu", "the mentor lies on her side on the futon lifting the blanket, patting the empty space beside her, inviting smile, andon lamp light"),
   "5": ("e3", "dojo", "the senior disciple sits cross-legged on the tatami holding " + BOOK + " and a brush, grinning, after-hours training, sunset through the window"),
 },
}
