# N85 牛頭の迷宮（Labyrinth）画像データ。登場人物は全員20歳以上。女性＋ふたなり（ミノタウロスの姉妹アステリア・タウリア）。女装なし。
# ミノタウロスは角・牛の耳・尻尾のある長身で豊満な成人女性。顔は人の女性（牛の頭にしない）、筋肉は描かない。骨・血・怖い小道具は置かない。
MINO_NEG = "cow head, animal face, bull head, snout, muscular woman, muscles, abs, hooves, bones, skull"
DATA = {
 "code": "Labyrinth",
 "world": "ancient underground stone labyrinth, torchlight and deep shadows, cold stone walls, moss, echoing water drops, detailed background",
 "bg": "ancient underground stone labyrinth corridor splitting into two identical passages, flickering torches on stone walls, moss, shallow water on the floor, a faint red thread trailing into the dark",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "アステリア", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, voluptuous, curvy, soft body, long legs, minotaur girl, human woman's face, large curved black horns, cow ears, cow tail, black hair, long hair, red eyes, leather breastplate with gold trim, leather loincloth skirt, gold bracelets, huge breasts, wide hips",
            "name": "the black-haired horned labyrinth mistress in a gold-trimmed leather breastplate",
            "pose": "leaning one arm on a stone wall, blocking the way, teasing low grin, looking down at viewer",
            "neg": MINO_NEG},
   "e1":   {"type": "woman", "jp": "アリア", "canon": False,
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, red hair, long braid, green eyes, traveler's clothes, short cape, ball of red yarn at her hip, holding a lantern, large breasts",
            "name": "the red-braided guide with a lantern and a ball of red thread",
            "pose": "holding up a lantern, finger to her lips, polite sly smile, looking at viewer"},
   "e2":   {"type": "woman", "jp": "フレスカ", "canon": False,
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, very long hair, brown eyes, ancient sheer dancer's robe, gold jewelry, gold armlets, faint painted pigment patterns on her skin, huge breasts",
            "name": "the blonde mural dancer in a sheer ancient robe",
            "pose": "dancing with arms raised, hips swaying, dreamy smile, looking at viewer"},
   "e3":   {"type": "woman", "jp": "ニーナ", "canon": False,
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, short hair, amber eyes, black leather light armor, tool belt, a bunch of small silver bells on her belt, large breasts",
            "name": "the pink-haired trapper in black leather with silver bells",
            "pose": "dangling a small silver bell from one finger, mischievous giggle, looking at viewer"},
   "boss": {"type": "woman", "jp": "タウリア", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 37 years old, adult proportions, beautiful detailed eyes, tall, voluptuous, curvy, soft body, long legs, minotaur girl, human woman's face, gold horns, cow ears, cow tail, white hair, very long hair, gold eyes, ancient white wrapped cloth dress, gold necklace, huge breasts",
            "name": "the white-haired gold-horned elder sister in white wrapped cloth",
            "pose": "standing before a gold-trimmed stone gate, hands folded, gentle sweet smile, looking at viewer",
            "neg": MINO_NEG},
 },
 "places": {
   "entrance":  "underground waterway entrance, wet stone steps, ankle-deep cold water, moss, faint daylight far above",
   "fork":      "forked stone corridor, two identical passages left and right, faded arrow carvings on the wall without text, torches",
   "deadend":   "narrow dead end, stone walls on three sides, one torch, cold damp stone",
   "mural":     "mural hall, ancient wall paintings of dancing women up to the ceiling, torchlight flickering on the pigments",
   "trap":      "trap corridor, thin threads stretched over the floor with small silver bells, narrow stone passage",
   "pit":       "bottom of a pitfall, thick dry straw bed, round opening far above with light",
   "spring":    "underground spring welling from rock, clear water reflecting torchlight, wet stones",
   "dark":      "pitch-dark corridor, a just-extinguished torch smoking, faint light only on skin",
   "stairs":    "spiral stone staircase going down, worn steps, warm air rising from below, torch on the wall",
   "yarn":      "small yarn room, balls of red thread on shelves, lantern light, woolen rug",
   "maps":      "old map archive, walls covered with parchment maps without text, dry paper, lantern",
   "gate":      "before the innermost gate, heavy stone double doors trimmed with gold, a gatekeeper's stone seat, light leaking from the gap",
   "hall":      "innermost hall of the labyrinth, ring of torches, high ceiling with a tiny shaft of light far above, stone bed covered with fur",
   "sisters":   "sisters' bedchamber, rock shelf spread with furs and white cloth, gold ornaments, warm lamp light",
   "chamber":   "small quiet hall before a closed stone chamber door, glowing moss, sleepy calm air",
 },
 "atk": {
   "m1": ("deadend", "he stands with his back against the stone wall, the horned labyrinth mistress clamps him between her thick thighs, rubbing his penis between her inner thighs, her tail blocking the way, pressing him to the wall"),
   "m2": ("hall", "his back is pressed against the stone wall, the horned labyrinth mistress hugs him from the front, his face buried between her huge breasts under her horns, her arms tightening, whispering"),
   "m3": ("hall", "from side, he is pinned against the stone wall with one leg lifted, the horned labyrinth mistress embraces him penetrating his anus with her own penis, anal, kissing him deeply, his own penis separate", {"pen": "penis"}),
   "e1": ("fork", "in the dark fork, the red-braided guide stands behind him holding a lantern, her lips at his ear whispering, licking the rim of his ear, trembling, blush"),
   "e2": ("mural", "he sits on the floor before the murals looking up, the mural dancer dances right in front of his face, her huge breasts swaying inches from his face, gold jewelry, dazed"),
   "e3": ("trap", "he sits tangled in floor threads, the pink-haired trapper flicks a small silver bell hanging from a loose silk loop on his nipple, giggling, back arched"),
   "boss": ("gate", "he stands before the gold-trimmed gate, the gold-horned elder sister bends down kissing him deeply, tongues, saliva trail, pinching both his nipples"),
 },
 "atk_desc": {
   "m1": "the labyrinth mistress traps him between her thighs at a dead end.",
   "m2": "the labyrinth mistress corners him against the wall in her embrace.",
   "m3": "the labyrinth mistress takes him to the deepest part of the labyrinth.",
   "e1": "the guide whispers the way down into his ear.",
   "e2": "the mural dancer sways her breasts before his eyes.",
   "e3": "the trapper hangs a silver bell on his nipple.",
   "boss": "the elder sister melts him with her kiss.",
 },
 "lose": {
   # アステリア 技1（行き止まりの太もも＋追い詰めの抱擁）
   "btl_m1":     ("deadend", "he slumps against the stone wall at the dead end, the horned labyrinth mistress clamps his hips between her thick thighs, her chest pressing him into the wall, red thread loosely around his wrist, cum on her thighs"),
   "onani_m1":   ("fork", "lying alone on the stone floor of the fork, a pillow clamped between his thighs, his chest pressed against the cold wall, stroking his own chest, penis untouched, the horned mistress watches from the dark passage"),
   "inochi_m1":  ("stairs", "on the spiral staircase, the horned labyrinth mistress carries him down in her arms, his hips clamped between her thighs as she sits on a step, his face in her cleavage, cum dripping"),
   "onedari_m1": ("fork", "he sits at a dead end with his knees buckled, the horned labyrinth mistress straddles him from the front clamping him between her thick thighs, grinning down, thin marks scratched on the wall without text, cum on her thighs"),
   # アステリア 技2（★追い詰めの抱擁）
   "btl_m2":     ("hall", "his back is against the stone wall, the horned labyrinth mistress wraps him in a full-body embrace, his face buried between her huge breasts under her black horns, her arms squeezing, twelve loops of red thread on his wrist, cum dripping"),
   "onani_m2":   ("dark", "alone in the pitch-dark corridor pressing his chest against the cold stone wall, arms wrapped around himself, penis untouched, the horned mistress's red eyes glint far away in the dark"),
   "inochi_m2":  ("spring", "beside the underground spring, the horned labyrinth mistress hugs his wet shivering body to her huge breasts, warming him, his face in her cleavage, water dripping, cum on the stone"),
   "onedari_m2": ("stairs", "on a landing of the spiral staircase, he stands with his back to the wall and arms opened, the horned labyrinth mistress embraces him tightly, his face in her cleavage, cum dripping"),
   # アステリア 技3（迷宮の最奥・ふたなり）
   "btl_m3":     ("hall", "from side, he is pinned between the stone wall and the horned labyrinth mistress with one leg lifted, the mistress penetrating his anus with her own penis, anal, kissing him deeply, his own penis separate, a tiny shaft of light far above", {"pen": "penis"}),
   "onani_m3":   ("chamber", "alone with his chest pressed against the stone wall, reaching behind with one wet fingertip only resting at his own anus, frozen, trembling, penis untouched, the horned mistress looks down from behind"),
   "inochi_m3":  ("gate", "on a fur-covered bed inside the gold-trimmed gate, the horned labyrinth mistress holds him in her embrace kissing him deeply, tongues, her arms wrapped around him, his legs limp, cum on the fur"),
   "onedari_m3": ("sisters", "from side, he lies on his back on the furs with legs lifted, the horned labyrinth mistress over him penetrating his anus with her own penis, anal, kissing him deeply, his own penis separate", {"pen": "penis"}),
   # アリア（★道しるべの囁き／糸の手）
   "btl_e1":     ("fork", "he stands at the fork with red thread wound around his wrist, the red-braided guide stands behind him whispering into his ear, her thread-wrapped fingers stroking his penis, lantern light, cum dripping"),
   "onani_e1":   ("yarn", "lying alone on the woolen rug, tracing the rim of his own ear with a wet fingertip, lips murmuring, penis untouched, the red-braided guide watches from the doorway with a lantern"),
   "inochi_e1":  ("dark", "in the pitch-dark corridor, the red-braided guide leads him by a red thread tied to his wrist, her lips at his ear breathing into it, trembling, knees weak, cum dripping"),
   "onedari_e1": ("maps", "he sits before a wall of maps without text, the red-braided guide leans close with her lips at his ear whispering, her breath on his ear, his hips trembling, cum on the floor"),
   # フレスカ（★壁画の舞／壁に押し付けて）
   "btl_e2":     ("mural", "he sits on the floor looking up, the mural dancer dances over him, her huge breasts swaying inches from his face, gold jewelry jingling, no hands on him, dazed, cum dripping"),
   "onani_e2":   ("mural", "sitting alone in the corridor before the murals with hands on his knees, staring at a painted dancer, breathing in rhythm, penis untouched, the mural dancer watches from the painted wall"),
   "inochi_e2":  ("spring", "he kneels at the edge of the underground spring staring at the water, the mural dancer dances above the water, her swaying breasts reflected on the surface, no hands on him, cum dripping"),
   "onedari_e2": ("mural", "he kneels before the murals looking up with his mouth open, the mural dancer sways her huge breasts before his face, slowly, dazed, cum on the floor, no hands on him"),
   # ニーナ（★鈴の罠／落とし穴の底で）
   "btl_e3":     ("trap", "he sits tangled in floor threads, small silver bells hanging from loose silk loops on both his nipples, the pink-haired trapper licks his nipple, giggling, cum on his belly"),
   "onani_e3":   ("pit", "lying alone on the straw at the bottom of the pit, small silver bells hanging from loose threads on his own nipples, swaying his body, penis untouched, the pink-haired trapper looks down from the rim far above"),
   "inochi_e3":  ("stairs", "he walks down the spiral staircase with small silver bells hanging on his nipples, the pink-haired trapper walks behind him giggling, his knees buckling, cum dripping"),
   "onedari_e3": ("trap", "he kneels in the trap corridor swaying his own body, small silver bells ringing on his nipples, the pink-haired trapper crouches beside him watching and giggling, cum on the floor"),
   # タウリア（★姉の口づけ／最奥の門番・ふたなり）
   "btl_boss":   ("gate", "from side, he lies on his back on a white fur before the gold-trimmed gate, the gold-horned elder sister over him penetrating his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("sisters", "sitting alone on the rock shelf sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched, the gold-horned elder sister watches from the lamp"),
   "inochi_boss":("chamber", "from side, he lies on a white fur, the gold-horned elder sister over him penetrating his anus slowly with her own penis, anal, kissing him gently, his eyes heavy, his own penis separate", {"pen": "penis"}),
   "onedari_boss":("hall", "he lies on the fur-covered stone bed, the gold-horned elder sister leans over him kissing him deeply, tongues, saliva trail, rolling both his nipples between her fingers, cum on the fur"),
 },
 "lose_desc": "keeps him at the bottom of the labyrinth, never to return to the surface.",
 "onanie": {
   "master": ("dark", "pressing his chest against the cold stone wall, a pillow clamped between his thighs, stroking his own chest, penis untouched"),
   "e1": ("yarn", "lying on the woolen rug in the dark, tracing the rim of his own ear with a wet fingertip, murmuring, penis untouched"),
   "e2": ("mural", "sitting with hands on his knees staring at a painted dancer, breathing in rhythm, no hands, penis untouched"),
   "e3": ("pit", "lying on the straw, small silver bells hanging from loose threads on his own nipples, swaying his body, penis untouched"),
   "boss": ("sisters", "sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("boss", "spring", "scooping cold spring water with both hands at her chest, offering it, gentle smile"),
   "2": (None, "maps", "an old parchment map of a labyrinth without text spread on a table, a lantern and a red thread laid across it"),
   "3": ("m", "deadend", "pushing a massive stone wall slowly closed with one hand, the passage behind her sealed, teasing grin"),
   "4": (None, "dark", "a just-extinguished torch on a stone wall, thin smoke curling in the pitch-dark corridor, a faint glow of embers"),
   "5": ("e1", "yarn", "holding up a ball of red thread with the cut end dangling, small scissors in her other hand, sly smile"),
 },
}
