# N99 石化の瞳（Medusa）画像データ。登場人物は全員20歳以上。女性のみ（ゴルゴン三姉妹・動く石像・人間の彫刻家）。
# 挿入扱いはメドゥナの髪の蛇だけ（体の一部なので pen なし）。髪の蛇は小さく眠たげで牙なし。石像はひびのない滑らかな寝顔。
# 主人公の石化は「灰色の石の指先」まで（全身の石化・ひびは描かない）。
SNAKE_NEG = "fangs, open-mouthed snake, scary snake, venom, cracks, cracked stone, broken statue, crumbling, fully petrified man, stone body on the man"
STONE = "his fingertips turned to smooth grey stone"
DATA = {
 "code": "Medusa",
 "world": "ancient greek-style temple on a southern rocky mountain, white marble columns, smooth marble statues with peaceful sleeping faces without cracks, moss and fountains, detailed background",
 "bg": "garden of an ancient marble temple, rows of smooth white marble statues with peaceful sleeping faces and no cracks, moss, a gently splashing fountain, white columns, warm afternoon light, no humans",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "リティア",
         "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, tall, long legs, green hair, very long hair, small cute sleepy snakes at the tips of her hair, amber eyes, glowing eyes, white ancient greek robe, gold armlets, huge breasts, gorgon",
         "name": "the green-haired gorgon in a white ancient robe",
         "pose": "one hand raised to her cheek, languid gentle smile, gazing at viewer with amber eyes",
         "neg": SNAKE_NEG},
   "e1": {"type": "woman", "jp": "ペトラ",
          "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, long curly hair, small cute sleepy snakes at the tips of her hair, red eyes, purple ancient greek robe, snake necklace, large breasts, gorgon",
          "name": "the purple-haired gorgon in a purple ancient robe",
          "pose": "finger on her lips, mischievous teasing smirk, looking at viewer",
          "neg": SNAKE_NEG},
   "e2": {"type": "woman", "jp": "カリアティ",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, grey hair, long hair, grey eyes, smooth pale grey marble skin without cracks, draped white cloth garment, large breasts, living statue, calm quiet expression",
          "name": "the grey-haired living statue in a draped cloth",
          "pose": "arms slightly open, standing still like a statue, quiet gentle expression, looking at viewer",
          "neg": SNAKE_NEG},
   "e3": {"type": "woman", "jp": "ロダナ",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, auburn hair, braided hair, green eyes, work clothes dusted with stone powder, apron, chisel, medium breasts, sculptor, human",
          "name": "the auburn-braided sculptor in a dusty apron",
          "pose": "holding a chisel up excitedly, eager passionate grin, leaning forward, looking at viewer",
          "neg": SNAKE_NEG},
   "boss": {"type": "woman", "jp": "メドゥナ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 30 years old, adult proportions, beautiful detailed eyes, tall, long legs, blonde hair, very long hair, small cute sleepy snakes at the tips of her hair, gold eyes, glowing eyes, sheer black veil lifted from her eyes, black ancient greek dress, huge breasts, gorgon",
            "name": "the blonde gorgon in a black ancient dress",
            "pose": "lifting the sheer veil from her eyes with one hand, clingy sweet smile, gazing at viewer with gold eyes",
            "neg": SNAKE_NEG},
 },
 "places": {
   "entrance": "temple entrance, sun-baked stone steps, bronze gate with a snake relief, dry wind",
   "colonnade":"colonnade of white marble columns, cool marble floor, echoing corridor",
   "garden":   "statue garden, rows of smooth marble statues with peaceful sleeping faces without cracks, moss, fountain",
   "nightgarden":"statue garden under the moon, smooth statues glowing white in moonlight, night dew",
   "throne":   "eldest sister's throne room, cold stone pedestal, gold candlesticks, frankincense smoke",
   "pool":     "still mirror-like spring in the temple, cold clear water, stone rim",
   "boudoir":  "gorgon's bedchamber, purple drapes, silk bed, silver cup of chilled wine",
   "studio":   "sculptor's workshop, stone dust in the air, chisels and mallets, unfinished smooth statues without faces",
   "coldspring":"underground cold spring, cold spring water, wet stones, swaying oil lamp",
   "cradle":   "youngest sister's chamber, black drapes, a large cradle shaped from smooth stone arms, myrrh smoke",
   "gallery":  "exhibition hall, rows of empty stone pedestals, blank nameplates without text",
   "roof":     "temple rooftop terrace at sunset, rocky mountains, stone balustrade, strong wind",
   "shedroom": "small room of shed snakeskins, bundles of translucent white shed skins, dried grass",
   "guest":    "cold small stone guest room, stone bed with a single blanket, small window",
 },
 "atk": {
   "m1": ("throne", "he sits on the cold stone pedestal, the green-haired gorgon straddles his lap squeezing his penis between her thighs, gazing down with glowing amber eyes, a sleepy hair snake nudging his chin up, " + STONE),
   "m2": ("entrance", "he stands frozen before the bronze gate, the green-haired gorgon bends down gazing into his face with glowing amber eyes, stroking his hand, " + STONE + ", no other touch, knees trembling"),
   "m3": ("colonnade", "he leans back against a marble column, small sleepy snakes from the green-haired gorgon's hair licking his nipples and his ear, the gorgon gazing at him, " + STONE + ", trembling"),
   "e1": ("boudoir", "he lies on the silk bed, the purple-haired gorgon leans over him kissing him deeply, tongues, feeding him chilled wine mouth to mouth, a wine drop on his lips, silver cup, " + STONE),
   "e2": ("garden", "the grey-haired living statue hugs him tightly from behind, her smooth cool grey arms wrapped around his chest and waist, he cannot move, gentle expression, " + STONE),
   "e3": ("studio", "he stands on the workbench like a model, the sculptor traces the outline of his nipple with her fingernail as if carving, stone dust in the air, eager face, " + STONE),
   "boss": ("cradle", "he lies in the stone-arm cradle with his face buried in the blonde gorgon's huge breasts, pafupafu, a small smooth hair snake entering his anus, anal, rocking, " + STONE),
 },
 "atk_desc": {
   "m1": "the gorgon squeezes him between her thighs on the cold stone pedestal.",
   "m2": "the gorgon's amber gaze turns his fingers to stone one by one.",
   "m3": "the sleepy snakes of her hair lick his nipples and ears.",
   "e1": "the gorgon kisses him with cold stone lips.",
   "e2": "the living statue embraces him with cool marble arms.",
   "e3": "the sculptor carves out the shape of his nipples with her nails.",
   "boss": "the gorgon rocks him in a cradle of stone arms.",
 },
 "lose": {
   # リティア 技1（石の台座で）
   "btl_m1":     ("throne", "he sits on the cold stone pedestal, the green-haired gorgon straddles his lap with his penis clamped between her thighs, gazing down with glowing amber eyes, a sleepy hair snake nudging his chin, " + STONE + ", cum on her thighs"),
   "onani_m1":   ("pool", "kneeling alone at the spring, his fingertips dipped in the cold water, thighs pressed against the cold stone rim, staring at his reflection, penis untouched, the green-haired gorgon watches far away across the spring"),
   "inochi_m1":  ("nightgarden", "he sits on an empty stone pedestal among moonlit statues, the green-haired gorgon sits on his lap with his penis between her thighs, holding his grey stone fingertips in her hand, cum on her thighs"),
   "onedari_m1": ("gallery", "he sits on a chosen empty pedestal with a blank nameplate without text, holding up one finger, the green-haired gorgon straddles his lap with his penis between her thighs, gazing at the finger, " + STONE),
   # リティア 技2（★石化の眼差し）
   "btl_m2":     ("entrance", "he kneels on the stone steps before the bronze gate, the green-haired gorgon bends down holding his chin, gazing into his face with glowing amber eyes, stroking his hand, " + STONE + ", back arched, cum on the steps"),
   "onani_m2":   ("pool", "kneeling alone at the spring, fingertips dipped in the cold water, staring at his own reflection, hips floating, penis untouched, the green-haired gorgon watches far behind him"),
   "inochi_m2":  ("guest", "he lies on the stone bed under a blanket, the green-haired gorgon stands in the doorway at dawn gazing at him with glowing amber eyes, " + STONE + ", his hips lifted, trembling, no hands on him"),
   "onedari_m2": ("roof", "at the sunset balustrade, he holds out one hand toward the green-haired gorgon, the gorgon gazes only at his outstretched finger with glowing amber eyes, " + STONE + ", knees trembling, sunset"),
   # リティア 技3（蛇の髪）
   "btl_m3":     ("colonnade", "he slumps against a marble column, small sleepy hair snakes of the green-haired gorgon licking both his nipples and his ear, the gorgon gazing down at him, " + STONE + ", cum on the marble floor"),
   "onani_m3":   ("shedroom", "sitting alone among bundles of shed snakeskins, trailing a thin shed skin over his own nipple and ear, penis untouched, " + STONE + ", the green-haired gorgon watches far away by the shelves"),
   "inochi_m3":  ("coldspring", "he sits chest-deep in the cold spring, small sleepy hair snakes of the green-haired gorgon crawling over his wet chest and licking his ear, the gorgon behind him gazing, swaying lamp light"),
   "onedari_m3": ("throne", "he kneels before the stone throne, small sleepy hair snakes of the green-haired gorgon coiling around his chest licking his nipple and his ear, the gorgon seated gazing down, " + STONE),
   # ペトラ（★石の唇）
   "btl_e1":     ("boudoir", "he lies on the silk bed behind purple drapes, the purple-haired gorgon kisses him deeply, tongues, chilled wine dripping from their lips, her cold hand stroking his penis, " + STONE + ", cum on the silk"),
   "onani_e1":   ("guest", "sitting alone on the stone bed pressing a cold silver cup to his lips, two of his own fingers in his mouth, penis untouched, the purple-haired gorgon watches far away from the doorway"),
   "inochi_e1":  ("coldspring", "he sits in the cold spring water, the purple-haired gorgon holds his face and kisses him deeply, tongues, wet stones, swaying lamp, " + STONE + ", trembling"),
   "onedari_e1": ("garden", "he sits on the fountain rim, the purple-haired gorgon kisses his grey stone fingertips, her lips moving to his neck, smooth statues around, trembling, blush"),
   # カリアティ（★石像の抱擁）
   "btl_e2":     ("garden", "the grey-haired living statue hugs him from behind, her smooth cool grey arms around his chest and waist, her marble breasts pressed to his back, " + STONE + ", cum dripping onto the moss"),
   "onani_e2":   ("colonnade", "lying alone face down on the cold marble floor, rubbing his chest against the stone, hips twitching, penis untouched, the grey-haired living statue watches far away between the columns"),
   "inochi_e2":  ("nightgarden", "he sleeps in the arms of the grey-haired living statue sitting among moonlit statues, her smooth grey arms wrapped around him, " + STONE + ", night dew, peaceful"),
   "onedari_e2": ("gallery", "on one pedestal, the grey-haired living statue embraces him from behind in the same pose, both standing still like a single sculpture, " + STONE + ", trembling"),
   # ロダナ（★彫り出す指）
   "btl_e3":     ("studio", "he stands on the workbench as a model, the sculptor traces his nipple with her fingernail as if carving, her knee pressing his penis, stone dust, " + STONE + ", cum on her apron"),
   "onani_e3":   ("guest", "sitting alone on the stone bed, tracing the outline of his own nipple with a fingernail, pulling it to a point, penis untouched, the sculptor watches far away through the window"),
   "inochi_e3":  ("nightgarden", "he poses on a moonlit pedestal, the sculptor stands beside him tracing his nipple with her fingernail, sketches without text scattered on the grass, " + STONE + ", trembling"),
   "onedari_e3": ("gallery", "he poses on an empty pedestal, the sculptor pinches his right nipple checking its shape, her knee pressing his penis, " + STONE + ", cum dripping, an unfinished statue without a face beside"),
   # メドゥナ（★石の揺りかご・髪の蛇）
   "btl_boss":   ("cradle", "from side, he lies in the stone-arm cradle with his face buried in the blonde gorgon's huge breasts, pafupafu, a small smooth hair snake entering his anus, anal, rocking, " + STONE + ", cum on his stomach"),
   "onani_boss": ("guest", "lying alone face down with his face buried in a cushion, one wet finger shallowly in his own anus, penis untouched, " + STONE + ", the blonde gorgon watches far away from the doorway"),
   "inochi_boss":("coldspring", "in the cold spring, the blonde gorgon holds him against her huge breasts, his face buried, a small smooth hair snake entering his anus, anal, lamp light, his body limp"),
   "onedari_boss":("garden", "from side, in a stone-arm cradle in the middle of the statue garden, he lies with his face buried in the blonde gorgon's huge breasts, a small smooth hair snake in his anus, anal, his grey stone toe tips, cum on his stomach"),
 },
 "lose_desc": "keeps him forever as a statue in the temple garden, waiting to be caressed.",
 "onanie": {
   "master": ("pool", "kneeling at the spring with his fingertips dipped in the cold water, staring at his own reflection, " + STONE + ", penis untouched"),
   "e1": ("boudoir", "pressing a cold silver cup to his lips, two of his own fingers in his mouth, penis untouched"),
   "e2": ("colonnade", "lying face down on the cold marble floor, rubbing his chest against the stone, penis untouched"),
   "e3": ("studio", "tracing the outline of his own nipple with a fingernail as if carving, penis untouched"),
   "boss": ("cradle", "lying face down with his face buried in a cushion, one wet finger shallowly in his own anus, penis untouched"),
 },
 "magic": {
   "1": (None, "shedroom", "a coil of translucent white shed snakeskin lying on dried grass, soft light, delicate texture"),
   "2": (None, "entrance", "sunlit ancient stone steps leading up to a bronze gate with a snake relief, rocky mountain"),
   "3": (None, "colonnade", "a glowing amber eye-shaped magic circle carved into the marble floor, faint golden light, empty colonnade"),
   "4": ("m", "throne", "lowering her face toward the viewer with glowing amber eyes, sleepy hair snakes swaying, hypnotic gaze"),
   "5": (None, "garden", "rows of smooth white marble statues with peaceful sleeping faces and no cracks, moss, a fountain in golden sunset light"),
 },
}
