# N86 女将校の捕虜収容所（Military）画像データ。登場人物は全員20歳以上。女性＋NH（軍医ヘルミーナ・副所長ジークリンデ）。女装なし。
# 架空の軍。軍服に階級章・紋章・旗・記章は描かない（no insignia）。拷問・鞭・痛みは描かない。主人公は捕虜（場面では裸、着衣の相手が上位）。
NOINS = "plain uniform without insignia, no badges, no emblems, no rank patches"
MIL_NEG = "insignia, rank insignia, emblem, badge, flag, national flag, patch, swastika, iron cross, medal, armband, whip, gun, rifle"
DATA = {
 "code": "Military",
 "world": "fictional frontier prisoner camp in the mountains, cold stone buildings, lamp light, leather and boot polish, no flags, no emblems, detailed background",
 "bg": "stone prisoner camp courtyard in a mountain valley at dawn, watchtower, barred cell windows, packed dirt roll-call ground, plain stone walls without flags or emblems, lamp posts, misty mountains",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "ヴァルトラウト", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, voluptuous, long legs, black hair, long hair tied in a low ponytail, red eyes, black officer uniform with the collar unbuttoned showing cleavage, " + NOINS + ", peaked cap, black leather gloves, polished black knee-high riding boots, huge breasts",
            "name": "the black-haired commandant in a black officer uniform",
            "pose": "standing with arms crossed, one gloved hand at her chin, cold composed smile, looking down at viewer",
            "neg": MIL_NEG},
   "e1":   {"type": "woman", "jp": "ツェツィーリエ", "canon": False,
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, twin braids, green eyes, khaki guard uniform, " + NOINS + ", garrison cap, ring of keys on her belt, large breasts",
            "name": "the brown-braided guard in a khaki uniform with a key ring",
            "pose": "jingling a ring of keys in one hand, cheerful teasing grin, looking at viewer",
            "neg": MIL_NEG},
   "e2":   {"type": "nh", "jp": "ヘルミーナ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 28 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, blonde hair, hair bun, amber eyes, glasses, white doctor's coat over a gray uniform, " + NOINS + ", white gloves, stethoscope around her neck, large breasts",
            "name": "the blonde bespectacled army doctor in a white coat",
            "pose": "adjusting a white glove, gentle polite smile, holding a stethoscope, looking at viewer",
            "neg": MIL_NEG},
   "e3":   {"type": "woman", "jp": "リーゼロッテ", "canon": False,
            "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, red hair, short bob, gold eyes, olive signal corps uniform, " + NOINS + ", headphone-type magic receiver around her neck, expressionless, medium breasts",
            "name": "the red-bobbed signal operator in an olive uniform",
            "pose": "holding a headphone-type receiver to one ear, expressionless, looking at viewer"},
   "boss": {"type": "nh", "jp": "ジークリンデ", "canon": False,
            "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, very tall, slender, elegant, feminine body, long legs, silver hair, very long hair with metallic sheen, purple eyes, gray officer uniform, " + NOINS + ", long black greatcoat, black gloves, large breasts",
            "name": "the silver-haired vice-commandant in a black greatcoat",
            "pose": "standing straight with hands behind her back, stern quiet expression, looking down at viewer",
            "neg": MIL_NEG},
 },
 "places": {
   "office":   "commandant's office, ebony desk, plain plaster walls without flags or emblems, leather armchair, ink bottle, mountain shadows beyond the window",
   "cell":     "stone prison cell, iron bars casting shadows, straw bed, thin moonlight from a high window, dripping water",
   "storage":  "confiscated goods storeroom, shelves with blank wooden tags, a sword and a travel cloak on the shelves, blank ledger without text",
   "infirmary":"infirmary, white folding screen, examination bed with white sheets, glass cabinet with medical instruments",
   "brig":     "windowless brig room, one lamp, hard cot with a wool blanket, heavy bolted door",
   "radio":    "radio room, humming magic receiver machine, blinking crystals, rolls of paper tape without text",
   "intake":   "intake inspection room, inspection table, wooden crate for belongings, height gauge on the wall without numbers",
   "yard":     "roll-call yard in cold morning air, packed dirt ground, watchtower looming, stone walls",
   "tower":    "windy watchtower platform, telescope, lamp and a blank logbook without text, cell windows far below",
   "bath":     "officers' bathhouse, steam, cypress wooden bathtub, soap, folded uniform and riding boots on a bench",
   "clothing": "clothing storeroom, stacks of plain gray prisoner clothes, clean folded cloth",
   "visit":    "visiting room, table divided by a grille, a blank roster without text, wax seal, wall clock without numbers",
   "private":  "commandant's private room, fireplace, thick carpet, polished boots lined on a shelf, wine glass",
   "stable":   "horse stable, hay, leather saddles, a boot-polishing stand",
   "mess":     "officers' mess hall, long table, silver candlesticks, bread and coffee",
 },
 "atk": {
   "m1": ("office", "he kneels on the carpet before the ebony desk, the commandant sits in the leather chair lifting his chin with the toe of her polished riding boot, the sole of her other boot stroking his penis, cold smile"),
   "m2": ("office", "he kneels between the knees of the seated commandant, his face buried in her cleavage through the unbuttoned black uniform, her gloved hands pressing her breasts together around his face, interrogating"),
   "m3": ("yard", "the commandant stands behind him holding his face into her chest, her lips at his ear reading a surrender demand, her black-gloved fingers pinching his nipple, his knees trembling"),
   "e1": ("intake", "he stands with both hands raised by the inspection table, the brown-braided guard pats his chest with her fingertips and pinches his nipple, grinning, keys jingling"),
   "e2": ("infirmary", "from side, he lies on his side on the white examination bed holding his knees, the army doctor sits beside him with two ointment-slick white-gloved fingers in his anus, fingering, calm smile, stethoscope"),
   "e3": ("radio", "he kneels on the floor wearing a headphone receiver over his ears, the signal operator leans down whispering a code word into his ear, expressionless, his body obeying, trembling"),
   "boss": ("brig", "in the dark brig, the vice-commandant holds his jaw and kisses him deeply, tongues, her other gloved hand pinching his nipple, lamp light, her greatcoat around him"),
 },
 "atk_desc": {
   "m1": "the commandant inspects him with her polished riding boots.",
   "m2": "the commandant interrogates him inside her breasts.",
   "m3": "the commandant reads the surrender demand into his ear.",
   "e1": "the guard runs a body search on him.",
   "e2": "the army doctor performs a sanitary inspection with her gloved fingers.",
   "e3": "the signal operator whispers code words into his ear.",
   "boss": "the vice-commandant takes the night roll call with her lips.",
 },
 "lose": {
   # ヴァルトラウト 技1（軍靴の検分＋尋問の胸）
   "btl_m1":     ("office", "he kneels on the carpet before the ebony desk, the seated commandant presses his penis between her black-stockinged feet, one polished riding boot beside, her gloved hand holding his face to her chest, cum on the stockings"),
   "onani_m1":   ("cell", "kneeling alone on the straw bed with his face pressed into a rolled-up jacket, breathing shallowly, stroking his own chest, penis untouched, the commandant watches from beyond the iron bars"),
   "inochi_m1":  ("stable", "he kneels by the boot-polishing stand pressing his cheek against the commandant's polished riding boot, the commandant stands over him in her black uniform, gloved hand on his head, cold smile"),
   "onedari_m1": ("private", "he sits barefoot on the thick carpet before the fireplace, the commandant sits in a chair stroking his bare foot and thigh with the sole of her polished boot, his face pulled into her cleavage, cum on the carpet"),
   # ヴァルトラウト 技2（★尋問の胸）
   "btl_m2":     ("office", "he kneels between the knees of the commandant in the leather armchair, his face buried deep in her cleavage, her gloved hands pressing her breasts around his face, cum dripping onto the carpet"),
   "onani_m2":   ("cell", "lying face down alone on the straw bed with his face buried in a rolled-up jacket, hands on his own chest, breath shallow, penis untouched, the commandant watches from the barred door"),
   "inochi_m2":  ("visit", "by the grilled table, the commandant holds his face buried in her cleavage, a sealed blank roster without text on the table, his hands limp, cum dripping"),
   "onedari_m2": ("storage", "among the shelves of confiscated goods, the commandant hugs his face into her cleavage, a small cloth charm bag on the shelf with a blank tag, cum dripping"),
   # ヴァルトラウト 技3（降伏勧告＋尋問の胸）
   "btl_m3":     ("yard", "he kneels on the packed dirt of the roll-call yard, the commandant holds his face into her chest from behind, her lips at his ear, her black-gloved fingers rolling his nipple, cum on the ground"),
   "onani_m3":   ("cell", "kneeling alone in the moonlit cell whispering to himself, both fingers pinching his own nipples, penis untouched, the commandant watches from beyond the iron bars"),
   "inochi_m3":  ("office", "he stands before the ebony desk with a blank sealed letter without text on it, the commandant holds his face in her chest, her lips at his ear, gloved fingers pinching his nipple, cum dripping"),
   "onedari_m3": ("mess", "he stands by the long table under silver candlesticks, the commandant holds him against her chest, her lips at his ear, gloved fingers pinching his nipple, a blank sheet without text on the wall, cum dripping"),
   # ツェツィーリエ（★所持品検査／検査台の脚）
   "btl_e1":     ("intake", "he stands with both hands raised, the brown-braided guard sits on the inspection table clamping his hips between her thighs, her fingers pinching his nipples, grinning, keys jingling, cum dripping"),
   "onani_e1":   ("cell", "standing alone in the cell, feeling for his own nipples with his fingertips, penis untouched, the brown-braided guard watches through the iron bars jingling keys"),
   "inochi_e1":  ("clothing", "he stands among stacks of gray prisoner clothes with both hands raised, the brown-braided guard pinches his nipples, grinning, a folded gray prisoner shirt on the shelf, cum dripping"),
   "onedari_e1": ("yard", "he stands on the roll-call ground with both hands raised high, the brown-braided guard stands in front of him pinching both his nipples, grinning, cum on the dirt"),
   # ヘルミーナ（★衛生検査／聴診の手・NH、挿入なし）
   "btl_e2":     ("infirmary", "from side, he lies on his back on the white examination bed holding his knees, the army doctor sits beside him with two white-gloved fingers in his anus, fingering, stethoscope on his chest, cum on his belly"),
   "onani_e2":   ("cell", "lying alone on his side on the straw bed wearing a white glove, two of his own wet gloved fingers in his own anus, penis untouched, the army doctor watches from beyond the bars"),
   "inochi_e2":  ("infirmary", "he lies face down on the examination bed with his hips raised, the army doctor sits beside him with two white-gloved fingers in his anus, fingering, a blank medical certificate without text on a clipboard, cum on the sheet"),
   "onedari_e2": ("infirmary", "behind the white folding screen, he lies on his side on the bed wearing one white glove, the army doctor's two white-gloved fingers in his anus, fingering, calm smile, cum on the sheet"),
   # リーゼロッテ（★暗号の囁き／伏せの姿勢で）
   "btl_e3":     ("radio", "he lies prone on the floor with his hips raised, wearing a headphone receiver, the signal operator kneels beside him whispering into his ear, expressionless, cum dripping onto the floor"),
   "onani_e3":   ("cell", "kneeling alone with both hands only cupped over his own ears, murmuring code words, hips floating, no hands on his body, penis untouched, a receiver hanging on the stone wall, the signal operator far away"),
   "inochi_e3":  ("tower", "he kneels on the windy watchtower platform, the signal operator leans down reading a blank paper tape without text into his ear, expressionless, trembling, cum on the floorboards"),
   "onedari_e3": ("radio", "he lies prone on the floor by the transmitter with his hips raised, the signal operator sits on his thighs rubbing her bottom against his, whispering into his ear, expressionless, cum dripping"),
   # ジークリンデ（★夜間点呼／営倉の夜・NH）
   "btl_boss":   ("brig", "from side, he lies on his back on the hard cot in the dark brig, the vice-commandant over him penetrating his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("cell", "lying alone in the dark cell sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched, the vice-commandant watches from beyond the bars"),
   "inochi_boss":("bath", "from side, he leans back on the edge of the cypress bathtub in steam, the vice-commandant over him penetrating his anus with her own penis, anal, kissing him deeply, her greatcoat on the bench, his own penis separate", {"pen": "penis"}),
   "onedari_boss":("office", "from side, he lies on his back on the ebony desk, the vice-commandant over him penetrating his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate, a blank sheet without text on the wall", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the prisoner camp as confiscated property forever.",
 "onanie": {
   "master": ("cell", "kneeling on the straw bed with his face pressed into a rolled-up jacket, breathing shallowly, stroking his own chest, penis untouched"),
   "e1": ("cell", "standing in the cell, feeling for his own nipples with his fingertips, penis untouched"),
   "e2": ("cell", "lying on his side wearing a white glove, two of his own wet gloved fingers in his own anus, penis untouched"),
   "e3": ("cell", "kneeling with both hands cupped over his own ears, murmuring code words, hips floating, no hands on his body, penis untouched"),
   "boss": ("cell", "lying in the dark sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "yard", "standing on the roll-call ground with one gloved hand raised, calling the roll, cold commanding expression"),
   "2": ("e3", "radio", "wearing the headphone receiver, operating the humming receiver machine with blinking crystals, expressionless"),
   "3": (None, "cell", "soft leather ankle cuffs joined by a thin chain lying open on the stone floor of the cell, moonlight"),
   "4": ("boss", "brig", "holding the heavy brig door open with one hand, a ring of keys in the other, stern look"),
   "5": (None, "office", "a closed blank ledger without text on the ebony desk, black leather gloves laid on top, an ink pen, lamp light"),
 },
}
