# N97 鏡の館（Mirror）画像データ。登場人物は全員20歳以上。女性のみ。挿入はアルジェンタの硝子のペニバン（btl_boss・onedari_boss）だけ。
# 主人公の顔は描かない：鏡に映るのは主人公の後ろ姿・紅潮した肩まで。鏡は割れない（ネガに broken glass）。
ST = {"pen": "strapon"}
GLASS_NEG = "broken glass, shattered mirror, cracked mirror, glass shards, his face reflected in the mirror"
DATA = {
 "code": "Mirror",
 "world": "old mansion deep in a forest at night whose walls are covered with mirrors, countless candle lights multiplied in the mirrors, greenish dark reflections, detailed background",
 "bg": "long mirror corridor of an old mansion, both walls covered with tall ornate mirrors, rows of candelabras multiplied endlessly in the reflections, polished floor, no humans, unbroken mirrors",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "スペクラ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, tall, slender, long legs, black hair, very long straight hair, purple eyes, black dress with silver trim, black lace gloves, silver hand mirror, large breasts, witch",
         "name": "the black-haired mirror witch in a silver-trimmed black dress",
         "pose": "holding up a silver hand mirror beside her face, sly amused smile, looking at viewer",
         "neg": GLASS_NEG},
   "e1": {"type": "woman", "jp": "リフレ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, bob cut, gold eyes, glossy white maid dress shining like a mirror, white headdress, large breasts, mirror spirit, playful",
          "name": "the pink-bobbed mirror maid in a glossy white maid dress",
          "pose": "mimicking a pose with both hands raised like a reflection, innocent playful grin, looking at viewer",
          "neg": GLASS_NEG},
   "e2": {"type": "woman", "jp": "ミュゼット",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, red hair, bob cut, green eyes, black apron dress, bundle of makeup brushes at her waist, large breasts, makeup artist",
          "name": "the red-bobbed makeup artist in a black apron dress",
          "pose": "holding a soft powder brush up near her lips, polite gentle smile, looking at viewer",
          "neg": GLASS_NEG},
   "e3": {"type": "woman", "jp": "グラシエ",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long wavy hair, amber eyes, wine red dress with gold ornaments, large breasts, mirror spirit, motherly",
          "name": "the golden-haired mirror spirit in a wine red dress",
          "pose": "arms opened wide inviting a hug, warm doting smile, looking at viewer",
          "neg": GLASS_NEG},
   "boss": {"strap": "clear glass strap-on on a black harness", "type": "woman", "jp": "アルジェンタ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, long legs, silver hair, very long hair, metallic hair sheen, red eyes, reflective silver and black gown, glass crown, huge breasts, queen, noble",
            "name": "the silver-haired mirror queen in a glass crown",
            "pose": "one hand on her hip, chin raised, cold noble smile, looking down at viewer",
            "neg": GLASS_NEG},
 },
 "places": {
   "hall":     "entrance hall of an old mansion, a huge dusty clouded mirror, cold stone floor, heavy closed door, a single candle",
   "corridor": "mirror corridor, both walls covered with tall ornate mirrors, rows of candelabras multiplied endlessly",
   "facing":   "room of two huge mirrors facing each other, infinite reflections fading into greenish darkness, silent",
   "bedroom":  "mirrored bedroom, mirrors on the ceiling and walls, black silk sheets, a silver-framed mirror by the pillow",
   "vanity":   "dressing room, triple vanity mirror, powder puffs and makeup brushes, soft round stool",
   "psyche":   "room with tall gold-framed standing mirrors arranged in a circle, wine red carpet, warm fireplace",
   "ballroom": "mirrored ballroom, walls covered with mirrors, polished floor, high chandelier light reflected many times",
   "bath":     "marble bathroom, steamed-up mirror with a wiped streak, marble bathtub, dripping water",
   "study":    "witch's study, shelves displaying a collection of silver hand mirrors, ebony desk, purple lamp light",
   "attic":    "attic storeroom, rows of mirrors covered with white cloths, slanted wooden ceiling, moonlight through a small window",
   "workshop": "underground mirror workshop, glass polishing table, mirrors turned face down, cool dim air",
   "throne":   "queen's throne room, a glass throne, silver and black drapes, mirrored floor reflecting everything",
   "greenhouse":"glass greenhouse at night, glass walls, night-blooming flowers, damp soil, moonlight through glass",
   "window":   "velvet chaise by a tall night window, the dark glass reflecting the candlelit room, dark forest outside",
   "spring":   "still spring in the back garden at night, mirror-like water surface reflecting the moon, moss, ferns",
 },
 "atk": {
   "m1": ("corridor", "he stands in the mirror corridor, the mirror witch stands behind him gripping his penis with her black-gloved hand, the mirror ahead reflects his back and flushed shoulders, candle lights multiplying, knees trembling"),
   "m2": ("facing", "he stands between two huge facing mirrors, endless reflections of his back fading into darkness, the mirror witch stands beside him touching only his chin, whispering into his ear, knees buckling"),
   "m3": ("ballroom", "in the mirrored ballroom, pale glassy hands reach out of the mirror surface pinching both his nipples, the mirror witch kisses him deeply, tongues, the mirror behind reflects his back"),
   "e1": ("psyche", "he stands facing the mirror maid who copies his exact pose like a reflection, the mirror maid pinching both his nipples, a tall gold-framed mirror behind him reflects his back, trembling"),
   "e2": ("vanity", "he sits on a round stool facing the triple mirror, the makeup artist stands behind him stroking the rim of his ear with a soft powder brush, the mirror shows only his back and red ear, trembling"),
   "e3": ("psyche", "the golden-haired mirror spirit hugs him tightly from behind, her large breasts pressed against his back, her hands stroking his chest, a tall gold-framed mirror behind them reflects his back in her arms"),
   "boss": ("throne", "on the glass throne, the mirror queen holds his face buried in her huge breasts, pafupafu, bending down to lick his ear, the mirrored floor reflects his back, his hips twitching"),
 },
 "atk_desc": {
   "m1": "the mirror witch strokes him while making him watch the mirror.",
   "m2": "the mirror witch multiplies him in the facing mirrors, three at a time.",
   "m3": "hands from the mirror pinch his nipples while the mirror witch kisses him.",
   "e1": "the mirror maid copies his every gesture and pinches his nipples.",
   "e2": "the makeup artist powders the inside of his ear with a soft brush.",
   "e3": "the mirror spirit embraces him from behind before the standing mirror.",
   "boss": "the mirror queen buries his face in her breasts in an endless mirror corridor.",
 },
 "lose": {
   # スペクラ 技1（鏡越しの・手コキ）
   "btl_m1":     ("corridor", "he kneels in the middle of the mirror corridor, the mirror witch kneels behind him gripping his penis with her black-gloved hand, the mirrors ahead reflect rows of his back, cum dripping onto the floor"),
   "onani_m1":   ("bedroom", "kneeling alone on black silk sheets, holding two silver hand mirrors facing each other before his chest, staring into the endless reflection, penis untouched, the mirror witch watches far behind by the mirrored wall"),
   "inochi_m1":  ("hall", "he stands with one palm pressed flat on the huge clouded mirror, the mirror witch stands behind him gripping his penis with her black-gloved hand, the mirror reflects his back, cum on the glass"),
   "onedari_m1": ("study", "he kneels by the ebony desk holding up a silver hand mirror, the mirror witch sits behind him gripping his penis with her black-gloved hand, shelves of hand mirrors, cum dripping, trembling"),
   # スペクラ 技2（★合わせ鏡）
   "btl_m2":     ("facing", "he kneels between two huge facing mirrors, endless reflections of his back fading into greenish darkness, the mirror witch touches only his chin, whispering into his ear, back arched, cum dripping, no other touch"),
   "onani_m2":   ("corridor", "sitting alone on the floor of the mirror corridor, holding two small hand mirrors facing each other, staring into them, hips lifting, penis untouched, the mirror witch watches far down the corridor"),
   "inochi_m2":  ("attic", "among rows of cloth-covered mirrors, the last white cloth slipping off a tall mirror, he kneels before it limp, the mirror witch stands behind him whispering into his ear, cum on the wooden floor"),
   "onedari_m2": ("bedroom", "he lies on black silk sheets between a pair of angled mirrors, endless reflections of his back above, the mirror witch sits beside him stroking his chin, whispering, back arched, cum on his stomach"),
   # スペクラ 技3（鏡から伸びる手）
   "btl_m3":     ("ballroom", "in the mirrored ballroom, pale glassy hands reach out of the mirror wall pinching both his nipples, the mirror witch kisses him deeply, tongues, saliva trail, he sags against the mirror, cum on the polished floor"),
   "onani_m3":   ("bath", "kneeling alone before the steamed-up mirror, pressing his lips to the wiped streak, chest thrust toward the glass, penis untouched, the mirror witch watches far behind in the steam"),
   "inochi_m3":  ("window", "he kneels on the velvet chaise with his chest pressed to the dark window glass, pale glassy hands reach through the glass pinching his nipples, the mirror witch kisses him from the side, cum on the chaise"),
   "onedari_m3": ("bedroom", "he lies on black silk sheets with his chest thrust up, pale glassy hands reach from the pillowside mirror pinching his nipples, the mirror witch kisses him deeply, tongues, trembling"),
   # リフレ（★映し身）
   "btl_e1":     ("psyche", "the mirror maid sits on a vanity table with his hips clamped between her thighs, copying his face and pose while pinching both his nipples, a tall mirror behind reflects his back, cum on her thighs"),
   "onani_e1":   ("vanity", "sitting alone on the round stool facing the triple mirror, pinching both of his own nipples at the same time, the mirror showing only his back, penis untouched, the mirror maid watches far behind"),
   "inochi_e1":  ("greenhouse", "among night flowers by the glass wall, he stands facing the mirror maid, both of them in the same pose, the mirror maid pinching both his nipples, the glass reflecting his back, cum dripping"),
   "onedari_e1": ("vanity", "he sits on the vanity table with his penis clamped between the mirror maid's thighs, the mirror maid copies his pose pinching his nipples, the triple mirror reflects his back, cum on her thighs"),
   # ミュゼット（★化粧筆）
   "btl_e2":     ("vanity", "he sits slumped on the round stool, the makeup artist sits facing him stroking the inside of his ear with a thin brush, her stockinged foot pressing his penis, the triple mirror reflects his back, cum on her foot"),
   "onani_e2":   ("bath", "sitting alone on the marble edge before the steamed-up mirror, stroking the rim of his own ear with a soft makeup brush, mouth open, penis untouched, the makeup artist watches far behind in the steam"),
   "inochi_e2":  ("window", "he lies on the velvet chaise, the makeup artist leans over him dabbing white powder on his ear with a soft brush, powder dust drifting, the dark window glass reflecting his back, trembling"),
   "onedari_e2": ("bedroom", "he sits on black silk sheets holding a hand mirror up, the makeup artist sits behind him slipping a soft brush into his ear, her foot stroking his penis, cum on the silk"),
   # グラシエ（★姿見の抱擁）
   "btl_e3":     ("psyche", "the golden-haired mirror spirit hugs him from behind, her large breasts pressed against his back, her hand stroking his penis, the tall gold-framed mirrors around them reflect his back in her arms, cum dripping"),
   "onani_e3":   ("ballroom", "standing alone before the mirrored wall, wrapping his own arms around himself from behind, stroking his own chest, the mirror shows only his back, penis untouched, the mirror spirit watches far across the ballroom"),
   "inochi_e3":  ("spring", "he kneels on the mossy bank, the golden-haired mirror spirit kneels behind him hugging him, her breasts pressed to his back, the still water reflecting the moon and his back, his body limp"),
   "onedari_e3": ("bedroom", "he lies on his side on black silk sheets, the golden-haired mirror spirit hugs him from behind, her breasts against his back, a gold-framed mirror by the pillow reflects his back, sleepy, cum on the silk"),
   # アルジェンタ（★無限回廊／硝子の張り型）
   "btl_boss":   ("throne", "from side, the mirror queen sits on the glass throne holding him on her lap by his hips, his face buried in her huge breasts, the mirror queen pegging his anus from below with her clear glass strap-on, anal, licking his ear, his own penis separate, cum on her gown", ST),
   "onani_boss": ("bedroom", "lying alone face down with his face buried in a cushion, licking two wet fingers and tracing his own ear, glancing at the pillowside mirror that reflects his back, penis untouched, the mirror queen watches far away"),
   "inochi_boss":("workshop", "among mirrors turned face down, the mirror queen presses his face into her huge breasts, pafupafu, licking his ear, pushing his back against an upturned mirror that reflects his back, his body limp"),
   "onedari_boss":("corridor", "at the far end of the mirror corridor, he lies on his back with his face in the mirror queen's huge breasts, the mirror queen pegging his anus with her clear glass strap-on, anal, his own penis separate, cum on his stomach", ST),
 },
 "lose_desc": "keeps him forever on the other side of the mirror as a resident of the mansion.",
 "onanie": {
   "master": ("facing", "kneeling between the facing mirrors, holding two small hand mirrors facing each other, staring into the endless reflection, penis untouched"),
   "e1": ("psyche", "kneeling before a tall gold-framed mirror, pinching both of his own nipples at the same time, the mirror showing only his back, penis untouched"),
   "e2": ("vanity", "sitting on the round stool, stroking the inside of his own ear with a soft makeup brush, mouth open, penis untouched"),
   "e3": ("psyche", "standing before the tall mirrors hugging himself with both arms, stroking his own chest, the mirror showing only his back, penis untouched"),
   "boss": ("bedroom", "lying face down with his face buried in a cushion, tracing his own ear with wet fingertips, penis untouched"),
 },
 "magic": {
   "1": ("m", "corridor", "polishing a silver hand mirror with a soft cloth, the mirror glowing violet, candle lights multiplied behind her, unbroken mirrors, sly smile"),
   "2": (None, "vanity", "a sealed invitation envelope with a silver wax seal without text leaning against a silver hand mirror on a vanity table, candle light"),
   "3": ("e1", "psyche", "standing beside a tall gold-framed mirror copying the exact pose of her own reflection, one finger on her lips, playful grin, unbroken mirror"),
   "4": ("m", "study", "holding out a silver hand mirror that glows with a hypnotic violet spiral, shelves of hand mirrors behind her, commanding smile"),
   "5": (None, "facing", "two huge ornate mirrors facing each other, infinite reflections of candle flames fading into greenish darkness, unbroken glass"),
 },
}
