# N93 鱗粉の館（Moth）画像データ。登場人物は全員20歳以上（魔物は見た目の年齢・成人）。女性のみ（蛾・蚕・蝶の魔物と人間のルーチェ）。
# 魔物は人の体に翅と触角だけ（虫の脚・腹は描かない）。鱗粉は金のきらめき（golden glitter particles）。挿入はツキヨのペニバン（黒い革と紫の帯）だけ。
ST = {"pen": "strapon"}
WINGNEG = "insect legs, extra arms, insect abdomen, bug body, compound eyes, monster face"
MARKS = "faint golden wing-shaped marks glowing on his skin"
DATA = {
 "code": "Moth",
 "world": "mansion of moth women deep in a night forest, every window glowing with lamplight, warm lamp light and soft shadows, drifting golden glitter particles, eternal night, detailed background",
 "bg": "grand old mansion in a dark night forest, every window glowing with warm lamplight, drifting golden glitter particles, moss-covered path leading to the heavy front door",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ヤママユ",
         "tags": "adult woman, mature female, mature face, 34 years old, adult proportions, beautiful detailed eyes, long legs, tall, moth woman, human body with moth wings, long dark brown hair, feathery moth antennae, gold eyes, large brown and gold moth wings with eye-spot patterns, black low-cut evening dress, golden glitter drifting from her wings, gentle alluring smile, huge breasts",
         "name": "the brown-haired moth lady in a black evening dress",
         "pose": "holding a glowing lamp at her chest, wings half spread, golden glitter drifting, gentle alluring smile, looking at viewer",
         "neg": WINGNEG},
   "e1": {"type": "woman", "jp": "マユラ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, silkmoth woman, human body with moth wings, fluffy long white hair, short feathery antennae, red eyes, short white fluffy silkmoth wings, white silk negligee, soft white silk threads from her fingertips, sleepy smile, large breasts",
          "name": "the white-haired silkmoth woman in a silk negligee",
          "pose": "winding soft white silk thread around her fingers, head tilted, sleepy half-lidded smile, looking at viewer",
          "neg": WINGNEG},
   "e2": {"type": "woman", "jp": "ルーチェ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, human woman, orange bob cut, brown eyes, black servant dress with white apron, black stockings, holding a brass oil lamp, quiet knowing smile, medium breasts",
          "name": "the orange-bobbed lamp keeper in a servant dress",
          "pose": "holding a brass oil lamp up beside her face, one finger on her lips, quiet knowing smile, looking at viewer",
          "neg": "wings, antennae"},
   "e3": {"type": "woman", "jp": "アゲハ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, butterfly woman, human body with butterfly wings, long blonde twintails, thin butterfly antennae, green eyes, black and yellow swallowtail butterfly wings, thin yellow sheer dress, honey on her lips, playful smile, large breasts",
          "name": "the blonde butterfly woman with black and yellow wings",
          "pose": "licking honey from her fingertip, wings spread wide, playful smile, looking at viewer",
          "neg": WINGNEG},
   "boss": {"strap": "black leather strap-on harness with purple straps", "type": "woman", "jp": "ツキヨ",
            "tags": "adult woman, mature female, mature face, 36 years old, adult proportions, beautiful detailed eyes, long legs, tall, moth noblewoman, human body with moth wings, very long black hair, black feathery antennae, purple eyes, huge black and purple moth wings, black lace gown, languid heavy-lidded expression, large breasts",
            "name": "the black-haired moth noblewoman in a black lace gown",
            "pose": "wings wrapped halfway around herself, one hand at her lips, languid heavy-lidded smile, looking at viewer",
            "neg": WINGNEG},
 },
 "places": {
   "komichi": "mossy forest path at night, countless glowing windows between the trees, cold night air",
   "genkan": "entrance hall of the mansion, rows of hanging lamps, polished black floor reflecting the lights, heavy wooden doors",
   "kairou": "long mansion corridor, rows of candlesticks, moth wing shadows on the window glass, thick carpet",
   "tsumesho": "lamp keeper's room, oil lamps on shelves, wick trimming scissors, narrow wooden bench",
   "kyakuma": "guest bedroom, canopy bed, a single oil lamp, dark window",
   "onshitsu": "glass greenhouse at night, hanging lamps under the glass roof, white night-blooming flowers, humid warm air",
   "mitsu": "honey storeroom, amber honey jars on cold stone shelves, dim lamp",
   "itokuri": "spinning room, wooden spinning wheels, bundles of white silk thread, mulberry leaves, lamp light",
   "ishou": "silk wardrobe room, rows of hanging white silk garments, lamp light",
   "yudono": "white marble bathhouse, bath water with floating golden glitter, sweet steam, lamps",
   "yakai": "ballroom, candle chandelier, black and gold drapes, velvet guest-of-honor chair, golden glitter in the air",
   "shishitsu": "mistress's private room, gold-embroidered chaise longue, large lamp, window full of night sky",
   "rodai": "moon-viewing balcony at night, full moon, black lace chaise longue, moth shadows on the railing",
   "sanshitsu": "attic silkworm room, sloped ceiling, hay bedding, shelves of white cocoons",
   "mayu": "cocoon room, rows of large white silk cocoons hanging from the ceiling, pale gold lamp light",
 },
 "atk": {
   "m1": ("yakai", "he kneels under the chandelier, the moth lady holds a lamp up lighting her deep cleavage and presses her huge breasts against his face, golden glitter falling from her wings, dazed, trembling"),
   "m2": ("kyakuma", "he sits on the edge of the canopy bed, the moth lady leans to his neck blowing a soft breath of golden glitter onto his collarbone, " + MARKS + ", no hands on him, trembling"),
   "m3": ("yakai", "he stands in the ballroom, the moth lady holds him and kisses him deeply, both of her hands rolling his nipples, golden glitter passing between their lips, tongues, saliva trail"),
   "e1": ("itokuri", "he lies among the spinning wheels wrapped in soft white silk thread from ankles to chest, the silkmoth woman winds more thread from her fingertips, the threads sliding over his nipples, sleepy smile"),
   "e2": ("genkan", "he stands in the dim hall, the lamp keeper turns her brass lamp low and whispers into his ear from the shadow, her lips at his ear rim, lamp shadows on the wall, trembling"),
   "e3": ("onshitsu", "he lies among white flowers, the butterfly woman licks honey off his nipple with her long tongue, honey dripping on his chest, her wings spread, playful smile"),
   "boss": ("rodai", "he stands at the railing, the moth noblewoman hugs him from behind wrapping him in her huge black and purple wings, whispering into his ear and nibbling his earlobe, moonlight, trembling"),
 },
 "atk_desc": {
   "m1": "the moth lady shows off her breasts under the lamplight.",
   "m2": "the moth lady blows a breath of golden scales onto his skin.",
   "m3": "the moth lady greets him with the ballroom kiss.",
   "e1": "the silkmoth woman wraps him in a silk cocoon.",
   "e2": "the lamp keeper whispers from the lamp's shadow.",
   "e3": "the butterfly woman sucks honey from his nipples.",
   "boss": "the moth noblewoman cages him in her wings.",
 },
 "lose": {
   # ヤママユ 技1（灯りの下で）
   "btl_m1":     ("yakai", "he kneels under the candle chandelier, the moth lady holds a lamp lighting her cleavage and presses her huge breasts on his face, blowing golden glitter over him, " + MARKS + ", cum on the floor"),
   "onani_m1":   ("kyakuma", "sitting alone on the floor staring at the single lamp flame, breathing deeply, hands resting on his knees, golden glitter in the air, hips twitching, penis untouched, the moth lady's wing shadow on the window far away watching"),
   "inochi_m1":  ("yudono", "he sits in the bath with golden glitter floating on the water, the moth lady in her wet black dress lifts her huge breasts close to his face, breathing glittering steam onto him, dazed, a pale window behind"),
   "onedari_m1": ("ishou", "he stands among hanging silk robes, the moth lady traces an eye-spot wing pattern on his chest with her fingertip, her deep cleavage right before his face, blowing golden glitter, trembling"),
   # ヤママユ 技2（★鱗粉の吐息）
   "btl_m2":     ("genkan", "he kneels on the black floor under the hanging lamps, the moth lady stands behind him blowing golden glitter onto the nape of his neck, twelve glowing golden wing marks all over his body, no hands on him, cum on the floor"),
   "onani_m2":   ("kyakuma", "sitting alone before the lamp with his mouth open, breathing in drifting golden glitter, faint golden marks on the backs of his hands, trembling, penis untouched, the moth lady's wing shadow on the window watching"),
   "inochi_m2":  ("shishitsu", "he lies on the gold-embroidered chaise longue, the moth lady bends over him blowing golden glitter over his lower belly and inner thighs, " + MARKS + ", a pale dawn-like window behind, trembling"),
   "onedari_m2": ("yakai", "he stands under the chandelier pointing at his own collarbone begging, the moth lady leans in blowing golden glitter onto the spot, a new golden mark glowing, other marks lined up on his skin"),
   # ヤママユ 技3（夜会の口づけ）
   "btl_m3":     ("yakai", "he sits in the velvet guest-of-honor chair, the moth lady leans over him kissing him deeply, rolling both of his nipples, golden glitter passing mouth to mouth, saliva trail, cum on his thigh"),
   "onani_m3":   ("kyakuma", "sitting alone on the canopy bed, tracing his own lips with a fingertip, the other wet fingertip rubbing his own nipple, lips parted, penis untouched, the moth lady's wing shadow on the window watching"),
   "inochi_m3":  ("rodai", "he lies on the black lace chaise longue, the moth lady kisses him deeply under the moon, rolling his nipple, golden glitter on his lips, a blank black invitation card without text on his chest"),
   "onedari_m3": ("shishitsu", "he sits on the chaise longue, the moth lady kisses him deeply while her fingertip draws a glittering embroidery pattern around his nipple, golden glitter, flushed"),
   # マユラ（★絹糸の繭／絹の手袋）
   "btl_e1":     ("itokuri", "he lies by the spinning wheel wrapped in a white silk cocoon with only his face and crotch showing, the silkmoth woman strokes his penis with her white silk-gloved hand, handjob, cum on the silk"),
   "onani_e1":   ("kyakuma", "lying alone on the canopy bed wrapped in many layers of thin white cloth like a cocoon, rubbing his own chest through the fabric, penis untouched, the silkmoth woman's white wing shadow on the window watching"),
   "inochi_e1":  ("ishou", "he lies wrapped in a white silk cocoon among the hanging silk robes, only his face out, the silkmoth woman strokes his chest through the threads, pale morning-like light, sleepy smile"),
   "onedari_e1": ("mayu", "he lies inside a white silk cocoon among the hanging cocoons, only his face showing, the silkmoth woman slides her silk-gloved hand inside the opening stroking his penis, handjob, pale gold light"),
   # ルーチェ（★ランプの影／給仕の脚）
   "btl_e2":     ("genkan", "he lies on the black floor, the lamp keeper sits astride his legs squeezing his penis between her stockinged thighs under her skirt, thighjob, leaning down to whisper in his ear, brass lamp turned low, cum on her stockings"),
   "onani_e2":   ("kyakuma", "sitting alone in the room lit only by the lamp, tracing his own ear with a fingertip, lips murmuring words, trembling, penis untouched, the lamp keeper's lamp glowing outside the window far away"),
   "inochi_e2":  ("tsumesho", "he lies on the narrow bench, the lamp keeper sits at his head whispering and licking his ear, her brass lamp casting long shadows, dazed, trembling"),
   "onedari_e2": ("kairou", "he stands in the corridor, the lamp keeper holds a brass lamp casting a wing-shaped shadow on the wall and whispers behind his ear, lips touching his ear, trembling"),
   # アゲハ（★蜜吸いの舌／花粉の胸）
   "btl_e3":     ("onshitsu", "he lies in the flower bed under a hanging lamp, the butterfly woman sucks his nipple with her long tongue, honey dripping over his chest, her wings spread over him, cum on the flowers"),
   "onani_e3":   ("kyakuma", "sitting alone on the canopy bed with honey smeared on his nipples, pinching and pulling his own nipple, a honey jar beside him, penis untouched, the butterfly woman's black and yellow wing shadow on the window watching"),
   "inochi_e3":  ("mitsu", "he sits against the stone shelves of amber honey jars, the butterfly woman kneels licking honey from his nipple, honey on his chest, dim lamp, trembling"),
   "onedari_e3": ("rodai", "his face is buried in the butterfly woman's cleavage on the moonlit balcony, her fingertip painting a honey swallowtail pattern around his nipple, golden glitter, trembling"),
   # ツキヨ（★翅の檻／夜明けまで・ペニバン）
   "btl_boss":   ("rodai", "from side, he lies on his side on the black lace chaise, the moth noblewoman lies behind him wrapping both in her huge wings, pegging his anus with a black leather strap-on with purple straps, anal, whispering into his ear, his own penis separate", ST),
   "onani_boss": ("kyakuma", "sitting alone on the bed with a blanket draped over his head and back like wings, one hand tracing his own ear, the other arm hugging his own chest, penis untouched, the moth noblewoman's black and purple wing shadow on the window"),
   "inochi_boss":("shishitsu", "from side, he leans on the window sill, the moth noblewoman stands behind him wrapping her huge wings around them both, pegging his anus with a black leather strap-on with purple straps, anal, nibbling his ear, his own penis separate", ST),
   "onedari_boss":("mayu", "from side, he is on all fours among the hanging cocoons, a golden wing pattern between his shoulder blades, the moth noblewoman kneels behind him pegging his anus with a black leather strap-on with purple straps, anal, wings half closed around them, his own penis separate", ST),
 },
 "lose_desc": "seals him in a white silk cocoon to dream of a night without dawn.",
 "onanie": {
   "master": ("kyakuma", "sitting alone on the floor gazing at the lamp flame, breathing deeply with his mouth open, hands on his knees, golden glitter in the air, penis untouched"),
   "e1": ("itokuri", "lying alone wrapped in layers of thin white cloth like a cocoon, rubbing his own chest through the fabric, penis untouched"),
   "e2": ("tsumesho", "sitting alone on the narrow bench beside a dim lamp, tracing his own ear with a fingertip, lips murmuring, penis untouched"),
   "e3": ("onshitsu", "sitting alone among white flowers with honey on his nipples, pinching and pulling his own nipple, penis untouched"),
   "boss": ("kyakuma", "sitting alone with a blanket over his back and head like wings, tracing his own ear with one hand, the other arm hugging his chest, penis untouched"),
 },
 "magic": {
   "1": ("m", "genkan", "the moth lady holds up a glowing lamp and beckons with one finger, golden glitter swirling from her wings, alluring smile"),
   "2": (None, "kyakuma", "a sealed black envelope with a gold wax seal without text on a silver tray under a lamp, golden glitter"),
   "3": (None, "kairou", "a glittering cloud of golden scales hanging in the air of a dim corridor between candlesticks"),
   "4": ("e1", "itokuri", "the silkmoth woman spins soft white silk thread from her fingertips, threads floating around her, sleepy smile"),
   "5": (None, "kairou", "a single brass lamp burning on a windowsill against an endless dark night, moth wing shadows on the glass, golden glitter"),
 },
}
