# N73 百器使いの道場（Musashi）画像データ。登場人物は全員20歳以上。全員女性。稽古帳・誓紙・札は文字なし。
# 本編キャラ（ムサシ）は本編の立ち絵を見ずに、本文の手がかり（稽古着・袴・刀・羽織・足袋・大きな胸・体の線に自信）と役から決めた見た目。
# 髪色は門下生と被らないよう金髪にした（本編の立ち絵と違えば tags を直す）。武器は峰・柄・鎖で触れるだけ（痛み・流血なし）。
ST = {"pen": "strapon"}      # ユウギリ（免許皆伝のペニバン）
BOOK = "a blank training ledger without text"

DATA = {
 "code": "Musashi",
 "world": "traditional japanese martial arts dojo compound, polished wooden floors, weapon racks with naginata spears and wooden swords, paper shoji, detailed background",
 "bg": "interior of an empty traditional japanese dojo, polished wooden floor, weapon racks with wooden swords and naginata on the walls, kamidana shelf, open shoji facing a garden, afternoon light",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ムサシ", "canon": True, "canon_img": "F21.png",
         "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, tall, blonde hair, long hair, ponytail, amber eyes, swordswoman, white keikogi worn loosely with a deep open collar, cleavage, black hakama, katana at her waist, white tabi, confident teasing smile, large breasts",
         "name": "the blonde swordswoman in a black hakama",
         "pose": "one hand resting on the katana hilt at her waist, hip cocked to show her body line, confident teasing smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "門下生 カエデ",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, reddish brown hair, ponytail, brown eyes, white training gi, crimson hakama, naginata, serious polite expression, medium breasts",
          "name": "the reddish-brown-ponytailed disciple in a crimson hakama",
          "pose": "holding a naginata upright beside her, standing straight after a polite bow, serious gentle expression, looking at viewer"},
   "e2": {"type": "woman", "jp": "門下生 アヤメ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, bob cut, gold eyes, black kunoichi outfit, fishnet sleeves, kusarigama with a long chain, sly smile, large breasts",
          "name": "the purple-bobbed kunoichi with a chain",
          "pose": "swinging the chain of her kusarigama loosely in one hand, leaning forward, sly teasing grin, looking at viewer"},
   "e3": {"type": "woman", "jp": "門下生 シノ",
          "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, black hair, short hair, green eyes, short-sleeved training gi, black hakama, white leg wraps, bo staff, stoic expression, medium breasts",
          "name": "the short-black-haired disciple with a bo staff",
          "pose": "holding a long bo staff across her shoulders, calm stoic face, slight head tilt, looking at viewer"},
   "boss": {"type": "woman", "jp": "師範代 ユウギリ",
            "tags": "adult woman, mature female, mature face, 30 years old, adult proportions, beautiful detailed eyes, long legs, tall, white hair, very long hair, high ponytail, red eyes, black kinagashi kimono, two katana at her waist, calm severe expression, large breasts",
            "name": "the white-haired instructor in a black kimono",
            "pose": "standing straight with both hands resting on the two katana at her waist, calm severe gaze, looking at viewer"},
 },
 "places": {
   "dojo":      "wide dojo hall with a polished wooden floor, weapon racks on the wall, kamidana shelf, bright daylight",
   "evening":   "dojo at a summer sunset, orange light slanting through open shoji, polished wooden floor, sweat towel on the floor",
   "armory":    "dim weapon storehouse at the back of the dojo, wall racks full of spears, naginata, katana on stands, wooden chests",
   "winter":    "cold dojo on a snowy winter morning, white breath, frost on the wooden floor, snow falling outside the open shoji",
   "night":     "dojo at night lit only by stone lanterns and an andon lamp, long shadows on the wooden floor, weapon rack",
   "changing":  "small wooden changing room of the dojo, folded training clothes on shelves, sweat towels, wooden bench",
   "bamboo":    "bamboo grove behind the dojo under moonlight, tall bamboo trunks, fallen leaves on the ground",
   "kura":      "upper floor of an old wooden storehouse, iron chains hanging from the beams, dusty floorboards, small window",
   "judo":      "tatami grappling room of the dojo on a rainy afternoon, rain on the windows, green tatami mats",
   "dorm":      "large training camp hall at night with futons laid across the tatami, zabuton cushions, dim lamp",
   "futonroom": "narrow futon storage room at night, stacked futons and pillows, paper lamp",
   "courtyard": "sand training yard in the dojo courtyard at sunset, raked sand, wooden practice posts",
   "engawa":    "wooden engawa veranda of the dojo after morning rain, flat stepping stone, wet garden moss",
   "garden":    "moonlit inner garden of the dojo, lit stone lanterns, white gravel, pine trees",
   "inner":     "candlelit inner tatami room at the back of the dojo, candle stands, a sword stand with two katana, folding screen",
   "hanare":    "detached wooden cottage on a snowy night, sunken irori hearth with glowing charcoal, wooden floor, snow outside",
   "roof":      "tiled roof of the dojo under a bright full moon, grey roof tiles, night sky",
 },
 "atk": {
   "m1": ("dojo", "from side, he lies on his back on the wooden floor, the swordswoman sits at his feet in her black hakama, gripping his penis between both bare soles, quick sweeping strokes, amused smile, his toes curled"),
   "m2": ("evening", "he kneels on the wooden floor, the swordswoman locks his head under her arm and presses his face into her sweaty bare armpit against her breast, he breathes in deeply, trembling, no hands on his penis"),
   "m3": ("armory", "he stands against a weapon rack, the swordswoman clamps his penis inside her bare armpit and strokes by squeezing her arm, her other hand pinching his nipple, katana on the stand beside"),
   "e1": ("dojo", "he kneels in seiza on the wooden floor with his chest out, the disciple holds her naginata reversed and presses the rounded butt end of the shaft onto his nipple, serious polite face, he trembles"),
   "e2": ("bamboo", "he sits against a bamboo trunk with both wrists bound by the kunoichi's chain, the kunoichi straddles his thighs and kisses him deeply, tongues, saliva trail, the chain pulled taut"),
   "e3": ("judo", "he lies face down on the tatami, the disciple lies on his back pinning him in a hold, her lips at his ear licking and whispering, his cheek pressed to the mat, trembling"),
   "boss": ("inner", "from side, he lies on his back on the tatami with legs lifted, the instructor kneels between his legs pegging his anus with her strap-on, anal, rolling his nipple with her fingertips, his own penis separate", ST),
 },
 "atk_desc": {
   "m1": "the swordswoman sweeps his legs and pins him with her bare feet.",
   "m2": "the swordswoman locks his head in her armpit.",
   "m3": "the swordswoman switches weapons and uses her own body.",
   "e1": "the disciple strikes his chest with the butt of her naginata.",
   "e2": "the kunoichi binds him with her chain and kisses him.",
   "e3": "the disciple pins him down and whispers into his ear.",
   "boss": "the instructor grants him the secret final lesson.",
 },
 "lose": {
   # ムサシ 技1（足払いからの・足コキ）
   "btl_m1":     ("dojo", "from side, he lies on his back on the wooden floor, the swordswoman sits at his feet squeezing his penis between both bare soles in quick strokes, cum dripping between her toes, her teasing smile"),
   "onani_m1":   ("dojo", "kneeling alone in the middle of the wooden floor, one arm wrapped around his own head with his nose buried in his inner elbow sniffing deeply, the other hand pinching his own nipple, penis untouched, the swordswoman watches from far away in a low sweeping stance"),
   "inochi_m1":  ("evening", "he sits on his bottom on the wooden floor with his knees buckling, the swordswoman stands a step away drawing one bare foot back in a sweeping stance without touching him, cum dribbling, " + BOOK + " on the floor"),
   "onedari_m1": ("engawa", "he kneels before the flat stepping stone, the swordswoman sits on the edge of the veranda sweeping one bare foot through the air before his face, no touch, cum on the stone, " + BOOK + " beside her"),
   # ムサシ 技2（脇固め）
   "btl_m2":     ("evening", "he kneels with his face buried in the swordswoman's bare armpit, the swordswoman locks his head under her arm against her breast, no hands on his penis, sweat, cum on the wooden floor, sunset light"),
   "onani_m2":   ("winter", "kneeling alone on the frosty wooden floor with white breath, one arm wrapped around his own head sniffing his inner elbow, the other hand pinching his own nipple, penis untouched, the swordswoman watches from far away in a haori"),
   "inochi_m2":  ("changing", "he sits against the wooden wall of the changing room, the swordswoman drapes her sweat-damp white hand towel over his nose, no hands on him, he breathes in deeply, cum dribbling, trembling"),
   "onedari_m2": ("winter", "he kneels on the cold floor, the swordswoman stands over him in a haori with one arm raised, faint steam from her open sleeve, he breathes in the scent with his mouth open, trembling, cum on the frosty floor"),
   # ムサシ 技3（武器を持ち替えて・脇コキ＋乳首）
   "btl_m3":     ("armory", "he stands pressed against a weapon rack, the swordswoman clamps his penis in her bare armpit squeezing it, her other hand pinching his nipple, cum spilling from her armpit, spears and katana on the racks"),
   "onani_m3":   ("night", "kneeling alone on the lantern-lit floor, one arm around his own head sniffing his inner elbow, the other hand pinching his own nipple, hips floating, penis untouched, the swordswoman stands far away at the weapon rack holding a spear"),
   "inochi_m3":  ("armory", "he sits slumped on the floor before the weapon racks, the swordswoman flicks the guard of a sheathed katana on its stand with one finger, no touch, his hips jerking, cum dribbling"),
   "onedari_m3": ("dojo", "he kneels in seiza before weapons laid out in rows on the floor, the swordswoman sits beside him clamping his penis in her bare armpit, pinching his nipple, a closed folding fan tucked in her hakama, cum on the floor"),
   # カエデ（柄の先で・乳首）
   "btl_e1":     ("dojo", "he kneels in seiza on the misty morning floor with his chest out, the disciple presses the rounded butt end of her reversed naginata onto his nipple and bows politely, cum on the floorboards, trembling"),
   "onani_e1":   ("courtyard", "kneeling alone on the raked sand, holding a wooden sword upside down and pressing its rounded pommel against his own nipple, penis untouched, the disciple watches from far away holding her naginata"),
   "inochi_e1":  ("dojo", "he lies on his back in the morning sun on the wooden floor, the disciple taps the rounded butt of her naginata on the middle of his chest and bows deeply, cum on his belly, a blank pledge paper without text"),
   "onedari_e1": ("night", "he lies on his back on the lamp-lit floor, the disciple stands over him pressing the rounded butt end of her naginata onto his nipple, serious polite face, cum on his belly, " + BOOK),
   # アヤメ（鎖で絡めて・キス）
   "btl_e2":     ("bamboo", "he sits against a bamboo trunk with his wrists bound by the chain, the kunoichi straddles his thighs kissing him deeply, tongues, saliva trail, no hands on his penis, cum on the chain links, moonlight"),
   "onani_e2":   ("kura", "kneeling alone under the hanging chains with his own wrists loosely tied together by a hakama cord, sucking two of his own fingers and twisting his tongue around them, penis untouched, the kunoichi watches from the far beam"),
   "inochi_e2":  ("bamboo", "he sits against a bamboo trunk with the kusarigama chain wound around his chest, the kunoichi kneels over him pecking his lips, rattling the chain, cum on the chain links, trembling"),
   "onedari_e2": ("roof", "he lies on his back on the moonlit roof tiles, the kunoichi winds the chain slowly around his wrists again and kisses him deeply, tongues, saliva trail, cum on his belly"),
   # シノ（組討ち・耳）
   "btl_e3":     ("judo", "he lies face down on the tatami, the disciple lies on top of him in a pinning hold, licking inside his ear and whispering, her knee set aside, cum on the tatami, rain on the window"),
   "onani_e3":   ("dorm", "lying alone face down on a futon with his face pressed into a zabuton cushion, tracing the rim of his own ear with his fingertips, hips twitching, penis untouched, the disciple watches from the far futon"),
   "inochi_e3":  ("judo", "he lies on his back pinned under the disciple in a side hold on the tatami, the disciple licks his ear slowly, the bo staff lying beside them, cum on his belly"),
   "onedari_e3": ("futonroom", "he lies on his back on the stacked futons held in a side control pin, the disciple lies beside him breathing softly into his ear, no hands on his penis, cum on the futon"),
   # ユウギリ（免許皆伝・乳首＋ペニバン）
   "btl_boss":   ("inner", "from side, he lies on his back on the tatami with legs lifted, the instructor kneels between his legs pegging his anus with her strap-on, anal, rolling his nipple with her fingertips, his own penis separate, cum on his chest", ST),
   "onani_boss": ("garden", "kneeling alone on the white gravel, two of his own oil-slick fingers pushed into his own anus from behind, the other hand pinching his own nipple, penis untouched, the instructor watches from beside a stone lantern with her two swords"),
   "inochi_boss":("inner", "he lies face down on the tatami with his hips raised, the instructor kneels behind him holding her strap-on still deep inside his anus, anal, only rolling his nipple with her fingertips, his own penis separate, cum dripping", ST),
   "onedari_boss":("hanare", "from side, he lies on his back on the wooden floor beside the sunken hearth with legs lifted, the instructor pegs his anus with her strap-on, anal, pinching his nipple, his own penis separate, a small pot of camellia oil", ST),
 },
 "lose_desc": "keeps him in the dojo as a living wooden training dummy.",
 "onanie": {
   "master": ("dojo", "kneeling on the wooden floor, one arm wrapped around his own head with his nose buried in his inner elbow, breathing in deeply, the other hand pinching his own nipple, penis untouched"),
   "e1": ("courtyard", "kneeling on the sand, holding a wooden sword upside down and pressing its rounded pommel against his own nipple, penis untouched"),
   "e2": ("kura", "kneeling with his own wrists loosely tied by a cord, sucking two of his own fingers deeply with his tongue, penis untouched"),
   "e3": ("dorm", "lying face down on a futon with his face pressed into a pillow, tracing his own ear with his fingertips, penis untouched"),
   "boss": ("garden", "kneeling on the gravel, two of his own oiled fingers in his own anus from behind, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "armory", "standing before the weapon racks, putting her katana back on its stand while reaching for a spear with her other hand, switching weapons, playful smile"),
   "2": (None, "armory", "rows of spears, naginata, kusarigama and wooden swords on wall racks, katana on stands, wooden chests, lantern light"),
   "3": ("e1", "dojo", "turning her naginata around in a smooth counter stance, the rounded butt end of the shaft thrust forward, calm serious eyes"),
   "4": (None, "winter", "wooden practice swords leaning on a rack in the snowy morning dojo, frost on the floor, a wooden bucket of cold water"),
   "5": ("m", "dojo", "standing in the center of the dojo surrounded by a hundred weapons displayed on racks and the floor, arms spread wide, proud smile"),
 },
}
