# N74 廃坑の死霊術師（Necro）画像データ。登場人物は全員20歳以上。全員女性。ノート・祈祷書・帳簿・手紙は文字なし。
# 本編キャラ（ネクロ・ゾンビガール・下級堕天使・死を振りまくもの）は本編の立ち絵を見ずに、本文の手がかりと役から決めた見た目。
#  ネクロ＝紫髪・ローブの下に体に張り付く黒い服・スレンダーで巨乳／ゾンビガール＝顔色の白い眠たげな娘（腐敗・傷は描かない）／
#  下級堕天使＝黒い翼／死を振りまくもの＝人間大の闇の妖精・羽・紫の甘い霧。
DATA = {
 "code": "Necro",
 "world": "abandoned mine hideout of a bandit gang, rough rock tunnels, wooden support beams, rusty trolley rails, hanging lanterns, dim warm light, detailed background",
 "bg": "interior of an abandoned mine tunnel, wooden support beams, rusty minecart on rails, hanging oil lanterns, faint purple glow deeper in the darkness",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ネクロ", "canon": True, "canon_img": "F23.png",
         "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, tall, slender, purple hair, long wavy hair, red eyes, half-closed eyes, necromancer, black hooded robe worn open, skin-tight black bodysuit underneath, lazy seductive smile, large breasts",
         "name": "the purple-haired necromancer in a black robe",
         "pose": "leaning lazily with her weight on one hip, one hand under her chest, robe slipping off one shoulder, drowsy seductive smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "ゾンビガール", "canon": True, "canon_img": "EU53.png",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, undead woman, very pale skin, light green hair, messy medium hair, dull yellow eyes, sleepy half-closed eyes, tattered grey rag dress, loose bandage wraps on her arms, blank dreamy expression, large breasts",
          "name": "the pale green-haired undead woman in a tattered dress",
          "pose": "standing slightly slouched with arms hanging loosely, head tilted, sleepy dreamy gaze, looking at viewer",
          "neg": "rotting flesh, wounds, stitches, gore, exposed bone, bite marks, grey rotten skin"},
   "e2": {"type": "woman", "jp": "下級堕天使", "canon": True, "canon_img": "EU54.png",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, fallen angel, silver hair, long hair, purple eyes, large black feathered wings, dark broken halo, black revealing dress, smug smile, medium breasts",
          "name": "the silver-haired fallen angel with black wings",
          "pose": "black wings half spread, one hand on her hip, the other fingertip on her lips, smug grin, looking at viewer"},
   "e3": {"type": "woman", "jp": "盗賊団の頭目 ザザ",
          "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, tall, dark skin, red hair, messy hair, gold eyes, bandit leader, leather breastplate, loincloth, dagger at her hip, wide grin, large breasts",
          "name": "the red-haired dark-skinned bandit leader",
          "pose": "one foot up on a treasure chest, dagger twirling in one hand, bold wide grin, looking at viewer"},
   "boss": {"type": "woman", "jp": "死を振りまくもの", "canon": True, "canon_img": "EU56.png",
            "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, human-sized dark fairy, pointy ears, black hair, long twintails, pink eyes, translucent black butterfly-like fairy wings, black and purple revealing fairy outfit, thin purple mist swirling around her, mischievous grin, large breasts",
            "name": "the black-twintailed dark fairy with butterfly wings",
            "pose": "floating slightly above the ground, twirling in the air, blowing a puff of purple mist from her palm, mischievous grin, looking at viewer"},
 },
 "places": {
   "trolley":  "trolley yard near the mine entrance, rusty minecarts on old rails, wooden beams, daylight from the entrance",
   "tunnel":   "narrow mine tunnel lit by a hanging lantern, rough rock walls, wooden support beams",
   "lake":     "underground lake deep in the mine, pale green glowing moss on the rocks reflecting on still water",
   "barracks": "old miners' barracks carved into rock, straw beds on the floor, broken lamps, wooden bunks",
   "shaft":    "bottom of a vertical mine shaft, a single beam of light falling from a crack far above, rubble and rock ledges",
   "vault":    "bandit treasure vault in the mine, piles of gold coins and jewels, open treasure chests, torchlight",
   "abyss":    "deepest cavern of the mine, sweet purple mist pooling knee-deep over the ground, faint glowing crystals",
   "hall":     "old excavation hall with a high rock ceiling, a single lantern hanging from a beam, scattered tools",
   "sidetunnel": "cramped side tunnel just wide enough for one person, damp rock walls close on both sides, small candle",
   "guardpost": "sooty old miners' guard post, long wooden bench, thin plank walls, wooden board with carved tally scratches",
   "spring":   "tunnel junction with a small spring, water dripping from the rock ceiling into a stone basin, wet rocks",
   "messhall": "abandoned underground mess hall, long wooden tables and benches, empty bowls, dim lamp",
   "tavern":   "bandit tavern inside the mine, barrels of ale, rough wooden tables, torches on rock walls",
   "mosscave": "cave covered in faintly glowing moss, soft light, smooth rocks, quiet",
   "room":     "the necromancer's cozy chamber carved in rock, messy bed with purple sheets and many pillows, candles, stacked grimoires without text",
   "hut":      "small wooden lookout hut at the mine entrance, wooden crates, lantern, window to the night",
   "tent":     "bandit leader's tent deep in the tunnel, bed covered with furs, loot sacks, lantern light",
   "crystal":  "small hollow surrounded by glowing purple crystals, thin purple mist crawling on the floor",
   "chapel":   "tiny old miners' chapel in the rock, small stone altar with a faintly glowing round stone, candles",
 },
 "atk": {
   "m1": ("trolley", "he kneels on the rusty rails, the necromancer leans over him with her robe slipped off her shoulders, squeezing his penis between her breasts through the open neckline of her black bodysuit, lazy smile"),
   "m2": ("tunnel", "he kneels on the tunnel floor, the necromancer holds his face and kisses him deeply, tongues, saliva trail, purple kiss marks glowing on his neck, she whispers between kisses"),
   "m3": ("lake", "he sits by the underground lake with his face buried between the necromancer's breasts, the necromancer hugs his head and whispers into his ear, her lips at his ear, glowing moss light"),
   "e1": ("barracks", "he lies on his back on a straw bed, the pale undead woman leans over his chest nibbling his nipple gently with her lips and teeth, her cold hands on his shoulders, sleepy eyes"),
   "e2": ("shaft", "he lies on his back in the beam of light, the fallen angel kneels over him holding his cheeks and blowing a long sweet breath into his open mouth, black wings spread, no hands on his body below"),
   "e3": ("vault", "he is on all fours with his hands on an open treasure chest, the bandit leader kneels behind him with two oiled fingers in his anus, fingering, gold coins spilled around, wide grin"),
   "boss": ("abyss", "he lies in the knee-deep purple mist, the dark fairy kneels beside him blowing sweet purple mist onto his face while pinching his nipples, butterfly wings fluttering"),
 },
 "atk_desc": {
   "m1": "the necromancer traps him between her soft breasts.",
   "m2": "the necromancer gives him the kiss of the dead with a whispered spell.",
   "m3": "the necromancer whispers 'you can never win' into his melting brain.",
   "e1": "the undead woman nibbles his nipple instead of biting.",
   "e2": "the fallen angel feeds him her addictive breath.",
   "e3": "the bandit leader searches his body from the inside.",
   "boss": "the dark fairy drowns him in sweet purple mist.",
 },
 "lose": {
   # ネクロ 技1（お姉さんの・パイズリ）
   "btl_m1":     ("trolley", "he kneels on the rusty rails, the necromancer holds his penis still between her breasts through the open neckline of her bodysuit, hugging it tight without moving, cum oozing from her cleavage, a yellowed blank paper without text in a minecart"),
   "onani_m1":   ("hall", "standing alone under the hanging lantern, sucking two of his own fingers deeply, the other hand stroking the purple kiss marks on his neck, penis untouched, the necromancer watches from the far side of the hall"),
   "inochi_m1":  ("room", "he lies with his face buried between the necromancer's breasts, the necromancer hugs his head with both arms on the messy bed, his hips pressed against her belly, cum on her bodysuit, lazy smile"),
   "onedari_m1": ("hut", "he kneels before the necromancer seated on a wooden crate, the necromancer squeezes his penis between her breasts through her open bodysuit, cum spilling from her cleavage, a blank leather notebook without text beside her"),
   # ネクロ 技2（死者の口づけ・キス＋囁き）
   "btl_m2":     ("tunnel", "he kneels on the tunnel floor, the necromancer kisses him deeply while tracing the purple kiss marks on his neck and collarbone with a fingertip, no hands on his penis, cum dribbling"),
   "onani_m2":   ("sidetunnel", "standing alone in the cramped tunnel, sucking two of his own fingers and twisting his tongue around them, the other hand stroking the purple kiss marks on his neck, penis untouched, the necromancer watches from the tunnel mouth"),
   "inochi_m2":  ("tunnel", "he leans against the rock wall under a lantern, the necromancer strokes a purple kiss mark on his neck and kisses him, an unopened sealed envelope without text dropped at his feet, cum dribbling"),
   "onedari_m2": ("lake", "he lies on his back by the glowing lake, the necromancer lies on top of him kissing him deeply, tongues, saliva trail, fingertip on the kiss mark on his neck, cum between their bellies"),
   # ネクロ 技3（とろけた脳に・耳＋ぱふぱふ）
   "btl_m3":     ("lake", "he sits by the underground lake with his face wrapped between the necromancer's breasts, the necromancer holds his head and whispers into his ear, her lips touching his ear, no hands on his penis, cum on the rocks"),
   "onani_m3":   ("guardpost", "sitting alone on the sooty bench, one wet finger in his own ear, the other hand stroking the kiss marks on his neck, whispering to himself, penis untouched, the necromancer watches from the doorway"),
   "inochi_m3":  ("room", "he lies on the messy bed with his face held between the necromancer's breasts, the necromancer whispers into his ear with her lips at his ear, no hands on him, cum on the purple sheets"),
   "onedari_m3": ("chapel", "he kneels before the small altar, the necromancer hugs his face into her breasts and whispers into his ear, a faintly glowing round stone on the altar, cum on the stone floor"),
   # ゾンビガール（かじる代わりに・乳首の甘噛み）
   "btl_e1":     ("barracks", "he lies on his back on the straw bed, the pale undead woman leans over him nibbling his nipple with her lips and teeth, her hands on the straw beside him, no hands on his penis, cum on his belly"),
   "onani_e1":   ("spring", "sitting alone on a wet rock by the spring, pinching both of his own nipples lightly with his fingernails in a slow rhythm, penis untouched, the pale undead woman watches from the tunnel"),
   "inochi_e1":  ("trolley", "he lies on his back beside the old rails, the pale undead woman kneels over him sucking his nipple, his nipple glossy with her saliva, cum on his belly, sleepy eyes"),
   "onedari_e1": ("barracks", "he lies on his back on the straw, the pale undead woman nibbles and sucks his swollen nipple, rows of tally scratches on the rock wall, cum on his belly"),
   # 下級堕天使（中毒の吐息・息）
   "btl_e2":     ("shaft", "he lies on his back in the beam of light, the fallen angel holds his cheeks with her lips sealed over his, blowing her breath into his mouth, black wings spread, no hands on his penis, cum on the rubble"),
   "onani_e2":   ("messhall", "sitting alone at the end of a long table, both hands cupped over his own mouth breathing in and out of his palms, dazed, penis untouched, the fallen angel watches from the far end of the hall"),
   "inochi_e2":  ("shaft", "he kneels on the rubble, the fallen angel holds his chin and blows a long breath into his mouth while stroking his penis with her other hand, cum on her fingers, black feathers falling"),
   "onedari_e2": ("hut", "he sits on the plank floor, the fallen angel crouches before him blowing a long sweet breath into his open mouth, no touch, cum on the boards, a black prayer book without text, a small glass vial on a string"),
   # ザザ（身体検め・アナル開発）
   "btl_e3":     ("vault", "he is on all fours with his hands on a treasure chest, the bandit leader kneels behind him with two oiled fingers deep in his anus, fingering, tapping inside, cum on the gold coins, wide grin"),
   "onani_e3":   ("tavern", "on all fours alone on the tavern floor with his hips raised high, reaching behind with two of his own wet fingers in his own anus, penis untouched, the bandit leader watches from a barrel far away"),
   "inochi_e3":  ("vault", "he bends over an open treasure chest, the bandit leader stands behind him with two oiled fingers in his anus pressing upward, a small oil vial in her other hand, cum spattered on the chest lid"),
   "onedari_e3": ("tent", "he lies on his back on the fur-covered bed with his knees spread, the bandit leader kneels between them with two fingers in his anus pressing up, cum on her dark belly, a blank ledger without text on the furs"),
   # 死を振りまくもの（甘い霧・脳イキ＋乳首）
   "btl_boss":   ("abyss", "he lies on his back in the purple mist, the dark fairy kneels beside him with a thin scarf draped over his face, pinching and rolling his nipples, mist swirling, no hands on his penis, cum in the mist"),
   "onani_boss": ("mosscave", "sitting alone against a mossy rock, pressing a thin perfumed scarf over his own nose and breathing in deeply, the other hand pinching his own nipple, penis untouched, the dark fairy watches from far above"),
   "inochi_boss":("abyss", "he lies asleep with his head on the dark fairy's lap, purple mist wrapped around him like a blanket, the dark fairy pinches his nipple, cum dribbling, butterfly wings folded"),
   "onedari_boss":("crystal", "he lies asleep on the dark fairy's chest, the dark fairy rolls his nipples with her fingertips, purple mist crawling over them, cum on his belly, glowing crystals"),
 },
 "lose_desc": "keeps him in the abandoned mine as a lazy, melted pet forever.",
 "onanie": {
   "master": ("hall", "standing under the lantern, sucking two of his own fingers deeply, the other hand stroking the purple kiss marks on his neck, whispering to himself, penis untouched"),
   "e1": ("spring", "sitting on a wet rock, pinching both of his own nipples with his fingernails in a slow rhythm, penis untouched"),
   "e2": ("messhall", "sitting at a long table, both hands cupped over his own mouth breathing his own breath in and out, dazed, penis untouched"),
   "e3": ("tavern", "on all fours with his hips raised, reaching behind with two of his own wet fingers in his own anus, penis untouched"),
   "boss": ("mosscave", "sitting against a mossy rock, pressing a perfumed scarf over his own nose, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "tunnel", "beckoning with one finger, purple ghostly lights drifting from her palm toward the viewer, robe slipping off her shoulder, drowsy inviting smile"),
   "2": ("e3", "hut", "keeping watch at the window of the lookout hut, one foot on a crate, spyglass in hand, grinning over her shoulder"),
   "3": ("m", "hall", "blowing a kiss, a small purple heart-shaped glow flying from her lips, one eye closed, lazy smile"),
   "4": (None, "tunnel", "a mine tunnel swallowed by thick darkness, a single lantern flickering out, wooden beams fading into black"),
   "5": (None, "room", "a messy comfortable bed with purple sheets and many soft pillows in a rock chamber, candles burning low, a blanket half fallen to the floor"),
 },
}
