# N70 路地裏の猫使い（Neneko）画像データ。登場人物は全員20歳以上。すべて女性（人外の女性を含む）。
# ネネコ・煙猫・妖狐・猫又は本編キャラ（立ち絵を見ずに本文から作った見た目。canon_img と見比べて直す）。
# 妖狐は本文では四人に分身するが、絵は「責め手1人＋主人公」の決まりどおり一人だけ描く。
# 主人公は鈴のついた赤い首輪（bell collar）をしている（鈴が十二個たまってネネコの猫になる）。
BELL = "a red collar with small gold bells on his neck"
DATA = {
 "code": "Neneko",
 "world": "old downtown back alleys of a fantasy town at dusk, stone steps, paper lanterns, stray cats on the roofs, warm orange light, detailed background",
 "bg": "narrow back alley of an old fantasy downtown at dusk, stone steps, wooden eaves, hanging paper lanterns, potted plants, stray cats sleeping on the roofs, no people",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "ネネコ", "canon": True, "canon_img": "F18.png",
            "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, tall, black hair, medium hair, cat ears, black cat tail, yellow eyes, slit pupils, fang, bell choker, loose cropped hoodie, short pleated skirt, thick thighs, plump body, wide hips, large breasts",
            "name": "the black-haired cat-eared tamer with thick thighs",
            "pose": "hands on her hips, leaning forward with a pouting frown and one fang showing, tail raised, looking at viewer"},
   "e1":   {"type": "woman", "jp": "煙猫", "canon": True, "canon_img": "EU42.png",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, lavender hair, long wavy hair, cat ears, pink eyes, half-closed eyes, wisps of white smoke rising from her hair and shoulders, her hair tips and tail dissolving into white smoke, loose off-shoulder smoky gray dress, large breasts",
            "name": "the lavender-haired smoke cat woman wreathed in white smoke",
            "pose": "floating slightly, blowing a thin stream of white smoke from her lips, lazy smile, looking at viewer"},
   "e2":   {"type": "woman", "jp": "妖狐", "canon": True, "canon_img": "EU45.png",
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, tall, golden blonde hair, very long hair, fox ears, large fluffy golden fox tail, amber eyes, seductive smile, white off-shoulder kimono with red obi and red trim, pale skin, large breasts",
            "name": "the golden-haired fox woman in a white kimono",
            "pose": "hiding her smile behind the sleeve of her kimono, fox tail swaying, sly half-closed eyes, looking at viewer"},
   "e3":   {"type": "woman", "jp": "野良猫 ミケコ",
            "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, calico hair, multicolored hair, white brown and black patches, short hair, cat ears, calico cat tail, gold eyes, short yukata, friendly smile, medium breasts",
            "name": "the calico-haired cat woman in a short yukata",
            "pose": "crouching playfully with her hands like cat paws, cheerful smile, calico tail curled, looking at viewer"},
   "boss": {"type": "woman", "jp": "猫又", "canon": True, "canon_img": "EU41.png",
            "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, tall, nekomata, white hair, long hair, loose low bun, white cat ears, two white cat tails, red eyes, red eyeshadow, bewitching smile, black kimono with red spider lily pattern worn loosely off the shoulders, pale moist skin, medium breasts",
            "name": "the white-haired nekomata with two tails in a black kimono",
            "pose": "standing half-turned with her kimono slipping off one shoulder, her two white tails curling around her, bewitching smile, looking back at viewer"},
 },
 "places": {
   "stairs":   "landing on a long stone stairway in a hilly old downtown at sunset, stone walls, rooftops below",
   "alley":    "narrow back alley behind a tavern at night, empty wooden barrels, cobblestones, one hanging lantern",
   "cloth":    "eaves of a closed cloth shop in the market, piles of colorful fabric bolts, paper lantern",
   "forge":    "abandoned old smithy, cold brick forge, anvil, iron tools on the wall, dim light",
   "shrine":   "dead-end alley with a tiny inari shrine, small red torii gate, stone fox statues, paper lanterns",
   "bakery":   "back of a bakery before dawn, warm brick wall of a stone oven, piles of wheat sacks, stray cats sunbathing",
   "clock":    "machine room of an old clock tower, huge brass gears, wooden floorboards, moonlight through the clock face",
   "river":    "riverbank under an old stone bridge at sunset, grass, pebbles, water reflecting the orange sky",
   "home":     "cozy living room of a small old house, low round chabudai table, long sofa with an embroidered cushion, wall clock, small blackboard without text",
   "bedroom":  "tamer's bedroom, futon with a long hugging pillow, sunny window, cat toys",
   "market":   "night market alley, stalls selling incense burners, rising sweet smoke, paper lanterns",
   "roof":     "tiled rooftops at sunset where stray cats gather, chimneys, orange sky",
   "theater":  "stage of a small abandoned theater, heavy red curtain half lowered, old footlights, empty seats with cats",
   "well":     "small square in the back alleys with an old stone well, lanterns, moss",
   "bath":     "washing area of a public bathhouse after closing, white tiles, wooden buckets, rising steam",
   "mirror":   "mirror room of an old sideshow tent behind the night market, walls covered with tall mirrors, dim lamps",
   "pipe":     "upper room of an old pipe shop, worn floor cushions, incense burner, sweet smoke filling the room",
   "waiting":  "arena fighters' waiting room, long bench, lockers, towels",
   "attic":    "harbor warehouse attic with old blankets spread as a nest, moonlight from a skylight",
 },
 "atk": {
   "m1": ("stairs", "he lies on his back on the stone landing, the tamer sits over his hips and squeezes his erection between her thick thighs, thighjob, pinching his nipple, teasing grin, precum"),
   "m2": ("cloth", "he leans on the piles of fabric bolts, the tamer hugs him tightly from the front with her whole body, her arms around his back and her thick thighs locked around his leg, her breasts pressed on his chest, cheek to cheek, his arms limp"),
   "m3": ("alley", "he sits on the tamer's lap on a barrel, the tamer hugs him from behind, pinching both his nipples, gently biting his earlobe, her thighs holding his legs apart, trembling"),
   "e1": ("forge", "he lies before the cold forge, the smoke cat woman lies over him and blows thick sweet white smoke into his mouth and nose, his head tilted back, mouth open, hips twitching, no hands on him"),
   "e2": ("shrine", "he sits against a stone fox statue, the fox woman kneels at his side with her lips at his ear whispering, tongue in his ear, her fox tail wrapped around his chest, foxfire glowing around them, trembling"),
   "e3": ("bakery", "he lies face down on the wheat sacks with his hips raised, the calico cat woman kneels behind him licking his anus with her rough tongue, anilingus, her hands spreading his buttocks, her tail swaying"),
   "boss": ("clock", "he lies on his side on the floorboards, the nekomata lies behind him, one white tail coiling around his chest rubbing his nipples, her other white tail pushing into his anus, anal, her hand stroking his thigh, gears above"),
 },
 "atk_desc": {
   "m1": "the tamer squeezes him between her plump thighs.",
   "m2": "the tamer catches him in a full-body hug.",
   "m3": "the tamer plays with his nipples and bites his ear on her lap.",
   "e1": "the smoke cat woman makes him breathe her sweet smoke.",
   "e2": "the fox woman whispers into his ears from every direction.",
   "e3": "the calico cat woman grooms his bottom with her rough tongue.",
   "boss": "the nekomata teases his nipples and anus with her two tails.",
 },
 "lose": {
   # ネネコ 技1（むちむちの）
   "btl_m1":     ("stairs", "he lies on his back on the stone landing with his head squeezed between the tamer's thick thighs, the tamer sits holding his head in her thighs, smirking down at him, cum on her knees, " + BELL),
   "onani_m1":   ("river", "lying alone on the grass under the bridge hugging a long hugging pillow with both arms, the pillow clamped between his thighs and pressed to his chest, " + BELL + ", penis untouched, the tamer squats far away watching"),
   "inochi_m1":  ("bedroom", "he lies on the futon with his face buried between the tamer's thick thighs, the tamer lies with her thighs closed around his head, sleepy smile, " + BELL + ", cum dripping"),
   "onedari_m1": ("waiting", "he kneels on the long bench facing away, the tamer hugs him from behind with his penis squeezed between her thick thighs, thighjob, her hips pressed to his buttocks, flicking the bells of his collar, cum between her thighs"),
   # ネネコ 技2（捕まえたにゃ）
   "btl_m2":     ("cloth", "he is caught in the tamer's full-body hug on the fabric bolts, the tamer squeezes him with her arms and thick thighs, her lips at his ear, cum dripping onto the fabric, " + BELL + ", limp and trembling"),
   "onani_m2":   ("home", "rolling alone on the floor hugging a long hugging pillow with his arms and legs wrapped around it, cheek pressed to it, " + BELL + ", penis untouched, the tamer watches from across the low table"),
   "inochi_m2":  ("alley", "he stands under the eaves in the rain, the tamer holds him in a tight full-body hug, stroking his back, cheek to cheek, cum spreading between their bellies, a paper with a cat paw print without text in her hand"),
   "onedari_m2": ("roof", "he sits among white sheets hanging on a rooftop drying line at sunset, clinging to the tamer as she hugs him tightly, his arms around her back, a small spiral seashell tied to his bell collar, cum between their bellies"),
   # ネネコ 技3（膝の上で）
   "btl_m3":     ("alley", "he sits on the tamer's lap on a barrel with his back arched, the tamer bites his earlobe and pinches his nipple, cum on the cobblestones, " + BELL),
   "onani_m3":   ("home", "sitting alone on the sofa hugging an embroidered cushion, rubbing his chest against it, pinching his own nipple, " + BELL + ", penis untouched, the tamer watches from the low table"),
   "inochi_m3":  ("home", "he sits on the tamer's lap on the window sofa with his shirt open, the tamer bites his ear and rolls his cum-shiny nipples between her fingers, sunset window, " + BELL),
   "onedari_m3": ("alley", "he sits on the tamer's lap on an old bench under a single street lamp, the tamer bites his ear and pinches both nipples, tally marks in red lipstick on his chest, cum on his chest, " + BELL),
   # 煙猫（煙を吸わせる）
   "btl_e1":     ("forge", "he lies before the cold forge, the smoke cat woman hugs him and blows sweet white smoke into his face, her smoky paw stroking his penis, cum splashing into the smoke, his head tilted back"),
   "onani_e1":   ("market", "kneeling alone before an incense stall with his hands on his knees, breathing in the sweet rising smoke deeply, head tilted back, " + BELL + ", penis untouched, the smoke cat woman watches from far away"),
   "inochi_e1":  ("market", "he lies with his face buried in the smoke cat woman's cleavage as white smoke rises from between her breasts, the smoke cat woman's smoky paw stroking his penis, cum on her paw, his arms limp"),
   "onedari_e1": ("pipe", "he sits on an old floor cushion, face buried between the smoke cat woman's breasts in thick sweet smoke, a sheath of white smoke around his penis, cum, " + BELL),
   # 妖狐（分身の囁き）
   "btl_e2":     ("shrine", "he kneels before the small inari shrine, the fox woman hugs him from behind whispering into his ear, her tongue in his ear, her hand stroking his penis, cum on the stone, foxfire glowing"),
   "onani_e2":   ("well", "sitting alone by the old stone well, tracing both of his own ears with his fingertips, head tilted as if listening, " + BELL + ", penis untouched, the fox woman watches from the far side of the square"),
   "inochi_e2":  ("alley", "he kneels at a lantern-lit crossroads, the fox woman holds his penis between her breasts, paizuri, her lips at his ear whispering, foxfire around them, cum between her breasts"),
   "onedari_e2": ("mirror", "he sits on the floor of a mirrored room, the fox woman kneels behind him licking his ear and stroking his penis, many mirrors reflecting only the two of them, cum splashed on a mirror"),
   # ミケコ（毛づくろい）
   "btl_e3":     ("bakery", "he lies on his back on the wheat sacks with his legs lifted, the calico cat woman licks his anus with her rough tongue, anilingus, her calico tail coiled around his penis, cum on his own chest and belly"),
   "onani_e3":   ("roof", "crouching alone on the tiles at sunset, one arm reaching behind with his own wet fingers stroking his anus, the other hand at his mouth, " + BELL + ", penis untouched, the calico cat woman watches from far across the roof with the cats"),
   "inochi_e3":  ("alley", "he lies bent over a wooden crate behind a fish shop, the calico cat woman kneels behind him with her tongue deep in his anus, anilingus, her hand on his penis, cum on the crate, cats on the roofs"),
   "onedari_e3": ("attic", "he lies on his back on the blanket nest holding his knees to his chest, the calico cat woman licks his anus, anilingus, her calico tail wrapped around his penis, cum on his chest, moonlight, a small blank tag without text on his collar"),
   # 猫又（二股の尻尾）
   "btl_boss":   ("clock", "he lies on the floorboards, the nekomata holds him from behind, one white tail coiled on his nipples, her other white tail in his anus, anal, her hand stroking his penis, cum on her white fingers, gears above"),
   "onani_boss": ("theater", "standing alone on the stage with his shirt open, dangling two soft curtain tassels over his own nipples, the other hand reaching behind with fingers in his own anus, " + BELL + ", penis untouched, the nekomata watches from the seats"),
   "inochi_boss":("roof", "he lies on a moonlit rooftop by a water tower, the nekomata kneels beside him, one white tail coiled around his chest rubbing his nipples, her other white tail in his anus, anal, her hand stroking his penis, cum"),
   "onedari_boss":("bath", "he sits on the steamy white tiles, the nekomata kneels before him with her kimono slipped off her shoulders squeezing his penis between her moist breasts, paizuri, one white tail on his nipples, her other white tail in his anus, anal, cum between her breasts"),
 },
 "lose_desc": "keeps him as a house cat with twelve bells on his collar.",
 "onanie": {
   "master": ("bedroom", "hugging a long hugging pillow with his whole body, clamping it between his thighs, pressing his chest against it, " + BELL + " ringing, penis untouched"),
   "e1": ("market", "kneeling with his hands on his knees, breathing in sweet incense smoke deeply, head tilted back, mouth open, penis untouched"),
   "e2": ("well", "sitting and tracing both of his own ears alternately with his fingertips, head tilted as if listening, penis untouched"),
   "e3": ("roof", "crouching with one arm reaching behind, his own wet fingertips stroking his anus as if licking, penis untouched"),
   "boss": ("theater", "dangling two soft cords over his own nipples with one hand, the other hand reaching behind with fingers gently loosening his own anus, penis untouched"),
 },
 "magic": {
   "1": ("m", "alley", "holding up a sprig of silvervine and waving it, sparkles, stray cats gathering at her feet, grin"),
   "2": (None, "roof", "many stray cats gathering in a circle on moonlit rooftop tiles, a cat meeting"),
   "3": ("boss", "theater", "nine pale violet spirit flames floating around her like cat souls, her two tails raised, bewitching smile"),
   "4": ("e3", "roof", "waving a fluffy foxtail cat teaser toy, playful smile, tail swaying"),
   "5": (None, "alley", "a warm sunny corner of a back alley packed with sleeping stray cats, cushions, bells hanging from the eaves"),
 },
}
