# N102 質屋の女主人（Pawn）画像データ。登場人物は全員20歳以上。女性とニューハーフの混合（オパリナ・ヴェルヴェット＝NH）。女装なし。
# 質札・帳面・値札・鑑定書・契約書に文字や数字は描かない（blank / without text）。挿入はヴェルヴェットの落札の証（NH・背後から）だけ。
# オパリナのペニスは見せない（キスと白手袋だけ）。主人公の手首には質札の数だけ細い金の鎖の輪。
PN = {"pen": "penis"}   # ヴェルヴェットの落札の証（椿油で指でほぐした後）
CHAIN = "thin gold chain rings around his wrists"

DATA = {
 "code": "Pawn",
 "world": "old pawnshop in a back alley of a fantasy town, dark wooden lattice, soroban abacus, blank ledgers and paper tags without text, thin gold chains, lantern light, detailed background",
 "bg": "interior of a pawnshop counter at night, black polished lattice counter, soroban abacus, stacks of blank ledgers without text, wooden pillar hung with thin gold chains, paper lantern light",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ギルダ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, long legs, voluptuous, black hair, chignon with gold hairpins, red eyes, red lipstick, tight black dress, gold-chained monocle loupe, holding a soroban abacus, huge breasts",
         "name": "the black-haired pawnshop mistress in a tight black dress",
         "pose": "leaning on a counter peering through a gold-chained loupe, sweet merchant smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "ツバキ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, red hair, bob cut, brown eyes, striped kimono, black apron, holding a blank ledger without text and a writing brush, large breasts",
          "name": "the red-bobbed clerk in a striped kimono",
          "pose": "holding a blank ledger to her chest with a brush, quiet shy expression, looking at viewer"},
   "e2": {"type": "nh", "jp": "オパリナ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, slender, long legs, long pink hair, green eyes, white blouse, black tight skirt, white gloves, loupe hanging from her neck, medium breasts",
          "name": "the pink-haired appraiser in a white blouse and white gloves",
          "pose": "raising a loupe to her eye with a white-gloved hand, calm gentle smile, looking at viewer"},
   "e3": {"type": "woman", "jp": "ドーラ",
          "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, curvy, blonde hair, short hair, amber eyes, work vest, shorts, heavy key ring at her waist, bare thighs, huge breasts",
          "name": "the blonde storekeeper in a work vest with a key ring",
          "pose": "hands on her hips with a heavy key ring at her waist, bold grin, looking at viewer"},
   "boss": {"type": "nh", "jp": "ヴェルヴェット",
            "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, long wavy purple hair, gold eyes, black velvet dress with purple accents, long black opera gloves, auction gavel, large breasts",
            "name": "the purple-haired auctioneer in a black velvet dress",
            "pose": "raising an auction gavel with a gloved hand, glamorous composed smile, looking at viewer"},
 },
 "places": {
   "counter": "pawnshop counter, black polished lattice, soroban abacus, blank ledgers without text, pillar hung with gold chains, paper lantern",
   "front": "back alley shop front at dusk, wet cobblestones, lattice door, dark noren curtain without text",
   "shelf": "earthen-floored storeroom, shelves of pawned swords and cloaks with blank paper tags without text, dusty cloth",
   "kura": "inside a dim storehouse, thick earthen walls, heavy barred door, single candle, dust and silence",
   "kura2": "storehouse attic, low beams, stacked long wooden chests, moonlight from a narrow window, creaking floorboards",
   "appraisal": "appraisal room, desk covered with white cloth, loupes and a brass scale, white lamp light",
   "auction": "auction hall at the back of the shop, semicircle of empty chairs, auction stand, velvet curtains, gavel",
   "koagari": "cozy tatami room behind the counter, zabuton cushions, charcoal brazier, sliding paper door",
   "binding": "narrow binding room with blank ledgers without text stacked to the ceiling, thin lamp light, ink stones",
   "private": "mistress's private room, ebony dresser, box of gold hairpins, sandalwood incense, silk futon",
   "guestroom": "upstairs tatami guest room, alcove with a blank hanging scroll without text, low table, cold tea",
   "bath": "cypress wood bathhouse, wooden tub, steam, soap, slatted duckboards",
   "well": "backyard well at night, wooden bucket and rope, cold water, wooden fence",
   "night": "closed pawnshop at night, noren curtain taken down, inside the shut lattice door, faint shadows of passersby outside",
 },
 "atk": {
   "m1": ("counter", "he sits at the counter, the pawnshop mistress sits beside him weighing and stroking his penis with an appraiser's grip, handjob, pausing to peer at his nipple through her gold-chained loupe, soroban abacus beside, " + CHAIN),
   "m2": ("counter", "he sits at the counter with his chest thrust out, the pawnshop mistress holds her loupe to his nipple and rolls it with her fingertip, pinching the other, soroban abacus beside, trembling, " + CHAIN),
   "m3": ("counter", "he sits at the counter, the pawnshop mistress kisses him deeply, tongues, saliva trail, then whispers into his ear, a blank pawn ticket without text between her fingers, " + CHAIN),
   "e1": ("counter", "he sits at the counter, the clerk leans close blowing a soft breath into his ear, a blank ledger without text and a brush in her hands, no hands on him, shivering"),
   "e2": ("appraisal", "he sits by the white-clothed appraisal table, the appraiser holds his chin with a white-gloved hand and kisses him deeply, tongues, saliva trail, loupe hanging from her neck"),
   "e3": ("kura", "he kneels in the dim storehouse with his face buried in the storekeeper's huge breasts, the storekeeper squeezes her breasts around his head, candle light, key ring at her waist"),
   "boss": ("auction", "he stands on the auction stand facing the empty chairs, the auctioneer embraces him tightly from behind pinching both of his nipples with her gloved fingers, gavel in her hand, " + CHAIN),
 },
 "atk_desc": {
   "m1": "the pawnshop mistress appraises him by hand.",
   "m2": "the pawnshop mistress prices his nipples through her loupe.",
   "m3": "the pawnshop mistress seals the pawn contract with a kiss.",
   "e1": "the clerk counts his pawn tickets with her breath in his ear.",
   "e2": "the appraiser tests if he is genuine with a kiss.",
   "e3": "the storekeeper stores him away in her bosom.",
   "boss": "the auctioneer shows him off on the auction stand.",
 },
 "lose": {
   # ギルダ 技1（鑑定の手）
   "btl_m1":     ("counter", "he sits at the counter, the pawnshop mistress sits beside him weighing and stroking his penis with an appraiser's grip, handjob, peering at his nipple through her gold-chained loupe, blank ledger without text, cum, " + CHAIN),
   "onani_m1":   ("shelf", "standing alone before the shelf of pawned goods, cupping and weighing his own chest with one hand, the other fingers rolling his nipple, penis untouched, the pawnshop mistress watches far away from behind the shelf, " + CHAIN),
   "inochi_m1":  ("guestroom", "he sits on a zabuton, the pawnshop mistress kneels beside him gently stroking his penis, handjob, looking at his nipple through her loupe, a blank appraisal paper without text on the low table, cum"),
   "onedari_m1": ("koagari", "he kneels on the tatami pushing his hips forward, the pawnshop mistress sits by the brazier stroking his penis, handjob, a spare gold chain wrapped around his waist, loupe on her chest, cum"),
   # ギルダ 技2（値踏みのルーペ）
   "btl_m2":     ("counter", "he sits at the counter with his chest thrust out, the pawnshop mistress holds her loupe to his right nipple and pinches his left nipple, soroban abacus, blank white tags without text, trembling, cum, " + CHAIN),
   "onani_m2":   ("private", "sitting alone before the ebony dresser, holding a hand mirror to his chest, rolling his own nipple with his fingertip, penis untouched, the pawnshop mistress watches far away from the doorway"),
   "inochi_m2":  ("binding", "he sits among stacks of blank ledgers without text, the pawnshop mistress leans over him peering at his nipple through her loupe while rolling it with her fingertip, blowing on the other nipple, cum"),
   "onedari_m2": ("appraisal", "he lies on the white-clothed appraisal table offering his chest, the pawnshop mistress bends over him peering through her loupe and pinching both nipples, a brass scale beside, cum, " + CHAIN),
   # ギルダ 技3（質入れの契約）
   "btl_m3":     ("counter", "he sits at the counter, the pawnshop mistress kisses him deeply, tongues, saliva trail, holding her loupe over his nipple and rolling it, blank pawn tickets without text piled, cum, " + CHAIN),
   "onani_m3":   ("night", "sitting alone inside the shut lattice door at night, sucking his own finger as if kissing, the other hand rolling his own nipple, penis untouched, the pawnshop mistress watches far away from the dark counter"),
   "inochi_m3":  ("guestroom", "he kneels at the low table, the pawnshop mistress kisses him deeply, tongues, saliva trail, a blank contract paper without text with a red lip print on the table, cum"),
   "onedari_m3": ("private", "he lies on the silk futon, the pawnshop mistress covers his mouth with a deep kiss, tongues, pinching his nipple, sandalwood incense smoke, cum, " + CHAIN),
   # ツバキ（帳付けの吐息／帳場の下で）
   "btl_e1":     ("counter", "he sits at the counter, the clerk sits beside him blowing a soft breath into his ear while holding a blank ledger without text, her bare foot stretched under the counter rubbing his penis, footjob, cum"),
   "onani_e1":   ("binding", "sitting alone among stacked blank ledgers without text, cupping his palms over his ears, breathing into them, lips counting silently, penis untouched, the clerk watches far away holding a brush"),
   "inochi_e1":  ("koagari", "he sits on a zabuton, the clerk kneels close beside him whispering into his ear with a long thin breath, a blank ledger without text open on her knees, no hands on him, trembling, cum"),
   "onedari_e1": ("shelf", "he sits on a low step by the shelf of pawned goods, the clerk sits beside him blowing into his ear, her bare foot rubbing his penis, footjob, blank paper tags without text on the shelf, cum"),
   # オパリナ（真贋の口づけ／白手袋で）
   "btl_e2":     ("appraisal", "he sits on a stool by the appraisal table, the appraiser kisses him deeply, tongues, saliva trail, her white-gloved hand stroking his penis, handjob, loupe hanging from her neck, a white ribbon on the table, cum"),
   "onani_e2":   ("guestroom", "sitting alone on the tatami, sucking his own finger and exploring it with his tongue, the other fingers tracing his lips, penis untouched, a white glove left on the table, the appraiser watches far away from the sliding door"),
   "inochi_e2":  ("well", "he kneels by the well at night with wet lips, the appraiser kisses him deeply, tongues, her white-gloved hand on his cheek, wooden well bucket beside them, cold water drops, blush"),
   "onedari_e2": ("appraisal", "he sits at the appraisal table with his tongue out, the appraiser sucks his tongue in a deep kiss, her white-gloved hand stroking his neck, a blank name tag without text on the table, cum"),
   # ドーラ（蔵の中で／鍵束を鳴らして）
   "btl_e3":     ("kura", "he kneels in the dark storehouse with his face buried in the storekeeper's huge breasts, the storekeeper squeezes his head between her breasts, her bare thighs clamping his penis, thighjob, key ring at her waist, cum"),
   "onani_e3":   ("kura2", "curled up alone behind a long wooden chest with his face buried in a blanket, stroking his own chest, penis untouched, the storekeeper stands far away holding a candle, watching"),
   "inochi_e3":  ("bath", "he sits in the steaming cypress tub, the storekeeper in a wet work vest hugs his face into her huge breasts, steam, sleepy, flushed, cum floating in the water"),
   "onedari_e3": ("shelf", "he lies with his head in the storekeeper's lap by the shelf, his face buried in her huge breasts, key ring jingling at her waist, sleepy, blank paper tags without text on the shelf, cum"),
   # ヴェルヴェット（競売台の抱擁／落札の証）
   "btl_boss":   ("auction", "from behind, he stands bent forward on the auction stand facing the empty chairs, the auctioneer holds him from behind penetrating his anus with her own penis, anal, pinching his nipples, a blank price tag without text on a string around his neck, his own penis separate, cum", PN),
   "onani_boss": ("night", "standing alone inside the shut lattice door, one arm wrapped around himself from behind, the other hand pinching his own nipple, penis untouched, the auctioneer watches far away holding a gavel"),
   "inochi_boss":("guestroom", "he sits in the auctioneer's lap in the empty guest room, the auctioneer hugs him tightly from behind pinching both nipples, her lips at his ear, gavel on the low table, a blank certificate without text, cum"),
   "onedari_boss":("auction", "from behind, he bends over the auction stand, the auctioneer embraces him from behind penetrating his anus with her own penis, anal, pinching his nipple, a bottle of camellia oil and a gavel on the stand, his own penis separate, cum", PN),
 },
 "lose_desc": "keeps him in the pawnshop as a pledge that can never be redeemed.",
 "onanie": {
   "master": ("counter", "sitting at the counter holding a hand mirror to his chest, rolling his own nipple with his fingertip, penis untouched"),
   "e1": ("binding", "cupping his palms over his ears, breathing into them, lips counting silently, penis untouched"),
   "e2": ("appraisal", "sucking his own finger and exploring it with his tongue, the other fingers tracing his lips, penis untouched"),
   "e3": ("kura", "curled up in the dark with his face buried in a blanket, stroking his own chest, penis untouched"),
   "boss": ("auction", "one arm wrapped around himself from behind, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "counter", "the pawnshop mistress flicks the beads of a soroban abacus with one finger, a blank ledger without text open beside her, thin gold chains draped over her other hand, sly smile"),
   "2": (None, "shelf", "an open blank catalog ledger without text on a dusty shelf of pawned swords and cloaks with blank paper tags without text, lantern light"),
   "3": (None, "appraisal", "a blank appraisal certificate without text on white cloth, a magnifying loupe and a brass scale, faint pink glow over the paper"),
   "4": ("m", "counter", "the pawnshop mistress leans over the counter holding out a blank pawn ticket without text between two fingers, beckoning, alluring smile"),
   "5": (None, "kura", "inside a dim storehouse, heavy door draped with thin gold chains, shelves of pawned goods with blank tags without text, single candle"),
 },
}
