# N80 夜の女王の玉座（Queen）画像データ。登場人物は全員20歳以上。女性＋ふたなり（グラディス・メフィスタ）。女装なし。
# 女王は常に主人公より高い位置（玉座・階段の上）。膝の「跪礼の紋」は淡く光る赤い印（痛みなし）。
PEN = {"pen": "penis"}   # ふたなりのグラディス・メフィスタが自分の体で入れる本だけ
DATA = {
 "code": "Queen",
 "world": "gothic castle of the succubus queen in the demon realm at night, red carpets, golden candelabras, red moon, dark opulent atmosphere, detailed background",
 "bg": "grand throne room of a demon castle, long red carpet, rows of lit golden candelabras, high golden throne on top of seven white marble steps, red moon through tall windows",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "リリスティア",
         "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, black hair, very long straight hair, gold eyes, gold crown, curved black horns, large black bat wings, black succubus tail, black and gold gown, crimson cape, huge breasts",
         "name": "the black-haired succubus queen in a gold crown",
         "pose": "sitting on a golden throne with legs crossed, chin resting on her hand, haughty smile, looking down at viewer"},
   "e1": {"type": "woman", "jp": "ロザンヌ",
          "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, long legs, dark brown hair, french twist updo, green eyes, long black maid dress, white apron, white gloves, key ring at her waist, head maid, large breasts",
          "name": "the brown-haired head maid in a long black dress",
          "pose": "standing straight with hands folded in front of her apron, polite strict smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "グラディス",
          "tags": "adult woman, mature female, mature face, sharp adult features, 28 years old, adult proportions, beautiful detailed eyes, long legs, tall, succubus, red hair, high ponytail, gold eyes, crimson light armor, crimson breastplate, armored loincloth, black bat wings, holding a spear, knight captain, athletic, large breasts",
          "name": "the red-haired knight captain in crimson armor",
          "pose": "standing at attention holding a spear upright, serious face, looking at viewer"},
   "e3": {"type": "woman", "jp": "セレスタ",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, succubus, pink hair, long loose wavy hair, purple eyes, small horns, pale pink draped dress, holding a small harp, court musician, large breasts",
          "name": "the pink-haired harpist in a pale pink dress",
          "pose": "holding a small harp against her chest, languid mischievous smile, head tilted, looking at viewer"},
   "boss": {"type": "woman", "jp": "メフィスタ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 40 years old, adult proportions, beautiful detailed eyes, long legs, tall, demon woman, purple hair, very long hair, crimson eyes, monocle, two long straight horns, black chancellor's long robe with gold trim, black gloves, large breasts",
            "name": "the purple-haired chancellor in a black robe and monocle",
            "pose": "standing holding a rolled blank parchment, adjusting her monocle, cold polite smile, looking at viewer"},
 },
 "places": {
   "throne":   "grand throne room, long red carpet, rows of golden candelabras, high golden throne on top of seven marble steps, low angle",
   "steps":    "seven white marble steps leading up to a high golden throne, red carpet runner, candlelight, low angle looking up",
   "bedroom":  "queen's bedchamber, canopy bed with black silk sheets, thin incense smoke, dim candlelight",
   "corridor": "castle corridor, framed portraits, suits of armor, tall window with a red moon",
   "ante":     "anteroom, long velvet sofa, wall clock without numbers, closed heavy wooden door",
   "dress":    "maids' dressing room, vanity mirror, ceremonial clothes on racks, starched linen",
   "guard":    "royal guard room, spear rack, polished armor on stands, leather straps",
   "check":    "castle checkpoint, burning brazier, shadows of iron bars on the stone floor, wooden bench",
   "music":    "music room, standing harp and music stand, moonlit window, cushions on the floor",
   "banquet":  "banquet hall, long dining table, golden wine goblets, rows of candelabras",
   "office":   "chancellor's office, piles of blank parchment without text, sealing wax, inkwell, heavy dark desk",
   "bath":     "royal bath, rising steam, black marble bathtub, rose petals floating on the water",
   "balcony":  "castle balcony, stone railing, red night sky of the demon realm, lights of the town below",
   "gate":     "closed great black gate of the demon realm, faintly pulsing glowing crest, stone pavement, night",
   "wing":     "backstage wing of the throne room, heavy red velvet curtain, candle stand",
   "bed_ante": "small waiting chamber beside the queen's bedchamber, single chair, candle, heavy curtain",
 },
 "atk": {
   "m1": ("throne", "low angle, he kneels on the red carpet at the foot of the throne, the succubus queen sits high on the golden throne stretching one bare foot down, her sole pressing his penis, footjob, her other toes lifting his chin, haughty smile"),
   "m2": ("throne", "low angle, he kneels on both knees on the red carpet with his head bowed, faint glowing red marks on his knees, the succubus queen sits high on the golden throne pointing down at him, commanding, no hands on him, trembling"),
   "m3": ("throne", "he kneels between the succubus queen's knees at the throne with his face buried in her cleavage, the queen hugs his head to her chest, the tip of her black tail flicking his nipple, trembling"),
   "e1": ("dress", "he stands before the vanity mirror, the head maid stands behind him with her lips at his ear, licking the rim of his ear, whispering, her white-gloved hand stroking his penis, handjob, key ring at her waist"),
   "e2": ("guard", "he stands caught in a full nelson from behind, the knight captain locks his arms behind his head, her unbuckled breastplate on the floor, her chest pressed against his back, serious face, flushed, trembling"),
   "e3": ("music", "he lies on the cushions with his head on the harpist's lap, the harpist plucks his nipples with her fingernails like harp strings, small harp beside her, moonlit window, trembling"),
   "boss": ("office", "he sits on the edge of the heavy desk, the chancellor stands behind him breathing into his ear, pinching both his nipples with black-gloved fingers, monocle glinting, piles of blank parchment"),
 },
 "atk_desc": {
   "m1": "the succubus queen strokes him with her bare foot from the throne.",
   "m2": "the succubus queen commands him to kneel with a word of power.",
   "m3": "the succubus queen invites him into her bosom while her tail flicks his nipples.",
   "e1": "the head maid whispers court etiquette into his ear.",
   "e2": "the knight captain locks him in a full nelson from behind.",
   "e3": "the harpist plucks his nipples like harp strings.",
   "boss": "the chancellor breathes a royal decree into his ear.",
 },
 "lose": {
   # リリスティア 技1（玉座の足）
   "btl_m1":     ("steps", "low angle, he kneels on the top marble step with his forehead touching the tip of the queen's bare foot, the succubus queen sits high on the golden throne with legs crossed, twelve faint glowing marks on his knees, cum on the red carpet, trembling"),
   "onani_m1":   ("ante", "kneeling alone in seiza on the wooden floor, forehead pressed to the floor, hands on his knees, hips trembling, penis untouched, the succubus queen sits far away on the sofa by the open door, watching"),
   "inochi_m1":  ("steps", "low angle, he kneels at the bottom of the seven marble steps looking up, the succubus queen sits high on the golden throne swaying one bare foot from her gown hem, no hands on him, cum dripping on the marble step"),
   "onedari_m1": ("throne", "low angle, he kneels before the throne, the succubus queen sits high above wrapping his penis with the soles of both bare feet, footjob, cum on her toes, glowing marks on his knees, haughty smile"),
   # リリスティア 技2（跪礼の言霊）
   "btl_m2":     ("throne", "he lies prostrate with his forehead on the red carpet, the succubus queen has descended from the throne and stands over him stroking his head with one hand, glowing marks on his knees, cum on the carpet, the high throne behind"),
   "onani_m2":   ("bedroom", "kneeling alone in seiza on the floor before the canopy bed, hands on his knees, head bowed, hips twitching, penis untouched, the succubus queen stands far behind the bed curtain, watching"),
   "inochi_m2":  ("gate", "he kneels before the closed black gate with his hands clasped begging, the crest pulsing, the succubus queen floats above him on spread black wings leaning down to whisper in his ear, no hands on him, cum on the stones"),
   "onedari_m2": ("throne", "low angle, he lies prostrate on the red carpet, the succubus queen sits high on the golden throne with one hand raised, lips parted to give a command, no hands on him, cum on the carpet, glowing marks on his knees"),
   # リリスティア 技3（御前へ・胸元＋尻尾で乳首）
   "btl_m3":     ("throne", "he kneels between the succubus queen's knees at the throne with his face buried in her cleavage, the queen hugs his head, the tip of her black tail touching his nipple, cum on the red carpet, trembling"),
   "onani_m3":   ("bath", "kneeling alone in seiza at the edge of the black marble bath, flicking his own nipples with his fingertips, rose petals on the water, penis untouched, the succubus queen sits far away on the bath steps in the steam, watching"),
   "inochi_m3":  ("bedroom", "he kneels by the canopy bed with his face buried in the queen's cleavage, the succubus queen sits on the bed edge hugging his head, her black tail flicking his nipple, his mouth open mid-word, cum on the black silk"),
   "onedari_m3": ("banquet", "beside the long banquet table, he kneels with his face buried in the queen's cleavage, the succubus queen sits in a tall chair raising a golden goblet, her black tail flicking his nipple, cum on the floor"),
   # ロザンヌ（作法の耳打ち／身支度の手）
   "btl_e1":     ("dress", "he stands before the vanity mirror, the head maid stands behind him with her tongue in his ear, whispering, her white-gloved hand stroking his penis, handjob, cum on the vanity table, knees shaking"),
   "onani_e1":   ("ante", "sitting alone on the long sofa, tracing the rim of his own ear with a wet fingertip, lips murmuring, flushed, penis untouched, the head maid stands far away by the door with her key ring, watching"),
   "inochi_e1":  ("corridor", "he stands in front of a portrait in the corridor, the head maid stands behind him with her lips at his ear blowing a breath into it, no hands on him, red moon in the window, cum dripping on the floor"),
   "onedari_e1": ("wing", "he kneels behind the heavy red curtain, the head maid kneels behind him licking his ear, her white-gloved hand stroking his penis, handjob, a closed record book without text in her other hand, cum on the floor"),
   # グラディス（近衛の羽交い絞め／近衛の検め・ふたなり）
   "btl_e2":     ("guard", "from side, he stands bent forward held in a full nelson from behind, the knight captain penetrating his anus with her own penis from behind, anal, her unbuckled breastplate on the floor, her chest pressed against his back, his own penis separate, cum dripping", PEN),
   "onani_e2":   ("check", "lying alone face down on the wooden bench by the brazier, both hands clasped behind his back, rubbing his chest against the bench, penis untouched, the knight captain stands far away by the iron bars, watching"),
   "inochi_e2":  ("gate", "before the closed black gate, he stands held from behind by the knight captain, her arms wrapped around his chest, her chest pressed against his back, the crest glowing, cum on the stones, trembling"),
   "onedari_e2": ("ante", "from side, he sits on the knight captain's lap on the long sofa with his back to her, held in a full nelson, the knight captain penetrating his anus with her own penis from below, anal, her chest pressed against his back, his own penis separate, wall clock without numbers", PEN),
   # セレスタ（竪琴の指／楽師の膝枕）
   "btl_e3":     ("music", "he lies on the cushions with his head on the harpist's lap, the harpist plucks the small harp above his chest without touching him, his nipples erect and trembling, cum on his stomach, moonlit window"),
   "onani_e3":   ("balcony", "standing alone at the stone railing under the red night sky, flicking both of his own nipples with his fingernails, penis untouched, the harpist sits far away on a bench with a small harp, watching"),
   "inochi_e3":  ("banquet", "he lies on a rug beside the long banquet table with his head on the harpist's lap, the harpist plucks his nipples with her fingernails like harp strings, golden goblets, candelabras, cum on his stomach"),
   "onedari_e3": ("music", "he lies with his head on the harpist's lap, the harpist plucks both his nipples at once like a chord, a blank music sheet without notes on the music stand, cum on his stomach, trembling"),
   # メフィスタ（詔の吐息／宰相の裁き・ふたなり）
   "btl_boss":   ("office", "from side, he lies on his back on the heavy desk among blank parchment with legs lifted, the chancellor penetrating his anus with her own penis, anal, leaning down to breathe into his ear, pinching his nipple, his own penis separate, cum on his stomach", PEN),
   "onani_boss": ("bed_ante", "sitting alone on the chair, one palm cupped over his own ear breathing into it, the other hand pinching his own nipple, penis untouched, the chancellor stands far away by the curtain adjusting her monocle, watching"),
   "inochi_boss":("throne", "he kneels on the red carpet hugging a black box sealed with red wax, the chancellor bends over him breathing into his ear, holding a blank parchment without text, pinching his nipple, cum on the carpet"),
   "onedari_boss":("throne", "from side, he is on all fours on the red carpet before the steps of the throne, the chancellor kneels behind him penetrating his anus with her own penis, anal, leaning over to breathe into his ear, his own penis separate, glowing marks on his knees", PEN),
 },
 "lose_desc": "keeps him kneeling before the throne forever as the queen's vassal.",
 "onanie": {
   "master": ("throne", "kneeling alone in seiza on the red carpet before the empty throne, forehead lowered to the floor, hands on his knees, hips twitching, penis untouched"),
   "e1": ("ante", "sitting on the long sofa, tracing the rim of his own ear with a wet fingertip, lips murmuring, penis untouched"),
   "e2": ("check", "lying face down on the wooden bench with both hands clasped behind his back, rubbing his chest against the bench, penis untouched"),
   "e3": ("music", "sitting on the cushions, flicking his own nipples with his fingernails like harp strings, penis untouched"),
   "boss": ("bed_ante", "sitting on the chair, one palm cupped over his own ear breathing into it, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "throne", "the succubus queen sits on the golden throne raising a golden goblet of sweet red wine, a lipstick mark on the rim, sultry smile"),
   "2": (None, "office", "an invitation letter sealed with black wax without text on a silver tray, candlelight"),
   "3": (None, "throne", "a long red carpet with faint crimson glowing patterns leading up to an empty golden throne, trap"),
   "4": ("m", "throne", "the succubus queen looks down from the golden throne with glowing gold eyes, chin on her hand, crimson aura"),
   "5": (None, "throne", "an empty grand throne room, golden throne on seven marble steps, rows of lit golden candelabras, crimson banners without text"),
 },
}
