# N82 ミルク牧場（Ranch）画像データ。登場人物は全員20歳以上。女性＋ふたなり（ダリア・ボヴィーナ）。女装なし。
# 牛の獣人は耳・角・尻尾だけ（体毛・蹄なし）。シェパは犬の垂れ耳と尻尾だけ。主人公の首に小さなカウベルのチョーカー。
# 主人公の胸からは何も出ない（瓶に詰まるのは精）。瓶の名札・当番表・伝票は文字なし。
PEN = {"pen": "penis"}
BELL = "a small cowbell choker on his neck"
COWNEG = "hooves, furry, body fur, animal nose, cow print skin, animal feet"
DATA = {
 "code": "Ranch",
 "world": "pastoral dairy ranch on a green hill, wooden barns and fences, hay, milk bottles, warm country atmosphere, detailed background",
 "bg": "dairy ranch on a green hill at sunset, red wooden barn, wooden fences, hay bales, crates of glass milk bottles on a loading dock",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ダリア",
         "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, cow girl, cow ears, cow horns, cow tail, white hair with black streaks, long hair, brown eyes, open-collar shirt, denim overalls, cowbell choker, rancher, gigantic breasts",
         "name": "the white-haired cow girl rancher in overalls",
         "pose": "hands on her hips, one overall strap slipping off her shoulder, easygoing smile, looking at viewer",
         "neg": COWNEG},
   "e1": {"type": "woman", "jp": "ミルカ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, cow girl, cow ears, small cow horns, cow tail, flaxen hair, twintails, black eyes, white blouse, apron, milkmaid, huge breasts",
          "name": "the flaxen-haired cow girl milkmaid in a white blouse",
          "pose": "hugging a big cushion under her huge breasts, sleepy droopy-eyed smile, looking at viewer",
          "neg": COWNEG},
   "e2": {"type": "woman", "jp": "シェパ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, dog girl, floppy dog ears, dog tail, auburn hair, short hair, gold eyes, bandana around her neck, tank top, short pants, boots, sheepdog, athletic, medium breasts",
          "name": "the auburn-haired dog girl in a bandana and short pants",
          "pose": "leaning forward pointing ahead energetically, tail wagging, bright grin, looking at viewer",
          "neg": COWNEG},
   "e3": {"type": "woman", "jp": "ブリエ",
          "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, human, orange hair, chignon, green eyes, white work coat, white cap, holding a cheese spatula, cheesemaker, large breasts",
          "name": "the orange-haired cheesemaker in a white work coat",
          "pose": "holding a wooden cheese spatula and a cup of warm milk, cheerful wink, looking at viewer"},
   "boss": {"type": "woman", "jp": "ボヴィーナ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 40 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, cow girl, cow ears, large cow horns, cow tail, dark brown hair, long wavy hair, brown eyes, off-white long dress, shawl, large cowbell on her neck, motherly, gigantic breasts",
            "name": "the dark-brown-haired cow girl matron in an off-white dress and shawl",
            "pose": "arms open wide as if inviting a hug, gentle motherly smile, looking at viewer",
            "neg": COWNEG},
 },
 "places": {
   "barn":      "cow barn, hay-strewn aisle, wooden stalls, blank name plates without text on the fence",
   "straw":     "back of the cow barn, fluffy straw bedding, dim oil lamp, large cowbell hanging from a beam",
   "milking":   "milking room, leather-padded wooden milking bench, rows of empty glass bottles",
   "milking_am": "milking room in the cold morning light, leather-padded wooden milking bench, rows of empty glass bottles",
   "milking_pm": "milking room in orange evening sunlight, leather-padded wooden milking bench, rows of empty glass bottles",
   "loft":      "hayloft on the barn's second floor, dry hay piles, wooden ladder",
   "pasture":   "morning pasture, dewy grass, wooden fence, distant cowbells, morning mist",
   "hut":       "small watch hut by the livestock pen, wooden fence, wool blanket on the floor",
   "cheese":    "cheese workshop, big pot of steaming milk, wooden worktable, butter",
   "cellar":    "underground aging cellar, stone walls, rows of round cheese wheels, single lamp",
   "kitchen":   "farmhouse kitchen, fresh bread, big wooden table, blank duty chart without text on the wall",
   "guest":     "farmhouse guest room, simple bed with cushions and blankets, window showing the barn",
   "bedroom":   "rancher's bedroom, large bed, cowbell on the windowsill, sun-dried sheets",
   "well":      "stone well in the yard, wooden bucket, stone sink, cold water",
   "wagon":     "covered wagon bed loaded with wooden crates of glass milk bottles, canvas cover, country road",
   "hill":      "shade of a big tree on the hilltop, afternoon sunlight, hay bedding",
   "road":      "dirt road down the hill, pasture fence, distant town roofs",
 },
 "atk": {
   "m1": ("milking_am", "he lies on his back on the milking bench, the cow girl rancher kneels over him with her overall bib pulled down, squeezing his penis between her gigantic breasts, paizuri, pinching his nipple, " + BELL),
   "m2": ("milking_pm", "he sits on the milking bench, the cow girl rancher sits behind him hugging him, oiled fingers pinching both his nipples from base to tip like milking, rhythmic, " + BELL + ", trembling"),
   "m3": ("milking", "from side, he lies face down on the milking bench, the cow girl rancher over him penetrating his anus with her own penis, anal, kissing him over his shoulder, pinching his nipple, his own penis separate", PEN),
   "e1": ("loft", "he lies on the hay, the cow girl milkmaid lies over him pressing his face deep into her huge breasts, face buried in breasts, hugging his head, sleepy smile"),
   "e2": ("pasture", "he is pinned back against the wooden fence, the dog girl licks the rim of his ear with her tongue, nibbling his earlobe, sniffing his neck, tail wagging"),
   "e3": ("cheese", "he sits on the worktable, the cheesemaker holds his face and kisses him, pouring warm milk from her mouth into his, milk dripping from his chin, cup of milk in her hand"),
   "boss": ("straw", "he is wrapped in a full-body hug on the straw bedding, the cow girl matron holds him against her gigantic breasts inside her shawl, rolling his nipples with her fingers, gentle smile"),
 },
 "atk_desc": {
   "m1": "the cow girl rancher milks him between her breasts in the morning.",
   "m2": "the cow girl rancher teaches him how to be milked by his nipples.",
   "m3": "the cow girl rancher kisses him while squeezing him from behind.",
   "e1": "the cow girl milkmaid lets him nap on her breasts.",
   "e2": "the dog girl grooms his ears to herd him.",
   "e3": "the cheesemaker feeds him warm milk mouth to mouth.",
   "boss": "the cow girl matron wraps him in a mother's embrace.",
 },
 "lose": {
   # ダリア 技1（朝の搾乳・パイズリ）
   "btl_m1":     ("milking_am", "he lies on his back on the milking bench, the cow girl rancher kneels over him with her bib down, his penis between her gigantic breasts, paizuri, milking his nipples with her fingers, cum between her breasts, a glass bottle beside, " + BELL),
   "onani_m1":   ("barn", "sitting alone in the shadow of a stall fence, pinching his own nipples from base to tip with thumb and finger, " + BELL + ", penis untouched, the cow girl rancher stands far away down the aisle, watching"),
   "inochi_m1":  ("wagon", "in the swaying wagon bed between crates of milk bottles, he lies on his back, the cow girl rancher squeezes his penis between her gigantic breasts, paizuri, pinching his nipple, cum on his stomach, " + BELL),
   "onedari_m1": ("kitchen", "he sits on the big kitchen table, the cow girl rancher squeezes his penis between her gigantic breasts, paizuri, milking his nipple, the blank duty chart without text on the wall, cum on her breasts"),
   # ダリア 技2（★乳搾りの手ほどき）
   "btl_m2":     ("milking_pm", "he sits on the milking bench in the evening sun, the cow girl rancher behind him touches his nipples through his thin shirt with her fingertips, cum soaking his trousers, glass bottles lined up, " + BELL),
   "onani_m2":   ("loft", "lying alone on his back in the hay, pinching his own nipples from base to tip in rhythm with thumb and finger, counting, " + BELL + ", penis untouched, the cow girl rancher watches from the top of the ladder far away"),
   "inochi_m2":  ("well", "he sits on the stone edge of the well, the cow girl rancher stands behind him milking his nipples with cold wet fingers, wooden bucket, cum on the stones, trembling, " + BELL),
   "onedari_m2": ("barn", "he stands with his back against a barn pillar, the cow girl rancher milks both his nipples from base to tip with oiled fingers, the blank duty chart without text on the pillar, cum dripping on the hay"),
   # ダリア 技3（締め搾り・キス＋ふたなり逆アナル）
   "btl_m3":     ("milking", "from side, he lies face down on the milking bench, the cow girl rancher lies over him penetrating his anus with her own penis, anal, kissing him deeply over his shoulder, milking his nipple, his own penis separate, cum dripping into a glass bottle", PEN),
   "onani_m3":   ("barn", "lying alone face down on the hay in the dark barn at night, pinching both his own nipples, hips raised and twitching, penis untouched, the cow girl rancher stands far away holding up an oil lamp, watching"),
   "inochi_m3":  ("wagon", "from side, inside the closed canvas wagon bed, he lies on a blanket between milk crates, the cow girl rancher penetrating his anus with her own penis, anal, kissing him deeply, milking his nipple, his own penis separate", PEN),
   "onedari_m3": ("bedroom", "from side, he lies on his back on the large bed with legs lifted, the cow girl rancher penetrating his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate, cum on his stomach", PEN),
   # ミルカ（乳枕／干し草の上で）
   "btl_e1":     ("loft", "he lies on the hay with his face buried in the cow girl milkmaid's huge breasts, the milkmaid hugs his head, his penis squeezed between her thighs, thighjob, cum on her thighs, sleepy smile"),
   "onani_e1":   ("guest", "lying alone face down on the bed with his face buried between two big cushions, stroking his own chest, penis untouched, the cow girl milkmaid peeks from the doorway far away, watching"),
   "inochi_e1":  ("hill", "under the big tree in the afternoon sun, he naps with his face buried in the cow girl milkmaid's huge breasts, the milkmaid strokes his head, cum on the hay, dozing"),
   "onedari_e1": ("loft", "he lies on the hay with his face buried in the cow girl milkmaid's huge breasts, the milkmaid squeezes his penis between her thighs, thighjob, hugging his head, cum on the hay"),
   # シェパ（毛づくろい／追い込みの足）
   "btl_e2":     ("pasture", "he sits against the wooden fence, the dog girl licks inside his ear, her bare foot rubbing his penis, footjob, her boots tossed on the grass, cum on her foot, morning dew"),
   "onani_e2":   ("hut", "sitting alone on the wool blanket, tracing his own ear upward with a wet finger as if licking, flushed, penis untouched, the dog girl stands far away at the hut door with her ears perked, watching"),
   "inochi_e2":  ("road", "on the dirt road with the town roofs far behind, he kneels, the dog girl licks his ear and points back toward the ranch, tail wagging, cum on the dirt"),
   "onedari_e2": ("barn", "inside a wooden stall, he sits on the hay, the dog girl licks his ear, her bare foot rubbing his penis, footjob, a bandana tied around his neck, cum on the hay"),
   # ブリエ（味見の口移し／バター塗りの手）
   "btl_e3":     ("cheese", "he sits on the worktable, the cheesemaker kisses him pouring warm milk into his mouth, milk dripping from his chin, her buttered hand stroking his penis, handjob, cum on the table"),
   "onani_e3":   ("cellar", "sitting alone against the cheese shelves, sucking two of his own fingers with milk dripping from his lips, a cup of milk beside him, penis untouched, the cheesemaker stands far away holding a lamp, watching"),
   "inochi_e3":  ("wagon", "behind the covered wagon, he leans on the milk crates, the cheesemaker holds his face and kisses him pouring milk from her mouth into his, milk dripping, a small tasting spoon in her hand"),
   "onedari_e3": ("kitchen", "he sits at the big kitchen table, the cheesemaker kisses him deeply pouring thick warm milk into his mouth, her buttered hand stroking his penis, handjob, cum on the table"),
   # ボヴィーナ（母牛の抱擁／牛舎の奥で・ふたなり）
   "btl_boss":   ("straw", "from side, he lies on his back on the straw bedding, the cow girl matron embraces him fully while penetrating his anus with her own penis, anal, his face against her gigantic breasts, rolling his nipple, his own penis separate", PEN),
   "onani_boss": ("guest", "lying alone curled up wrapped in a blanket as if embraced, pinching his own nipples inside the blanket, penis untouched, the cow girl matron stands far away in the doorway, watching"),
   "inochi_boss":("wagon", "from side, in the wagon bed at night, he lies on a blanket, the cow girl matron embraces him while penetrating his anus with her own penis, anal, his face in her gigantic breasts, her shawl over them, his own penis separate", PEN),
   "onedari_boss":("straw", "from side, he lies on the straw bedding with his own pillow, the cow girl matron embraces him fully while penetrating his anus with her own penis, anal, rolling his nipple inside her shawl, his own penis separate", PEN),
 },
 "lose_desc": "keeps him on the ranch as one of the herd, his name plate hung on the fence.",
 "onanie": {
   "master": ("milking", "sitting on the milking bench, pinching both his own nipples from base to tip with thumb and finger in rhythm, " + BELL + ", penis untouched"),
   "e1": ("guest", "lying face down with his face buried between two big cushions, stroking his own chest, penis untouched"),
   "e2": ("hut", "sitting on the wool blanket, tracing his own ear upward with a wet finger as if licking, penis untouched"),
   "e3": ("cheese", "sitting on the worktable, sucking two of his own fingers with warm milk dripping from his lips, a cup of milk beside him, penis untouched"),
   "boss": ("guest", "curled up wrapped in a blanket as if embraced, pinching his own nipples inside the blanket, penis untouched"),
 },
 "magic": {
   "1": ("m", "milking", "holding up a glass bottle of fresh milk with a blank label without text, offering it, easygoing smile"),
   "2": (None, "wagon", "a blank shipping slip without text pinned on a wooden crate of glass milk bottles"),
   "3": (None, "barn", "a large brass cowbell hanging from a barn beam, ringing, faint pink sound waves"),
   "4": ("e1", "loft", "lying on a soft bed of hay, patting the hay beside her invitingly, sleepy smile"),
   "5": (None, "milking", "an empty leather-padded wooden milking bench, rows of glass bottles, warm evening light"),
 },
}
