# N17 スキュラの海底神殿（Scylla）画像データ。登場人物は全員20歳以上。全員女性（クラーケはふたなり。挿入する本だけ pen=penis）。
# 舞台は海底神殿（主人公は魔法で水中でも息ができる）。女装なし。日誌・札・板は文字なし。
# 以前の生成で、オナニーの絵の主人公が貝殻のブラを着けてしまったので、全員の neg に「男の貝殻ブラ・ビキニ」を入れてある。
# メルティナ・アネモ・メドゥの触手や糸はその人物の体の一部（道具ではない）。尿道への挿入は描かない。
MAN_NEG = "seashell bra on the man, bikini top on the man, bra on the man, shell ornaments on the man"

DATA = {
 "code": "Scylla",
 "world": "sunken undersea temple, underwater, air bubbles, light rays from the surface far above, coral, swaying seaweed, ancient stone ruins, he can breathe underwater, detailed background",
 "bg": "underwater ruins of a sunken temple, great hall with broken stone pillars, a coral throne, light rays falling from the surface, fish and air bubbles, emerald green water",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "海魔メルティナ",
         "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, tall, scylla, octopus girl, light purple hair, long wavy hair, gold eyes, eight purple octopus tentacles from the waist down, suction cups on the tentacles, seashell and pearl hair ornaments, pearl necklace, sheer lavender cloth draped over her chest and hips, gentle alluring smile, large breasts",
         "name": "the purple-haired octopus woman",
         "pose": "floating upright with her eight tentacles spread in a wide circle, one hand at her lips, gentle alluring smile, looking at viewer",
         "neg": "human legs, feet, " + MAN_NEG},
   "e1": {"type": "woman", "jp": "人魚 セイレ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, mermaid, blonde hair, very long hair, green eyes, pearl bra, golden fish tail instead of legs, fin-shaped ear ornaments, sweet gentle smile, medium breasts",
          "name": "the blonde mermaid with a golden tail",
          "pose": "sitting sideways on a rock with her golden tail curled, one hand on her chest as if singing, sweet smile, looking at viewer",
          "neg": "legs, human legs, feet, " + MAN_NEG},
   "e2": {"type": "woman", "jp": "イソギンチャク娘 アネモ",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, sea anemone girl, pink hair, short hair with tentacle-like tufts, red eyes, skirt of soft pink swaying tentacles rooted on a rock, bare shoulders, playful grin, medium breasts",
          "name": "the pink-haired anemone woman with a tentacle skirt",
          "pose": "sitting on her rock with the pink tentacle skirt spread out, arms open wide, playful grin, looking at viewer",
          "neg": "human legs, feet, " + MAN_NEG},
   "e3": {"type": "woman", "jp": "クラゲ娘 メドゥ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, jellyfish girl, translucent white hair, long hair, pale pink eyes, translucent bell-shaped jellyfish dress with long trailing threads, faint glow, sleepy calm expression, small breasts",
          "name": "the white-haired jellyfish woman in a translucent bell dress",
          "pose": "floating softly with her bell-shaped dress spread like an umbrella, threads trailing below, sleepy calm gaze, looking at viewer",
          "neg": MAN_NEG},
   "boss": {"type": "woman", "jp": "深海の女王 クラーケ",
            "tags": "adult woman, mature female, mature face, 35 years old, adult proportions, beautiful detailed eyes, very tall, kraken queen, crimson hair, very long hair, black eyes, giant dark red tentacles from the waist down, black scale outfit, black scale bodice, gold circlet, imperious smile, large breasts",
            "name": "the crimson-haired kraken queen",
            "pose": "towering with giant tentacles coiled beneath her like a throne, one hand extended palm up, imperious smile, looking down at viewer",
            "neg": "human legs, feet, " + MAN_NEG},
 },
 "places": {
   "hall":      "great hall of the sunken temple, coral throne, broken stone pillars standing in a circle, light rays falling from above",
   "bedchamber": "pearl bedchamber, a giant open clam shell used as a bed, curtains of strung pearls, soft glowing light",
   "inkcave":   "ink cave in the temple, thick purple-black ink swirling through the water, dim light at the cave mouth",
   "tidepool":  "tide-pool corridor of the temple, waist-deep stone pools, light beams through cracks in the ceiling, stone pedestals along the walls",
   "cove":      "mermaid cove under a rock dome, smooth rock shelf, drifting seaweed, soft golden light",
   "anemone":   "warm rocky field covered with colorful sea anemones, a column of light falling from a crack above",
   "jelly":     "jellyfish waters, a bowl of white sand under a pillar of light, many glowing translucent jellyfish drifting",
   "trench":    "edge of an abyssal trench, a rock ledge over endless darkness, a glowing red stone lantern, faint red light",
   "ship":      "tilted captain's cabin of a sunken ship, round porthole, brass compass, blank logbook without text on the desk, old wooden crates",
   "shaft":     "vertical underwater shaft in the temple, spiral lines of ink drawn on the stone walls, a faint light far above",
   "pledgewall": "rock wall in the deep sea glowing with three red marks without text, darkness around, drifting bubbles",
 },
 "atk": {
   "m1": ("bedchamber", "he floats on his back in the giant clam, the octopus woman wraps him loosely in her purple tentacles, two suction cups sucking hard on his nipples, round sucker marks on his chest, gentle smile"),
   "m2": ("inkcave", "he floats in the swirling ink, the octopus woman exhales a cloud of purple-black ink over his face while a suction cup sucks on his nipple, his mouth open breathing it in, dazed"),
   "m3": ("hall", "he is held in the air by the octopus woman's eight tentacles, one thick tentacle pushed into his anus, anal, two suction cups on his nipples, tentacles around his wrists and ankles, his own penis separate"),
   "e1": ("cove", "he lies in the mermaid's arms on the rock shelf, the mermaid wraps her golden tail around his legs and sings softly into his ear, her lips at his ear, no other touch, trembling"),
   "e2": ("anemone", "he sits on the anemone woman's pink tentacle skirt with his back against her chest, a soft pink tentacle slipping into his anus, anal, swaying slowly, the anemone woman hugging his waist"),
   "e3": ("jelly", "he floats under the jellyfish woman's translucent bell dress, fine translucent threads looped around his nipples and trailing over his belly and between his legs, sparkling numbness, trembling"),
   "boss": ("trench", "from side, he is held on his back by giant dark red tentacles over the trench, the kraken queen between his legs penetrating his anus with her own penis, anal, suckers on his nipples, his own penis separate", {"pen": "penis"}),
 },
 "atk_desc": {
   "m1": "the octopus woman caresses his nipples with her suction cups.",
   "m2": "the octopus woman clouds his mind with her illusion ink.",
   "m3": "the octopus woman fills him with all eight of her legs.",
   "e1": "the mermaid sings her song into his ear.",
   "e2": "the anemone woman sways her tentacles inside him.",
   "e3": "the jellyfish woman numbs him with transparent threads.",
   "boss": "the kraken queen takes him in the abyssal union.",
 },
 "lose": {
   # メルティナ 技1（吸盤の愛撫・乳首）
   "btl_m1":     ("bedchamber", "he floats on his back inside the half-closed giant clam, the octopus woman's tentacles wrap his limbs, suction cups sucking deeply on both nipples, rows of red sucker marks on his skin, no hands on his penis, white cum clouding the water"),
   "onani_m1":   ("tidepool", "kneeling alone in a waist-deep stone pool, pinching and pulling both of his own nipples as if sucked, round sucker marks around them, penis untouched, the octopus woman watches from a far pedestal"),
   "inochi_m1":  ("hall", "he lies at the foot of the coral throne, the octopus woman leans over him with two suction cups sucking his nipples, purple ring-shaped sucker marks around them, cum drifting like white mist"),
   "onedari_m1": ("hall", "he kneels before the coral throne thrusting his chest out, the octopus woman's tentacles press suction cups onto both nipples, pearls lined up on a stone board beside them, cum drifting in the water"),
   # メルティナ 技2（墨の幻惑）
   "btl_m2":     ("inkcave", "he floats in layers of swirling purple-black ink, the octopus woman blows ink over his face while suction cups suck his nipples, his mouth open, no hands on his penis, cum clouding the ink"),
   "onani_m2":   ("hall", "kneeling alone among the stone pillars, breathing in drifting purple ink with his mouth open, pinching both of his own nipples, penis untouched, the octopus woman watches from the coral throne"),
   "inochi_m2":  ("shaft", "he sinks down the vertical shaft past spiral ink lines into the octopus woman's spread tentacles, a sucker tentacle attached to his nipple like a lifeline, cum trailing upward"),
   "onedari_m2": ("bedchamber", "he lies in the giant clam, the octopus woman's biggest suction cups sucking both nipples, a small bottle of ink on the clam edge, purple sucker marks, cum clouding the water"),
   # メルティナ 技3（八本の脚・アナル＋乳首）
   "btl_m3":     ("hall", "he is held before the coral throne by the octopus woman's eight tentacles, one thick tentacle in his anus, anal, two suction cups on his nipples, tentacles wrapped around his waist, his own penis separate, cum drifting"),
   "onani_m3":   ("bedchamber", "lying alone in the open giant clam, pinching both of his own nipples, legs trembling, penis untouched, the octopus woman watches from behind the pearl curtains"),
   "inochi_m3":  ("tidepool", "he floats in a beam of light, the octopus woman's tentacles wind around his waist, one tentacle in his anus, anal, suction cups on his nipples, his own penis separate, cum drifting"),
   "onedari_m3": ("ship", "he lies on the tilted cabin floor, the octopus woman's tentacles wrap his body, one tentacle in his anus, anal, suction cups on both nipples, his own penis separate, cum clouding the porthole light"),
   # セイレ（人魚の歌声・耳）
   "btl_e1":     ("cove", "he lies in the mermaid's arms on the rock shelf, the mermaid covers his ears with her palms and sings into them, her golden tail wrapped around his legs, no hands on his penis, cum rising with bubbles"),
   "onani_e1":   ("tidepool", "sitting alone on the stone floor with his hands floating on the water, singing to himself with his lips moving, hips twitching, penis untouched, the mermaid watches from a pedestal far away"),
   "inochi_e1":  ("cove", "he sinks in dark water held by the mermaid, the mermaid cups his ears with her palms and sings, her golden tail curled around him, cum rising in bubbles, trembling"),
   "onedari_e1": ("bedchamber", "he lies with his head in the mermaid's lap on the edge of the giant clam, the mermaid covers both his ears with her palms and sings, three small conch shells on a string beside him, cum drifting"),
   # アネモ（揺れる触手・アナル）
   "btl_e2":     ("anemone", "he sits on the anemone woman's tentacle skirt leaning back against her chest, a soft pink tentacle swaying inside his anus, anal, anemones blooming around them, his own penis separate, cum clouding the water"),
   "onani_e2":   ("anemone", "sitting alone on a warm rock, reaching behind with two of his own fingers in his own anus, rocking his hips slowly, penis untouched, the anemone woman watches from her rock far away"),
   "inochi_e2":  ("anemone", "he sits on the anemone woman's pink tentacles, three soft tentacles swaying in his anus, anal, the anemone woman lifting his chin with a finger, his own penis separate, cum drifting"),
   "onedari_e2": ("anemone", "he sits on the anemone woman's tentacle skirt in the column of light, soft pink tentacles slipping into his anus, anal, white anemones blooming around, his own penis separate, cum drifting"),
   # メドゥ（透明な糸）
   "btl_e3":     ("jelly", "he floats under the jellyfish woman's translucent bell dress like a puppet, fine threads looped around his nipples and trailing between his legs, glowing jellyfish around, no hands on his penis, cum drifting as white mist"),
   "onani_e3":   ("jelly", "sitting alone on the white sand, one hand pinching his own nipple, the other hand pressing below his navel, trembling, penis untouched, the jellyfish woman watches from inside the pillar of light"),
   "inochi_e3":  ("jelly", "he sinks onto the sand, the jellyfish woman hugs him from behind with her translucent dress clinging to his body, fine threads trailing over his chest and belly, cum drifting"),
   "onedari_e3": ("ship", "he kneels before the jellyfish woman sitting on an old crate, threads from her fingertips looped around his nipples, a small glass jar with a tiny jellyfish on the floor, cum drifting"),
   # クラーケ（深淵の交わり・乳首＋ふたなり）
   "btl_boss":   ("trench", "from side, he lies on his back wrapped in giant dark red tentacles over the trench, the kraken queen penetrates his anus with her own penis, anal, suckers on his nipples, his own penis separate, cum drifting in the red light", {"pen": "penis"}),
   "onani_boss": ("trench", "kneeling alone on the rock ledge by the red lantern, two of his own fingers coated in red jelly pushed into his own anus from behind, a black clam full of red jelly beside him, penis untouched, the kraken queen watches from the darkness"),
   "inochi_boss":("trench", "from side, he lies on his back held by giant tentacles, the kraken queen penetrates his anus with her own penis, anal, tentacle suckers on his nipples, red light and white mist swirling, his own penis separate", {"pen": "penis"}),
   "onedari_boss":("pledgewall", "from side, he lies on his back before the glowing rock wall held by giant tentacles, the kraken queen penetrates his anus with her own penis, anal, suckers on his nipples, his own penis separate, cum drifting", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the sunken temple as a servant of the sea forever.",
 "onanie": {
   "master": ("tidepool", "kneeling in a waist-deep stone pool, pinching and pulling both of his own nipples as if sucked by suction cups, penis untouched"),
   "e1": ("cove", "sitting on the rock shelf with his hands resting on his knees, singing to himself, hips twitching, penis untouched"),
   "e2": ("anemone", "sitting on a warm rock, reaching behind with two of his own fingers in his own anus, rocking his hips, penis untouched"),
   "e3": ("jelly", "sitting on the white sand, one hand pinching his own nipple, the other pressing below his navel, penis untouched"),
   "boss": ("trench", "kneeling on the rock ledge, two of his own fingers coated in red jelly in his own anus from behind, pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": (None, "hall", "the tide rising through the temple hall, water flooding over the stone floor and pillars, seaweed and bubbles swaying"),
   "2": (None, "hall", "a swirling whirlpool at the foot of the coral throne, sand and bubbles spinning in a vortex"),
   "3": ("e1", "cove", "sitting on the rock shelf singing with her eyes closed, glowing musical notes drifting through the water, golden tail swaying"),
   "4": ("m", "hall", "calling out with one hand beside her mouth, her tentacles spread wide, ripples spreading through the water, gentle smile"),
   "5": ("m", "inkcave", "blowing a thick cloud of purple-black ink from her lips, the ink spreading like smoke, seductive smile"),
 },
}
