# N105 天女の羽衣（Sky）画像データ。登場人物は全員20歳以上（天女は見た目の年齢・成人）。女性＋NH（スイレン・シュカ＝NH）。女装なし。
# 挿入はシュカの「天への道」（NHの逆アナル）だけ。羽衣は薄絹で包んで浮かせるだけ（縄・緊縛にしない）。鎧・武器・翼・天馬は描かない。
HAGO = "sheer iridescent white silk hagoromo loosely wrapped around him, softly floating"
PN = {"pen": "penis"}
NEG_SKY = "wings, feathered wings, angel wings, armor, weapon, horse, rope, bondage, shibari, tied up, restraints"

DATA = {
 "code": "Sky",
 "world": "east asian celestial realm of tennyo maidens, floating iridescent hagoromo shawls, soft clouds, pine coast far below, peach blossoms, vermilion and gold, elegant atmosphere, detailed background",
 "bg": "celestial palace above the clouds, white wooden pillars and vermilion railings, pale pink hanging curtains, floor of soft clouds, huge vermilion gate glowing in the distance, peach blossom petals drifting, golden light",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "コウカ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, tall, long legs, tennyo, celestial maiden, blonde hair, very long hair in an elegant celestial updo, jade hairpins, red eyes, pale pink hanfu robe, iridescent white hagoromo shawl floating around her, huge breasts, graceful smile",
         "name": "the blonde celestial maiden with a rainbow hagoromo shawl",
         "pose": "floating slightly above the ground, iridescent shawl drifting around her, one sleeve raised gracefully, gentle elegant smile, looking at viewer",
         "neg": NEG_SKY},
   "e1": {"type": "woman", "jp": "リンカ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, tennyo, celestial maiden, pink hair, very long straight hair, green eyes, pale peach hanfu robe, sheer shawl, holding a sho mouth organ, large breasts, dreamy smile",
          "name": "the pink-haired celestial musician holding a sho",
          "pose": "playing a sho mouth organ with eyes half-lidded, dreamy expression, floating shawl, looking at viewer",
          "neg": NEG_SKY},
   "e2": {"type": "nh", "jp": "スイレン",
          "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, tennyo, celestial dancer, purple hair, very long hair, amber eyes, purple and white dance robe with very long flowing sleeves, large breasts, graceful smile",
          "name": "the purple-haired celestial dancer with very long sleeves",
          "pose": "mid dance turn, very long sleeves flowing in an arc, graceful soft smile, looking at viewer",
          "neg": NEG_SKY},
   "e3": {"type": "woman", "jp": "フワリ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, tennyo, celestial maiden, brown hair, very long fluffy wavy hair, brown eyes, soft white cloud-like robe, fluffy cloud floating around her, huge breasts, sleepy smile",
          "name": "the fluffy brown-haired cloud maiden in a white cloud robe",
          "pose": "lying lazily on a fluffy cloud, hugging a bit of cloud, sleepy half-closed eyes, yawning smile, looking at viewer",
          "neg": NEG_SKY},
   "boss": {"type": "nh", "jp": "シュカ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, celestial court lady, vermilion hair, very long hair, gold eyes, vermilion and gold court robes, jade crown, large breasts, solemn gentle expression",
            "name": "the vermilion-haired celestial head court lady in vermilion and gold robes",
            "pose": "standing before a vermilion gate with hands folded in her sleeves, solemn gentle expression, softly exhaling a faint glittering breath, looking at viewer",
            "neg": NEG_SKY},
 },
 "places": {
   "pine": "seaside pine grove, twisted pine trees, dry sand and pine needles, sea glimpsed between trunks",
   "beach": "beach at sunset, gentle waves, wet sand, crimson and orange sky",
   "teahouse": "seaside teahouse inn room, tatami and shoji, andon paper lamp, wooden veranda facing the pine grove",
   "stairs": "stairway of soft clouds rising into the sky, pine coast tiny far below",
   "gate": "huge vermilion celestial gate on the clouds, golden light spilling through, cloud floor",
   "hall": "celestial palace hall, white wooden pillars, vermilion railings, pale pink hanging curtains, floor of clouds",
   "music": "celestial music pavilion, sho and koto on stands, thin incense smoke from a censer, clouds outside",
   "stage": "white wooden dance stage in the clouds, pale pink curtains, small bells hanging",
   "field": "endless field of fluffy cotton clouds in warm sunlight",
   "peach": "celestial peach orchard, blooming peach trees, pale pink petals drifting, ripe peaches, dappled light",
   "river": "bridge over the milky way river of glowing stars, jade stone railings, night sky",
   "robes": "robe hall, rows of stands hung with iridescent hagoromo shawls, shimmering rainbow silk",
   "edge": "edge of the clouds, gap in the clouds showing the pine grove and sea far below, dizzying height",
   "lotus": "lotus pond water pavilion at night, white lotus flowers, moon reflected on the water",
   "chamber": "head court lady's chamber, vermilion and gold furnishings, thick silk bedding, incense smoke",
 },
 "atk": {
   "m1": ("pine", "he floats above the sand wrapped in sheer silk, the celestial maiden sits on a cloud with him on her lap, his penis squeezed between her breasts through the hagoromo, paizuri, his toes off the ground"),
   "m2": ("beach", "he floats above the wet sand, the celestial maiden winds her sheer iridescent hagoromo loosely around his wrist and chest, her fingers slipping under the silk stroking his skin, his feet lifting off, trembling"),
   "m3": ("river", "he floats above the star bridge railing, the celestial maiden kisses him deeply, tongues, the tip of her hagoromo tickling his nipple, sheer silk around his wrists, stars below"),
   "e1": ("pine", "he kneels on the pine needles, the celestial musician leans at his ear playing the sho right beside it, her lips close to his earlobe, his shoulders trembling, pine wind"),
   "e2": ("beach", "the celestial dancer covers his eyes with her very long sleeve and hugs his face into her cleavage, swaying, the sleeves wrapped around his head, sunset waves"),
   "e3": ("field", "he sinks into the fluffy clouds, the cloud maiden hugs him tight, his face pressed into her breasts, her legs wrapped around his, cloud wrapping them both, sleepy smile"),
   "boss": ("gate", "he stands before the vermilion gate, the head court lady cups his chin and breathes a glittering sweet breath onto his lips, pinching his nipple, his mouth open inhaling, hazy look"),
 },
 "atk_desc": {
   "m1": "the celestial maiden holds him between her breasts above the clouds.",
   "m2": "the celestial maiden winds her hagoromo around him until he floats.",
   "m3": "the celestial maiden gives him a heavenly kiss.",
   "e1": "the musician plays a heavenly melody into his ear.",
   "e2": "the dancer wraps his face in her dancing sleeves.",
   "e3": "the cloud maiden embraces him in a soft cloud.",
   "boss": "the head court lady breathes her jade breath onto him.",
 },
 "lose": {
   # コウカ 技1（雲の上の＝パイズリ＋羽衣の巻きつけ）
   "btl_m1":     ("pine", "high above the pine treetops, he lies on the celestial maiden's lap on a cloud, " + HAGO + ", his penis squeezed between her breasts, paizuri, cum splashing on her chest, his feet dangling in the air"),
   "onani_m1":   ("teahouse", "sitting alone on the veranda, a thin cloth sash wound from his wrist around his chest, fingers under the cloth stroking his own chest, penis untouched, the celestial maiden watches from the pine grove"),
   "inochi_m1":  ("edge", "at the edge of the clouds, he lies on the celestial maiden's lap looking down at the tiny pine coast far below, " + HAGO + ", his penis between her breasts, paizuri, cum dripping"),
   "onedari_m1": ("hall", "in the palace hall on the clouds, the celestial maiden holds him up in her lap, " + HAGO + ", his penis squeezed between her breasts, paizuri, his arms around her neck, cum on her chest"),
   # コウカ 技2（羽衣の巻きつけ）
   "btl_m2":     ("beach", "he floats above the waves, sheer iridescent silk loosely wrapped from his wrists to his legs, the celestial maiden strokes him through the silk, back arched, cum dripping into the water, a pair of shoes left on the sand"),
   "onani_m2":   ("robes", "floating alone above the floor of the robe hall, a borrowed sheer shawl wound around his wrist and waist, his fingers under the silk stroking his own chest, penis untouched, the celestial maiden watches from between the robe stands"),
   "inochi_m2":  ("stairs", "on the cloud stairway, he floats one step above the celestial maiden, " + HAGO + ", the celestial maiden rewinding the silk around his chest and waist, the coast tiny below, trembling"),
   "onedari_m2": ("gate", "passing through the glowing vermilion gate, he floats wrapped in sheer iridescent silk from chest to waist, the celestial maiden guides him by the silk end, her fingers under the silk stroking his side, dazed smile"),
   # コウカ 技3（天の口づけ＋羽衣の巻きつけ）
   "btl_m3":     ("river", "above the star bridge, the celestial maiden kisses him deeply, tongues, saliva trail, the tip of her hagoromo wrapped around his nipple, " + HAGO + ", cum drifting down toward the glowing river"),
   "onani_m3":   ("lotus", "floating alone above the lotus pond, drawing a strip of sheer cloth over his own nipple, lips parted waiting for a kiss, penis untouched, the celestial maiden watches from the moonlit water"),
   "inochi_m3":  ("peach", "under a blooming peach tree, the celestial maiden kisses him deeply, the tip of her hagoromo coiled on his nipple, a peach falling, pink petals, " + HAGO),
   "onedari_m3": ("music", "in the music pavilion, he rises toward the cloud ceiling locked in the celestial maiden's kiss, the tip of her hagoromo rolling his nipple, " + HAGO + ", incense smoke"),
   # リンカ（天の調べ／羽衣越しの）
   "btl_e1":     ("pine", "he floats above the pine needles, the celestial musician holds him from behind playing the sho beside his ear, licking his ear rim, his penis squeezed between her thighs through a sheer shawl, cum dripping"),
   "onani_e1":   ("teahouse", "sitting alone in the lamplit tatami room, a wet fingertip tracing deep into his own ear, head tilted listening, penis untouched, the celestial musician watches from outside the open shoji holding a sho"),
   "inochi_e1":  ("music", "in the music pavilion, he sits with his penis between the celestial musician's thighs through her shawl, the celestial musician plays the sho into his ear, drool, trembling"),
   "onedari_e1": ("stairs", "at the top of the cloud stairway, the celestial musician lays her lips on his ear with the sho beside it, her tongue in his ear, " + HAGO + ", his body arched"),
   # スイレン（袖の舞／舞いながら）NH・挿入なし
   "btl_e2":     ("beach", "on the sunset beach, the celestial dancer hugs his face into her cleavage with her very long sleeves over his eyes, her bare foot rubbing his penis, cum on her foot, he floats above the waves"),
   "onani_e2":   ("robes", "floating alone above piled silk in the robe hall, his face buried in folded cloth, a long cloth trailing over his cheek, rubbing his own chest, penis untouched, the celestial dancer watches from between the robe stands"),
   "inochi_e2":  ("stage", "at the center of the white dance stage, the celestial dancer twirls while holding his face in her cleavage inside her very long sleeves, his feet off the floor, dazed"),
   "onedari_e2": ("lotus", "above the moonlit lotus pond, the celestial dancer carries him wrapped in her very long sleeves, his face against her breasts, stroking his cheek with a sleeve, his eyes hidden, sleepy"),
   # フワリ（雲の抱擁／雲の上で）
   "btl_e3":     ("field", "he sinks deep into the cloud field, the cloud maiden hugs him with her breasts pressing on his face, her legs wrapped around his, cum on the fluffy clouds, cards falling through the clouds"),
   "onani_e3":   ("teahouse", "curled up alone in a fluffy down futon floating just above the tatami, sinking into it, rubbing his own chest, penis untouched, the cloud maiden watches from the window on a cloud"),
   "inochi_e3":  ("edge", "at the edge of the clouds, he lies asleep hugged like a body pillow by the cloud maiden, his face buried in her breasts, the pine coast far below through the gap"),
   "onedari_e3": ("hall", "he sinks into a cloud bed at the back of the palace hall, the cloud maiden clings to him with her breasts pressed on his face, her legs wrapped around his, cloud swirling over them, cum on the cloud"),
   # シュカ（玉の吐息／天への道＝NH逆アナル）
   "btl_boss":   ("gate", "from side, he lies on his back on the cloud before the vermilion gate with his legs lifted, the head court lady over him penetrating his anus with her own penis, anal, breathing glittering breath onto his lips, pinching his nipple, his own penis separate", PN),
   "onani_boss": ("chamber", "floating alone above the silk bedding, covering his face with his own scented palm, inhaling deeply, pinching his own nipple, penis untouched, the head court lady watches from the incense smoke"),
   "inochi_boss":("edge", "from side, at the edge of the clouds he lies on his back holding his knees, the head court lady penetrating his anus with her own penis, anal, breathing into his mouth, the pine coast far below, his own penis separate", PN),
   "onedari_boss":("chamber", "from side, he lies on his back on the thick silk bedding, the head court lady over him penetrating his anus with her own penis, anal, breathing onto his lips and pinching his nipple, " + HAGO + ", his own penis separate", PN),
 },
 "lose_desc": "carries him through the heavenly gate to live above the clouds forever.",
 "onanie": {
   "master": ("teahouse", "sitting on the tatami winding a thin cloth from his wrist around his chest and waist, fingers under the cloth stroking his skin, penis untouched"),
   "e1": ("teahouse", "sitting by the shoji listening to faint music, a wet fingertip tracing deep into his own ear, penis untouched"),
   "e2": ("robes", "brushing his cheek with a long silk sleeve, face half buried in folded silk, rubbing his own chest, penis untouched"),
   "e3": ("teahouse", "curled up in a fluffy down futon, sinking in, rubbing his own chest, penis untouched"),
   "boss": ("chamber", "covering his face with his own scented palm, inhaling, pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": (None, "peach", "a single large ripe celestial peach glowing softly on a branch, pink blossoms and petals around it"),
   "2": (None, "river", "an arched bridge of jade stone over the glowing milky way river of stars, soft light, clouds at both ends"),
   "3": ("m", "pine", "the celestial maiden lets her iridescent hagoromo shawl drift out through the pine grove like a floating ribbon trap, sly graceful smile"),
   "4": ("e3", "field", "the cloud maiden pats a soft round cloud bed beside her, inviting, sleepy smile"),
   "5": (None, "hall", "the celestial palace seen above the sea of clouds, vermilion gate, white pillars, golden light, peach blossoms drifting"),
 },
}
