# N95 炎の鍛冶場（Smith）画像データ。登場人物は全員20歳以上の成人。女性＋NH（スレイア・アグネッサ）。
# 炉の橙の光（warm orange forge light）の中、汗に濡れた肌。槌は金床だけを打つ（主人公の体は打たない）。火傷・火の粉の傷は描かない。
# 責め手はしなやかな腕（筋肉質にしない）。挿入はアグネッサ（NH・自分の体で、抱いたまま）だけ。スレイアは指だけ。
NH_PEN = {"pen": "penis"}
SMITHNEG = "burns, burn marks, sparks on skin, injury, muscular arms, abs, hammer hitting a person"
DATA = {
 "code": "Smith",
 "world": "blacksmith workshop in a volcanic forge town, warm orange forge light, glowing furnace, anvils and hammers, heat haze, sweat and steam, detailed background",
 "bg": "interior of a blacksmith workshop, glowing furnace with warm orange forge light, heavy anvil with a hammer resting on it, leather bellows, racks of tools, steam rising from a quenching tank",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "グンヒルダ",
         "tags": "adult woman, mature female, mature face, 36 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, master blacksmith, short red hair sticking to her sweaty forehead, gold eyes, sweat-soaked thin white shirt clinging to her skin, rolled-up sleeves, leather apron, sweaty glistening skin, hearty confident grin, huge breasts",
         "name": "the red-haired master smith in a leather apron",
         "pose": "resting a smithing hammer on her shoulder, wiping sweat from her brow, hearty confident grin, looking at viewer",
         "neg": SMITHNEG},
   "e1": {"type": "woman", "jp": "ティンカ",
          "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, long legs, blacksmith apprentice, orange twintails, green eyes, soot-smudged cheeks, soot-stained short work overalls, leather gloves, towel around her neck, cheerful grin, medium breasts",
          "name": "the orange-twintailed apprentice in soot-stained overalls",
          "pose": "puffing out her cheeks to blow, one gloved hand on her hip, cheerful grin, looking at viewer",
          "neg": SMITHNEG},
   "e2": {"type": "nh", "jp": "スレイア",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, slender, knife sharpener, shoulder-length grey hair, amber eyes, black work dress, waterproof apron, holding a whetstone, calm polite smile, medium breasts",
          "name": "the grey-haired sharpener in a black work dress",
          "pose": "holding a whetstone in both hands, head slightly bowed, calm polite smile, looking at viewer",
          "neg": SMITHNEG},
   "e3": {"type": "woman", "jp": "リンネ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, metal engraver, short green bob cut, purple eyes, magnifying goggles pushed up on her forehead, maroon vest, white shirt, dark short skirt, focused eager expression, medium breasts",
          "name": "the green-bobbed engraver with magnifying goggles",
          "pose": "holding a fine engraving tool up, goggles on her forehead, focused eager smile, looking at viewer",
          "neg": SMITHNEG},
   "boss": {"type": "nh", "jp": "アグネッサ",
            "tags": "adult woman, mature female, mature face, 35 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, forge mistress, long wavy black hair tied in a single low ponytail, red eyes, black leather work dress, long black gloves, gold bracelets, sultry smile, large breasts",
            "name": "the black-haired forge mistress with gold bracelets",
            "pose": "leaning against a pillar with arms folded under her breasts, gold bracelets gleaming, sultry smile, looking at viewer",
            "neg": SMITHNEG},
 },
 "places": {
   "ro": "in front of the roaring furnace, warm orange forge light, heat haze, sweat glistening",
   "kanadoko": "heavy iron anvil with a hammer resting on it, stone floor, warm orange forge light",
   "fuigo": "large leather bellows beside the forge, glowing orange coals, soot in the air",
   "choukin": "engraving workbench, magnifying lens on an arm, oil lamp, glittering brass dust",
   "togi": "sharpening station, wet whetstones, water trough, damp stone bench",
   "shinjo": "sleeping quarters behind the furnace, black fur rug, warm glow through the wall, gold bracelets on a shelf",
   "yakiire": "quenching water tank with rising steam, forge light reflected on the water",
   "sumi": "charcoal storeroom, piled sacks of charcoal, dim light, glowing embers",
   "yudono": "artisans' bathhouse, wooden tubs, thick steam, soap",
   "chouba": "smithy office, blank order sheets without text pinned on the wall, ledger, inkpot, oil lamp",
   "ido": "stone well behind the smithy at night, cool night wind, steam rising from warm skin",
   "yaneura": "hot attic drying loft, towels and leather aprons hanging on lines, warm dim air",
   "dougu": "aisle between tool racks, rows of hammers and files, oil lamp",
   "saka": "sloping cobblestone street of a forge town at dusk, chimney smoke, orange windows",
 },
 "atk": {
   "m1": ("ro", "he kneels before the furnace, the master smith hugs his head into her sweat-soaked shirt, his face buried between her huge wet breasts, steaming, warm orange forge light, dazed, trembling"),
   "m2": ("kanadoko", "he leans back against the anvil, the master smith pinches and rolls both of his nipples, a hammer resting on the anvil beside him, sweat glistening, confident grin, trembling"),
   "m3": ("yakiire", "beside the steaming quenching tank, the master smith kisses him deeply while her fingers trace the grooves of his ear, tongues, saliva trail, steam around them, dazed"),
   "e1": ("fuigo", "he sits by the bellows with his chest bare, the apprentice leans in blowing a long hot breath onto his nipple, cheeks puffed, coals glowing orange, no hands on him, trembling"),
   "e2": ("togi", "from side, he lies face down on the damp stone bench, the sharpener kneels beside him with two oiled fingers in his anus, fingering, steady strokes, calm face, whetstones beside"),
   "e3": ("choukin", "he sits at the engraving bench, the engraver with her goggles down holds his earlobe and traces the grooves of his ear with her fingertip, lamp light, focused face, trembling"),
   "boss": ("shinjo", "on the black fur rug, the forge mistress hugs him from behind pressing her breasts against his back, pinching both of his nipples, gold bracelets clinking, sultry smile"),
 },
 "atk_desc": {
   "m1": "the master smith steams him in her sweaty cleavage.",
   "m2": "the master smith reforges his nipples to the beat of the hammer.",
   "m3": "the master smith quenches him with a deep kiss.",
   "e1": "the apprentice blows on him like working the bellows.",
   "e2": "the sharpener hones him from behind with steady fingers.",
   "e3": "the engraver carves patterns into his ear with her fingertip.",
   "boss": "the forge mistress anneals him slowly in her embrace.",
 },
 "lose": {
   # グンヒルダ 技1（汗だくの胸）
   "btl_m1":     ("ro", "he kneels before the furnace with his face buried in the master smith's sweat-soaked cleavage, the master smith pinches his nipple, sweat dripping, warm orange forge light, cum on the floor"),
   "onani_m1":   ("yaneura", "standing alone in the hot attic with his face buried in a hanging leather apron, pinching his own nipple, sweat on his skin, penis untouched, the master smith watches from the attic stairs far away"),
   "inochi_m1":  ("chouba", "the master smith holds him against her sweaty chest, reading a blank estimate sheet without text over his head, pinching his nipple, his face in her cleavage, oil lamp"),
   "onedari_m1": ("yudono", "in the steamy bathhouse he kneels begging, the master smith presses his face into her sweat-soaked cleavage, pinching his nipple, a blank order sheet without text on the door, steam"),
   # グンヒルダ 技2（★鍛え直し）
   "btl_m2":     ("kanadoko", "he leans back against the anvil with his back arched, the master smith pinches and flicks both of his nipples, a hammer resting on the anvil, sweat glistening, cum on his belly"),
   "onani_m2":   ("ro", "sitting alone at a workbench tapping the table with one finger like a hammer beat, pinching his own nipple with the other hand, sweat, penis untouched, the master smith watches from beside the furnace far away"),
   "inochi_m2":  ("ido", "he sits on the rim of the well at night, the master smith stands behind him pinching both of his nipples, forge town lights far below, steam rising from his skin"),
   "onedari_m2": ("chouba", "he stands holding a blank order sheet without text, the master smith stands behind him rolling both of his nipples, oil lamp, flushed, trembling"),
   # グンヒルダ 技3（焼き入れ）
   "btl_m3":     ("yakiire", "beside the steaming quenching tank, the master smith kisses him deeply, her fingers in his ear, her other hand pinching his nipple, tongues, steam, cum on his thigh"),
   "onani_m3":   ("dougu", "standing alone between the tool racks, sucking two of his own fingers, the other hand tracing his own ear then pinching his own nipple, penis untouched, the master smith watches from the end of the aisle far away"),
   "inochi_m3":  ("sumi", "among the charcoal sacks lit by glowing embers, the master smith kisses him deeply, her fingers stroking his ear, pinching his nipple, saliva trail, dazed"),
   "onedari_m3": ("ro", "before the dying furnace, the master smith holds his face and kisses him deeply, her fingers in his ear, a blank order sheet without text pinned beside the furnace, flushed"),
   # ティンカ（★ふいごの息／金床の上で）
   "btl_e1":     ("fuigo", "he lies on his back on a sturdy workbench by the bellows, the apprentice sits on his hips grinding her bottom in soot-stained shorts on his penis, buttjob, leaning down to blow on his nipple, cum on her shorts"),
   "onani_e1":   ("yudono", "sitting alone in the steamy bathhouse with his chest bare, hands resting on the tub rim, breathing hard, flushed, hips twitching, penis untouched, the apprentice peeks from the doorway far away"),
   "inochi_e1":  ("sumi", "he sits on a charcoal sack, the apprentice leans in blowing a hot breath onto his neck and chest like fanning embers, soot smudge on his cheek, glowing embers"),
   "onedari_e1": ("kanadoko", "he lies on his back on a sturdy workbench before the anvil, the apprentice sits on his hips pressing her bottom on his penis, buttjob, blowing on his chest, a blank order sheet without text on the wall"),
   # スレイア（NH・★砥石の指／研ぎ汁の手）
   "btl_e2":     ("togi", "from side, he lies face down on the damp stone bench, the sharpener kneels beside him with two oiled fingers in his anus, fingering in steady strokes, calm face, cum dripping on the stone"),
   "onani_e2":   ("ido", "crouching alone by the well at night, one arm reaching behind with two of his own wet fingers in his own anus, knees trembling, penis untouched, the sharpener watches from the back door far away"),
   "inochi_e2":  ("dougu", "he stands bent over a tool rack shelf, the sharpener stands behind him with two slick fingers in his anus, her other slick hand stroking his penis, handjob, calm face"),
   "onedari_e2": ("chouba", "he lies face down over the office desk with a blank order sheet without text beside him, the sharpener stands behind him with two oiled fingers in his anus, fingering, calm face"),
   # リンネ（★彫金の細工／作業台の脚）
   "btl_e3":     ("choukin", "he lies on his back on the long engraving bench, the engraver sits astride his thighs squeezing his penis between her bare thighs, thighjob, bending to trace the grooves of his ear with her fingertip, cum on her thighs"),
   "onani_e3":   ("choukin", "sitting alone at the engraving bench at night, tracing the grooves of his own ear with a fingertip, oil lamp, magnifying lens, penis untouched, the engraver watches from the door far away"),
   "inochi_e3":  ("yudono", "he sits in a wooden tub in the steam, the engraver kneels beside the tub tracing the grooves of his wet ear with her fingertip, goggles on her forehead, dazed"),
   "onedari_e3": ("chouba", "he sits holding a blank sketch paper without text, the engraver stands beside him pinching his earlobe and tracing the grooves of his ear with her fingertip, focused face, trembling"),
   # アグネッサ（NH・★焼きなまし／鋼を打つ）
   "btl_boss":   ("shinjo", "from side, he lies on his side on the black fur rug, the forge mistress hugs him from behind penetrating his anus with her own penis, anal, pinching his nipple, gold bracelets, his own penis separate", NH_PEN),
   "onani_boss": ("ro", "sitting alone before the furnace with a warm blanket draped over his back, pinching both of his own nipples, penis untouched, the forge mistress watches from the far side of the furnace"),
   "inochi_boss":("yaneura", "from side, he lies on his side in the hot attic among hanging towels, the forge mistress hugs him from behind penetrating his anus with her own penis, anal, sweat, pinching his nipple, his own penis separate", NH_PEN),
   "onedari_boss":("kanadoko", "from side, he kneels before the anvil, the forge mistress kneels behind him hugging him tightly, penetrating his anus with her own penis, anal, pinching his nipple, his own penis separate", NH_PEN),
 },
 "lose_desc": "keeps him in the smithy forever as her forged steel, his chest swelling at every hammer beat.",
 "onanie": {
   "master": ("kanadoko", "sitting alone by the anvil tapping it with one finger like a hammer beat, pinching his own nipple with the other hand, penis untouched"),
   "e1": ("fuigo", "sitting alone by the bellows with his chest bare, hands resting on his knees, breathing hard, penis untouched"),
   "e2": ("togi", "lying alone on his side on the stone bench, two of his own wet fingers in his own anus, steady strokes, penis untouched"),
   "e3": ("choukin", "sitting alone at the engraving bench, tracing the grooves of his own ear with a fingertip, penis untouched"),
   "boss": ("shinjo", "sitting alone on the black fur rug with a warm blanket over his back, pinching his own nipples, penis untouched"),
 },
 "magic": {
   "1": ("m", "kanadoko", "the master smith swings a hammer down onto glowing iron on the anvil, sweat flying, confident grin"),
   "2": (None, "chouba", "a blank order sheet without text pinned to a wooden wall with a nail, inkpot and quill on a desk, oil lamp"),
   "3": (None, "ro", "a wave of shimmering heat haze rolling out of an open furnace mouth, glowing coals"),
   "4": ("e1", "fuigo", "the apprentice pumps a large leather bellows with both hands, coals flaring orange, cheerful grin"),
   "5": (None, "ro", "a roaring furnace fire burning bright orange, tongs and hammers hanging around it"),
 },
}
