# N100 スフィンクスの謎（Sphinx）画像データ。登場人物は全員20歳以上。女性のみ（挿入はアンクエスの黄金の張り型だけ）。
# 壁画・巻物・紋様・地図に文字は描かない。スフィンクスの獅子の部分は耳・尾・翼・手足の毛並みまで。アンクエスは健康的な肌の女王（干からびた姿にしない）。
ST = {"pen": "strapon"}   # アンクエスの黄金の張り型（白い革のハーネス・香油で指ほぐしの後）

DATA = {
 "code": "Sphinx",
 "world": "ancient royal tomb at the edge of a vast desert, sandstone halls, gold ornaments, murals without text, warm lamplight, drifting sand, detailed background",
 "bg": "great royal tomb gate at the edge of the desert at sunset, huge stone gate carved with gold patterns without text, long sunlit stone steps, sand dunes, orange sky",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ネフェルカ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, tall, long legs, voluptuous, sphinx, monster woman, dark skin, long blonde hair, red eyes, lion ears, lion tail with a soft tuft, large feathered wings, lion paws on hands and feet with soft paw pads, golden fur on forearms and lower legs, gold collar necklace, gold breast ornament, white loincloth, gold armlets, huge breasts",
         "name": "the blonde sphinx with lion ears and large wings",
         "pose": "sitting on a stone block with wings folded, one paw raised with a finger to her lips, arrogant smile, looking down at viewer",
         "neg": "quadruped, lion body, four legs, animal body, full lion, feral"},
   "e1": {"type": "woman", "jp": "ハトラ",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, egyptian priestess, black hair, blunt bob cut with gold hair ornaments, brown eyes, eyeliner, white linen dress, gold usekh collar, gold bracelets, holding a handheld oil jar, large breasts",
          "name": "the black-bobbed priestess in a white linen dress",
          "pose": "standing straight holding an oil jar in both hands, calm devout expression, looking at viewer"},
   "e2": {"type": "woman", "jp": "ルマル",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, sand spirit, long orange hair with hair tips crumbling into golden sand, amber eyes, thin sand-colored silk dress, gold anklets, barefoot, sand particles floating around her, large breasts",
          "name": "the orange-haired sand spirit in a sand-colored silk dress",
          "pose": "leaning forward and blowing a kiss of glittering sand, playful grin, looking at viewer"},
   "e3": {"type": "woman", "jp": "セシャ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, egyptian scribe, pink hair, bob cut, green eyes, leopard print shawl over the shoulders, white dress, reed pen, blank scroll without text, large breasts",
          "name": "the pink-bobbed scribe in a leopard-print shawl",
          "pose": "holding an unrolled blank scroll without text and a reed pen, caring smile, looking at viewer"},
   "boss": {"strap": "golden strap-on on a white leather harness", "type": "woman", "jp": "アンクエス",
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, long legs, voluptuous, mummy queen, healthy smooth tan skin, long purple hair, gold crown, gold eyes, elegant dress made of gold and white silk bandages, gold broad necklace, gold bracelets, huge breasts",
            "name": "the purple-haired mummy queen in a gold and white bandage dress",
            "pose": "standing with loose gold bandages floating around her, one hand extended, proud yet lonely smile, looking at viewer",
            "neg": "rotting, decayed, skull, skeleton, zombie, withered skin, dried skin, grey skin, bandaged face, horror, undead monster"},
 },
 "places": {
   "gate": "stone steps before the great tomb gate at sunset, gold patterns on the gate without text, hot desert wind, huge shadow of wings",
   "gold_chamber": "golden burial chamber, gold wall murals without text, flickering oil lamps, cool stone floor",
   "lair": "sphinx's sleeping chamber, large lion fur rug, cushions, myrrh incense burner, dim light",
   "purify": "priest's purification room, rows of oil jars, stone bathing basin, frankincense smoke, wet stone",
   "sand": "sand corridor inside the tomb, sand pouring endlessly from cracks in the ceiling, warm sand floor, torchlight",
   "scribe": "scribe's room, shelves of blank scrolls without text, reed pens and ink pots, low wooden desk, oil lamp",
   "coffin": "queen's coffin chamber, golden sarcophagus, piles of gold and white bandages, beeswax candles, myrrh smoke",
   "riddle": "riddle hall, round stone floor carved with patterns without text, very high ceiling, pillars, echoing dimness",
   "oasis": "desert oasis spring at night, cold water, palm trees, moon reflected on the water, damp sand",
   "tent": "expedition tent on the sand dunes at night, blankets, hanging lantern, canvas flapping in the wind",
   "guard": "tomb guards' quarters, gold necklaces hanging in a row on the wall, spear rack, hard stone bed",
   "treasury": "treasury vault, piles of gold coins and jewels, golden scales, dazzling lamplight",
   "terrace": "stargazing terrace on top of the tomb at night, starry sky, endless desert horizon, night wind",
   "canal": "underground waterway, dripping water, damp stone walls, narrow stone ledge, dim light",
 },
 "atk": {
   "m1": ("gate", "from above, he lies on his back on the stone steps, the sphinx sits above him pressing the soft paw pad of her foot on his crotch, footjob, her other paw foot on his chest, leaning down whispering into his ear, wings spread"),
   "m2": ("gold_chamber", "he sits on the cool stone floor wrapped in the sphinx's large wings, the sphinx leans in from behind licking the rim of his ear and whispering, her lips at his ear, no hands on his crotch, trembling, drool"),
   "m3": ("lair", "he kneels on the lion fur rug with his face buried in the sphinx's huge breasts, the sphinx holds his head to her chest, the soft tuft of her lion tail sweeping his nipple, wings folded around him"),
   "e1": ("purify", "he sits on the edge of the stone basin, the priestess stands beside him drawing circles of golden oil on his nipple with her fingertip, oil jar in her other hand, calm expression, glistening oiled chest"),
   "e2": ("sand", "he is buried to the waist in warm sand, the sand spirit crouches in front of him blowing a sweet breath onto his lips, glittering sand in her breath, no hands on him, dazed, drool"),
   "e3": ("scribe", "he sits on the scribe's lap, the scribe holds a blank scroll without text in one hand and kisses him deeply, tongues, saliva trail, her other hand on his cheek"),
   "boss": ("coffin", "he stands wrapped in soft gold and white silk bandages from toes to chest, his nipples showing through gaps, the mummy queen embraces him from behind rolling his nipple with her fingertips, beside the golden sarcophagus"),
 },
 "atk_desc": {
   "m1": "the sphinx treads on him with soft paw pads and whispers the answer.",
   "m2": "the sphinx whispers riddles and answers into his ears.",
   "m3": "the sphinx buries his face in her bosom and sweeps his nipples with her tail.",
   "e1": "the priestess anoints his nipples with fragrant oil.",
   "e2": "the sand spirit makes him breathe her sweet sandy breath.",
   "e3": "the scribe teaches him the answer mouth to mouth.",
   "boss": "the mummy queen seals him in golden bandages for a thousand years.",
 },
 "lose": {
   # ネフェルカ 技1（肉球の）
   "btl_m1":     ("gate", "he lies collapsed on the sunset stone steps, the sphinx sits on the step above pressing the soft paw pad of her foot on his crotch, footjob, her other paw pad covering his mouth, leaning down whispering into his ear, cum on her paw"),
   "onani_m1":   ("tent", "sitting alone on a blanket in the tent, rubbing the soles of his own feet together, one wet finger tracing inside his own ear, lips mouthing a riddle, penis untouched, the sphinx peeks in from the tent entrance far away, watching"),
   "inochi_m1":  ("riddle", "he kneels on the carved round stone floor staring at the patterns, the sphinx stands over him pressing her paw foot on his crotch, footjob, bending down whispering into his ear, cum on the carved floor"),
   "onedari_m1": ("lair", "he kneels on the lion fur rug, the sphinx reclines on cushions pressing the soft paw pad of one foot against his cheek, her other paw foot on his crotch, footjob, claw marks on the fur, smug smile, cum"),
   # ネフェルカ 技2（謎かけの囁き）
   "btl_m2":     ("gold_chamber", "he sits wrapped inside the sphinx's large wings, the sphinx pushes her tongue into his ear and whispers, her lips at his ear, no hands on his crotch, back arched, cum on the stone floor, drool"),
   "onani_m2":   ("canal", "kneeling alone on the wet stone ledge by the waterway, a wet finger pushed into his own ear, lips mouthing a riddle, hips twitching, penis untouched, the sphinx stands far behind in the dim tunnel with wings folded, watching"),
   "inochi_m2":  ("terrace", "he lies on his back on the terrace under the starry sky, one hand raised counting stars, the sphinx lies beside him licking his ear and whispering, her wing over him, no hands on his crotch, cum on his belly"),
   "onedari_m2": ("gate", "he kneels on the stone steps at sunset tilting his head to offer his ear, the sphinx sits above him holding his head with both paws, licking his ear and whispering, cum dripping on the step, trembling"),
   # ネフェルカ 技3（獅子の懐）
   "btl_m3":     ("lair", "he kneels on the lion fur rug with his face buried in the sphinx's huge breasts, the sphinx hugs his head, the tuft of her lion tail sweeping his nipples, her lips at his ear, cum on the fur rug"),
   "onani_m3":   ("oasis", "kneeling alone on the damp sand by the moonlit spring, his face buried in a rolled blanket, stroking his own nipple with the blanket tassel, penis untouched, the sphinx stands far across the water with wet wings, watching"),
   "inochi_m3":  ("treasury", "he kneels among gold coins with his face buried in the sphinx's huge breasts, the sphinx holds his head down, the tuft of her lion tail sweeping his nipple, golden scales beside them, cum on the gold coins"),
   "onedari_m3": ("tent", "he lies curled in the sphinx's lap inside the tent with his face buried in her huge breasts, a lion fur blanket over them, her wings wrapped around him, her tail tuft brushing his nipple, cum on the blanket"),
   # ハトラ（香油の指／儀式の）
   "btl_e1":     ("purify", "he sits on the edge of the stone basin, the priestess stands behind him rubbing golden oil onto his nipple with one fingertip, her other oiled hand stroking his penis, handjob, oil jar beside, cum, glistening chest"),
   "onani_e1":   ("guard", "sitting alone on the hard stone bed, drawing circles of golden oil on both of his own nipples with his fingertips, handheld oil jar by the pillow, penis untouched, the priestess stands far away at the doorway, watching"),
   "inochi_e1":  ("gold_chamber", "he kneels on the stone floor with his chest thrust out, the priestess kneels in front of him dripping golden oil from the jar onto his swollen nipple and circling it with her fingertip, oil running down, trembling, cum"),
   "onedari_e1": ("canal", "he sits on the stone ledge, the priestess pours a jar of golden oil over his chest and circles both nipples with her fingertips, empty oil jars lined up beside them, glistening skin, cum"),
   # ルマル（砂の吐息／砂に埋めて）
   "btl_e2":     ("sand", "he is buried to the waist in warm sand, the sand spirit presses her bare foot on the sand over his crotch and blows a sweet breath into his mouth, glittering sand in her breath, dazed, drool, cum staining the sand"),
   "onani_e2":   ("tent", "sitting alone in the tent pressing a sand-colored cloth over his nose and mouth with both hands, breathing in deeply, pile of sand on the floor, penis untouched, the sand spirit watches far away from the tent gap"),
   "inochi_e2":  ("oasis", "he is buried up to his chest in damp sand by the moonlit spring, the sand spirit lies on her stomach in front of his face blowing a single sand grain off his lips, no hands on him, dazed, drool"),
   "onedari_e2": ("terrace", "he kneels on the terrace in the night wind with his mouth open, the sand spirit holds his cheeks and exhales a sweet glittering breath into his mouth, an hourglass beside them, no hands on his crotch, cum"),
   # セシャ（答えの口移し／書記の膝）
   "btl_e3":     ("scribe", "he sits sideways on the scribe's lap, the scribe kisses him deeply, tongues, saliva trail, her raised knee rubbing his penis, kneejob, a blank scroll without text in her hand, cum on her knee"),
   "onani_e3":   ("riddle", "kneeling alone on the carved stone floor, sucking two of his own fingers deeply as if kissing, tongue wrapped around them, penis untouched, the scribe watches from far across the hall holding a blank scroll without text"),
   "inochi_e3":  ("treasury", "he sits among piles of gold holding an unrolled blank scroll without text, the scribe leans in kissing him deeply, tongues, saliva trail, more blank scrolls piled around, blush"),
   "onedari_e3": ("guard", "he sits on the stone bed, the scribe sits beside him holding his chin and kissing him deeply, tongues, saliva trail, blank paper tags without text pinned on the wall, gold necklaces hanging on the wall"),
   # アンクエス（千年の封印／黄金の張り型）
   "btl_boss":   ("coffin", "from side, he lies on his back beside the golden sarcophagus wrapped in gold bandages from toes to chest with legs lifted, the mummy queen kneels between his legs pegging his anus with her golden strap-on, anal, rolling his exposed nipple, his own penis separate, cum", ST),
   "onani_boss": ("gold_chamber", "sitting alone against the wall, thin cloth strips wrapped around his chest and arms, rolling his own nipples with his fingertips through the gaps, penis untouched, the mummy queen sits up in an open golden sarcophagus far away, watching"),
   "inochi_boss":("riddle", "from side, he lies on his back on the carved stone floor wrapped in gold bandages, a gold necklace around his neck, the mummy queen kneels between his legs pegging his anus with her golden strap-on, anal, hugging him, his own penis separate, cum", ST),
   "onedari_boss":("treasury", "from side, he lies on his back on gold coins wrapped in gold bandages up to his chest, the mummy queen over him pegging his anus with her golden strap-on, anal, rolling his nipple through a gap, his own penis separate, cum on the bandages", ST),
 },
 "lose_desc": "keeps him in the royal tomb forever as her gatekeeper.",
 "onanie": {
   "master": ("lair", "kneeling alone on the lion fur rug, one wet finger tracing inside his own ear, rubbing the soles of his feet together, whispering a riddle to himself, penis untouched"),
   "e1": ("purify", "sitting on the edge of the stone basin, drawing circles of golden oil on both of his own nipples with his fingertips, oil jar beside him, penis untouched"),
   "e2": ("sand", "sitting on warm sand holding a sand-colored cloth over his nose and mouth, breathing in deeply, no hands on his body, penis untouched"),
   "e3": ("scribe", "sitting on the floor sucking two of his own fingers deeply as if kissing, a blank scroll without text beside him, penis untouched"),
   "boss": ("coffin", "thin cloth strips wrapped around his chest and arms, rolling his own nipples with his fingertips through the gaps, penis untouched"),
 },
 "magic": {
   "1": ("m", "gold_chamber", "the sphinx holds up a glowing golden ankh in her paw, golden light spilling from it, wings spread, arrogant smile"),
   "2": (None, "tent", "an old treasure map on parchment with drawn paths and no text, spread on a blanket beside a compass, lantern light"),
   "3": (None, "gold_chamber", "trap of the burial chamber, a stone floor slab sinking, golden chains springing up, sand pouring down, glowing carved patterns without text"),
   "4": ("m", "riddle", "the sphinx sits on the carved round floor with one finger to her lips posing a riddle, glowing patterns without text around her, sly smile"),
   "5": ("boss", "coffin", "the mummy queen stands before the golden sarcophagus spreading her arms, gold bandages floating around her in the candlelight, the chamber glowing with golden light"),
 },
}
