# N92 四大精霊の泉（Spirit）画像データ。登場人物は全員20歳以上（精霊は見た目の年齢・成人）。女性＋ふたなり（ルサルカ・エーテリア）。
# 水と光は green and gold light で表す（青・水色は使わない）。溺れる・火傷の描写はしない。ふたなりの挿入は口づけしたまま・抱いたままの構図。
FUTA = {"pen": "penis"}      # ルサルカ（27cm・水のように滑らか）・エーテリア（24cm・四色の光の紋）の逆アナル
RINGS = "glowing rings of light stacked on his wrist"
DATA = {
 "code": "Spirit",
 "world": "enchanted spring deep in an ancient forest, green and gold light filtering through the leaves, water lilies, glittering green and gold water, mystical, detailed background",
 "bg": "enchanted forest spring, green and gold sunlight filtering through tall trees, calm clear water with white and pink water lilies, mossy rocks, soft grass on the shore",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ルサルカ",
         "tags": "adult woman, mature female, mature face, 32 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, water spirit goddess, very long flowing jade green hair drifting like water, gold eyes, white water lily hair ornament, layered sheer white and pale green veil dress like water droplets, gentle motherly smile, huge breasts",
         "name": "the jade-haired water goddess in a sheer veil dress",
         "pose": "standing ankle-deep in water, one hand reaching out gently, tender smile, looking at viewer"},
   "e1": {"type": "woman", "jp": "サラマンドラ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, fire spirit, long red hair with flickering flame-like tips, gold eyes, sheer red and orange layered dress, glowing ember-like markings on her skin, confident grin, large breasts",
          "name": "the red-haired fire spirit in a sheer red dress",
          "pose": "hand on hip, puffing a warm breath from her lips, playful confident grin, looking at viewer"},
   "e2": {"type": "woman", "jp": "ヴェントゥラ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, slender adult body, wind spirit, fluffy short blonde hair, green eyes, light white feathered robe like a celestial shawl, feather hair ornaments, mischievous smile, medium breasts",
          "name": "the blonde wind spirit in a white feather robe",
          "pose": "floating slightly above the ground, one finger on her lips, white feathers drifting, mischievous smile, looking at viewer"},
   "e3": {"type": "woman", "jp": "テラ",
          "tags": "adult woman, mature female, mature face, 28 years old, adult proportions, beautiful detailed eyes, long legs, voluptuous, earth spirit, long brown braid woven with moss and flowers, amber eyes, moss green dress, flower crown, soft gentle smile, huge breasts",
          "name": "the brown-braided earth spirit in a moss green dress",
          "pose": "holding a soft round ball of moss in both hands, head tilted, gentle droopy smile, looking at viewer"},
   "boss": {"type": "woman", "jp": "エーテリア",
            "tags": "adult woman, mature female, mature face, 35 years old, adult proportions, beautiful detailed eyes, long legs, tall, great elemental spirit, very long silver hair with metallic sheen, purple eyes, white and gold ceremonial robe, four floating rings of light in crimson, green, amber and jade around her, serene dignified expression, large breasts",
            "name": "the silver-haired great spirit in a white and gold robe",
            "pose": "standing tall with arms slightly open, four rings of light floating around her, serene smile, looking at viewer"},
 },
 "places": {
   "hotori": "shore of the forest spring, soft grass, clear water surface reflecting green and gold light, white water lilies",
   "hotori_night": "forest spring at night, moon reflected on the dark water, white water lilies glowing faintly, fireflies of gold light",
   "asase": "water lily shallows, knee-deep warm water, fine sand, white and pink water lilies, green and gold ripples",
   "naka": "middle of the spring, chest-deep water, gold light dancing on the surface, water lilies around",
   "soko": "underwater temple at the bottom of the spring, clear green-tinted water, pillars of green and gold light, fallen white marble columns, gentle air bubbles",
   "takitsubo": "bottom of a deep waterfall basin, green-tinted water, white sand, shafts of gold light from above, rising bubbles",
   "iwaba": "sun-warmed red rocks, dry air, heat haze, crackling campfire, orange sunset glow",
   "iwaba_oku": "hollow deep in the red rocks, warm stone walls glowing orange, heat shimmer",
   "takibi": "campfire on the spring shore at night, crackling flames, orange glow on the grass",
   "oka": "windy hilltop meadow, tall swaying grass, wide open sky, white feathers drifting on the breeze",
   "hora": "earth cave, walls covered in thick moss, amber lantern glow, tree roots hanging from the ceiling",
   "saidan": "white stone stage on an island in the spring, four floating rings of light in crimson, green, amber and jade, starry night sky",
   "taki": "grotto behind a waterfall, curtain of falling water, glittering spray mist, wet rocks, stone water basin",
   "kiri": "misty valley, thick milky white fog, glittering dew drops, faint trees",
   "koke": "mossy hollow in the forest, thick soft moss bed, tree root pillow, wildflowers, ferns",
   "taiju": "spring welling up between the huge roots of a giant tree, rustling leaves, green and gold light",
   "komichi": "narrow forest path between tall trees, fallen leaves, green and gold light",
   "yado_bath": "inn room at the edge of the forest at night, wooden bathtub with lukewarm water, fireplace glow, open window with night breeze",
   "yado": "inn room at the edge of the forest at night, wooden bed, crackling fireplace, open window with fluttering curtain and the moon outside",
   "tent": "camp tent by a clear stream at night, lantern light, damp grass, bedroll",
 },
 "atk": {
   "m1": ("asase", "he kneels in the knee-deep water, his face buried between the water goddess's huge breasts, sweet water welling from her cleavage over his lips, her arms cradling his head, gulping, trembling"),
   "m2": ("naka", "he stands chest-deep in the spring, the water goddess embraces him from the front, her arms and long jade hair dissolving into flowing glittering water wrapping his whole body, underwater fingertips stroking his nipples, dazed"),
   "m3": ("soko", "from side, underwater, he lies on his back on white marble, the water goddess lies over him kissing him deeply while penetrating his anus with her own penis, anal, flowing water wrapping them both, his own penis separate", FUTA),
   "e1": ("iwaba", "he lies on his back on the sun-warmed red rock, the fire spirit leans over his chest blowing a long hot breath onto his nipple, shimmering heat from her lips, no hands on him, flushed skin, trembling"),
   "e2": ("oka", "he lies in the tall swaying grass, the wind spirit lies beside him with her lips at his ear whispering, a swirling breeze and white feathers circling his ear, his back arched, trembling"),
   "e3": ("hora", "he lies on his back on a thick moss bed, the earth spirit sits beside him stroking his nipple in slow circles with a soft tuft of moss, gentle smile, amber lantern light, trembling"),
   "boss": ("saidan", "he kneels on the white stone stage, the great spirit holds his chin and kisses him deeply, her other hand pinching his nipple, one ring of light glowing on his wrist, tongues, saliva trail"),
 },
 "atk_desc": {
   "m1": "the water goddess lets him drink from the spring welling between her breasts.",
   "m2": "the water goddess immerses him in her body of water.",
   "m3": "the water goddess binds the pact at the bottom of the spring.",
   "e1": "the fire spirit blows a feverish breath over his skin.",
   "e2": "the wind spirit whispers into his ear on the breeze.",
   "e3": "the earth spirit strokes his nipples with soft moss.",
   "boss": "the great spirit seals the four-element pact with a kiss.",
 },
 "lose": {
   # ルサルカ 技1（湧き水の胸）
   "btl_m1":     ("asase", "he kneels in the knee-deep water, face buried in the water goddess's cleavage drinking the sweet water welling between her breasts, her water arms wrapping his whole body, " + RINGS + ", cum clouding the water"),
   "onani_m1":   ("yado_bath", "sitting alone in the wooden bathtub with lukewarm water up to his shoulders, face pressed into a wet pillow, one hand stroking his own chest, a water lily petal floating, penis untouched, the water goddess watches far away in the steam"),
   "inochi_m1":  ("taki", "he sits on the wet rocks behind the waterfall, the water goddess holds his face between her wet breasts, sweet water flowing from her cleavage into his mouth, twelve rings reflected in the stone basin, dazed"),
   "onedari_m1": ("hotori", "he kneels on the grass begging with his mouth open, the water goddess sits on the shore pressing his face into her deep cleavage, water lily engraved jade rings stacked up to his elbow, trembling"),
   # ルサルカ 技2（★泉に浸す）
   "btl_m2":     ("naka", "he floats chest-deep, the water goddess hugs him from behind, her body dissolving into glittering water enveloping him up to the neck, underwater fingers stroking his nipples and inner thighs, head tilted back, cum drifting in the water"),
   "onani_m2":   ("tent", "lying alone on his back in the shallow stream beside the tent, water flowing over his body, arms hugging himself, fingertips stroking his own chest, penis untouched, the water goddess watches far upstream"),
   "inochi_m2":  ("kiri", "he kneels in the thick milky fog, the fog gathers into the water goddess's arms hugging him from behind, drop-shaped patterns glowing on his skin, glittering dew on his body, dazed, trembling"),
   "onedari_m2": ("taiju", "he floats in the spring between the giant roots with water up to his chin, the water goddess holds him from behind swaying him slowly, carved water level lines without text on the stone rim, trembling"),
   # ルサルカ 技3（水底の契り・ふたなり）
   "btl_m3":     ("soko", "from side, underwater, he lies on his back on white marble between fallen columns, the water goddess lies over him kissing him deeply while penetrating his anus with her own penis, anal, flowing water wrapping him, rings up to his elbow, his own penis separate", FUTA),
   "onani_m3":   ("hotori_night", "standing alone waist-deep in the night spring, sucking two of his own fingers deeply as if kissing, the other hand stroking his own nipple, moon reflected around him, penis untouched, the water goddess watches from the far shore"),
   "inochi_m3":  ("takitsubo", "from side, underwater at the bottom of the waterfall basin, he lies on the white sand, the water goddess lies over him kissing him and breathing into his mouth while penetrating his anus with her own penis, anal, his own penis separate", FUTA),
   "onedari_m3": ("asase", "from side, he lies on his back on the sandy bed of the deeper shallows among water lilies, a water lily stem wound around his ankle, the water goddess over him kissing him deeply while penetrating his anus with her own penis, anal, his own penis separate", FUTA),
   # サラマンドラ（★火照りの吐息／燃える脚）
   "btl_e1":     ("iwaba", "he lies on the warm red rock, the fire spirit sits beside him pressing one warm bare foot on his penis, footjob, leaning down to blow a long hot breath on his nipple, crimson glow on his chest, cum on her foot"),
   "onani_e1":   ("yado", "sitting alone on the floor before the fireplace with his chest bare, hands resting on the floor behind him, breathing hard, flushed chest, hips twitching, penis untouched, the fire spirit watches from inside the fireplace flames far away"),
   "inochi_e1":  ("iwaba_oku", "he lies on his back in the warm rock hollow, the fire spirit's bare foot resting lightly on his chest holding him down, she bends to blow a hot breath on his neck, crimson rings on his wrist, flushed, trembling"),
   "onedari_e1": ("takibi", "he kneels by the campfire pushing his chest out begging, the fire spirit leans across and blows a long hot breath onto his nipple, crimson rings of light on his wrist, flushed skin, trembling"),
   # ヴェントゥラ（★そよ風の囁き／つむじ風の手）
   "btl_e2":     ("oka", "he lies pushed down in the tall grass, the wind spirit lies over his shoulder whispering and licking his ear rim, her hand wrapped in a swirling breeze stroking his penis, handjob, white feathers flying, cum on the grass"),
   "onani_e2":   ("yado", "sitting alone at the open window at night with his ear turned to the breeze, tracing his own ear rim with a fingertip, lips murmuring, curtain fluttering, penis untouched, the wind spirit watches from the moonlit sky far away"),
   "inochi_e2":  ("komichi", "the wind spirit carries him in her arms flying low over the forest path, her lips at his ear whispering, feather charms tied to branches, his legs dangling, dazed, trembling"),
   "onedari_e2": ("oka", "he sits on the hilltop with his head tilted, the wind spirit kneels behind him blowing a spiraling breeze into his ear, feathers swirling, pale green rings of light on his wrist, trembling"),
   # テラ（★苔の褥／大地の重み）
   "btl_e3":     ("hora", "he lies on his back on the moss bed, the earth spirit sits on his hips pressing her heavy bottom in the moss green dress onto his penis, buttjob, both hands stroking his nipples with soft moss, cum on the moss"),
   "onani_e3":   ("tent", "lying alone on the bedroll in the tent, rubbing his own nipple slowly with a round moss ball, lantern light, blush, penis untouched, the earth spirit watches from outside the tent flap far away"),
   "inochi_e3":  ("koke", "he lies asleep with his head on the earth spirit's lap in the mossy hollow, a blanket of moss over his legs, the earth spirit strokes his nipple with a tuft of moss, gentle smile, amber rings on his wrist"),
   "onedari_e3": ("taiju", "he lies on the giant tree roots with a root as his pillow, the earth spirit kneels beside him stroking both of his nipples with soft moss, falling leaves, blush, trembling"),
   # エーテリア（★四元の契り／虚空の器・ふたなり）
   "btl_boss":   ("saidan", "from side, he lies on his back on the white stone stage, the great spirit lies over him kissing him deeply while penetrating his anus with her own penis, anal, pinching his nipple, four rings of light glowing above, his own penis separate", FUTA),
   "onani_boss": ("yado", "sitting alone on the inn bed by the moonlit window, sucking two of his own fingers, the other hand pinching his own nipple, four colored rings glowing on his wrist, penis untouched, the great spirit watches from the moon far outside"),
   "inochi_boss":("saidan", "he kneels on the white stone stage in the middle of the spring, the great spirit holds him and kisses him deeply, pinching his nipple, crimson, green, amber and jade rings glowing in turn on his arm, saliva trail"),
   "onedari_boss":("hotori_night", "from side, he lies on his back on the grass of the night shore, the great spirit lies over him kissing him while penetrating his anus with her own penis, anal, four colored rings stacked on his arm, his own penis separate", FUTA),
 },
 "lose_desc": "keeps him by the spring forever as a servant of the spirits, twelve rings of light stacked up to his elbow.",
 "onanie": {
   "master": ("asase", "sitting alone sunk to his shoulders in the warm shallow water, arms hugging himself, stroking his own chest, water lilies around him, penis untouched"),
   "e1": ("iwaba", "lying alone on the warm red rock with his chest bare, hands resting beside him, breathing hard, flushed skin, hips twitching, penis untouched"),
   "e2": ("oka", "sitting alone in the tall grass with his ear turned to the wind, tracing his own ear rim with a fingertip, lips murmuring, penis untouched"),
   "e3": ("koke", "lying alone on the soft moss, rubbing his own nipple slowly with a round moss ball, penis untouched"),
   "boss": ("saidan", "kneeling alone on the white stone, sucking two of his own fingers, the other hand pinching his own nipple, colored rings glowing on his wrist, penis untouched"),
 },
 "magic": {
   "1": ("m", "hotori", "the water goddess scoops glowing spring water in her cupped hands, sweet water overflowing between her fingers, green and gold droplets sparkling, gentle smile"),
   "2": ("boss", "saidan", "the great spirit raises one open palm calling out, four rings of light in crimson, green, amber and jade spreading from her hand, serene face"),
   "3": (None, "kiri", "a thick bank of milky fog hanging over a narrow forest path, glittering dew drops, a faint jade ring of light hidden inside the fog"),
   "4": ("e2", "oka", "the wind spirit twirls playfully in midair, a spiraling breeze and white feathers around her, teasing wink"),
   "5": (None, "hotori", "the forest spring overflowing onto the grassy shore, water lilies, twelve glowing rings of light floating above the green and gold water"),
 },
}
