# N77 学園首席の練習台（Sylvia）画像データ。登場人物は全員20歳以上。学園は成人が通うカードマスターの学校（academy uniform・mature female）。
# 女性＋ニューハーフ（NH＝寮監ヘンリエッタ・実技主任オーレリア）。女装なし。練習台ノート・教科書・点呼簿は文字なし。
# 本編キャラ：シルヴィア（F26.png）・光の先導者（EU67.png）・聖盾の騎士（EU68.png）。本編の立ち絵は見られないので、本文の手がかり（学園の制服・学園一の胸・黒いストッキング／白い衣と掌の光／鎧と大盾）＋役に合う見た目。
NHP = {"pen": "penis"}   # ヘンリエッタ・オーレリアの逆アナル（指でほぐした後だけ）

DATA = {
 "code": "Sylvia",
 "world": "fantasy card master academy for adults, stone practice buildings, orange evening light after classes, detailed background",
 "bg": "empty practice hall of a fantasy academy for adults, polished wooden floor, a wall of full-length mirrors, orange sunset light through tall windows",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "シルヴィア", "canon": True, "canon_img": "F26.png",
         "tags": "adult woman, mature female, mature face, 21 years old, adult proportions, beautiful detailed eyes, tall, long legs, blonde hair, very long hair, hair ribbon, purple eyes, proud confident smile, academy uniform, white blouse, dark red blazer, pleated skirt, black pantyhose, huge breasts",
         "name": "the blonde academy ace in black pantyhose",
         "pose": "arms folded under her huge breasts, lifting them, proud smile, looking down at viewer"},
   "e1": {"type": "woman", "jp": "光の先導者", "canon": True, "canon_img": "EU67.png",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, white hair, long flowing hair, gold eyes, white robe with gold trim, white hood down, gentle smile, glowing orb of light in her palm, large breasts",
          "name": "the white-haired light guide in a white robe",
          "pose": "holding a small glowing orb of light in her open palm, gentle smile, looking at viewer"},
   "e2": {"type": "woman", "jp": "聖盾の騎士", "canon": True, "canon_img": "EU68.png",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, tall, long legs, orange hair, high ponytail, brown eyes, silver plate armor, white tabard, knee guards, large tower shield, stern expression, large breasts",
          "name": "the orange-haired shield knight in silver armor",
          "pose": "standing firmly behind a large tower shield, stern calm expression, looking at viewer"},
   "e3": {"type": "nh", "jp": "ヘンリエッタ",
          "tags": "adult woman, mature female, mature face, 30 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, reddish-brown hair, neat hair bun, green eyes, black long dress, white collar, ring of keys at her waist, strict gentle smile, large breasts",
          "name": "the reddish-brown-haired dorm warden in a black long dress",
          "pose": "holding a roll book without text to her chest, a ring of keys at her waist, strict gentle smile, looking at viewer"},
   "boss": {"type": "nh", "jp": "オーレリア",
            "tags": "adult woman, mature female, mature face, 36 years old, adult proportions, beautiful detailed eyes, very tall, elegant, feminine body, long legs, black hair, very long straight hair, red eyes, white instructor robe over a black tight dress, black pointer stick, cool expression, large breasts",
            "name": "the black-haired chief instructor in a white robe",
            "pose": "holding a black pointer stick, one hand on her hip, calm lecturing expression, looking at viewer"},
 },
 "places": {
   "drill": "practice hall of an academy for adults, polished wooden floor, a wall of full-length mirrors",
   "private": "small private practice room, a long couch and one desk, orange sunset light through curtains",
   "inn": "simple inn room, a single wooden chair and a bed, morning light",
   "lecture": "tiered lecture hall, teacher's podium, blackboard without text, chalk dust, orange evening light",
   "library": "library reading seats, old books, shadows of tall bookshelves, hushed silence",
   "armory": "shield storage armory, rows of shields on racks, cold stone walls, a line drawn on the stone floor",
   "arena": "circular sand practice arena, stone spectator seats, faint glowing summoning circle marks, sunset",
   "corridor": "dark dormitory corridor after lights-out, a small night lamp, closed doors",
   "warden": "dormitory warden's office, roll book without text on the desk, rows of keys on wall hooks, steaming teacup",
   "sylroom": "tidy dormitory room, neat bookshelf, bed with white sheets, a stack of blank schedule papers without text on the desk",
   "locker": "academy locker room, rows of lockers, long bench, humid air from the baths",
   "roof": "rooftop of the practice building at sunset, spires, cold metal railing",
   "chapel": "chapel of light, pillars of light from high windows, white stone floor, stone columns",
   "lab": "chief instructor's study, piles of textbooks, leather couch, blackboard without text, ink bottle",
   "guest": "small dark dormitory guest room, bed against the wall, thick futon, thin light from the door gap",
 },
 "atk": {
   "m1": ("private", "he lies on the long couch, the academy ace kneels over his hips with her blouse unbuttoned, squeezing his penis between her huge breasts and rubbing them left and right alternately, paizuri, an open textbook without text beside her"),
   "m2": ("drill", "he kneels on the wooden floor before the mirrors, the academy ace stands over him with her blouse open, lifting and swaying her huge breasts right before his face, no hands on him, his reflection dazed"),
   "m3": ("drill", "he lies face down on the wooden floor, the academy ace lies on his back hugging him from behind, her huge breasts pressed on his back, his penis clamped between her black pantyhose thighs, thighjob"),
   "e1": ("chapel", "he kneels in a pillar of light, dazed, the light guide holds a glowing orb of light before his eyes, his gaze following it, no hands on him, mouth open, trembling"),
   "e2": ("armory", "he is pinned between the knight's large tower shield at his back and the shield knight's armored chest, hug, her arms locking him in, no way out, trembling"),
   "e3": ("warden", "he sits on a hard chair beside the desk, the dorm warden leans in from behind whispering into his ear and licking the rim of his ear, ear licking, a roll book without text on the desk, flushed"),
   "boss": ("lecture", "he sits on the teacher's podium, the chief instructor kisses him deeply, tongues, her fingers rolling both his nipples, calm lecturing face, blackboard without text"),
 },
 "atk_desc": {
   "m1": "the academy ace gives him a by-the-textbook paizuri.",
   "m2": "the academy ace sways her breasts before his eyes: basic technique.",
   "m3": "the academy ace pins him down with her pantyhose thighs.",
   "e1": "the light guide leads his mind away with her light.",
   "e2": "the shield knight locks him in a cage of shield and breasts.",
   "e3": "the dorm warden takes roll call in his ear after lights-out.",
   "boss": "the chief instructor gives a model demonstration on him.",
 },
 "lose": {
   # シルヴィア 技1（教科書どおりのパイズリ）
   "btl_m1": ("private", "he lies on the long couch, the academy ace kneels over his hips with her blouse open, squeezing his penis between her huge breasts, paizuri, cum on her cleavage, an open textbook without text, thin gold lines on his inner thigh"),
   "onani_m1": ("library", "sitting alone at a reading desk staring at an open book without text, hands gripping his knees, knees trembling, penis untouched, the academy ace watches far behind a bookshelf holding a dark green notebook"),
   "inochi_m1": ("inn", "he lies on the bed in the morning light, the academy ace kneels between his legs squeezing his penis between her huge breasts, paizuri, rubbing left and right, cum on her chest"),
   "onedari_m1": ("lecture", "he sits on the teacher's podium, the academy ace kneels before him reading from an open textbook without text while squeezing his penis between her huge breasts, paizuri, a bookmark in the book"),
   # シルヴィア 技2（★基本技術）
   "btl_m2": ("drill", "he kneels on the wooden floor before the mirrors, the academy ace bounces her huge breasts against his cheek, blouse open, no hands on him, cum on the floor, his dazed reflection in the mirror"),
   "onani_m2": ("roof", "standing alone gripping the rooftop railing with both hands, mouth open, hips twitching, penis untouched, the academy ace stands far away in the sunset swaying her breasts, watching"),
   "inochi_m2": ("sylroom", "he sits on the white sheets, the academy ace kneels before him unbuttoning her blouse and lifting her huge breasts, no hands on him, cum on the sheets, blank schedule papers without text on the desk"),
   "onedari_m2": ("arena", "he sits alone in the front row of the stone spectator seats, the academy ace stands in the middle of the sand arena swaying her huge breasts, no hands on him, cum on his thigh, sunset"),
   # シルヴィア 技3（体術の押さえ込み）
   "btl_m3": ("drill", "he lies face down on the wooden floor, the academy ace lies on him from behind, her huge breasts pressed on his back, his penis clamped between her black pantyhose thighs, thighjob, cum on her pantyhose"),
   "onani_m3": ("locker", "sitting alone on the long bench, pressing his own inner thighs together with his knees, a folded bundle of black pantyhose beside him, hands on the bench, penis untouched, the academy ace sits far away crossing her legs, watching"),
   "inochi_m3": ("armory", "he lies on his back on the stone floor on a drawn line, the academy ace stands over him pressing his penis with her black pantyhose foot, footjob, looking down, cum on her foot"),
   "onedari_m3": ("lab", "he sits on the leather couch, the academy ace hugs him tightly from the side, her huge breasts pressed on his cheek, his penis clamped between her black pantyhose thighs, thighjob, cum dripping"),
   # 光の先導者（★導きの光）
   "btl_e1": ("chapel", "he kneels in a pillar of light with his back arched, the light guide stands before him closing her palm to put out the orb of light, no hands on him, dazed, cum on the white stone floor"),
   "onani_e1": ("inn", "sitting alone on the wooden chair staring at the lamp light, hands resting on his knees, dazed, mouth open, penis untouched, the light guide stands far away by the window, watching"),
   "inochi_e1": ("drill", "he stands before the full-length mirrors, the light guide stands beside him letting tiny glowing particles of light fall on his chest and belly, no hands on him, dazed, cum dripping"),
   "onedari_e1": ("lecture", "he sits in the dark back row of the lecture hall, the light guide holds a glowing orb close to his face, her other hand stroking his penis, handjob, a white armband on his arm"),
   # 聖盾の騎士（★盾の檻）
   "btl_e2": ("armory", "he is pinned between the large tower shield at his back and the shield knight's armored chest, hug, her bare knee pressing up at his crotch, kneejob, cum dripping, rows of shields"),
   "onani_e2": ("guest", "pressed alone between the wall and a thick futon, one hand stroking his own chest, trembling, penis untouched, the shield knight watches far away in the doorway holding a small shield"),
   "inochi_e2": ("arena", "he sits in the sand inside four tower shields standing around them like a cage, the shield knight holds him tight against her armored chest, hug, no hands on his crotch, cum on the sand"),
   "onedari_e2": ("chapel", "he is pressed between a stone column and the shield knight's tower shield, the shield knight holds the shield against him, her bare knee pressing his crotch, kneejob, pillars of light"),
   # ヘンリエッタ（★消灯後の見回り／門限破りの罰・NH）
   "btl_e3": ("warden", "from side, he lies bent over the desk beside the roll book without text, the dorm warden stands behind him penetrating his anus with her own penis, anal, whispering into his ear, his own penis separate, keys on the wall", NHP),
   "onani_e3": ("guest", "lying alone on the bed in the dark, tracing the rim of his own ear with a wet fingertip, the other hand on the sheet, penis untouched, the dorm warden stands far away in the doorway with a ring of keys, watching"),
   "inochi_e3": ("guest", "he lies on the hard bed in the dark, the dorm warden sits on the bed edge leaning over him licking his ear, whispering, a key in his hand, trembling, cum on the sheet"),
   "onedari_e3": ("warden", "from side, he lies on his back on the carpet with legs lifted, the dorm warden kneels between his legs penetrating his anus with her own penis, anal, whispering into his ear, his own penis separate, steaming teacup", NHP),
   # オーレリア（★模範演技／教本の最終章・NH）
   "btl_boss": ("lecture", "from side, he lies on his back on the teacher's podium with legs lifted, the chief instructor penetrates his anus with her own penis, anal, kissing him deeply, rolling his nipples, his own penis separate, blackboard without text", NHP),
   "onani_boss": ("lab", "sitting alone on the leather couch before the blackboard without text, sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched, the chief instructor watches far away at the door"),
   "inochi_boss": ("private", "he lies on the long couch in the sunset, the chief instructor stands beside him pointing the tip of her black pointer stick just short of his nipple, no hands on him, cum on his belly"),
   "onedari_boss": ("lecture", "from side, he lies on his back on the front-row long desk, the chief instructor penetrates his anus with her own penis, anal, kissing him deeply, pinching his nipple, his own penis separate, a red bookmark in an open textbook", NHP),
 },
 "lose_desc": "keeps him at the academy after classes forever as a practice dummy.",
 "onanie": {
   "master": ("drill", "kneeling before the mirrors with both hands resting on his thighs, staring into space, imagining swaying breasts, mouth open, hips twitching, penis untouched"),
   "e1": ("inn", "sitting on the chair staring into the lamp light, hands resting on his knees, no hands on his body, dazed, penis untouched"),
   "e2": ("guest", "pressed between the wall and a thick futon, one hand stroking his own chest, penis untouched"),
   "e3": ("guest", "lying in the dark, tracing the rim of his own ear with a wet fingertip, mouth open, penis untouched"),
   "boss": ("lab", "sitting on the leather couch, sucking two of his own fingers as if kissing, the other hand pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "drill", "standing before the mirrors holding an open textbook without text, one hand lifting her huge breasts, confident smile"),
   "2": (None, "lab", "a thick practice textbook without text lying open on a desk, a ribbon bookmark"),
   "3": ("m", "drill", "leaning forward, her huge breasts swaying in her unbuttoned blouse, teasing smile"),
   "4": ("m", "private", "sitting on the long couch after class, crossing her legs in black pantyhose, beckoning with one finger, proud smile"),
   "5": (None, "lab", "a closed dark green notebook without text and a thin gold pen on a desk"),
 },
}
