# N88 茶室の家元（Tea）画像データ。登場人物は全員20歳以上。女性のみ（女装なし）。挿入はカヅラのペニバン（一期一会）だけ。掛け軸は文字なし。
DATA = {
 "code": "Tea",
 "world": "quiet traditional japanese tea house in an otherworldly old capital, tatami, shoji paper screens, soft dim light, detailed background",
 "bg": "interior of a small four-and-a-half tatami tea room, sunken hearth with an iron kettle giving off steam, blank hanging scroll without text in the tokonoma alcove, shoji screens with soft light, tea utensils",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "ミナセ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, tall, long legs, voluptuous, black hair, very long hair tied low at the nape, red eyes, red lipstick, wisteria purple plain silk kimono, white obijime cord, tea ceremony master, huge breasts",
            "name": "the black-haired tea master in a wisteria kimono",
            "pose": "kneeling in seiza, holding a purple silk fukusa cloth, calm gentle smile, looking at viewer"},
   "e1":   {"type": "woman", "jp": "コトネ",
            "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, bob cut, blunt bangs, brown eyes, light green practice kimono, white tabi, tea ceremony apprentice, medium breasts",
            "name": "the brown-bob apprentice in a light green kimono",
            "pose": "kneeling in seiza, holding a bamboo tea whisk, earnest polite smile, looking at viewer"},
   "e2":   {"type": "woman", "jp": "アオイ",
            "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, elegant updo, purple eyes, pale pink houmongi kimono, holding a small lacquered incense case, large breasts",
            "name": "the pink-haired hostess in a pale pink kimono",
            "pose": "standing gracefully, sleeve raised to her lips, mischievous smile, looking at viewer"},
   "e3":   {"type": "woman", "jp": "ハギ",
            "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, braided bun, gold eyes, white work coat over kimono, apron, tasuki sash tying up her sleeves, confectioner, large breasts",
            "name": "the purple-haired confectioner in a white work coat",
            "pose": "standing, wiping her hands on her apron, expressionless calm face, looking at viewer"},
   "boss": {"strap": "black lacquered strap-on on a black silk cord harness", "type": "woman", "jp": "カヅラ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 46 years old, adult proportions, beautiful detailed eyes, very tall, long legs, voluptuous, white hair, long hair in a tall updo, gold eyes, gray kimono, black haori coat, grand tea master, huge breasts",
            "name": "the tall white-haired grand master in a black haori",
            "pose": "standing with arms folded in her sleeves, serene knowing smile, looking at viewer"},
 },
 "places": {
   "chashitsu": "four-and-a-half tatami tea room, sunken hearth with an iron kettle, blank hanging scroll without text in the alcove, shoji with soft light, rows of tea bowls on the tatami",
   "nijiri":    "small low crawl-in door of a tea house, wooden threshold, sword rack shadow, moss outside",
   "roji":      "tea garden path, mossy stepping stones, stone water basin with a bamboo ladle, wet green leaves, stone lantern",
   "machiai":   "garden waiting arbor, long wooden bench, bamboo blinds, bamboo deer scarer by a pond",
   "mizuya":    "tea preparation room, shelves of tea utensils, bamboo slatted drain floor, damp tea cloths, water jar",
   "keiko":     "tea practice hall, wooden floor and tatami, rows of zabuton cushions, sliding doors",
   "kashi":     "japanese confectioner's workshop, wooden work table, pot of white bean paste, carved wooden sweets molds, glass jar of clear kuzu syrup, zabuton",
   "kou":       "incense room, incense burner with white ash, thin rising smoke, lacquered incense case, dim light",
   "inkyo":     "grand master's retreat, sunken hearth with glowing charcoal, black haori on a kimono rack, polished old pillars",
   "yobanashi": "inner tatami room at night, a single short candle lamp, hearth glowing, deep shadows",
   "engawa":    "polished wooden veranda at night, garden under the moon, shoji behind",
   "kura":      "tea utensil storehouse, shelves of paulownia wood boxes, cool earthen walls, dim light",
   "ishidan":   "stone steps before the tea house gate at dusk, stone lanterns, sloping path, the tea room light behind",
 },
 "atk": {
   "m1": ("chashitsu", "he kneels in seiza on the tatami, the tea master kneels close beside him, her lips sealing his mouth feeding him thick matcha, her hand wrapping his penis in a purple silk fukusa and stroking it, trembling"),
   "m2": ("chashitsu", "he kneels in seiza with his face tilted up, the tea master holds his chin and kisses him mouth to mouth, green thick matcha flowing from her lips into his, tongues, a tea bowl on the tatami"),
   "m3": ("chashitsu", "he lies on his back with his head on the tea master's lap as she kneels in seiza, the tea master leans down licking his ear, her hands inside her sleeves pinching both his nipples, back arched"),
   "e1": ("keiko", "he kneels in seiza with his chest pushed out, the apprentice kneels in front of him brushing his nipple rapidly with the wet tips of a bamboo tea whisk, froth on his nipple, trembling"),
   "e2": ("kou", "he kneels before an incense burner, the hostess leans close holding the incense case and blows sweet incense-scented breath onto his neck and ear, thin smoke curling, no hands on him, flushed"),
   "e3": ("kashi", "from side, he lies face down on a zabuton on the work table with his hips raised, the confectioner stands behind him with two syrup-wet fingers in his anus, fingering, a jar of kuzu syrup beside"),
   "boss": ("inkyo", "he kneels in seiza before the glowing hearth, the grand master kneels behind him wrapping him inside her black haori in a tight embrace, her breasts pressed against his back, pinching his nipples"),
 },
 "atk_desc": {
   "m1": "the tea master purifies him with her silk fukusa.",
   "m2": "the tea master feeds him thick tea mouth to mouth.",
   "m3": "the tea master gives him her lap as a pillow.",
   "e1": "the apprentice whisks his nipples like frothing tea.",
   "e2": "the hostess lets him listen to incense on her breath.",
   "e3": "the confectioner kneads him like a sweet.",
   "boss": "the grand master embraces him for the opening of the hearth.",
 },
 "lose": {
   # ミナセ 技1（袱紗さばき）
   "btl_m1":     ("chashitsu", "he kneels in seiza holding out an empty tea bowl with both hands, twelve tea bowls lined up on the tatami, the tea master kisses him feeding him thick matcha, a cum-soaked purple fukusa folded at her obi"),
   "onani_m1":   ("mizuya", "kneeling alone in seiza behind the utensil shelf, wiping his own bare chest with a folded hand towel like a fukusa, sucking his own fingers, penis untouched, the tea master stands at the far doorway watching"),
   "inochi_m1":  ("ishidan", "he sits collapsed on the stone steps at dusk, a gift box wrapped in purple fukusa on his lap, the tea master kneels beside him untying the knot and kissing him mouth to mouth, trembling"),
   "onedari_m1": ("yobanashi", "he kneels in seiza under the single candle lamp, a blank menu book without text open on the tatami, the tea master kneels close stroking his penis wrapped in purple silk fukusa, cum on the silk"),
   # ミナセ 技2（濃茶の口移し）
   "btl_m2":     ("chashitsu", "he kneels in seiza clutching a tea bowl with a red lipstick mark on its rim, mouth open waiting, the tea master brings her lips just above his, twelve tea bowls on the tatami, cum on the tatami"),
   "onani_m2":   ("mizuya", "kneeling alone in seiza in the preparation room, a lukewarm tea bowl beside him, sucking two of his own fingers deeply with green tea dripping from his lips, penis untouched, the tea master watches from the doorway"),
   "inochi_m2":  ("machiai", "he sits on the long bench of the waiting arbor, the tea master holds his face and melts a dry sweet into his mouth with a deep kiss, tongues, saliva trail, blank register paper without text on the bench"),
   "onedari_m2": ("yobanashi", "he kneels in seiza under the candle lamp with his mouth open, the tea master kisses him long and deep, thick matcha flowing mouth to mouth, green trail on his chin, tea bowl on a tray"),
   # ミナセ 技3（正座の膝枕）
   "btl_m3":     ("chashitsu", "he lies on his back beside the hearth with his head on the kneeling tea master's lap, holding up an empty tea bowl, the tea master bends down feeding him matcha mouth to mouth, her hand in her sleeve on his nipple, cum on his belly"),
   "onani_m3":   ("engawa", "lying alone on his back on the moonlit veranda, tracing his own ear with one finger, pinching his own nipple with the other hand, penis untouched, the tea master kneels far down the veranda watching"),
   "inochi_m3":  ("yobanashi", "he lies sleepily with his head on the kneeling tea master's lap, the tea master bends down kissing him mouth to mouth, her sleeve over his chest pinching his nipple, drowsy, trembling"),
   "onedari_m3": ("yobanashi", "he lies with his head on the kneeling tea master's lap, the tea master licks his right ear and pinches both his nipples under her sleeves, a tea bowl by the pillow on a blank folded paper without text"),
   # コトネ（茶筅の穂先）
   "btl_e1":     ("keiko", "he kneels on a zabuton arching his back and pushing out his chest, the apprentice kneels before him whisking his nipple with a bamboo tea whisk, froth on his chest, cum on the cushion, a tea bowl held out in his hands"),
   "onani_e1":   ("mizuya", "kneeling alone in seiza by the utensil shelf, brushing his own nipple rapidly with a soft calligraphy brush tip, back arched, penis untouched, the apprentice watches from the far doorway"),
   "inochi_e1":  ("roji", "he kneels on the mossy stepping stones by the stone water basin, the apprentice kneels before him tracing his nipple with the dripping tip of a tea whisk, trembling, night"),
   "onedari_e1": ("keiko", "he kneels on a zabuton with his chest out, the apprentice whisks matcha in a bowl right beside his ear, his nipples stiff, cum on the cushion, a blank practice schedule without text on the wall"),
   # アオイ（香を聞く）
   "btl_e2":     ("kou", "his face buried in the hostess's chest at the opened collar of her kimono, the hostess blows sweet incense breath over his hair, the incense burner smoking, no hands on his crotch, cum on the tatami"),
   "onani_e2":   ("mizuya", "kneeling alone in seiza with hands on his knees, leaning over a small incense burner breathing in the smoke deeply, hips floating, penis untouched, the hostess watches from the far doorway with her sleeve over her lips"),
   "inochi_e2":  ("ishidan", "he sits on the stone steps at dusk clutching a small incense pouch, the hostess leans over him blowing sweet breath into his ear, no hands on him, flushed, trembling"),
   "onedari_e2": ("machiai", "he sits on the long bench, the hostess holds his face with both hands and blows white incense smoke from her lips onto his lips, smoke drifting over his chest, cum on the bench"),
   # ハギ（練り切りの指）
   "btl_e3":     ("kashi", "from side, he kneels on a zabuton on the work table with his hips raised, the confectioner stands behind him with two syrup-wet fingers deep in his anus pressing his prostate, her other hand on her knee, cum dripping"),
   "onani_e3":   ("mizuya", "kneeling alone on all fours on the slatted floor, one arm reaching behind with two of his own wet fingers in his own anus, penis untouched, the confectioner watches expressionless from the far doorway"),
   "inochi_e3":  ("machiai", "he kneels on all fours on a zabuton on the bench, the confectioner holds his hips with two fingers in his anus pressing up, a gift box of sweets with a blank menu slip without text beside"),
   "onedari_e3": ("kashi", "from side, he is on all fours on a zabuton with his hips raised, the confectioner with two fingers deep in his anus, fingering, carved wooden molds on the shelf, blank menu paper without text on the pillar, cum dripping"),
   # カヅラ（炉開きの抱擁／一期一会）
   "btl_boss":   ("inkyo", "from side, he is on all fours before the glowing hearth, the grand master kneels behind him with her black haori over them both pegging his anus with a black lacquered strap-on, anal, reaching around pinching his nipples, his own penis separate", {"pen": "strapon"}),
   "onani_boss": ("keiko", "kneeling alone in seiza with a black haori draped over his own shoulders, pinching both his own nipples, penis untouched, the grand master watches from the far doorway"),
   "inochi_boss":("kura", "he kneels between shelves of paulownia boxes, the grand master kneels behind him wrapping him in her black haori, her arms around his chest pinching his nipples, charcoal-stained hands, cum on the floor"),
   "onedari_boss":("yobanashi", "from side, he kneels by the hearth under the candle lamp, the grand master hugs him from behind inside her haori pegging his anus with a black lacquered strap-on, anal, pinching his nipple, his own penis separate", {"pen": "strapon"}),
 },
 "lose_desc": "keeps him in the tea house as a live-in disciple forever.",
 "onanie": {
   "master": ("chashitsu", "kneeling in seiza, holding a tea bowl to his lips, sucking two of his own fingers with green tea dripping, the other hand wiping his chest with a folded cloth, penis untouched"),
   "e1": ("keiko", "kneeling in seiza with his chest out, brushing his own nipple rapidly with a soft brush tip, penis untouched"),
   "e2": ("kou", "kneeling in seiza with both hands on his knees, leaning over an incense burner breathing the smoke deeply, no hands on himself, penis untouched"),
   "e3": ("kashi", "on all fours on a zabuton, reaching behind with two of his own syrup-wet fingers in his own anus, penis untouched"),
   "boss": ("inkyo", "kneeling in seiza before the hearth with a black haori draped over his shoulders, pinching both his own nipples, penis untouched"),
 },
 "magic": {
   "1": ("m", "chashitsu", "kneeling in seiza and holding out a fresh bowl of thick green tea with both hands, steam rising, another serving"),
   "2": (None, "chashitsu", "a folded blank invitation letter without text on a lacquered tray beside a tea bowl, wisteria sprig"),
   "3": (None, "nijiri", "the tiny crawl-in door of the tea house half open, silk cords hanging from the lintel like a snare, shadows inside"),
   "4": ("boss", "keiko", "kneeling in perfect seiza on the tatami, demonstrating formal posture, one hand raised in instruction, serene smile"),
   "5": (None, "engawa", "an iron tea kettle steaming on a brazier on the veranda under the full moon, tea bowl beside, autumn grass"),
 },
}
