# N83 天狗の山（Tengu）画像データ。登場人物は全員20歳以上。女性＋ふたなり（アマギリ・オボロ）。女装なし。
# 天狗は赤い顔・長い鼻にしない（翼・一本歯の高下駄・羽団扇・山伏装束で天狗らしさを出す）。地図・札・行者帳は文字なし。
PEN = {"pen": "penis"}
TNEG = "red face, long nose, tengu mask, mask, beak"
DATA = {
 "code": "Tengu",
 "world": "misty sacred mountain of the tengu, towering cedar forest, drifting fog, vermilion shrine gates, moss, wind blowing, detailed background",
 "bg": "mountaintop shrine of the tengu in thick mist, vermilion torii gate, shimenawa rope, white gravel, towering cedars, sea of clouds below",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "アマギリ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, long legs, tall, tengu, large white feathered wings, white hair, very long hair, gold eyes, loosely worn white and vermilion yamabushi robes, tokin cap, one-toothed tall geta, holding a large white feather fan, large breasts",
         "name": "the white-haired great tengu with white wings",
         "pose": "standing on tall one-toothed geta fanning with a large white feather fan, wings spread, relaxed haughty smile, looking at viewer",
         "neg": TNEG},
   "e1": {"type": "woman", "jp": "クロハ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, long legs, crow tengu, black feathered wings, black hair, short bob, red eyes, black yamabushi robes, tokin cap, holding a black feather, large breasts",
          "name": "the black-bobbed crow tengu with black wings",
          "pose": "crouching on a branch twirling a black feather between her fingers, cheeky grin, looking at viewer",
          "neg": TNEG},
   "e2": {"type": "woman", "jp": "イブキ",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, human, brown hair, long low ponytail, wet hair, green eyes, white ascetic robe, prayer beads, mountain ascetic, medium breasts",
          "name": "the brown-haired ascetic in a white robe",
          "pose": "standing with prayer beads held between her palms, serious calm face, looking at viewer",
          "neg": TNEG},
   "e3": {"type": "woman", "jp": "ヤマビコ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, slender, tree spirit, green hair, very long hair with fresh green leaves, amber eyes, thin moss-green gauzy dress, barefoot, medium breasts",
          "name": "the green-haired tree spirit in a moss-green gauze dress",
          "pose": "hands cupped by her mouth as if calling out, innocent playful smile, looking at viewer",
          "neg": TNEG},
   "boss": {"type": "woman", "jp": "オボロ",
            "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, long legs, tall, tengu, very large black feathered wings, magenta hair, very long hair, red eyes, dark purple and black yamabushi robes, large breasts",
            "name": "the magenta-haired tengu with huge black wings",
            "pose": "half wrapped in her own huge black wings, quiet possessive smile, looking at viewer",
            "neg": TNEG},
 },
 "places": {
   "trail":    "mountain trail at the foot, avenue of tall cedars, damp earth, fog behind",
   "falls":    "waterfall basin, roaring water, cold spray, wet black rocks",
   "cedar":    "cedar forest, sunlight through leaves, soft green moss",
   "shrine":   "mountaintop shrine, vermilion torii, shimenawa rope, bells ringing in the wind, white gravel",
   "cave":     "rock cave training hall, candlelight, damp rock walls",
   "bridge":   "swaying rope suspension bridge over a deep valley, mist rising from below",
   "ridge":    "windy ridge path, sea of clouds, rustling bamboo grass",
   "roost":    "lookout platform high in a giant cedar, black feathers scattered, crows",
   "lodge":    "temple lodging room, tatami, thin futon, charcoal brazier, shoji screen open to the wind",
   "hollow":   "hollow inside a giant camphor tree, softly glowing moss",
   "spring":   "mountain spring, icy clear water, wet moss, mossy rocks",
   "lookout":  "misty lookout deck, cold wooden railing, faint village lights through a gap in the fog",
   "brewery":  "tengu sake storehouse, cedar barrels, cool earthen floor, dim light",
   "corridor": "inner sanctum corridor, black pillars, stone lanterns, incense smoke, shadows of wings",
   "sanctum":  "innermost sleeping chamber of the inner sanctum, darkness, piles of soft black and white feathers",
 },
 "atk": {
   "m1": ("shrine", "he lies on his back on the white gravel, the great tengu stands over him with one bare sole pressing his penis, footjob, a tall one-toothed geta beside, fanning his chest with her white feather fan, haughty smile"),
   "m2": ("ridge", "he stands trembling on the windy ridge, the great tengu hovers above him on white wings swinging her white feather fan, a visible stream of wind swirling over his nipples and thighs, no hands on him, sea of clouds"),
   "m3": ("corridor", "from side, he lies face down on the floor between black pillars, the great tengu lies over him penetrating his anus with her own penis, anal, kissing him deeply over his shoulder, fanning his back, his own penis separate", PEN),
   "e1": ("trail", "he lies against a cedar root, the crow tengu kneels over him brushing his nipple with the tip of a black feather, circling the areola, black wings half spread, cheeky grin"),
   "e2": ("falls", "he sits on a wet rock before the waterfall, the ascetic sits close beside him with her lips at his ear chanting, licking his ear, prayer beads dangling by his ear, cold spray"),
   "e3": ("cedar", "he lies on the moss, the tree spirit lies beside him whispering into his ear, faint echoing ripples of sound in the air around his head, no hands on him, sunlight through leaves"),
   "boss": ("sanctum", "he is wrapped inside the tengu's huge black wings in the dark, pressed against her chest, the tengu pinches and rolls his nipple, black feathers all around, quiet smile"),
 },
 "atk_desc": {
   "m1": "the great tengu tramples him with her bare sole after kicking off her geta.",
   "m2": "the great tengu caresses his whole body with the wind of her feather fan.",
   "m3": "the great tengu performs the initiation rite on him with a kiss.",
   "e1": "the crow tengu brushes his nipples with a black feather.",
   "e2": "the ascetic chants a mantra into his ear.",
   "e3": "the tree spirit echoes his moans back into his head.",
   "boss": "the tengu wraps him in her black wings.",
 },
 "lose": {
   # アマギリ 技1（一本歯の下駄）
   "btl_m1":     ("shrine", "he lies on his back on the white gravel, the great tengu stands over him with her bare sole pressing his penis, footjob, fanning his nipples with her white feather fan, a tall one-toothed geta beside, cum on her toes, black feathers on his shoulder"),
   "onani_m1":   ("lodge", "sitting alone by the open shoji in the valley wind, rubbing the soles of his feet against the tatami, body trembling, penis untouched, the great tengu stands far away on the veranda on tall geta, watching"),
   "inochi_m1":  ("bridge", "on the swaying suspension bridge, he lies on the planks, the great tengu stands over him on one leg pressing his penis with her bare sole, footjob, fanning him with her white feather fan, mist rising, cum on the planks"),
   "onedari_m1": ("cave", "he sits cross-legged in the candlelit cave, the great tengu sits before him with one bare foot on his lap, her toes pinching his penis, footjob, a blank folded map without text on the ground, cum on her foot"),
   # アマギリ 技2（★羽団扇の風）
   "btl_m2":     ("ridge", "he kneels on the windy ridge path above the sea of clouds, the great tengu hovers above swinging her white feather fan, a swirling vortex of wind wrapping his whole body, no hands on him, cum scattered by the wind"),
   "onani_m2":   ("lookout", "leaning alone against the cold railing of the misty lookout, baring his skin to the valley wind, trembling, penis untouched, the great tengu floats far above in the fog on white wings, watching"),
   "inochi_m2":  ("trail", "he kneels on the cedar avenue trail, the great tengu stands behind him fanning his back with her white feather fan, wind whipping his hair, no hands on him, cum on the damp earth, his travel cloak dropped"),
   "onedari_m2": ("shrine", "he kneels before the shrine with a blank map without text fluttering in his hands, the great tengu swings her white feather fan, wind streaming over his chest and inner thighs, no hands on him, cum on the gravel"),
   # アマギリ 技3（峰入りの儀・口づけ＋ふたなり逆アナル）
   "btl_m3":     ("corridor", "from side, he lies face down on the floor by the stone lanterns, the great tengu lies over him penetrating his anus with her own penis, anal, kissing him deeply, fanning his back with her feather fan, his own penis separate, cum on the floor", PEN),
   "onani_m3":   ("spring", "kneeling alone at the edge of the icy spring with his back to the wind, hips clenched and trembling, hands on his knees, penis untouched, the great tengu stands far away on a mossy rock, watching"),
   "inochi_m3":  ("lodge", "from side, he lies on his back on the thin futon with legs lifted, the great tengu over him penetrating his anus with her own penis, anal, kissing him deeply, a white feather on the futon, his own penis separate", PEN),
   "onedari_m3": ("sanctum", "from side, he lies on his back on the piled feathers with legs lifted, the great tengu over him penetrating his anus with her own penis, anal, kissing him deeply, white wings spread above them, his own penis separate", PEN),
   # クロハ（黒羽根の筆／烏の手並み）
   "btl_e1":     ("trail", "he lies pinned against a cedar root, the crow tengu straddles his legs brushing both his nipples alternately with black feathers, her other hand stroking his penis fast, handjob, cum on his stomach, black wings spread"),
   "onani_e1":   ("lodge", "sitting alone on the thin futon, brushing his own nipple with the tip of a black feather, penis untouched, the crow tengu perches far away on the window frame, watching"),
   "inochi_e1":  ("cedar", "he stands leaning on a cedar trunk, the crow tengu brushes his nipple with a black feather, her other hand stroking his penis, handjob, a bundle of black feathers hanging from a branch, cum on the moss"),
   "onedari_e1": ("roost", "he lies on a pile of black feathers on the high lookout platform, pushing his chest out, the crow tengu brushes both his nipples with a bundle of black feathers, her hand stroking his penis, handjob, crows around"),
   # イブキ（真言の耳打ち／滝行の膝）
   "btl_e2":     ("falls", "he sits on a wet rock, the ascetic sits beside him licking inside his ear while chanting, her wet knee pressing up against his penis, prayer beads by his ear, cold spray, cum on the rock"),
   "onani_e2":   ("cave", "sitting alone in the candlelit cave, tracing his own ear with a wet finger, murmuring a chant, penis untouched, the ascetic stands far away in the candle shadow holding prayer beads, watching"),
   "inochi_e2":  ("bridge", "on the middle of the swaying suspension bridge, he clings to the rope, the ascetic stands close with her lips at his ear chanting, her knee pressing up against his penis, sunset mist, cum dripping"),
   "onedari_e2": ("lodge", "he kneels in seiza on the tatami, the ascetic kneels beside him chanting into his ear and licking it, her knee pressing his penis, prayer beads around his wrist, his mouth open chanting with her"),
   # ヤマビコ（山彦の囁き／木漏れ日の口づけ）
   "btl_e3":     ("cedar", "he lies on the moss with his back arched, the tree spirit kneels beside him whispering into his ear, faint echoing ripples of sound all around him, no hands on him, cum on the moss, sunlight through leaves"),
   "onani_e3":   ("hollow", "sitting alone inside the tree hollow with his mouth open speaking, glowing ripples of echoes returning around him, hands on his knees, trembling, penis untouched, the tree spirit peeks far away from the hollow entrance, watching"),
   "inochi_e3":  ("lookout", "he stands at the railing shouting toward the faint village lights, the tree spirit holds his face and kisses him deeply, tongues, echoing ripples in the fog, cum on the deck"),
   "onedari_e3": ("spring", "he lies on a bed of moss by the spring, the tree spirit leans over kissing him deeply, echoing ripples spreading on the water surface, no other touch, cum on the moss"),
   # オボロ（翼の抱擁／奥の院の秘儀・ふたなり）
   "btl_boss":   ("sanctum", "from side, he lies on the piled feathers wrapped inside the tengu's huge black wings, the tengu penetrating his anus with her own penis, anal, pinching his nipple, his own penis separate, black feathers everywhere", PEN),
   "onani_boss": ("lodge", "lying alone under a feather duvet pulled over his head, pinching his own nipples in the dark, penis untouched, the tengu stands far away by the shoji with her black wings folded, watching"),
   "inochi_boss":("brewery", "from side, he lies among cedar barrels wrapped in the tengu's huge black wings, the tengu penetrating his anus with her own penis, anal, pinching his nipple, a sake cup on the earthen floor, his own penis separate", PEN),
   "onedari_boss":("corridor", "from side, he is wrapped inside the tengu's huge black wings in the lantern-lit corridor, the tengu penetrating his anus with her own penis, anal, pinching his nipple, one stone lantern gone dark, his own penis separate", PEN),
 },
 "lose_desc": "spirits him away to the inner sanctum, never to be seen in the village again.",
 "onanie": {
   "master": ("lodge", "sitting by the open shoji facing the valley wind, hands resting on his knees, skin trembling in the wind, hair blown back, penis untouched"),
   "e1": ("lodge", "sitting on the thin futon, brushing his own nipple with the tip of a black feather, penis untouched"),
   "e2": ("cave", "sitting in the candlelit cave, tracing his own ear with a wet finger, murmuring a chant, penis untouched"),
   "e3": ("hollow", "sitting inside the tree hollow with his mouth open speaking, glowing ripples of echoes returning around him, hands on his knees, penis untouched"),
   "boss": ("lodge", "lying under a feather duvet pulled over his head, pinching his own nipples in the dark, penis untouched"),
 },
 "magic": {
   "1": ("e2", "spring", "scooping icy spring water in both palms, water dripping between her fingers, calm face"),
   "2": (None, "cave", "an old blank map scroll without text unrolled on a rock by candlelight, showing only drawn mountain peaks"),
   "3": (None, "cedar", "thick white mountain fog rolling between towering cedars, faint glowing mist, trap"),
   "4": ("m", "brewery", "sitting on a cedar barrel raising a shallow red sake cup, relaxed tipsy smile"),
   "5": (None, "shrine", "a thick shimenawa rope with white paper streamers strung between two cedars, faint golden barrier glow"),
 },
}
