# N91 冥府の審判（Underworld）画像データ。登場人物は全員20歳以上（冥府の者は見た目の年齢・成人）。
# 女性（カロネ・ケルベラ）＋ふたなり（ヘルヴィア・モルテ・ネメシア。type は woman、挿入の本だけ pen=penis）。女装なし。
# 死体・骸骨・腐敗・血は描かない。帳面・判決文・契約書は文字なし（blank）。主人公は生きている。
GOLD = "faint glowing golden light strokes on his skin, illegible, without text"
DATA = {
 "code": "Underworld",
 "world": "serene gothic underworld realm, black stone and gold candelabras, drifting mist, calm dark river, pomegranates, detailed background",
 "bg": "underworld judgment hall, polished black stone floor, rows of gold candelabras, a huge golden balance scale, black and gold throne on a dais, drifting mist, myrrh smoke",
 "josou": None,
 "chars": {
   "m":    {"type": "woman", "jp": "ヘルヴィア",
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, very tall, long legs, voluptuous, underworld queen, black hair, very long hair, pomegranate hair ornament, red eyes, red lipstick, classical black and gold gown, sheer black veil, barefoot, huge breasts",
            "name": "the tall black-haired underworld queen in a black and gold gown",
            "pose": "sitting on a black and gold throne with legs crossed, bare feet, holding half a pomegranate, merciful calm smile, looking at viewer"},
   "e1":   {"type": "woman", "jp": "カロネ",
            "tags": "adult woman, mature female, mature face, 29 years old, adult proportions, beautiful detailed eyes, long legs, ferrywoman, gray hair, long hair in a single tie, amber eyes, gray hooded cloak over a thin sheer robe, holding a long oar, huge breasts",
            "name": "the gray-haired ferrywoman in a gray cloak",
            "pose": "standing holding a long oar, cloak open, quiet half-lidded smile, looking at viewer"},
   "e2":   {"type": "woman", "jp": "ケルベラ",
            "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, dog girl, one head, reddish-brown hair, messy wavy hair, black dog ears, black dog tail, gold eyes, black collar with a small bell, short black leather tunic, large breasts",
            "name": "the reddish-brown-haired dog-eared gatekeeper",
            "pose": "crouching forward sniffing the air, tail wagging, bright open grin, looking at viewer"},
   "e3":   {"type": "woman", "jp": "モルテ",
            "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, bob cut, green eyes, glasses, long black scribe robe, holding a quill pen and a blank ledger without text, large breasts",
            "name": "the purple-bob scribe in glasses",
            "pose": "standing holding a quill over an open blank ledger, adjusting her glasses, businesslike faint smile, looking at viewer"},
   "boss": {"type": "woman", "jp": "ネメシア",
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, very tall, long legs, judge, blonde hair, very long hair, purple eyes, white and gold judicial robe, blindfold cloth hanging loose around her neck, holding a small golden balance scale, huge breasts",
            "name": "the tall blonde judge in a white and gold robe",
            "pose": "standing holding a small golden balance scale in one hand, composed smile, looking at viewer"},
 },
 "places": {
   "river":    "shore of a calm black river, gray cold sand, drifting mist, a distant boat lantern",
   "boat":     "small wooden ferry boat on a black river, lantern at the bow, mist on the water",
   "pier":     "wet black wooden pier, mooring rope, lapping black water, a moored ferry",
   "gate":     "huge black stone gate of the underworld with gold studs, cold wind, small bells",
   "kennel":   "gatekeeper's den, black fur rug, hay, glowing embers",
   "waiting":  "waiting room, black ebony long bench, hourglass on the wall, summoning bell",
   "archive":  "records hall, bookshelves up to the ceiling, blank old ledgers without text, candlesticks",
   "desk":     "scribe's slanted writing desk, quill pen, ink pot, open blank ledger without text",
   "scale":    "hall of the balance, a human-sized golden balance scale with large polished pans, small gold weights",
   "court":    "judgment hall, black stone floor, rows of gold candelabras, a railed witness stand",
   "corridor": "underworld corridor, rows of candelabras, candlelight reflected on the black floor",
   "throne":   "throne room, black and gold throne on a dais, rug below the steps, myrrh smoke",
   "queenbed": "queen's bedchamber, black silk canopy, very soft bed, a bowl of pomegranates",
   "garden":   "pomegranate garden, black leaves and red fruit, split pomegranates, a fountain",
   "lethe":    "spring of the river of forgetfulness, pale hazy white water surface, soft mist",
 },
 "atk": {
   "m1": ("throne", "he kneels on the rug below the throne, the underworld queen sits on the throne pressing her bare black-nailed foot against his chest and sliding it down his thigh, her toes near his penis, blush"),
   "m2": ("throne", "he kneels before the throne, the underworld queen leans down and kisses him, pushing a red pomegranate seed into his mouth with her tongue, red juice on his lips, tongues"),
   "m3": ("court", "from side, he is bent over the witness stand railing, the underworld queen behind him penetrating his anus with her own penis, anal, reaching around pinching his nipples, his own penis separate", {"pen": "penis"}),
   "e1": ("boat", "he lies in the bottom of the ferry boat with his face held inside the ferrywoman's cloak between her huge breasts, the boat rocking, the ferrywoman cradling his head, trembling"),
   "e2": ("gate", "he leans back against the black gate pillar with his arms raised, the dog-eared gatekeeper sniffs his armpit and neck, her breath on his skin, no hands on him, tail wagging, flushed"),
   "e3": ("archive", "he stands before the bookshelves, the scribe writes on his bare chest with a quill pen, " + GOLD + ", his mouth open, trembling"),
   "boss": ("scale", "he sits on the large pan of the golden scale, the judge stands behind him pinching both his nipples, whispering into his ear, one pinch harder than the other, trembling"),
 },
 "atk_desc": {
   "m1": "the underworld queen judges him with her bare feet from the throne.",
   "m2": "the underworld queen feeds him a pomegranate seed mouth to mouth.",
   "m3": "the underworld queen hands down the final judgment.",
   "e1": "the ferrywoman cradles him in the rocking boat.",
   "e2": "the gatekeeper sniffs out his sins.",
   "e3": "the scribe records his sins on his skin.",
   "boss": "the judge weighs him with both hands.",
 },
 "lose": {
   # ヘルヴィア 技1（玉座の脚）
   "btl_m1":     ("throne", "he kneels on the rug below the throne placing a small gold weight on a scale pan, the underworld queen leans down feeding him a pomegranate seed mouth to mouth, her bare foot resting on his chest, cum on her foot"),
   "onani_m1":   ("throne", "kneeling alone on the rug below the throne, sucking his own red juice-stained fingers, stroking his own thigh with the top of his foot, penis untouched, the underworld queen watches from the high throne"),
   "inochi_m1":  ("queenbed", "he lies asleep at the foot of the soft bed with his cheek held between the underworld queen's bare feet, her toes stroking his hair, a black ribbon tied around his ankle, pomegranate bowl"),
   "onedari_m1": ("court", "he kneels on the black stone floor, the underworld queen stands pressing her bare sole onto his chest, holding a blank judgment scroll without text, red juice on his lips, cum on the floor"),
   # ヘルヴィア 技2（柘榴の口移し）
   "btl_m2":     ("garden", "he kneels among the pomegranate trees, the underworld queen kisses him pushing the last pomegranate seed into his mouth with her tongue, red juice dripping down his chin, split fruit on the ground, cum on the grass"),
   "onani_m2":   ("lethe", "kneeling alone by the hazy spring, sucking his own fingers wet with red pomegranate juice, eyes hidden, dazed, penis untouched, the underworld queen watches from across the mist"),
   "inochi_m2":  ("river", "he kneels on the gray sand of the black river shore, the underworld queen lifts her veil and kisses him long, a pomegranate seed on her tongue, a boat lantern far in the mist"),
   "onedari_m2": ("throne", "he kneels on the steps of the throne with his mouth open, the underworld queen bends down letting a single pomegranate seed melt on his tongue in a deep kiss, a blank register without text on the steps"),
   # ヘルヴィア 技3（最終判決・ふたなり）
   "btl_m3":     ("court", "from side, he is bent over the witness stand railing, the underworld queen behind him penetrating his anus with her own penis, anal, pinching both his nipples, red pomegranate juice on his lips, his own penis separate, cum dripping", {"pen": "penis"}),
   "onani_m3":   ("queenbed", "lying alone on the soft bed, sucking red juice-stained fingers, pinching his own nipple, pressing two fingers of his other hand into his own anus, penis untouched, the underworld queen watches from the canopy curtain"),
   "inochi_m3":  ("corridor", "from side, he stands bent forward with hands against the wall under the candelabras, the underworld queen behind him penetrating his anus with her own penis, anal, kissing him over his shoulder, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("throne", "he is lowered onto the lap of the underworld queen seated on the throne, facing away, her own penis in his anus, anal, her hands pinching both his nipples, his own penis separate, myrrh smoke", {"pen": "penis"}),
   # カロネ（舟の揺り籠）
   "btl_e1":     ("boat", "he lies in the bottom of the boat with his face buried between the ferrywoman's huge breasts inside her cloak, the ferrywoman strokes his penis with the hand that held the oar, cum on his belly, a tiny gold scale on the gunwale"),
   "onani_e1":   ("river", "sitting alone on the gray sand rocking his body slowly, his face buried in a cushion, stroking his own chest, penis untouched, the ferrywoman watches from her boat in the mist"),
   "inochi_e1":  ("boat", "he sleeps with his face on the ferrywoman's chest inside her cloak, the ferrywoman rows slowly with one hand, the boat in the middle of the black river, mist all around"),
   "onedari_e1": ("pier", "he lies in the moored boat against the ferrywoman's bare cleavage, her sheer robe opened, the ferrywoman rocks him, a mooring rope tied loosely around his ankle, cum on his thigh"),
   # ケルベラ（番犬の鼻先）
   "btl_e2":     ("gate", "he leans against the black gate pillar with his arms raised, the dog-eared gatekeeper sniffs his armpit, her bell jingling, her tail wagging, no hands on him, cum on the stone"),
   "onani_e2":   ("waiting", "sitting alone on the ebony bench with both arms raised behind his head, exposing his armpits, trembling, no hands on himself, penis untouched, the dog-eared gatekeeper watches from the doorway"),
   "inochi_e2":  ("river", "he lies drowsily on the gray sand, the dog-eared gatekeeper sniffs his neck, a black collar with a bell around his own neck, tail wagging, mist"),
   "onedari_e2": ("kennel", "he lies on the black fur rug, the dog-eared gatekeeper crouches over him blowing her breath onto his penis without touching, her tail swaying, embers glowing, cum on the fur"),
   # モルテ（罪の記帳）
   "btl_e3":     ("archive", "he sits on the scribe's lap before the bookshelves, the scribe writes on his chest with a quill, her knee rubbing his penis, " + GOLD + ", cum on his thigh"),
   "onani_e3":   ("desk", "sitting alone by the writing desk, drawing invisible lines on his own chest with the shaft of a quill pen, reading aloud, penis untouched, the scribe watches from the far bookshelf"),
   "inochi_e3":  ("lethe", "he lies on the soft ground by the hazy spring, the scribe kneels beside him writing along his inner thigh with a quill, " + GOLD + ", dazed, trembling"),
   "onedari_e3": ("archive", "he sits on the scribe's lap deep among the bookshelves, the scribe reads from a blank ledger without text into his ear, her knee rubbing his penis, " + GOLD + ", cum dripping"),
   # ネメシア（天秤の両手／判決の執行・ふたなり）
   "btl_boss":   ("scale", "from side, he is on all fours on the large pan of the golden scale, the judge behind him penetrating his anus with her own penis, anal, pinching both his nipples, the pan tilted down to the black floor, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("court", "standing alone before the witness stand, pinching both his own nipples with uneven force, reading aloud, penis untouched, the judge watches from the high bench"),
   "inochi_boss":("waiting", "he sits on the ebony bench, the judge stands behind him pinching one nipple harder than the other, whispering conditions into his ear, a small gold weight in his hand, trembling"),
   "onedari_boss":("court", "from side, he stands bent over the witness stand railing, the judge behind him penetrating his anus with her own penis, anal, pinching his left nipple harder, his own penis separate, a blank verdict plaque without text", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the underworld forever as one of its residents.",
 "onanie": {
   "master": ("throne", "kneeling on the rug, sucking his own fingers wet with red pomegranate juice, rolling his tongue, penis untouched"),
   "e1": ("boat", "sitting in the boat rocking slowly, his face buried in a cushion, stroking his own chest, penis untouched"),
   "e2": ("gate", "standing against the gate pillar with both arms raised behind his head, exposing his armpits, no hands on himself, penis untouched"),
   "e3": ("desk", "sitting by the writing desk, drawing on his own chest with the shaft of a quill pen, reading aloud, penis untouched"),
   "boss": ("scale", "sitting on the golden scale pan, pinching both his own nipples with uneven force, penis untouched"),
 },
 "magic": {
   "1": ("boss", "scale", "placing a small gold weight onto the pan of the huge golden scale, the pan sinking, composed smile"),
   "2": (None, "court", "a sealed black envelope summons without text with a gold wax seal on the black stone floor under candlelight"),
   "3": (None, "lethe", "the hazy white spring of forgetfulness with pale mist rising and curling like reaching hands, calm water"),
   "4": ("m", "queenbed", "reclining on the soft bed holding out a split pomegranate, drowsy purple haze drifting from it, merciful smile"),
   "5": (None, "court", "a large golden bell hanging above the judgment hall, candelabras, drifting mist"),
 },
}
