# N101 戦乙女の選定（Valkyrie）画像データ。登場人物は全員20歳以上。女性のみ（挿入はエイラヴィルの光の槍だけ）。
# 鎧は白と金／白と赤／黒と銀で青系の差し色なし。選定の羽根は光の羽根で、胸に溶けるように沈む（刺さる絵にしない）。槍で突かない。
ST = {"pen": "strapon"}   # エイラヴィルの光の槍（光でできた張形・指でほぐした後）
NOBLUE = "blue armor, blue trim, blue accents, blue cape, feather piercing skin, feather stuck in skin, arrow, impaled, spear stabbing"
FEATHER = "a glowing white feather of light softly melting into his chest"

DATA = {
 "code": "Valkyrie",
 "world": "northern heroic heaven, valkyries with white wings, old battlefield hill and a golden hall above the clouds, drifting glowing white feathers, detailed background",
 "bg": "old battlefield hill at night under a starry sky, many rusted swords standing in the grass, mossy stone cairn with an old round shield, night wind, distant clouds",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "ヘルヴォラ",
         "tags": "adult woman, mature female, mature face, sharp adult features, 31 years old, adult proportions, beautiful detailed eyes, tall, long legs, valkyrie, long blonde hair in a thick braid, red eyes, white and gold breastplate, winged helmet, white cape, white feathered wings, silver spear, large breasts",
         "name": "the blonde-braided valkyrie chief in white and gold armor",
         "pose": "standing with a silver spear planted beside her, white wings half spread, proud dignified smile, looking at viewer",
         "neg": NOBLUE},
   "e1": {"type": "woman", "jp": "ルーネ",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, long legs, valkyrie, red hair, ponytail, green eyes, white and red light armor, large round white shield with red rim, short white wings, large breasts",
          "name": "the red-ponytailed shield maiden in white and red armor",
          "pose": "holding a large round white shield with a red rim in front of her, earnest protective smile, looking at viewer",
          "neg": NOBLUE},
   "e2": {"type": "woman", "jp": "スヴァナ",
          "tags": "adult woman, mature female, mature face, 23 years old, adult proportions, beautiful detailed eyes, long legs, valkyrie, black hair, short hair, amber eyes, white riding outfit with feather ornaments, riding boots, long white feather duster, short white wings, medium breasts",
          "name": "the black-haired rider valkyrie in a white riding outfit",
          "pose": "twirling a long white feather duster, cheerful grin, one hand on her hip, looking at viewer",
          "neg": NOBLUE},
   "e3": {"type": "woman", "jp": "ミードラ",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, long legs, valkyrie, long wavy pink hair, brown eyes, gold-trimmed white serving dress, cleavage, drinking horn, short white wings, huge breasts",
          "name": "the pink-haired mead valkyrie in a gold-trimmed serving dress",
          "pose": "raising a drinking horn of golden mead, tipsy cheerful smile, slight blush, looking at viewer",
          "neg": NOBLUE},
   "boss": {"strap": "glowing strap-on made of white light", "type": "woman", "jp": "エイラヴィル",
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, tall, long legs, valkyrie, long metallic silver hair, gold eyes, black and silver armor, large black feathered wings, large breasts",
            "name": "the silver-haired black-winged valkyrie in black and silver armor",
            "pose": "standing with large black wings spread wide, arms slightly open, quiet gentle expression, looking at viewer",
            "neg": NOBLUE},
 },
 "places": {
   "hill": "old battlefield hill at night, rusted swords standing in the grass, starry sky, night wind",
   "cairn": "mossy stone cairn on the hilltop, old round shield leaning on it, cold stones, night",
   "tent": "adventurer's camp tent, blankets, leather bags, campfire shadows flickering on the canvas",
   "fire": "campfire on the hill at night, crackling logs, flying sparks, dark grass around",
   "creek": "moonlit creek at the foot of the hill, wet grass, cold water, moon reflected on the surface",
   "sky": "night sky above a sea of clouds, riding on a flying white pegasus with a two-seat leather saddle, strong wind",
   "stable": "pegasus stable above the clouds, hay, white feathers floating in the air, sunlit wooden stalls",
   "hall": "great hall of the heavenly mansion, ceiling tiled with golden shields, long wooden tables, drinking horns, an empty hero's seat",
   "cellar": "mead cellar, rows of barrels, amber lamplight, dripping taps",
   "shields": "hall of shields, walls covered with polished round shields reflecting the room, cold metal fittings",
   "bath": "heavenly bathhouse, white steam, golden spout, white feathers floating on the water, warm stone floor",
   "chief": "valkyrie chief's chamber, spear rack, white fur rug, fireplace, window over a sea of clouds",
   "wingbed": "quiet bedchamber, large bed of black down feathers, low dim lamp",
   "spring": "spring of selection above the clouds, faintly glowing water, sinking feathers of light, clear cold air",
   "terrace": "terrace at the edge of the heavenly mansion, railing over a golden sea of clouds at dawn, thin cold air",
 },
 "atk": {
   "m1": ("hill", "he lies on his back in the grass, the valkyrie chief kneels over his hips squeezing his penis between her long thighs, thighjob, her silver spear planted in the ground beside them, leaning down to kiss him, " + FEATHER),
   "m2": ("fire", "he kneels before the campfire, the valkyrie chief holds his face with both hands and kisses him deeply, sucking his tongue, saliva trail, no hands on his crotch, three glowing feathers sinking into his chest"),
   "m3": ("sky", "he sits in front on the saddle of a flying white pegasus, the valkyrie chief sits behind him pressing her breasts against his back and whispering into his ear, lips on his earlobe, white cape fluttering"),
   "e1": ("cairn", "he sits against the stone cairn, the shield maiden kneels in front of him with her large round shield raised around them, sucking his nipple and pinching the other, dim shadow, " + FEATHER),
   "e2": ("stable", "he sits on the hay, the rider valkyrie sits behind him sweeping the rim of his ear with a long white feather duster, her breath on his other ear, white feathers floating, shivering"),
   "e3": ("hall", "he sits in the empty hero's seat, the mead valkyrie pours golden mead into her cleavage from a drinking horn and presses his face between her huge breasts, he sips the mead, tipsy blush"),
   "boss": ("wingbed", "he is held against the black-winged valkyrie inside her large black wings wrapped around them both, the black-winged valkyrie slowly pinches his nipple, dim warm darkness, " + FEATHER),
 },
 "atk_desc": {
   "m1": "the valkyrie chief lays down her spear and clamps him between her thighs.",
   "m2": "the valkyrie chief sucks out his soul with the kiss of selection.",
   "m3": "the valkyrie chief proclaims his selection on the pegasus saddle.",
   "e1": "the shield maiden guards him inside her shield and plays with his nipples.",
   "e2": "the rider valkyrie tickles his ears with a feather duster.",
   "e3": "the mead valkyrie makes him drink mead from her cleavage.",
   "boss": "the black-winged valkyrie embraces his soul inside her wings.",
 },
 "lose": {
   # ヘルヴォラ 技1（槍を置いて）
   "btl_m1":     ("hill", "he lies on his back in the grass among old swords, the valkyrie chief kneels over his hips squeezing his penis between her long thighs, thighjob, leaning down kissing him deeply, silver spear planted in the ground, cum on her thighs, " + FEATHER),
   "onani_m1":   ("tent", "sitting alone on the blanket with a rolled blanket squeezed between his knees, sucking his own finger hard, other fingertips tracing a glowing feather mark on his chest, penis untouched, the valkyrie chief stands far away at the raised tent flap with her spear, watching"),
   "inochi_m1":  ("cairn", "he straddles the lap of the valkyrie chief sitting on the mossy stone cairn, her long thighs clamped around his waist, kissing him deeply, sucking his tongue, her spear leaning on the cairn, glowing feathers sinking into his chest, cum"),
   "onedari_m1": ("sky", "he sits in front on the saddle of a flying white pegasus, the valkyrie chief behind him clamps his hips between her thighs and turns his face back to kiss him deeply, sea of clouds, white cape fluttering, cum, " + FEATHER),
   # ヘルヴォラ 技2（選定の口づけ）
   "btl_m2":     ("fire", "he kneels before the campfire with his sword dropped in the grass, the valkyrie chief kisses him deeply, sucking his tongue, saliva trail, her gauntlet off, her hand stroking his penis, handjob, three glowing feathers sinking into his chest, sparks, cum"),
   "onani_m2":   ("creek", "kneeling alone by the moonlit creek, sucking his own finger hard, other fingertips tracing glowing feather marks on his chest, penis untouched, reflection of white wings on the water, the valkyrie chief stands far on the opposite bank, watching"),
   "inochi_m2":  ("chief", "he lies on the white fur rug by the fireplace, the valkyrie chief lies over him in a long deep kiss, sucking his tongue, saliva trail, glowing feathers sinking into his chest, spear on the rack, no hands on his crotch, cum"),
   "onedari_m2": ("spring", "he sits in front on the saddle of a white pegasus standing at the glowing spring, the valkyrie chief behind him turns his face back and kisses him deeply, her hand stroking his penis, handjob, feathers of light sinking into the water, cum"),
   # ヘルヴォラ 技3（天馬の鞍上）
   "btl_m3":     ("sky", "he sits in front on the saddle of a flying white pegasus, the valkyrie chief hugs him from behind pressing her breasts to his back, whispering into his ear, turning his face back to kiss him, his sword falling into the clouds, cum, " + FEATHER),
   "onani_m3":   ("tent", "sitting alone with his bare back pressed against the tent pole, sucking his own finger, other fingertips tracing a glowing feather mark on his chest, penis untouched, the valkyrie chief stands far away at the tent entrance, watching"),
   "inochi_m3":  ("stable", "he sits on the hay, the valkyrie chief sits behind him hugging him, pressing her breasts to his back and whispering into his ear, reins hanging on a wooden post, a white pegasus in the stall, glowing feathers drifting, cum"),
   "onedari_m3": ("terrace", "he stands at the railing of the terrace at dawn, the valkyrie chief behind him pressing her breasts to his back, turning his face back to kiss him deeply, golden sea of clouds, glowing feather mark on his back, cum on the railing"),
   # ルーネ（盾の内側／鎧を脱いで）
   "btl_e1":     ("cairn", "he sits against the stone cairn, the shield maiden kneels over him with her large round shield raised around them, her breastplate removed, squeezing his penis between her clothed breasts, paizuri, pinching his nipple, cum, " + FEATHER),
   "onani_e1":   ("tent", "lying alone under a blanket pulled over his head, pinching both of his own nipples in the dark, penis untouched, a large round white shield leaning outside, the shield maiden stands far away beside the shield, watching"),
   "inochi_e1":  ("shields", "he kneels in the hall of shields, the shield maiden kneels beside him gently biting his nipple and pinching the other, polished shields on every wall reflecting him, trembling, cum, " + FEATHER),
   "onedari_e1": ("sky", "he sits in front on the saddle of a flying white pegasus, the shield maiden behind him holds her large round shield in front of him and pinches both of his nipples, night sky, cum, " + FEATHER),
   # スヴァナ（羽根ぼうき／鞍の上で）
   "btl_e2":     ("stable", "he straddles a leather saddle on the hay, the rider valkyrie sits close behind him, her thigh rubbing his penis, sumata, sweeping inside his ear with a long white feather duster, a white pegasus behind, white feathers floating, cum"),
   "onani_e2":   ("fire", "sitting alone before the campfire, brushing inside his own ear with a single white feather, head tilted, mouth open, penis untouched, the rider valkyrie stands far away beyond the fire with a feather duster, watching"),
   "inochi_e2":  ("creek", "he kneels at the moonlit creek where a white pegasus drinks, the rider valkyrie hugs him from behind, her thigh rubbing his penis, sumata, tickling his ear with the feather duster, blowing on his other ear, cum"),
   "onedari_e2": ("sky", "he sits in front on the saddle of a flying white pegasus, reins slipping from his hands, the rider valkyrie behind him hugs his hips tightly, sumata, sweeping both of his ears with the feather duster, cum, " + FEATHER),
   # ミードラ（蜜酒の谷間／角杯を持つ手で）
   "btl_e3":     ("hall", "he sits in the empty hero's seat, the mead valkyrie pours golden mead into her cleavage and holds his face buried in her huge breasts, he sips the mead, her hand wrapped around his penis like a drinking horn, handjob, cum"),
   "onani_e3":   ("cellar", "sitting alone behind barrels with mead in his mouth, his face buried in a rolled cloak, stroking his own chest, penis untouched, the mead valkyrie peeks far away from between the barrels holding a drinking horn, watching"),
   "inochi_e3":  ("fire", "he kneels before the campfire with his face buried in the mead valkyrie's cleavage, the mead valkyrie pours golden mead between her breasts from a drinking horn, her hand stroking his penis, handjob, tipsy blush, cum"),
   "onedari_e3": ("bath", "he sits in the steaming bath among floating white feathers, the mead valkyrie sits on the bath edge pouring golden mead into her cleavage and holding his face between her breasts, her hand on his penis, handjob, steam, cum"),
   # エイラヴィル（魂の抱擁／光の槍）
   "btl_boss":   ("hill", "from side, he lies on his back on the hilltop grass wrapped in large black wings, the black-winged valkyrie over him pegging his anus with her glowing strap-on of light, anal, slowly pinching his nipple, his own penis separate, a black feather on his chest, cum", ST),
   "onani_boss": ("tent", "lying alone wrapped completely in a blanket like folded wings, slowly pinching his own nipples inside it, penis untouched, the black-winged valkyrie stands far away at the tent entrance with her black wings folded, watching"),
   "inochi_boss":("wingbed", "from side, he lies on his back on the black down bed wrapped in large black wings, the black-winged valkyrie over him pegging his anus with her glowing strap-on of light, anal, slowly pinching his nipple, his own penis separate, sleepy, cum", ST),
   "onedari_boss":("terrace", "from side, he lies on his back on a white cloak on the dawn terrace, the black-winged valkyrie over him wrapping him in her black wings, pegging his anus with her glowing strap-on of light, anal, pinching his nipple, his own penis separate, twelve glowing feather marks on his chest, cum", ST),
 },
 "lose_desc": "carries him alive to the heavenly hall as her chosen hero.",
 "onanie": {
   "master": ("fire", "sitting alone by the campfire sucking his own finger hard, other fingertips tracing a glowing feather mark on his chest, penis untouched"),
   "e1": ("tent", "lying under a blanket pulled over his head, pinching both of his own nipples in the dark, penis untouched"),
   "e2": ("stable", "sitting on the hay brushing inside his own ear with a white feather, head tilted, mouth open, penis untouched"),
   "e3": ("cellar", "sitting against barrels with a cup of mead, face buried in a rolled cloak, stroking his own chest, penis untouched"),
   "boss": ("wingbed", "wrapped in a black feather blanket, slowly pinching his own nipples inside it, penis untouched"),
 },
 "magic": {
   "1": ("e3", "hall", "the mead valkyrie raises a drinking horn overflowing with golden mead in a toast, golden drops sparkling, cheerful tipsy smile"),
   "2": (None, "hill", "a white winged pegasus with an empty two-seat leather saddle landing on the moonlit hill among old swords, white feathers drifting"),
   "3": ("m", "hill", "the valkyrie chief raises her palm releasing a dazzling beam of white light, glowing white feathers swirling around her, her spear planted in the ground"),
   "4": ("m", "cairn", "the valkyrie chief holds a single glowing white feather of light between her fingers, offering it forward, gentle proud smile"),
   "5": (None, "terrace", "great golden gate of the heavenly hall above a sea of clouds, golden shields lining the walls, glowing white feathers drifting, dawn light"),
 },
}
