# N94 満月の群れ（Werewolf）画像データ。登場人物は全員20歳以上（人狼は見た目の年齢・成人）。女性＋ふたなり（フェンリエ・グレタ・アルテ）。
# 人狼は人の顔のまま、狼の耳・尾・手足の毛並みだけ（狼の頭・噛みつき・爪の傷は描かない）。満月の光は pale silver moonlight（髪・瞳に青は使わない）。
# 挿入はフェンリエとアルテだけ（ふたなり・自分の体で）。グレタは挿入なし。マルタの麻縄は緩く、食い込ませない。
FUTA = {"pen": "penis"}
WOLFNEG = "wolf head, animal face, snout, muzzle, furry face, fangs, sharp claws, bite marks, scratches, werewolf monster, full fur body"
DATA = {
 "code": "Werewolf",
 "world": "wild wolf territory in a deep forest under a huge full moon at night, pale silver moonlight, rocks and tall pine trees, night dew, detailed background",
 "bg": "flat boulder on a rocky outcrop under a huge full moon, pale silver moonlight over a dark pine forest, a fur rug spread on the rock, night mist",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "フェンリエ",
         "tags": "adult woman, mature female, mature face, 33 years old, adult proportions, beautiful detailed eyes, long legs, tall, voluptuous, wolf woman, human face, very long voluminous grey hair like a mane, grey wolf ears, fluffy grey wolf tail, gold eyes, fur mantle over her shoulders, leather chest armor, leather loincloth skirt, fur on her forearms and shins, bold generous grin, huge breasts",
         "name": "the grey-maned wolf chieftess in a fur mantle",
         "pose": "standing with hands on her hips, tail swaying, bold generous grin, looking at viewer",
         "neg": WOLFNEG},
   "e1": {"type": "woman", "jp": "ヴォルカ",
          "tags": "adult woman, mature female, mature face, 22 years old, adult proportions, beautiful detailed eyes, long legs, wolf woman, human face, short messy red hair, red wolf ears, red wolf tail, amber eyes, light leather tunic, leg wraps, furry lower legs, eager grin, medium breasts",
          "name": "the red-haired wolf scout in a leather tunic",
          "pose": "leaning forward sniffing the air, ears perked, tail wagging, eager grin, looking at viewer",
          "neg": WOLFNEG},
   "e2": {"type": "woman", "jp": "マルタ",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, human woman, brown hair tied back in a bun, green eyes, thick fur coat over hunter's clothes, leather boots, coil of soft hemp rope at her waist, kind easygoing smile, large breasts",
          "name": "the brown-haired huntress in a thick fur coat",
          "pose": "holding a loose coil of hemp rope, kind easygoing smile, looking at viewer",
          "neg": "animal ears, wolf ears, tail"},
   "e3": {"type": "woman", "jp": "グレタ",
          "tags": "adult woman, mature female, mature face, 27 years old, adult proportions, beautiful detailed eyes, long legs, lithe slender body, wolf woman, human face, long black ponytail, black wolf ears, black wolf tail, red eyes, black leather chest armor, short black loincloth skirt, calm blunt expression, large breasts",
          "name": "the black-ponytailed wolf woman in black leather",
          "pose": "arms crossed, ears slightly turned, calm blunt expression, looking at viewer",
          "neg": WOLFNEG + ", muscular, abs"},
   "boss": {"type": "woman", "jp": "アルテ",
            "tags": "adult woman, mature female, mature face, 35 years old, adult proportions, beautiful detailed eyes, long legs, tall, wolf priestess, human face, very long golden hair, golden wolf ears, golden wolf tail, purple eyes, white shrine priestess tunic robe, crescent moon ornaments, moonstone necklace, serene mysterious smile, huge breasts",
            "name": "the golden-haired wolf priestess in a white robe",
            "pose": "hands folded holding a moonstone necklace, tail curled, serene mysterious smile, looking at viewer",
            "neg": WOLFNEG},
 },
 "places": {
   "iwaba": "flat boulder of the chieftess under the full moon, fur rug spread on the rock, night wind",
   "nedoko": "inner bed of the wolf den, layered hay and furs, dim warm cave",
   "sumi": "corner of the wolf den, cool earthen wall, moonlight from the entrance, hay",
   "iriguchi": "entrance of the wolf den, full moon shining in, pale silver light on the ground",
   "kemonomichi": "narrow beast trail through the forest, dewy undergrowth, rustling branches",
   "koya": "hunter's log cabin, hearth with glowing embers, hanging furs and hemp ropes, smoky wood",
   "mizuba": "pack's watering spring among rocks, moss, full moon reflected on the water",
   "saidan": "moon altar, round stone table, row of moonstones, white cloth, silver glowing flagstones",
   "mori": "deep forest, tall trees, soft leaf litter, moonbeams through the branches",
   "sakai": "border rocks of the territory, distant village lights far beyond, fur spread on the rock",
   "koke": "mossy hollow surrounded by ferns, soft moss floor, damp earth",
   "touboku": "cozy hollow inside a huge fallen log, wood smell, moonlight at the opening",
   "oka": "open moon-viewing hill of grass, huge full moon low in the sky",
   "kashi": "thick branch of a lookout oak tree high above the forest, rough bark, night wind",
   "takitsubo": "wet rock ledge beside a waterfall basin, cold spray, rising mist",
 },
 "atk": {
   "m1": ("iwaba", "he kneels on the fur rug, the wolf chieftess wraps her fur mantle around him and presses his face between her huge breasts, rocking them side to side, her tail curled around his waist, dazed"),
   "m2": ("iwaba", "he lies on the fur rug, the wolf chieftess lies over his whole body rubbing her cheek against his neck, her chest pressed on his, legs entwined, fluffy tail around him, marking him with her scent, trembling"),
   "m3": ("iwaba", "from side, he is on all fours on the fur rug, the wolf chieftess covers his back from behind, penetrating his anus with her own penis, anal, licking behind his ear, her tail over him, his own penis separate", FUTA),
   "e1": ("kemonomichi", "he lies in the dewy undergrowth with one arm raised, the wolf scout presses her nose into his armpit sniffing deeply, hot breath on his skin, ears perked, no hands on him, trembling"),
   "e2": ("koya", "he sits by the hearth with soft hemp rope looped loosely around his chest, the huntress flicks his nipple peeking between the knots with her finger, kind smile, ember glow"),
   "e3": ("mizuba", "he kneels by the spring, the wolf woman holds his head and licks along the rim of his ear, her tongue behind his ear, moon on the water, trembling"),
   "boss": ("saidan", "he stands on the silver flagstones, the wolf priestess holds him and kisses him deeply with the full moon behind her, pinching his nipple, tongues, saliva trail"),
 },
 "atk_desc": {
   "m1": "the wolf chieftess buries his face in her breasts.",
   "m2": "the wolf chieftess rubs her pack scent into his whole body.",
   "m3": "the wolf chieftess takes him as her mate under the full moon.",
   "e1": "the wolf scout sniffs out every trace of human scent.",
   "e2": "the huntress ties him in her snare rope.",
   "e3": "the wolf woman grooms his ears with her tongue.",
   "boss": "the wolf priestess kisses him for as long as a howl lasts.",
 },
 "lose": {
   # フェンリエ 技1（長の胸）
   "btl_m1":     ("iwaba", "he collapses on the fur rug, the wolf chieftess holds his head against her huge breasts rubbing them over his face and neck, her tail wrapped around him, cum on the fur, dazed"),
   "onani_m1":   ("sumi", "alone in the den corner, his face buried in a pile of blankets, rubbing his chest against it, breathing in deeply, hips twitching, penis untouched, the wolf chieftess watches from the den entrance far away"),
   "inochi_m1":  ("sakai", "he sits on the fur-covered border rock with the village lights far behind, the wolf chieftess hugs his head to her huge breasts, rubbing her scent onto his face, her tail around his legs"),
   "onedari_m1": ("nedoko", "he lies in the hay and furs with his face held in the wolf chieftess's cleavage, her arms and tail wrapped around him, nose pressed between her breasts, blush"),
   # フェンリエ 技2（★匂い付け）
   "btl_m2":     ("oka", "he lies pushed down in the grass under the full moon, the wolf chieftess lies over his whole body rubbing her cheek against his neck, thighs entwined, tail wrapped around him, cum on his belly"),
   "onani_m2":   ("sumi", "alone in the den corner hugging a rolled blanket, rubbing his whole body against it, nose pressed into it, penis untouched, the wolf chieftess watches from the den entrance far away"),
   "inochi_m2":  ("touboku", "inside the hollow fallen log, the wolf chieftess lies over him rubbing her body and cheek against his armpit and chest, her tail over his legs, dim moonlight, trembling"),
   "onedari_m2": ("iwaba", "he kneels on the fur rug tilting his head to offer his neck, the wolf chieftess rubs her cheek slowly along his neck, her arms around him, dazed"),
   # フェンリエ 技3（満月の番い・ふたなり）
   "btl_m3":     ("iwaba", "from side, he is on all fours on the fur rug under the full moon, the wolf chieftess covers his back penetrating his anus with her own penis, anal, licking behind his ear, his own penis separate, cum on the fur", FUTA),
   "onani_m3":   ("sumi", "lying alone face down on the hay with a blanket draped over his back, tracing behind his own ear with his fingers, hips raised, penis untouched, the wolf chieftess watches from the den entrance far away"),
   "inochi_m3":  ("sakai", "from side, he lies face down on the border rock with the village lights far away, the wolf chieftess covers his back penetrating his anus with her own penis, anal, licking behind his ear, his own penis separate", FUTA),
   "onedari_m3": ("nedoko", "from side, he lies on his side in the hay and furs, the wolf chieftess hugs him from behind penetrating his anus with her own penis, anal, licking behind his ear, her tail over him, his own penis separate", FUTA),
   # ヴォルカ（★嗅ぎ回る／狼の脚）
   "btl_e1":     ("kemonomichi", "he lies pushed down on the beast trail, the wolf scout sits at his side pressing her furry bare foot on his penis, footjob, bending to sniff his neck deeply, cum on her foot"),
   "onani_e1":   ("sumi", "sitting alone against the earthen wall with both arms raised behind his head baring his armpits, breathing hard, flushed, penis untouched, the wolf scout watches from the den entrance far away"),
   "inochi_e1":  ("mori", "he sits panting against a tree trunk, the wolf scout crouches over him pressing her nose to his neck sniffing, hot breath, tail wagging, trembling"),
   "onedari_e1": ("kashi", "he lies along the thick oak branch with one arm raised, the wolf scout crouches on the branch sniffing his armpit deeply, ears perked, night sky, trembling"),
   # マルタ（★罠の縄／毛皮の外套の中で）
   "btl_e2":     ("koya", "the huntress holds him inside her thick fur coat, soft hemp rope looped loosely around his chest, pinching his nipple between the knots, his face against her breasts, cum on the coat"),
   "onani_e2":   ("sumi", "sitting alone with a string tied loosely around his own chest, flicking his own nipple between the knots, penis untouched, the huntress watches from the den entrance far away"),
   "inochi_e2":  ("sakai", "he sits on the border rock with one wrist loosely tied to it by a single loop of hemp rope, the huntress strokes his nipple with the rope end, village lights far away"),
   "onedari_e2": ("koya", "he kneels by the hearth holding out his wrists, the huntress loops the soft hemp rope loosely around his chest, flicking his nipple between the knots, ember glow"),
   # グレタ（★毛づくろい／群れの挨拶）
   "btl_e3":     ("mizuba", "he kneels by the spring, the wolf woman holds his head and licks inside his ear, her nose touching his temple, water dripping from his hair, cum on the moss"),
   "onani_e3":   ("sumi", "sitting alone in the den corner, stroking the rim and back of his own ear with wet fingers, slowly, penis untouched, the wolf woman watches from the den entrance far away"),
   "inochi_e3":  ("koke", "he lies with his head on the wolf woman's lap on the soft moss, the wolf woman bends down licking his ear, ferns around them, dazed"),
   "onedari_e3": ("takitsubo", "he kneels on the wet rock ledge, the wolf woman touches her nose to his and kisses him, her hand holding his ear, waterfall mist, blush"),
   # アルテ（★月下の遠吠え／群れの儀・ふたなり）
   "btl_boss":   ("saidan", "from side, he lies on his back on the round stone altar, a moonstone necklace on his neck, the wolf priestess lies over him kissing him deeply while penetrating his anus with her own penis, anal, pinching his nipple, his own penis separate", FUTA),
   "onani_boss": ("iriguchi", "sitting alone at the den entrance in the moonlight, sucking two of his own fingers, the other hand pinching his own nipple, holding his breath, penis untouched, the wolf priestess watches from the hill far away"),
   "inochi_boss":("sakai", "he kneels on the border rock, a moonstone set on the rock, the wolf priestess holds him and kisses him deeply under the full moon, pinching his nipple, saliva trail, village lights far away"),
   "onedari_boss":("oka", "from side, he lies on his back in the grass right under the huge full moon, the wolf priestess lies over him kissing him while penetrating his anus with her own penis, anal, her tail over his leg, his own penis separate", FUTA),
 },
 "lose_desc": "makes him the lowest member of the wolf pack, his human scent gone forever.",
 "onanie": {
   "master": ("sumi", "hugging a rolled blanket alone, rubbing his chest against it, face buried in it breathing deeply, penis untouched"),
   "e1": ("sumi", "sitting alone with both arms raised behind his head baring his armpits, breathing hard, penis untouched"),
   "e2": ("koya", "sitting alone by the hearth with a string tied loosely around his chest, flicking his own nipple between the knots, penis untouched"),
   "e3": ("mizuba", "kneeling alone by the spring, stroking the rim of his own ear with wet fingers, penis untouched"),
   "boss": ("iriguchi", "sitting alone in the moonlit den entrance, sucking his own fingers, pinching his own nipple, penis untouched"),
 },
 "magic": {
   "1": ("m", "iwaba", "the wolf chieftess stands on the boulder howling at the huge full moon, head tilted back, grey mane and tail flowing in the wind"),
   "2": ("e1", "kemonomichi", "the wolf scout runs along the beast trail cupping a hand to her mouth calling out, ears perked, tail streaming"),
   "3": (None, "kemonomichi", "a loose hemp rope snare hidden in the dewy undergrowth of a beast trail, pale silver moonlight"),
   "4": ("e3", "mizuba", "the wolf woman crouches by the spring sniffing a trail of scent on the moss, ears turned, calm face"),
   "5": (None, "oka", "a huge full moon rising over the grassy hill, swaying grass, pale silver glow over the dark forest"),
 },
}
