# N147 ゴルド火山（Volcano）画像データ。登場人物は全員20歳以上。5人とも女性（ふたなり・NH・女装なし）。
# 見た目は設計メモ・brief の文章の目印から作成（作品名・キャラ名は tags に書かない）。筋肉の線は描かない（武人の精霊も曲線のある体つき）。
# デーモンスキュラ：原作は水色の肌 → pale lavender-grey skin に置き換え（髪は緑、瞳は violet）。
# 髪色の描き分け：サラマンダー＝金色がかった炎の髪／ドラゴン娘＝深紅／溶岩娘＝橙に光る溶岩の髪／デーモンラミア＝紫／デーモンスキュラ＝緑。
# 挿入はデーモンスキュラの触手だけ（pen なし）。サラマンダーは指だけ。デーモンラミアの尻尾は入口を撫でるだけ。ドラゴン娘・溶岩娘は後ろに触れない。
# 炎・溶岩は「熱くない温かさ」。火傷・焦げ・傷は描かない。蛇体の締め付けは苦しくない。竜の爪・牙は使わない。主人公の胸に小さな赤い光。
GLOW = "a faint warm red light glowing in the center of his chest"
SOFT_NEG = "muscular female, abs, broad shoulders on the woman, biceps, scary, fangs, sharp claws, burn, burnt skin, scorch marks, wound, pain"
DATA = {
 "code": "Volcano",
 "world": "active volcano of a fantasy land, black volcanic rock, red glow of flowing lava, drifting embers and sparks, warm haze, detailed background",
 "bg": "rim of a volcano crater at night, red glowing crater below, a tall pillar of flame rising from the crater, black volcanic rocks, drifting embers, warm red haze, no humans",
 "josou": None,
 "chars": {
   "m": {"type": "woman", "jp": "サラマンダー",
         "tags": "adult woman, mature female, mature face, sharp adult features, 28 years old, adult proportions, beautiful detailed eyes, tall, long legs, fire spirit, long flowing hair made of golden-orange flames, flame hair, glowing red eyes, warm ember-glowing skin wreathed in soft gentle flames, flames flickering along her arms and legs, red dragon tail, dark red warrior breastplate, red waist cloth, soft curvy feminine body, huge breasts, wide hips",
         "name": "the flame-haired fire spirit with a red dragon tail",
         "pose": "arms crossed under her chest, flames rising behind her, bold hearty warrior smile, looking down at viewer with glowing red eyes",
         "height_note": "she is taller than him",
         "neg": SOFT_NEG},
   "e1": {"type": "woman", "jp": "デーモンラミア",
          "tags": "adult woman, mature female, mature face, 26 years old, adult proportions, beautiful detailed eyes, lamia, very long purple hair, dark pointed hat, pink eyes, bat wings on her back, black and purple bustier, long purple snake lower body, purple scales, snake tail, soft curvy feminine body, large breasts",
          "name": "the purple-haired lamia in a pointed hat with bat wings",
          "pose": "upper body raised on her coiled purple snake body, one finger at her lips, playful mischievous smile, the tip of her tail waving, looking at viewer",
          "height_note": "she is taller than him",
          "neg": SOFT_NEG + ", human legs on the lamia"},
   "e2": {"type": "woman", "jp": "デーモンスキュラ",
          "tags": "adult woman, mature female, mature face, 25 years old, adult proportions, beautiful detailed eyes, scylla, green hair, medium hair, red hair ribbon, violet eyes, pale lavender-grey skin, dark frilled dress top, lower body of many smooth dark green tentacles, soft round mouths at the tentacle tips, dark mist drifting around her, soft curvy feminine body, large breasts",
          "name": "the green-haired scylla with a red ribbon",
          "pose": "hands folded politely in front of her, tentacles spread gracefully around her, gentle polite smile, looking at viewer",
          "height_note": "she is taller than him",
          "neg": SOFT_NEG + ", human legs on the scylla, teeth on tentacles, horror"},
   "e3": {"type": "woman", "jp": "溶岩娘",
          "tags": "adult woman, mature female, mature face, 24 years old, adult proportions, beautiful detailed eyes, tall, magma slime woman, glowing orange molten hair flowing like thick lava, amber eyes, glossy red-orange glowing semi-liquid magma body, body shaped like a short dress of flowing lava, lower body melting into a pool of slow thick lava, soft voluptuous feminine body, huge breasts",
          "name": "the glowing magma slime woman",
          "pose": "rising from a slow stream of lava, both arms open as if to embrace, warm friendly smile, looking at viewer",
          "height_note": "she is taller than him",
          "neg": SOFT_NEG + ", black charred skin"},
   "boss": {"type": "woman", "jp": "ドラゴン娘",
            "tags": "adult woman, mature female, mature face, sharp adult features, 30 years old, adult proportions, beautiful detailed eyes, very tall, dragon woman, long crimson hair, dragon horns, golden eyes, red markings on her skin, red scale bikini armor, human upper body joined to a huge long green dragon body, green scales, red underbelly, very long broad smooth tongue, soft voluptuous feminine body, huge breasts",
            "name": "the crimson-haired dragon woman with a huge green dragon body",
            "pose": "upper body raised high above her coiled green dragon body on a pile of gold, arrogant smirk, tongue slightly out, looking down at viewer",
            "height_note": "she is much taller than him",
            "neg": SOFT_NEG + ", human legs on the dragon woman, fire breath"},
 },
 "places": {
   "foot":     "foot of the volcano, black rocks, cold wind, a distant plume of smoke over the peak",
   "gate":     "entrance of a lava mine cave, red light leaking from inside, cold grey daylight outside",
   "lava":     "bank of a slow red lava river inside a cave, warm smooth rocks, red glow",
   "quarry":   "ore mining chamber, glowing ore veins in the walls, an abandoned pickaxe, thick rock pillars",
   "pool":     "geothermal pool inside the mine, rising steam, round smooth sitting stones",
   "abyss":    "dark cavern pool of still warm water, drifting dark mist, dripping water, faint red glow far away",
   "cavegate": "mouth of a huge volcanic cave, deep claw marks on the rock, warm wind from inside",
   "hoard":    "dragon's lair, heaps of gold coins and gems, scattered green scales, warm golden light",
   "bed":      "dragon's sleeping place on a warm flat rock, layered furs, piles of treasure around",
   "ledge":    "high rock ledge inside the volcano, purple mist, red lava light flowing far below",
   "road":     "steep path to the crater, drifting sparks, a wayside campfire",
   "crater":   "rim of the volcano crater, red glowing crater, a tall pillar of flame, roaring warm wind",
   "forge":    "rock chamber deep in the crater, a great stone furnace with a pillar of flame, warm stone floor",
   "onsen":    "volcanic hot spring, thick steam, rock seats around the water",
   "cell":     "warm rock room deep in the crater, a bed of gentle low flames on a stone slab, dim red light",
 },
 "atk": {
   "m1": ("crater", "he walks toward the fire spirit with dazed unsteady steps, one hand half reaching out, the fire spirit stands before the pillar of flame with her flames flaring high, one hand beckoning him, confident smile, his shirt damp with sweat, " + GLOW),
   "m2": ("forge", "he stands limp in her arms, the fire spirit embraces him from behind, her gentle flames and flame hair wrapping around his whole body without burning, one hand pinching his nipple, her other palm glowing on his lower belly, his head leaning back on her chest, " + GLOW),
   "m3": ("forge", "he stands on tiptoe held close, the fire spirit holds his chin and kisses him deeply, warm glowing breath flowing between their lips, tongues, saliva, her other hand behind him with two fingers in his anus, fingering, her flames wrapped around his back, " + GLOW),
   "e1": ("ledge", "he stands wrapped from ankles to shoulders in the thick coils of the purple snake body, gently squeezed, the lamia's upper body leans over his shoulder smiling, the tip of her tail stroking his inner thigh, his penis pressed between the scales, " + GLOW),
   "e2": ("abyss", "surrounded by dark mist, he is held up by smooth tentacles around his arms and thighs, two mouth-tipped tentacles sucking his nipples, another sucking the tip of his penis, one smooth tentacle inside his anus, the scylla's upper body close behind him smiling politely, " + GLOW),
   "e3": ("lava", "he stands sunk to the waist in the thick glowing magma of her spread lower body, the magma slime woman hugs him from the front, her glowing hand stroking his nipple, slow lava flowing around his hips without burning, his knees weak, " + GLOW),
   "boss": ("hoard", "he sits on the gold coins surrounded by the coils of the huge green dragon body, the dragon woman leans down over him, her very long broad tongue licking up from his chest to his neck, her fingertip pad stroking his nipple, saliva glistening on his skin, " + GLOW),
 },
 "atk_desc": {
   "m1": "the fire spirit raises her flames and calls him to walk into her arms by himself.",
   "m2": "the fire spirit wraps him in her warm flame body, pinching his nipple and pouring warmth into his belly.",
   "m3": "the fire spirit kisses him with warm breath while her fingers press inside him.",
   "e1": "the lamia coils her snake body around him and teases him with the tip of her tail.",
   "e2": "the scylla sucks his whole body with mouth-tipped tentacles in the dark mist.",
   "e3": "the magma slime woman wraps his lower body in her thick warm magma.",
   "boss": "the dragon woman surrounds him and licks him up with her huge tongue.",
 },
 "lose": {
   # サラマンダー 技1（アグニの焦炎）
   "btl_m1":     ("crater", "the pillar of flame erupting high behind them, he has walked into her arms, the fire spirit embraces him from the front in her gentle flames, pinching his nipple, two fingers of her other hand in his anus, fingering, twelve tiny red lights glowing on his chest, cum dripping untouched"),
   "onani_m1":   ("road", "sitting alone before the wayside campfire, staring into the fire, one hand rubbing his own nipple, the other hand reaching behind to stroke his own anus, penis untouched, " + GLOW + ", the fire spirit watches far away taking shape from drifting sparks"),
   "inochi_m1":  ("foot", "in the cold wind at the foot of the volcano, he buries his face in her chest by himself, the fire spirit holds him wrapped in her gentle flames, one hand on the back of his head, her dragon tail around his waist, satisfied smile, cum dripping, " + GLOW),
   "onedari_m1": ("cell", "he crawls onto the bed of low flames toward her, the fire spirit sits with her flames flaring high, one hand beckoning, her other arm pulling him against her chest, her fingers pinching his nipple, he looks up begging, cum dripping untouched, " + GLOW),
   # サラマンダー 技2（★火龍の抱擁）
   "btl_m2":     ("forge", "before the great furnace, he is held limp in her arms from behind, the fire spirit's flames wrapping his whole body without burning, one hand pinching his nipple, two fingers of her other hand deep in his anus, fingering, her glowing palm on his lower belly, cum dripping untouched, a single strand of flame tied around his wrist"),
   "onani_m2":   ("pool", "kneeling alone pressing his chest and belly against a warm round rock beside the steaming pool, one hand rubbing his own nipple, a finger of the other hand at his own anus, penis untouched, " + GLOW + ", the fire spirit watches far away through the steam"),
   "inochi_m2":  ("forge", "at dawn in the doorway of the rock chamber, he stands frozen before the cold pale light outside, the fire spirit embraces him from behind wrapping him in her gentle flames, her glowing palm on his lower belly, his hands holding her arms, cum dripping, " + GLOW),
   "onedari_m2": ("cell", "he lies on his back on the bed of low flames, the fire spirit lies over him covering his whole body with her flame body, one hand rolling his nipple, two fingers of her other hand in his anus, fingering, her palm glowing on his belly, cum on his stomach, " + GLOW),
   # サラマンダー 技3（炎の口づけ）
   "btl_m3":     ("forge", "he is held against her body before the furnace, the fire spirit kisses him deeply, glowing warm breath flowing into his mouth, tongues, saliva trail, two fingers of her other hand in his anus, fingering, her flames wrapped around him, a tiny stone lantern with a flame beside them, cum dripping"),
   "onani_m3":   ("onsen", "sitting alone on a rock seat in the hot spring, sucking two of his own wet fingers as if kissing, the other hand reaching behind pressing a finger into his own anus, penis untouched, " + GLOW + ", the fire spirit watches far away through the steam"),
   "inochi_m3":  ("crater", "at the crater rim with the flame pillar rising higher, the fire spirit holds his face in both hands kissing him deeply, warm glowing breath, his fingers clutching her arms, his travel bag dropped at his feet, knees giving way, cum dripping, several red lights on his chest"),
   "onedari_m3": ("cell", "he lies in her arms on the bed of low flames, the fire spirit kisses him long and deep, glowing warm breath between their lips, saliva, her fingers deep in his anus, fingering, her flame hair spread over them, cum on his stomach, " + GLOW),
   # デーモンラミア（★ラミアロール）
   "btl_e1":     ("ledge", "he is wrapped from ankles to shoulders in the thick purple snake coils, gently squeezed, the lamia's face close to his looking into his face with softly glowing pink eyes, his mouth open without voice, the tip of her tail circling his anus without entering, a purple scale bracelet on his wrist, cum dripping between the scales"),
   "onani_e1":   ("gate", "sitting alone behind a rock at the mine entrance, a rope wound tightly around his chest and waist, pulling both ends, the other hand rubbing his own nipple, penis untouched, " + GLOW + ", the lamia watches far above with her bat wings spread"),
   "inochi_e1":  ("ledge", "he hangs half over the edge of the rock ledge as if climbing down, the purple snake tail coiled around his ankle and waist pulling him back, the lamia leans over him laughing, her fingers stroking his nipple, he looks back waiting, cum dripping, " + GLOW),
   "onedari_e1": ("ledge", "in the purple mist, he is fully coiled in the purple snake body with only his head and chest showing, the lamia hugs him from behind stroking his nipple, the tip of her tail circling his anus without entering, playful grin, cum dripping, " + GLOW),
   # デーモンスキュラ（★触手全身責め）
   "btl_e2":     ("abyss", "in thick dark mist, he is held up by tentacles with his legs apart, two mouth-tipped tentacles sucking his nipples, one smooth tentacle deep inside his anus, his penis untouched and dripping cum, the scylla's upper body behind him covering his eyes with one hand, a piece of red ribbon tied on his wrist"),
   "onani_e2":   ("quarry", "sitting alone behind a rock pillar with his face turned up, one hand rubbing his own nipple, a finger of the other hand in his own anus, penis untouched, " + GLOW + ", the scylla watches far away with dark mist drifting from her"),
   "inochi_e2":  ("abyss", "he clings to the far bank of the dark pool with both hands, his body still in the warm water, tentacles coiled around his legs pulling gently, a mouth-tipped tentacle sucking his nipple, the scylla's upper body rising behind him smiling politely, cum in the water, " + GLOW),
   "onedari_e2": ("abyss", "he floats on his back in the dark warm water cradled by five tentacles, two mouth-tipped tentacles sucking his nipples, one sucking his penis, one smooth tentacle inside his anus, the scylla's upper body above him stroking his hair, polite smile, cum, " + GLOW),
   # 溶岩娘（★マグマホールド）
   "btl_e3":     ("lava", "at the bank of the lava river, he is sunk to the waist in the thick glowing magma of her lower body, the magma slime woman hugs him from behind, both her glowing hands covering and stroking his nipples, slow lava kneading his hips without burning, cum mixing into the magma, a warm pebble in his hand"),
   "onani_e3":   ("pool", "sitting alone waist-deep in the steaming geothermal pool, both hands rubbing his own nipples through his wet shirt, penis untouched under the water, " + GLOW + ", a red glow watching from the bottom of the pool far away"),
   "inochi_e3":  ("gate", "at the mine entrance facing the cold grey wind outside, he stands unable to step out, the magma slime woman wraps him from behind up to the waist in her warm magma body, her arms around his chest, her warm breath on his neck, cum dripping, " + GLOW),
   "onedari_e3": ("lava", "he sits on a warm rock by the lava river with his lower body wrapped in her thick glowing magma, the magma slime woman sits facing him, pinching and rolling his nipples with her glowing fingers, warm happy smile, cum mixing into the magma, " + GLOW),
   # ドラゴン娘（★巨舌）
   "btl_boss":   ("hoard", "he lies back on the heap of gold coins enclosed by the coils of the huge green dragon body, the dragon woman over him, her very long broad tongue licking up from his lower belly over his penis to his chest, her fingertip pads rolling his nipples, saliva all over him, a green scale charm on his neck, cum on his stomach"),
   "onani_boss": ("cavegate", "sitting alone behind a claw-marked rock, licking the back of his own hand with his tongue, the other wet hand rubbing his own nipple, penis untouched, " + GLOW + ", the dragon woman watches far away from the dark of the cave"),
   "inochi_boss":("hoard", "he kneels on the gold reaching his hand not toward the treasure but toward her tongue, the dragon woman licks his hand and arm with her very long broad tongue, the green dragon body curled around him, a jeweled cup fallen beside him, his knees weak, cum dripping, " + GLOW),
   "onedari_boss":("bed", "he lies on the layered furs among treasure, the dragon woman leans over him licking his whole chest and neck in one long stroke with her very long broad tongue, her large breasts resting warm against his side, her fingertip pad on his nipple, cum on his stomach, " + GLOW),
 },
 "lose_desc": "keeps him inside the warm volcano forever as the fire spirit's cherished hearth keeper, twelve tiny red lights glowing in his chest.",
 "onanie": {
   "master": ("pool", "pressing his chest against a warm round rock, one hand rubbing his own nipple, a finger of the other hand at his own anus, penis untouched"),
   "e1": ("gate", "sitting behind a rock, a rope wound tightly around his chest, pulling it tight and rubbing his own nipple, penis untouched"),
   "e2": ("quarry", "sitting behind a rock pillar with his face turned up, rubbing his own nipple, a finger in his own anus, penis untouched"),
   "e3": ("pool", "sitting waist-deep in the warm pool, rubbing his own nipples through his wet shirt, penis untouched"),
   "boss": ("cavegate", "sitting behind a rock, licking the back of his own hand and rubbing his own nipple with the other hand, penis untouched"),
 },
 "magic": {
   "1": (None, "crater", "two tiny gentle embers floating in the air above the crater rim, soft warm glow, close-up, the flame pillar blurred behind"),
   "2": (None, "crater", "a tall plume of smoke lit red from below rising from the crater into the night sky, drifting sparks, wide view"),
   "3": ("e2", "abyss", "spreading a curtain of warm dark mist with both raised hands, tentacles spread around her, gentle polite smile"),
   "4": (None, "pool", "a steaming geothermal pool with round smooth sitting stones, warm amber light, drops of water, close view"),
   "5": ("m", "forge", "standing before the great stone furnace with one hand raised, a pillar of flame roaring up in the furnace, proud bold smile"),
 },
}
