# N51 錬金術師の塔（Alchemy）場面データ。登場人物は全員20歳以上。女性（パラケルシア・セリ）とニューハーフ（ミント・ホムラ・ヘルメス）の混合。
DATA = {
 "code": "Alchemy",
 "world": "tall stone alchemist tower at the edge of a misty city, shelves of glass flasks and colored potion bottles, brass instruments, warm lamplight, detailed background",
 "chars": {
   "m":    {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 37 years old, adult proportions, beautiful detailed eyes, long legs, green hair, long single braid, gold eyes, glasses, dark green robe over black dress, test tubes on belt, large breasts",
            "name": "the green-braided alchemist in glasses and a dark green robe"},
   "e1":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 22 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, orange hair, bob cut, green eyes, white lab coat with rolled sleeves, thin dress, medium breasts",
            "name": "the orange-bob apprentice in a white lab coat",
            "height_note": "she is about the same height as him"},
   "e2":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, long braid, purple eyes, leather apron, cream blouse, large breasts",
            "name": "the brown-braided herbalist in a leather apron"},
   "e3":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, red hair, medium hair, amber eyes, black gloves, short furnace-keeper robe, gold ring, medium breasts",
            "name": "the red-haired furnace keeper in black gloves"},
   "boss": {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 40 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, white hair, long hair, red eyes, white and gold robe, philosopher's stone pendant, large breasts",
            "name": "the white-haired grand alchemist in a white and gold robe"},
 },
 "places": {
   "toplab":   "top-floor alchemy laboratory, stone experiment table, hanging glass tubes glowing green, bellows and round flasks, lamplight",
   "brew":     "brewing room, walls lined with colorful potion bottles, wooden table with mortar and pestle, high-backed wooden chair",
   "basement": "stone basement laboratory, single cold stone experiment table, shelf of thin glass tubes, oil lamp, stone walls",
   "winlab":   "laboratory with a large window overlooking the misty city, wooden armchair with leather straps, clockwork glass apparatus",
   "study":    "alchemist's study, wide wooden desk, open blank notebook without text, quill and inkwell, bookshelves",
   "priv":     "alchemist's private room, bed with a dark green blanket, desk scattered with dried flowers, small incense burner with sweet smoke",
   "distill":  "distillation room, large copper alembic still bubbling, clear drops falling from a thin tube into a glass vessel, sweet steam",
   "archive":  "tower archive, old books stacked to the ceiling without text, reading desk, oil lamp",
   "rodlab":   "second-floor workroom, desk with polished glass rods lined up by thickness, cushioned bench, notebook without text",
   "store":    "equipment storeroom, shelves holding dozens of glass rods of different shapes, wooden workbench",
   "wash":     "washing room, wooden water tubs with glass rods shining under the water, stone floor",
   "green":    "glass rooftop greenhouse, potted herbs and green leaves, wooden cot and bench, misty light through the glass roof",
   "greennight": "glass greenhouse at night, small candles flickering among herb pots, bed of moss, moon blurred by mist",
   "herbroom": "herb drying room, bundles of dried herbs hanging from the ceiling, shelves with oil bottles",
   "furnace":  "furnace room, roaring transmutation furnace with red flames, stone workbench, red glow, heat haze",
   "hroom":    "furnace keeper's bedroom next to the furnace, warm room, bed, small wall window showing red furnace flames",
   "hall":     "white marble hall at the tower top, glowing blue transmutation circle on the floor, skylight with misty moonlight, throne",
   "bedch":    "grand alchemist's bedchamber, silk canopy bed with layered white curtains, thin incense smoke",
   "observ":   "observatory, domed ceiling painted with a star chart, brass armillary sphere, telescope, long sofa",
   "spring":   "elixir spring room, white marble basin filled with golden elixir, warm steam among pillars",
 },
 "atk": {
   "m1": ("toplab", "he lies on his back on the stone experiment table with his chest bared, round glass flasks suctioned onto both of his nipples, tubes to a bellows, the alchemist pumps the bellows while writing with a quill, his swollen nipples inside the glass, trembling"),
   "m2": ("brew", "he sits in the high-backed wooden chair gripping the armrests, the alchemist leans in grinding pink powder in a mortar under his nose, sweet pink vapor swirling around his head, mouth open, drool, cum on his thighs, no hands on him"),
   "m3": ("basement", "from side, he lies on his back on the stone experiment table holding his knees, a thin glass tube of pink jelly inserted in the tip of his penis, the alchemist stands between his legs pegging his anus with a green glass strap-on, anal, his own penis separate", {"pen": "strapon"}),
   "e1": ("rodlab", "from side, he is on all fours on the cushioned bench with his hips raised, the apprentice kneels behind him pushing a grooved glass rod into his anus against his prostate, precum dripping onto the bench, trembling knees", {"pen": "toy"}),
   "e2": ("green", "he lies face down on the wooden cot, the herbalist sits beside him sliding one finger coated in green ointment into his anus, a clay jar of ointment in her other hand, glistening ointment on his buttocks"),
   "e3": ("furnace", "he kneels on the stone floor with his hands behind his back, a thin gold ring clamped tight around the base of his erection, the furnace keeper sits on the workbench with legs crossed curling one gloved finger to tighten it, sweat, red glow"),
   "boss": ("hall", "from side, he lies on his back inside the glowing transmutation circle with legs raised, the grand alchemist leans over him licking his nipple while penetrating his anus, anal, his own penis separate, moonlight from the skylight", {"pen": "penis"}),
 },
 "atk_desc": {
   "m1": "the alchemist sucks his nipples into glass flasks with a bellows.",
   "m2": "the alchemist melts his mind with the scent of her aphrodisiac.",
   "m3": "the alchemist fills his urethra with jelly and pegs him on the experiment table.",
   "e1": "the apprentice probes his prostate with a glass rod.",
   "e2": "the herbalist rubs herbal ointment deep inside him.",
   "e3": "the furnace keeper locks his release with a transmutation ring.",
   "boss": "the grand alchemist licks his nipple while penetrating him.",
 },
 "lose": {
   # パラケルシア 技1 フラスコの吸引
   "btl_m1": ("toplab", "he lies on his back on the stone experiment table, the alchemist pins both of his wrists above his head with one hand, round glass flasks suctioned on both of his nipples, her other hand squeezing the bellows, swollen nipples in the glass, toes curling"),
   "onani_m1": ("brew", "sitting alone in a wooden chair with his chest out, two round glass flasks suctioned on his own nipples, squeezing a rubber bulb in his own hand, head tilted back, penis untouched, the alchemist stands by the brewing pot far behind watching"),
   "inochi_m1": ("winlab", "he sits in the wooden armchair by the window, wrists strapped loosely to the armrests with leather belts, clockwork suction flasks on both nipples, swollen pink nipples, the alchemist touches one nipple tip with a thin brush, a pale blue vial on the sill"),
   "onedari_m1": ("study", "he lies on his back on the wide study desk, a large bell-shaped glass flask suctioned over his nipple, the alchemist sucks on its thin tube, a notebook of his own handwriting open beside his face without text, quill and ink"),
   # 技2 媚薬の調合
   "btl_m2": ("brew", "he sits in the high-backed wooden chair clutching the armrests, the alchemist stands before him dripping a red drop from a glass pipette into the mortar, pink sweet vapor around his head, mouth open, cum on his thighs, no hands on him"),
   "onani_m2": ("archive", "sitting alone at the reading desk with his hands resting on his knees, head tilted back, mouth open, a recipe book open before him without text, faint pink vapor drifting, penis untouched, the alchemist watches from behind a far bookshelf"),
   "inochi_m2": ("priv", "he sits on the alchemist's bed, the alchemist sits beside him and draws his face to the side of her neck, sweet pink vapor rising from her skin, a green vial in her other hand, his mouth open, drool, trembling"),
   "onedari_m2": ("distill", "he sits on a stool before the copper still, the alchemist stands behind him spraying fine perfume mist at his face from an atomizer, pink mist, a clear drop falling from the still, cum on his thighs, a signed recipe paper without text"),
   # 技3 実験台の上で
   "btl_m3": ("basement", "from side, he lies on his back on the stone experiment table holding his knees, a thin glass tube of pink jelly in the tip of his penis, the alchemist between his legs pegging his anus with a green glass strap-on, anal, his own penis separate, pink jelly and cum on his belly", {"pen": "strapon"}),
   "onani_m3": ("basement", "sitting alone on a stool beside the stone table, fists clenched on his knees, head tilted back, mouth open, a glass tube and a green glass dildo lying on the table, faint pink vapor, penis untouched, the alchemist watches from the far doorway"),
   "inochi_m3": ("basement", "from side, he lies curled on his side on the stone table, the alchemist lies behind him hugging him and pegging his anus with a green glass strap-on, anal, her fingers pinching his nipple, blue jelly at the tip of his penis, his own penis separate, a clear vial nearby", {"pen": "strapon"}),
   "onedari_m3": ("basement", "from side, he stands bent over the stone table facing a tall old mirror, the alchemist behind him pegging his anus with a green glass strap-on, anal, a thin tube of amber jelly in the tip of his penis, his own penis separate, amber jelly dripping", {"pen": "strapon"}),
   # e1 ミント ガラス棒の
   "btl_e1": ("rodlab", "from side, he is on all fours on the cushioned bench, the apprentice kneels behind him slowly turning a thick grooved glass rod in his anus against his prostate, rows of glass rods on the desk, precum dripping onto the cloth", {"pen": "toy"}),
   "onani_e1": ("wash", "kneeling alone beside the water tubs, one arm reaching behind with two cold wet fingers in his own anus, the other hand gripping the tub rim, glass rods shining in the water, penis untouched, the apprentice watches from the far doorway holding a notebook"),
   "inochi_e1": ("store", "from side, he stands bent over the workbench with his palms flat, the apprentice kneels behind him pushing a glass rod with round beads into his anus, her fingertips on his inner thigh counting his pulse, a pale yellow vial on the shelf", {"pen": "toy"}),
   "onedari_e1": ("rodlab", "he lies on his back on the desk holding his own knees, the apprentice stands between his legs pushing a knobbed glass rod into his anus, her other hand writing in a notebook without text, a bundle of glass rods on a cloth", {"pen": "toy"}),
   # e2 セリ 薬草の軟膏
   "btl_e2": ("green", "he lies face down on the wooden cot, the herbalist sits beside him with one finger coated in green ointment deep in his anus, a clay jar of ointment in her other hand, cum on the sheet, potted herbs around"),
   "onani_e2": ("herbroom", "on all fours alone under hanging bundles of dried herbs, one arm reaching behind with oiled fingers in his own anus, an oil bottle beside his knee, penis untouched, the herbalist watches from the far doorway holding a basket"),
   "inochi_e2": ("green", "he lies face down across the herbalist's lap on the greenhouse bench with his hips raised, the herbalist spreads green ointment on his anus with a wooden spatula, a clay jar beside her, a brown vial on the bench"),
   "onedari_e2": ("greennight", "he lies on his back on the moss bed holding his knees, the herbalist kneels between his legs with two ointment-coated fingers inside his anus, a copper pot of melted green ointment over a candle, dazed"),
   # e3 ホムラ 錬成の指輪
   "btl_e3": ("furnace", "he lies on his back on the stone workbench before the roaring furnace, a thin gold ring clamped tight around the base of his erection, the furnace keeper stands beside him tossing a gold key into the flames, a drop of white fluid at his tip, sweat"),
   "onani_e3": ("furnace", "kneeling alone on the coal-strewn floor before the furnace, a gold ring around the base of his penis, one hand pressing his own perineum, the other arm reaching behind with a finger in his own anus, penis untouched, the furnace keeper watches from far behind"),
   "inochi_e3": ("furnace", "he kneels upright with his hands clasped behind his back, a gold ring tight on the base of his erection with a thin gold chain leading to the furnace keeper's gloved finger, the furnace keeper sits on the workbench with legs crossed, a red vial beside her"),
   "onedari_e3": ("hroom", "he lies on his back on the furnace keeper's bed, a plain gold ring tight around the base of his erection, the furnace keeper sits beside him stroking the underside of his shaft with one gloved fingertip, the furnace glowing through the wall window, tears under his bangs"),
   # boss ヘルメス 賢者の石の抱擁
   "btl_boss": ("hall", "from side, he lies on his back inside the glowing transmutation circle with his legs spread, the grand alchemist leans over him penetrating his anus, anal, her lips sucking his nipple, his own penis separate, moonlight through the skylight", {"pen": "penis"}),
   "onani_boss": ("observ", "sitting alone on the long sofa, one wet fingertip rubbing his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched, the grand alchemist watches from beside the brass telescope far behind"),
   "inochi_boss": ("bedch", "from side, he sits in the grand alchemist's lap facing her on the silk canopy bed, the grand alchemist holds his hips and thrusts up into his anus, anal, her lips sucking his nipple, his own penis separate, a silver vial on the pillow", {"pen": "penis"}),
   "onedari_boss": ("spring", "from side, he stands on one leg beside the marble basin, the grand alchemist holds his other knee up on her arm and penetrates his anus from the front, anal, bending to lick his nipple, his own penis separate, warm steam", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the alchemist tower as a vessel filled with twelve elixirs.",
 "onanie": {
   "master": ("brew", "sitting alone in the wooden chair gripping the armrests, head tilted back, mouth open, breathing in pink vapor from an open vial on the table, hands far from his crotch, penis untouched"),
   "e1": ("rodlab", "on all fours on the cushioned bench, one arm reaching behind with two fingers pressing into his own anus toward his prostate, precum dripping, penis untouched"),
   "e2": ("green", "lying face down on the wooden cot, one arm reaching behind with fingers coated in green ointment in his own anus, a clay jar of ointment beside him, penis untouched"),
   "e3": ("furnace", "kneeling with a thin gold ring around the base of his penis, one hand pressing his own perineum, the other arm reaching behind with a finger in his own anus, penis untouched"),
   "boss": ("hall", "kneeling inside the glowing transmutation circle, one wet fingertip rubbing his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched"),
 },
}
