# N35 堕天使の礼拝堂（Angel）場面データ。登場人物は全員20歳以上。責め手は女性の堕天使（ルシエル・セラ・アザリエル）と天使の男の娘（ノア・ベル）。光は赤・金・紫（青くしない）。
DATA = {
 "code": "Angel",
 "world": "ruined white chapel on a rocky peak above a sea of clouds, broken stained glass casting red gold and purple light, black feathers drifting, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 31 years old, tall, long legs, both eyes clearly visible, fallen angel, black wings, broken halo, blonde hair, long hair, red eyes, black and gold vestments, cleavage, benevolent smile, large breasts",
         "name": "the blonde fallen angel in black and gold vestments",
         "neg": "blue theme, blue light"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, angel, small grey wings, pink hair, short hair, gold eyes, white choir robe, earnest smile",
          "name": "the pink-haired choir angel in a white choir robe",
          "neg": "blue theme, blue light"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 26 years old, both eyes clearly visible, fallen angel, black wings, white hair, long hair, purple eyes, white nun-like dress, small oil bottle, calm, large breasts",
          "name": "the white-haired oil keeper in a white nun-like dress",
          "neg": "blue theme, blue light"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 24 years old, both eyes clearly visible, angel, grey wings, brown hair, curly hair, green eyes, short vestment, barefoot, mischievous grin",
          "name": "the curly-haired bell keeper in a short vestment",
          "neg": "blue theme, blue light"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 36 years old, tall, long legs, both eyes clearly visible, fallen angel, six black wings, black halo, black hair, long hair, gold eyes, black armored dress, majestic, huge breasts",
            "name": "the black-haired six-winged archangel in a black armored dress",
            "neg": "blue theme, blue light"},
 },
 "places": {
   "nave": "crumbling nave, broken wooden pews, golden light through a hole in the roof, black feathers on the floor",
   "organ": "far end of the ruined nave, old pipe organ, organ bench, candlelight",
   "altar": "white marble altar, candlesticks, red gold and purple stained glass light on the skin",
   "steps": "stone steps before the altar, candles, stained glass light",
   "confess": "narrow wooden confessional booth with a lattice window, dim, old wood",
   "font": "white stone holy water font at the nave entrance, cool water",
   "choir": "tiered wooden choir stalls, polished handrails, singing echoing from the ceiling",
   "choir_room": "choir dressing room, white choir robes on a rack, music stand, a single candle",
   "belfry": "bell chamber at the top of the tower, great bell and rows of small bells, cold wind",
   "belfry_top": "railing at the top of the bell tower above a sea of clouds, strong wind, sunset",
   "oil": "holy oil room, shelves of small bottles, steaming copper pot of amber oil",
   "cloister": "cloister and courtyard, broken pillar arches, white flowers, moon over the sea of clouds",
   "baptistery": "round baptistery, knee-deep baptismal pool of warm water, halo light reflected on the water",
   "sacristy": "sacristy, vestment shelves, silver censer, cup of quill pens, dripping candles",
   "crypt": "underground crypt, low stone ceiling, dozens of candlesticks",
   "pilgrim": "pilgrim's bedroom, simple wooden bed, white linen sheets, moonlight from a small window, small censer",
   "nest": "sunken bed filled with black feathers, soft and deep",
   "throne": "archangel's throne room, black stone throne, carpet of black feathers, dull gold light from a black halo",
   "roof": "edge of the collapsed roof under the full moon and stars, sea of clouds, skylight glowing below",
 },
 "atk": {
   "m1": ("confess", "he sits in the narrow confessional booth, the fallen angel sits behind him wrapping his head in her black wings, her lips on his earlobe whispering, a black feather in her fingers stroking his nipple, his lips repeating"),
   "m2": ("altar", "he lies on his back on the marble altar, the fallen angel leans over him stroking his nipple with the soft tip of a black feather, red and gold stained glass light on his chest, back arched"),
   "m3": ("steps", "from side, he kneels with his hands on the altar steps, the fallen angel behind him penetrating his anus with her penis, anal, stroking his nipple with a black feather, his caged penis glowing faint gold", {"pen": "penis", "cage": True}),
   "e1": ("choir", "he sits in the choir stall, the choir angel leans over him holding his cheeks and folding grey wings around his head, kissing him deeply, tongues, saliva trail, his mouth open"),
   "e2": ("oil", "he kneels on the stone floor, the oil keeper embraces him from behind with her black wings, two oiled fingers in his anus, her other hand spreading warm amber oil over his nipple, oil dripping"),
   "e3": ("belfry", "he sits beneath the great bell, tiny silver bells clipped to both of his nipples trembling, the bell keeper hovers above with flapping grey wings striking the great bell with his palm, vibration lines"),
   "boss": ("throne", "he is wrapped in six black wings before the throne, black feather tentacles curl around his nipples, two oil-slick feather tentacles enter his anus, the archangel holds him with one hand under his chin"),
 },
 "atk_desc": {
   "m1": "the fallen angel whispers his sins into his ear.",
   "m2": "the fallen angel purifies his chest with a black feather.",
   "m3": "the fallen angel locks him in her halo and takes him.",
   "e1": "the choir angel kisses him between hymns.",
   "e2": "the oil keeper purifies him inside with holy oil.",
   "e3": "the bell keeper makes the bells on his chest ring.",
   "boss": "the archangel wraps him in six wings.",
 },
 "lose": {
   # m1 告解の囁き
   "btl_m1": ("confess", "he slumps in the confessional booth, the fallen angel behind him wraps his head in black wings whispering into his ear, black feathers stuck flat on his shoulders, her black feather on his nipple, cum on his thighs"),
   "onani_m1": ("pilgrim", "lying alone on the simple bed, stroking his own nipple with the feather of a quill pen, lips whispering, penis untouched, the fallen angel stands at the far door watching"),
   "inochi_m1": ("font", "he kneels before the holy water font, the fallen angel bends over him tracing his lips with a wet finger and whispering into his ear, a black feather resting on his chest, his lips repeating"),
   "onedari_m1": ("roof", "he lies with his head in the fallen angel's lap on the roof edge under the moon, the fallen angel bends to whisper into his ear, a black feather stroking his chest, her wings spread"),
   # m2 黒い羽根
   "btl_m2": ("altar", "he lies on his back on the marble altar, the fallen angel strokes his nipple with the shaft of a black feather, stained glass light on his skin, black feathers stuck on his chest, cum on his belly"),
   "onani_m2": ("sacristy", "sitting alone on the sacristy floor among candles, stroking his own nipple with the feather of a quill pen, head tilted back, penis untouched, the fallen angel watches from the far doorway"),
   "inochi_m2": ("cloister", "he sits among white flowers in the moonlit courtyard, the fallen angel kneels beside him brushing his nipple with the tip of a black feather, his shoulders shaking"),
   "onedari_m2": ("nest", "he sinks on his back in the bed of black feathers, the fallen angel lies beside him wrapping him in one wing, stroking his right nipple with a black feather, his mouth open"),
   # m3 光輪を嵌めて
   "btl_m3": ("steps", "from side, he kneels with his hands on the altar steps, the fallen angel behind him penetrating his anus with her penis, anal, stroking his nipple with a black feather, his cage glowing gold, his own penis separate", {"pen": "penis", "cage": True}),
   "onani_m3": ("baptistery", "kneeling alone knee-deep in the baptismal pool, stroking his own nipple with a black feather, the other arm reaching behind with a finger in his own anus, not touching the cage, the fallen angel watches from the far door", {"cage": True}),
   "inochi_m3": ("choir", "from side, he kneels bent over a choir stall in a praying pose, the fallen angel behind him penetrating his anus with her penis, anal, her wing tip brushing his nipple, his own penis separate", {"pen": "penis", "cage": True}),
   "onedari_m3": ("crypt", "from side, he lies on his back on the stone floor among dozens of candles holding his knees, the fallen angel between his legs penetrating his anus with her penis, anal, his own penis separate", {"pen": "penis", "cage": True}),
   # e1 ノア
   "btl_e1": ("choir", "he sits in the choir stall, the choir angel holds his cheeks with grey wings folded around them, kissing him deeply, tongues, saliva dripping, cum on his thighs"),
   "onani_e1": ("choir_room", "sitting alone before the music stand, sucking his own fingers deeply, the other wet fingers tracing his own lips and nipple, penis untouched, the choir angel watches from the far doorway"),
   "inochi_e1": ("cloister", "he lies on the courtyard bench with his head in the choir angel's lap, the choir angel bends down kissing him, grey wings wrapped around them, white flowers"),
   "onedari_e1": ("organ", "he sits beside the choir angel on the organ bench, the choir angel presses one key and kisses him deeply, tongue deep, a grey wing around his shoulders"),
   # e2 セラ
   "btl_e2": ("oil", "he kneels on the stone floor, the oil keeper embraces him from behind with her black wings, two oiled fingers deep in his anus, the other hand oiling his nipple, amber oil dripping, cum on the floor"),
   "onani_e2": ("confess", "kneeling alone in the confessional booth, one arm reaching behind with oiled fingers in his own anus, lips moving in prayer, penis untouched, the oil keeper looks through the far lattice window"),
   "inochi_e2": ("pilgrim", "he lies on his side on the simple bed, the oil keeper lies behind him wrapping him in one black wing, two oiled fingers in his anus, oil glistening on his chest"),
   "onedari_e2": ("baptistery", "he kneels knee-deep in the warm pool bent forward, the oil keeper kneels beside him with two oiled fingers deep in his anus, the other hand on his back, lips moving in prayer"),
   # e3 ベル
   "btl_e3": ("belfry", "he sits beneath the great bell with his chest bare, tiny silver bells clipped to his nipples trembling, the bell keeper hovers above striking the great bell, vibration lines, cum on the floor"),
   "onani_e3": ("nave", "sitting alone on a broken pew in the evening light, trembling fingertips pressed on his own nipples, penis untouched, the bell keeper peeks out from behind a far pillar watching"),
   "inochi_e3": ("font", "he kneels before the holy water font, the bell keeper stands behind him covering his ears with both hands, tiny silver bells clipped to his nipples trembling, his mouth open"),
   "onedari_e3": ("belfry_top", "he sits on the platform by the railing above the sea of clouds, tiny silver bells on his nipples, the bell keeper stands before him pressing his bare sole on his penis, footjob, wind"),
   # boss アザリエル
   "btl_boss": ("throne", "from side, he lies on his back on the black feather carpet, the archangel over him penetrating his anus with her penis, anal, six black wings around them, feather tentacles curling on his nipples, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("nest", "lying alone in the bed of black feathers, one hand stroking his own nipple like a feather, the other arm reaching behind with fingers twisting into his own anus, penis untouched, the archangel stands far away watching"),
   "inochi_boss": ("cloister", "he is held in midair in six black wings between broken pillars under the moon, black feather tentacles curling on his nipples and two entering his anus, the archangel holding his chin"),
   "onedari_boss": ("altar", "from side, he lies on his back on the altar surrounded by six black wings, the archangel over him penetrating his anus with her penis, anal, feather tentacles on his nipples, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in the chapel forever as a devoted believer.",
 "onanie": {
   "master": ("altar", "lying alone on the marble altar, stroking his own nipple with a black feather, the other hand spread on the cold stone, back arched, penis untouched"),
   "e1": ("choir", "sitting alone in the choir stall, sucking his own fingers deeply as if kissing, the other wet fingers tracing his own lips and nipple, penis untouched"),
   "e2": ("oil", "kneeling alone on the stone floor, one arm reaching behind with fingers dripping amber oil in his own anus, lips moving in prayer, penis untouched"),
   "e3": ("belfry", "sitting alone beneath the great bell with his chest out, trembling fingertips pressed on his own nipples vibrating quickly like ringing bells, bare feet on the cold floor, penis untouched"),
   "boss": ("nest", "lying alone in the black feathers, one hand stroking his own nipple like a feather, the other arm reaching behind with fingers twisting into his own anus, penis untouched"),
 },
}
