# N32 蜘蛛の古城（Arachne）場面データ。登場人物は全員20歳以上。責め手は女性のアラクネ（アラーネ・ベラ・ネフィラ）と蜘蛛の男の娘（シルク・ヨル）。
DATA = {
 "code": "Arachne",
 "world": "misty ancient castle on a mountain peak at night, silver spider webs stretched everywhere, moonlight, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 32 years old, tall, long legs, both eyes clearly visible, arachne, spider lower body, black spider legs, black hair, long hair, red eyes, extra eyes, black lace bodice, elegant, large breasts",
         "name": "the black-haired spider queen with a black spider body",
         "neg": "human legs on the spider woman, human feet on the spider woman"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 22 years old, both eyes clearly visible, spider legs from back, white hair, short hair, red eyes, white woven short robe, innocent smile",
          "name": "the white-haired spinner in a woven white robe"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 27 years old, both eyes clearly visible, arachne, red striped spider lower body, red hair, wavy hair, gold eyes, black low-cut top, sultry, large breasts",
          "name": "the red-haired venom spider with a red striped spider body",
          "neg": "human legs on the spider woman, human feet on the spider woman"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 24 years old, both eyes clearly visible, spider legs from back, brown hair, braid, purple eyes, brown cloak, quiet",
          "name": "the braided web keeper in a brown cloak"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 38 years old, tall, long legs, both eyes clearly visible, arachne, gold and black spider lower body, silver hair, metallic hair, long hair, gold eyes, silver veil, motherly smile, huge breasts",
            "name": "the silver-haired cocoon mother with a gold and black spider body",
            "neg": "human legs on the spider woman, human feet on the spider woman"},
 },
 "places": {
   "gate": "castle gate and drawbridge in thick fog, rusty chains, wet stones, threads hanging from the gate arch",
   "stairs": "cold stone spiral staircase, landing with a window sealed by webs, wall torch",
   "hall": "great hall with a huge silver spider web from floor to ceiling, moonlight from high windows",
   "throne": "ebony throne at the center of a giant silver web, moonlit great hall",
   "guest": "canopy bed with dusty dark green velvet, spider webs as bed curtains, a single candle",
   "spin": "spinning room, old spinning wheel, piles of white thread skeins, beeswax candles",
   "wardrobe": "wardrobe room, rows of white woven robes hanging, tall standing mirror",
   "green": "poison greenhouse under a glass roof, moonlight, red flowers, stone table, damp soil",
   "bath": "old dry marble bathtub, cracked walls with moonlight shining through, cold stone",
   "chapel": "ruined chapel, broken stained glass casting colored moonlight, dusty pews",
   "cage": "large birdcage hanging from the corridor ceiling on silver threads, dark courtyard far below",
   "tower": "web keeper's tower, watch window with night wind, layers of webs, distant valley lights",
   "wall": "top of the castle wall at night, starry sky, thin threads on the parapet",
   "balcony": "moon-viewing balcony, huge full moon, railing tangled with vines and threads, mist rising from the valley",
   "cellar": "underground cocoon cellar, white silk cocoons hanging from every pillar, warm humid air",
   "cradle": "cocoon mother's chamber, huge cradle woven from silver thread, soft glow",
 },
 "atk": {
   "m1": ("hall", "he hangs in the silver web with his arms spread, the spider queen embraces him from behind with her black spider legs, her fangs resting on his neck without piercing, six red eyes glowing, no hand on his penis, trembling"),
   "m2": ("hall", "he is stuck spread-eagle on the silver web, the spider queen stands before him, a thick soft bundle of silver threads extends from her fingertips into his anus like a tentacle, glistening honey, his back arched"),
   "m3": ("hall", "from side, he is suspended in the air by silver threads with legs spread, the spider queen holds his hips with her black spider legs penetrating his anus with her penis, anal, thin threads tied to his nipples pulled by her fingers, his own penis separate", {"pen": "penis"}),
   "e1": ("spin", "he sits bound to a chair by white threads, the spinner kneels between his knees holding them apart with his back spider legs, guiding a hair-thin white thread into his urethra, the other fingers rolling his nipple"),
   "e2": ("green", "he lies on the stone table among red flowers, the venom spider leans over him with her red striped spider legs around the table, kissing him deeply, honey-colored saliva dripping, his lips glossy"),
   "e3": ("tower", "he lies on his back on layers of web before the watch window, legs spread, the web keeper kneels between his legs pushing a string of thread-wound beads into his anus one by one, the web swaying", {"pen": "toy"}),
   "boss": ("cradle", "inside a half-open white silk cocoon in the silver cradle, the cocoon mother embraces him and licks his nipple, a thick bundle of silver threads from her fingers enters his anus, his face buried in her chest"),
 },
 "atk_desc": {
   "m1": "the spider queen presses her venom fangs to his neck.",
   "m2": "the spider queen spins a thread bundle deep inside him.",
   "m3": "the spider queen hangs him in threads and takes him.",
   "e1": "the spinner threads a fine silk strand into him.",
   "e2": "the venom spider feeds him her venom kiss.",
   "e3": "the web keeper counts thread beads into him.",
   "boss": "the cocoon mother holds him inside her cocoon.",
 },
 "lose": {
   # m1 媚毒の牙
   "btl_m1": ("throne", "he hangs in threads before the ebony throne, the spider queen wraps him from behind with her black spider legs, fangs resting on his neck, two faint red dots, a bundle of silver threads in his anus, cum dripping"),
   "onani_m1": ("guest", "on his knees alone on the canopy bed, one arm reaching behind with bundled fingers twisting into his own anus, the other hand stroking his own neck, penis untouched, the spider queen hangs in the canopy web far above watching"),
   "inochi_m1": ("cage", "he sits in the swaying hanging birdcage with the door open, the spider queen clings to the bars from outside, fangs at his neck, a bundle of silver threads from her fingers into his anus, cut threads floating"),
   "onedari_m1": ("balcony", "he leans back against the railing held by threads under the full moon, the spider queen towers before him with her lips and fangs at his neck, a bundle of silver threads from her fingers into his anus, cum on his belly"),
   # m2 繭紡ぎ
   "btl_m2": ("hall", "he is stuck spread-eagle on the glowing silver web, the spider queen before him, a thick bundle of threads from her fingertips deep in his anus spreading open inside, cum on the web, the web trembling"),
   "onani_m2": ("spin", "on all fours alone beside the spinning wheel, one arm reaching behind with bundled fingers twisting into his own anus, penis untouched, white thread skeins around him, the spider queen watches from the far doorway"),
   "inochi_m2": ("stairs", "he is bent forward over the stone steps of the landing, threads holding his waist, the spider queen above him on the stairs, a thick bundle of silver threads from her fingertips entering his anus, torchlight"),
   "onedari_m2": ("cellar", "he hangs from a pillar by threads among white cocoons, legs apart, the spider queen before him counting on her fingers, a bundle of silver threads from her other hand deep in his anus, flushed"),
   # m3 吊るして貫く
   "btl_m3": ("hall", "from side, he is suspended in the center of the web by threads with legs spread, the spider queen holds his hips with her black spider legs penetrating his anus with her penis, anal, nipple threads pulled taut, his own penis separate, cum dripping", {"pen": "penis"}),
   "onani_m3": ("chapel", "kneeling alone on a dusty pew in colored moonlight, one arm reaching behind with bundled fingers in his own anus, the other hand pinching his own nipple, penis untouched, the spider queen hangs from the broken window watching"),
   "inochi_m3": ("gate", "from side, in the fog before the castle gate, he hangs in threads bent forward, the spider queen behind him penetrating his anus with her penis, anal, pulling the threads on his nipples, drawbridge chains, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("throne", "the spider queen sits on the ebony throne, he is lowered by threads onto her lap facing her, straddling her, her penis deep in his anus, anal, nipple threads in her fingers, his own penis separate", {"pen": "penis"}),
   # e1 シルク
   "btl_e1": ("spin", "he sits bound to a chair before the spinning wheel, the spinner holds his knees open with his back spider legs, guiding a hair-thin thread into his urethra, rolling his nipple with thread-wound fingers, cum leaking"),
   "onani_e1": ("wall", "sitting alone on the rampart under the stars with knees apart, one finger tracing a thin line up his own perineum, penis untouched, the spinner crawls down the far wall on his spider legs watching"),
   "inochi_e1": ("guest", "he lies on the canopy bed with loose threads around him, the spinner sits beside him unwinding one thread and guiding its thin end into his urethra, the other hand rolling his nipple, candlelight"),
   "onedari_e1": ("wardrobe", "he stands before the tall mirror among hanging white robes, the spinner behind him reaching around, one hand guiding a hair-thin thread into his urethra, the other rolling his nipple, knees shaking"),
   # e2 ベラ
   "btl_e2": ("green", "he lies on the stone table among red flowers, the venom spider leans over him kissing deeply, her red striped spider legs caging the table, one soft furry leg tip stroking his penis, cum on his belly"),
   "onani_e2": ("bath", "sitting alone in the dry marble bathtub, sucking his own fingers deeply, the other wet hand tracing his own neck and nipple, penis untouched, the venom spider hangs from the ceiling on a thread watching"),
   "inochi_e2": ("stairs", "he sits on the stone steps of the landing, the venom spider bends over him kissing him deeply as if sucking out poison, saliva trail, one furry red striped leg tip stroking his penis"),
   "onedari_e2": ("cage", "he kneels inside the swaying hanging birdcage, the venom spider hugs the cage with her red striped spider legs, leaning in through the open door kissing him, honey drops falling onto his tongue"),
   # e3 ヨル
   "btl_e3": ("tower", "he lies on his back on the layered web with legs spread, the web keeper kneels between his legs pushing a string of thread-wound beads into his anus, the web rocking, cum on his belly", {"pen": "toy"}),
   "onani_e3": ("hall", "on all fours alone at the edge of the great web, one arm reaching behind with a finger in his own anus, counting on his other hand, penis untouched, the web keeper descends on a thread far away watching"),
   "inochi_e3": ("chapel", "he lies on his side on a dusty pew, the web keeper sits by his hips slowly pulling a string of thread-wound beads out of his anus one by one, whispering into his ear, colored moonlight", {"pen": "toy"}),
   "onedari_e3": ("balcony", "he is bent over the railing held at the waist by threads under the full moon, the web keeper behind him pulling a string of thread-wound beads out of his anus all at once, cum dripping", {"pen": "toy"}),
   # boss ネフィラ
   "btl_boss": ("cradle", "inside a half-closed silk cocoon in the silver cradle, he lies on his back, the cocoon mother on top of him licking his nipple, her penis deep in his anus, anal, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("cellar", "curled up alone on the floor among hanging cocoons, wet fingers stroking his own nipple, the other arm reaching behind with fingers in his own anus, penis untouched, the cocoon mother watches from between pillars"),
   "inochi_boss": ("hall", "inside a closed translucent white cocoon on the web, moonlight through the silk, the cocoon mother holds him in her arms licking his nipple, a thick bundle of silver threads from her fingers in his anus"),
   "onedari_boss": ("guest", "from side, he lies on his back on the canopy bed turning into a cocoon, the cocoon mother over him penetrating his anus with her penis, anal, her silver veil over his face, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "wraps him in a warm silk cocoon to await his rebirth as the spiders' mate.",
 "onanie": {
   "master": ("hall", "kneeling alone at the foot of the silver web, one arm reaching behind with bundled fingers twisting into his own anus like a thread bundle, the other hand clutching the web, penis untouched"),
   "e1": ("spin", "sitting alone on the floor beside the spinning wheel with knees apart, one finger tracing a thin line up his own perineum, the other hand rolling his own nipple, penis untouched"),
   "e2": ("green", "sitting alone on the stone table among red flowers, sucking his own fingers deeply, the other wet hand tracing his own neck and nipple, penis untouched"),
   "e3": ("tower", "lying alone on the web on his side, one arm reaching behind with a finger sliding in and out of his own anus, counting on his other hand, penis untouched"),
   "boss": ("cellar", "curled up alone among hanging cocoons, wet fingers stroking his own nipple, the other arm reaching behind with fingers in his own anus, penis untouched"),
 },
}
