# N59 森のお菓子の家（Candy）場面データ。登場人物は全員20歳以上（女性＋ニューハーフ：マカロン・カラメラ）。食べる・焼く・溶かす結末は描かない。
DATA = {
 "code": "Candy",
 "world": "candy house deep in a forest, walls of cookies and chocolate, candy glass windows, cream frosting, warm light, sweet colors, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, mature face, sharp adult features, 32 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, long wavy hair, red eyes, chocolate brown dress, frilly apron, big witch hat, witch, large breasts, voluptuous",
         "name": "the brown-haired sweets witch in a chocolate dress and big witch hat"},
   "e1": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, pink hair, bob cut, small horns, green eyes, white chef coat, pink skirt, demon girl, medium breasts",
          "name": "the pink-bob horned patissier in a white chef coat"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, loose braid, brown eyes, translucent amber candy-colored apron dress, witch, small breasts",
          "name": "the blonde-braided candy artisan in an amber apron dress"},
   "e3": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, long legs, orange hair, short hair, amber eyes, toasty brown dress, cinnamon ribbon, fairy, small breasts",
          "name": "the orange-haired cookie fairy in a toasty brown dress"},
   "boss": {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 37 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, white hair, long hair, black horns, red eyes, black chef coat worn as a dress, caramel gold ornaments, demon girl, large breasts",
            "name": "the white-haired horned demon patissier in a black chef coat dress"},
 },
 "places": {
   "kitchen":  "candy house kitchen, big wooden table dusted with powdered sugar, bowls of whipped cream and whisks, jars of syrup, lamp light",
   "living":   "candy house living room, cookie walls, big amber candy lamp, low table with chocolates and sugar cubes",
   "dining":   "sunny morning dining room of the candy house, pot of chocolate sauce, pastry brush, framed paper napkin on the wall",
   "entrance": "candy house entrance hall, open door to the dark forest at morning, candy glass window",
   "pantry":   "chocolate pantry, shelves full of chocolates, tiny window",
   "guest":    "candy house guest room, bed with a plate of chocolates on the nightstand, window to a moonlit courtyard",
   "workshop": "patissier workshop, piping bags and nozzles on the wall, bowls of colorful jelly, steel worktable, wall calendar without text",
   "lounge":   "workshop break room, long couch, bottles of lotion on a shelf, tiny window to the workshop",
   "candyroom":"candy craft studio upstairs, candy birds and flowers glowing amber on the windowsill, thin golden candy threads, craft table",
   "veranda":  "wooden veranda of the candy house, floor cushion, cookie jar, afternoon light",
   "attic":    "cozy attic room of the candy house, wooden floor, cinnamon sticks, round window",
   "meadow":   "meadow behind the candy house, picnic blanket, jar of cinnamon powder, sunny sky",
   "forest":   "dark forest path at night, glowing sweets placed as a trail on the tree trunks",
   "honey":    "honey storeroom, shelves of amber honey pots, lotion bottle, ornate window",
   "blackroom":"black-doored room with glass display shelves of sleeping candy dolls, velvet sofa, pot of amber honey, piping bags",
 },
 "atk": {
   "m1": ("kitchen", "he sits on the wooden table with his chest out, the sweets witch stands in front of him pinching both of his nipples with fingertips covered in whipped cream, white cream on his chest, erect nipples"),
   "m2": ("living", "he lies on the sofa, the sweets witch leans over him feeding him melted chocolate mouth to mouth, deep kiss, tongues, brown chocolate saliva trail"),
   "m3": ("kitchen", "from side, he lies on his back on the powdered sugar table holding his knees, the sweets witch stands between his legs pegging his anus with a translucent amber candy strap-on, anal, licking his nipple, his own penis separate", {"pen": "strapon"}),
   "e1": ("workshop", "from side, he lies face down on the steel worktable with his hips raised, the patissier squeezes a piping bag with the metal nozzle in his anus, colorful jelly filling him, dripping"),
   "e2": ("candyroom", "he sits on a chair with legs spread, the candy artisan kneels before him threading a hair-thin golden candy thread into his urethra, her other fingers holding his penis gently, precum"),
   "e3": ("veranda", "he lies on the floor cushion, the cookie fairy lies beside him blowing a long cinnamon-scented breath into his ear, a sugar brush in her hand, his back arched, drool, hips twitching"),
   "boss": ("blackroom", "he lies on his back on the velvet sofa, the demon patissier bends over him licking honey from his nipple, her long honey-coated fingers in his anus, jelly dripping, amber honey on his chest"),
 },
 "atk_desc": {
   "m1": "the sweets witch plays his nipples with whipped cream fingers.",
   "m2": "the sweets witch feeds him chocolate mouth to mouth.",
   "m3": "the sweets witch pegs him on the kitchen table with a candy strap-on.",
   "e1": "the patissier pipes jelly into him.",
   "e2": "the candy artisan threads golden candy into his urethra.",
   "e3": "the cookie fairy melts his mind with cinnamon breath.",
   "boss": "the demon patissier steeps him in honey.",
 },
 "lose": {
   # m1 生クリームの指
   "btl_m1": ("kitchen", "he sits on the edge of the table with his shirt open and chest out, the sweets witch pinches both of his cream-covered nipples one by one, bowl of whipped cream, dazed"),
   "onani_m1": ("living", "sitting alone in the corner of the room sucking two of his own fingers, a piece of chocolate on his tongue, the other wet fingertip rubbing his own nipple, penis untouched, the sweets witch watches through the window far away"),
   "inochi_m1": ("entrance", "he sits on the stairs leaning back, dots of white whipped cream in a line from his collarbone to his nipples, the sweets witch pinches his nipples, forest seen through the open door"),
   "onedari_m1": ("kitchen", "he sits on a chair unbuttoning his shirt, chest out, the sweets witch reads an open leather recipe book without text while pinching his cream-covered nipple, bowl of whipped cream"),
   # m2 チョコの口移し
   "btl_m2": ("living", "he lies on the sofa lifting his head, the sweets witch holds a chocolate between her lips and kisses him deeply, tongues, chocolate saliva, amber lamp light"),
   "onani_m2": ("pantry", "kneeling alone between the chocolate shelves, sucking two of his own fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched, the sweets witch watches through the tiny window far away"),
   "inochi_m2": ("entrance", "morning, he kneels on the floor at the open front door with the forest behind, tongue out, the sweets witch bends down feeding him chocolate mouth to mouth, deep kiss, chocolate saliva trail"),
   "onedari_m2": ("dining", "he sits on a dining chair with his tongue out, the sweets witch paints chocolate sauce on his lips with a pastry brush and licks it off, deep kiss, brown saliva trail"),
   # m3 テーブルの上で（飴細工のペニバン）
   "btl_m3": ("kitchen", "from side, he lies on his back on the powdered sugar table with legs lifted, the sweets witch pegs his anus with a translucent amber candy strap-on, anal, licking his nipple, powdered sugar stuck to his sweaty skin, his own penis separate", {"pen": "strapon"}),
   "onani_m3": ("guest", "sitting alone on the bed sucking his own fingers, one arm reaching behind with two of his own fingers in his own anus, penis untouched, the sweets witch holding a lamp watches through the courtyard window far away"),
   "inochi_m3": ("kitchen", "from side, he lies on the powdered sugar table with his legs wrapped around the sweets witch's waist, the sweets witch pegs his anus with a translucent amber candy strap-on, anal, sucking his nipple, his own penis separate", {"pen": "strapon"}),
   "onedari_m3": ("kitchen", "from side, he lies on his back on the table holding his knees, reading from an open recipe book without text, the sweets witch pegs his anus with a translucent amber candy strap-on, anal, bottle of flower syrup, his own penis separate", {"pen": "strapon"}),
   # e1 絞り袋の（アナルゼリー）
   "btl_e1": ("workshop", "from side, he kneels on the steel worktable with his hips raised, the patissier squeezes a piping bag into his anus, pink jelly overflowing, her other hand flicking his nipple, his knees trembling"),
   "onani_e1": ("lounge", "kneeling alone on the couch with his hips raised, one arm reaching behind with lotion-covered fingers in his own anus, lotion dripping, penis untouched, the patissier peeks through the tiny window far away"),
   "inochi_e1": ("workshop", "he lies against the patissier on the worktable, the patissier hugs him from behind pinching his nipples, three colors of jelly dripping from his anus, a piping bag beside them"),
   "onedari_e1": ("workshop", "from side, he lies on his back on the worktable with legs spread, the patissier squeezes a piping bag of white jelly into his anus while licking whipped cream from his nipple, strawberry jelly leaking"),
   # e2 飴の糸（尿道）
   "btl_e2": ("candyroom", "he sits on a chair with legs spread, the candy artisan sits opposite rubbing his penis with the sole of her bare candy-glazed foot, a thin golden candy thread resting at his urethral opening, precum"),
   "onani_e2": ("candyroom", "sitting alone on a chair with legs spread, one fingertip tracing his own perineum upward slowly, the other hand gripping the chair, penis untouched, the candy artisan watches through a glass window far away"),
   "inochi_e2": ("candyroom", "he lies back on a couch, the candy artisan slides her bare candy-glazed sole up his penis, a golden candy thread with tiny beads hanging from his urethra, cum on his belly, candy birds on the windowsill"),
   "onedari_e2": ("candyroom", "he sits on the craft table with legs spread, the candy artisan sits on a chair rubbing his penis with her bare candy-glazed foot, a hair-thin golden candy thread inserted in his urethra, design drawings without text"),
   # e3 シナモンの吐息（脳イキ）
   "btl_e3": ("veranda", "he lies in the cookie fairy's arms on the floor cushion, the cookie fairy hugs him tightly blowing a long breath into his ear while brushing his nipple with a sugar brush, cum on his belly"),
   "onani_e3": ("attic", "lying alone on his back on the wooden floor breathing in deeply, a cinnamon stick under his nose, back arched, hands far from his crotch, penis untouched, the cookie fairy watches from the top of the stairs"),
   "inochi_e3": ("forest", "he sits on the grass blindfolded with a ribbon, the cookie fairy hugs him from behind blowing into his ear and brushing his nipple with a sugar brush, cinnamon sticks stuck in the ground, cum"),
   "onedari_e3": ("meadow", "he lies on his back on the picnic blanket, the cookie fairy lies over him brushing his cinnamon-dusted nipple with a sugar brush and blowing into his ear, jar of cinnamon powder, cum on his belly"),
   # boss 蜜漬け
   "btl_boss": ("blackroom", "he lies on his back on the velvet sofa limp, the demon patissier drapes thin shining golden candy glaze over his body like a blanket, honey shining on his nipples, jelly dripping from his anus, glass shelves of sleeping candy dolls, he falls asleep", {"flaccid": True}),
   "onani_boss": ("honey", "kneeling alone between the honey pots, one honey-dipped fingertip rubbing his own nipple, the other arm reaching behind with lotion fingers in his own anus, penis untouched, the demon patissier watches through the ornate window far away"),
   "inochi_boss": ("blackroom", "he lies on the velvet sofa drowsy, the demon patissier licks honey from his left nipple, her honey-coated fingers deep in his anus, jelly leaking, glass display shelves behind"),
   "onedari_boss": ("blackroom", "he lies across the demon patissier's lap on the velvet sofa, the demon patissier spoons amber honey onto his right nipple and licks it, her other hand's fingers in his anus, a piping bag beside them, black leather notebook without text"),
 },
 "lose_desc": "glazes him in golden candy and keeps him asleep on the display shelf as her sugar doll.",
 "onanie": {
   "master": ("living", "kneeling upright, a chocolate on his tongue, sucking two of his own fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched"),
   "e1": ("workshop", "on all fours on the worktable with hips raised, one arm reaching behind with lotion-covered fingers in his own anus, lotion dripping, penis untouched"),
   "e2": ("candyroom", "sitting on a chair with legs spread, one fingertip tracing his own perineum upward slowly, the other hand gripping the chair, penis untouched"),
   "e3": ("attic", "lying on his back breathing in deeply, a cinnamon stick held under his nose, back arched, hands far from his crotch, penis untouched"),
   "boss": ("honey", "kneeling between honey pots, one honey-dipped fingertip rubbing his own nipple, the other arm reaching behind with fingers in his own anus, penis untouched"),
 },
}
