# N58 夜想サーカス（Circus）場面データ。登場人物は全員20歳以上（女性＋ニューハーフ：団長カリオペ・ラン）。鞭・痛みなし、宙吊りは安全なハーネス。
DATA = {
 "code": "Circus",
 "world": "night circus big top at midnight, red and gold striped tent, spotlights, sawdust ring, detailed background",
 "chars": {
   "m": {"type": "nh",
         "tags": "adult woman, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, red hair, long wavy hair, gold eyes, red tailcoat jacket with cinched waist, black short shorts, fishnet tights, top hat, black cane, large breasts",
         "name": "the red-haired ringmaster in a red tailcoat and top hat"},
   "e1": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, twintails, green eyes, pink leotard, feather ornaments, slim flexible body, small breasts",
          "name": "the pink-twintailed tightrope walker in a pink leotard"},
   "e2": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, black hair, long ponytail, red eyes, black military style jacket, short shorts, long boots, bundle of leather collars on her belt, medium breasts",
          "name": "the black-ponytailed beast tamer in a black military jacket"},
   "e3": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, long legs, purple hair, bob cut, gold eyes, purple tailcoat dress, white gloves, small hat, large breasts",
          "name": "the purple-bob magician in a purple tailcoat dress"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long hair, red eyes, gold sequin leotard, white feather cape, long slender legs, medium breasts",
            "name": "the blonde trapeze star in a gold sequin leotard and feather cape"},
 },
 "places": {
   "ring":     "center of the circus ring on the sawdust stage, audience seats in the dark, red and gold curtains",
   "spot":     "dark circus stage with a single white spotlight making a round circle of light on the boards, thick tent pole",
   "backstage":"behind the tent at night, between painted wagons, wooden crates, a hanging lantern",
   "wagon":    "inside a red painted circus caravan wagon, velvet seats, lamp, curtains on the window, night road outside",
   "costume":  "costume tent, racks of glittering costumes, large standing mirror, lamp light",
   "wings":    "stage wings, a large blackboard program list without text on the wall, ropes and sandbags",
   "practice": "practice ring behind the tent, straw on the ground, a single stage lamp, practice ropes stretched between posts",
   "cages":    "beast cage area behind the tent, empty iron cages, hay on the floor, dim lantern",
   "magic":    "magician's prop wagon, top hats, bouquets, a pedestal draped in black cloth, a large black magic box",
   "trapeze":  "high above the ring, trapeze bars and safety harness straps hanging from the tent ceiling, spotlight",
   "rigging":  "rehearsal shed with safety harness straps hanging from the ceiling beams, mats on the floor",
   "royal":    "luxurious gold and white circus carriage, wide velvet seat, harness straps hanging from the ceiling, dawn at the window",
 },
 "atk": {
   "m1": ("ring", "he stands with his hands clasped behind his back thrusting his chest out, the ringmaster taps his nipple with the silver tip of her black cane, her gloved fingers pinching the other nipple, erect nipples"),
   "m2": ("ring", "he kneels on the stage with his hands behind his head, the ringmaster stands behind him bending down with her lips at his ear whispering yes, his back arching by itself, drool, no hands on him"),
   "m3": ("spot", "from side, he lies on his back in the spotlight circle holding his knees, the ringmaster kneels between his legs penetrating his anus with her own penis, anal, kissing him deeply, tongues, his own penis separate", {"pen": "penis"}),
   "e1": ("ring", "he sits on a stool with a soft white silk rope stretched tight across both of his nipples, the tightrope walker hugs him from behind walking two fingers along the rope, nipples pulled"),
   "e2": ("cages", "he kneels upright on the hay with his back straight, a black leather collar with a silver ring around his neck, the beast tamer stands a few steps away raising one finger, commanding wait, trembling, no hands on him"),
   "e3": ("magic", "from side, he lies face down on the black-draped pedestal with his hips raised, the magician pushes white pearl anal beads into his anus one by one with a white-gloved finger", {"pen": "toy"}),
   "boss": ("trapeze", "he hangs in a safety harness high above the ring, a gold chastity cage on his penis, the trapeze star hangs beside him on the harness holding him and sucking his nipple", {"cage": True}),
 },
 "atk_desc": {
   "m1": "the ringmaster plays his nipples with the tip of her cane.",
   "m2": "the ringmaster rewrites his head with a whispered yes.",
   "m3": "the ringmaster kisses and takes him under the spotlight.",
   "e1": "the tightrope walker walks a rope across his nipples.",
   "e2": "the beast tamer makes him climax on command.",
   "e3": "the magician makes pearls vanish into him.",
   "boss": "the trapeze star locks him in a gold ring and licks his nipples in the air.",
 },
 "lose": {
   # m1 ステッキの先で
   "btl_m1": ("ring", "he stands with his hands clasped behind his back thrusting his chest out, the ringmaster pinches both of his nipples between the silver tip of her cane and her gloved fingers, cum on his thighs, audience seats in the dark"),
   "onani_m1": ("backstage", "sitting alone on a wooden crate thrusting his chest forward, one wet fingertip rubbing his own nipple, the other hand pinching his own nipple, penis untouched, the ringmaster stands far away holding a lantern and watching"),
   "inochi_m1": ("wagon", "he sits on the velvet seat thrusting his chest forward, the ringmaster sits opposite pressing the tip of her cane to his nipple and pinching the other with her gloved fingers, cum on his thighs, night road through the window"),
   "onedari_m1": ("ring", "he kneels on the stage with hands behind his back begging, chest thrust toward the cane, the ringmaster taps his nipple with her cane tip, a program list without text and a quill on a side table"),
   # m2 「はい」の合図
   "btl_m2": ("ring", "he kneels upright on the stage with his hands behind his head and back arched, the ringmaster stands behind him with her lips on his earlobe whispering, cum on his thighs, no hands on his body"),
   "onani_m2": ("costume", "kneeling alone in front of the standing mirror with his hands behind his head, back arched, chest thrust out, mouthing yes to himself, hands far from his crotch, penis untouched, the ringmaster watches from behind the costume racks"),
   "inochi_m2": ("wagon", "he kneels on the wagon floor between the ringmaster's feet with his hands behind his head and chest out, the ringmaster sits on the velvet seat bending down to whisper in his ear, cum on his thighs"),
   "onedari_m2": ("wings", "he kneels on the floor with his hands behind his head in front of the blackboard program list without text, the ringmaster stands beside him tapping the blackboard and whispering into his ear, cum on his thighs"),
   # m3 スポットライトの下で（NH逆アナル＋キス）
   "btl_m3": ("spot", "from side, he lies on his back in the spotlight circle with legs lifted, the ringmaster penetrates his anus with her own penis, anal, kissing him deeply, cum leaking from his anus, his own penis separate", {"pen": "penis"}),
   "onani_m3": ("practice", "sitting alone on the straw hugging his knees in the circle of the stage lamp, mouthing yes, hips twitching, hands far from his crotch, penis untouched, the ringmaster stands far away at the lamp handle watching"),
   "inochi_m3": ("wagon", "from side, he lies on his back on the bed in the caravan under a stage spotlight lamp, the ringmaster penetrates his anus with her own penis, anal, kissing him deeply, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("spot", "from side, he stands with his back against the thick tent pole in the spotlight with one leg lifted, the ringmaster penetrates his anus with her own penis, anal, kissing him deeply, his own penis separate", {"pen": "penis"}),
   # e1 綱の上で
   "btl_e1": ("ring", "he sits on a stool, a white silk rope stretched across both of his nipples, the tightrope walker hugs him tightly from behind flicking the rope up with her fingers, nipples pulled, cum on his thighs"),
   "onani_e1": ("practice", "sitting alone on the grass with his shirt open, holding both ends of a thin cord drawn across his own nipples, pulling it slowly, penis untouched, the tightrope walker watches from a practice rope far above"),
   "inochi_e1": ("wagon", "he sits in the swaying caravan, two white ropes stretched across his chest sandwiching his nipples, the tightrope walker hugs him from behind flicking the upper rope, cum on his thighs"),
   "onedari_e1": ("ring", "he stands on stage leaning back into the tightrope walker's arms, a white silk rope tied tight across his nipples, the tightrope walker kicks the rope stake, the rope bouncing, a pink program list without text on the floor"),
   # e2 首輪の合図
   "btl_e2": ("ring", "he kneels curled on a low stand wearing a black leather collar with a silver ring, the beast tamer stands with her back half turned looking over her shoulder, saying good, no hands on him, cum on his thighs"),
   "onani_e2": ("cages", "sitting alone on the hay in an empty cage, tracing a ring around his own neck with his fingertips, hips twitching, hands far from his crotch, penis untouched, the beast tamer watches from outside the cage"),
   "inochi_e2": ("cages", "he kneels upright in seiza on the hay inside a wooden transport wagon, black leather collar on his neck with nothing attached, the beast tamer leans on the far wall tugging an unconnected leash, cum on his thighs"),
   "onedari_e2": ("cages", "he kneels upright in seiza on the hay wearing a black leather collar, mouth open, the beast tamer stands before him holding a slate board without text and chalk, cum on his thighs"),
   # e3 消える手品（アナルパール）
   "btl_e3": ("magic", "from side, he lies face down on the black-draped pedestal with his hips raised, the magician pulls a string of white pearl anal beads out of his anus, one bead popping out, cum on the cloth", {"pen": "toy"}),
   "onani_e3": ("backstage", "crouching alone in the shadow of the prop wagon, one arm reaching behind with one wet finger in his own anus, penis untouched, the magician leans on the wagon window far above watching"),
   "inochi_e3": ("magic", "he lies on his back on the long seat in the prop wagon, the magician presses his lower belly with her white-gloved hand while pulling the string of anal beads out of his anus, cum on his belly", {"pen": "toy"}),
   "onedari_e3": ("magic", "he is locked in the large black magic box with only his hips sticking out, the magician stands beside the box pushing white pearl anal beads into his anus with a white-gloved finger", {"pen": "toy"}),
   # boss 宙吊りの輪（金の貞操帯＋乳首舐め）
   "btl_boss": ("trapeze", "he hangs in a safety harness high above the ring, gold chastity cage on his penis, the trapeze star holds him on the harness sucking his left nipple and pinching the right, toes pointed and trembling, clear fluid dripping from the cage", {"cage": True}),
   "onani_boss": ("rigging", "hanging alone in a safety harness, one wet fingertip rubbing his own nipple, the other hand pressing his own perineum below the gold cage, not touching the cage, the trapeze star watches from the shadow of the straps", {"cage": True}),
   "inochi_boss": ("royal", "he hangs in the harness straps inside the carriage, gold chastity cage on his penis, the trapeze star sucks his left nipple and rubs the right with her fingertip, dawn at the window, clear fluid dripping from the cage", {"cage": True}),
   "onedari_boss": ("trapeze", "he hangs in a safety harness in the spotlight, gold chastity cage on his penis with a thin chain, the trapeze star sucks his nipple and shakes the chain with her fingers, clear fluid dripping from the cage", {"cage": True}),
 },
 "lose_desc": "takes him away in the circus wagon as a new troupe member.",
 "onanie": {
   "master": ("ring", "kneeling upright with his hands behind his back, chest thrust out, one wet fingertip tapping his right nipple, the other hand pinching his left nipple hard, penis untouched"),
   "e1": ("practice", "sitting on the straw with his shirt open, holding both ends of a thin cord drawn across his own nipples, pulling it slowly, penis untouched"),
   "e2": ("cages", "kneeling upright on the hay, fingertips tracing a ring around his own neck, back straight, hands far from his crotch, penis untouched"),
   "e3": ("magic", "on all fours on the black-draped pedestal with hips raised, one arm reaching behind with one wet finger in his own anus, penis untouched"),
   "boss": ("rigging", "hanging in a safety harness, one wet fingertip rubbing his own nipple, the other hand pressing his own perineum below the gold cage, not touching the cage", {"cage": True}),
 },
}
