# N39 黒森のダークエルフ（DarkElf）場面データ。登場人物は全員20歳以上（ダークエルフは年齢不詳の成人）。女性と男の娘の混合。
ST = {"pen": "strapon"}    # ヴェイラ（黒檀）・シルヴァナ（白樺色・蔦の意匠）のペニバン

DATA = {
 "code": "DarkElf",
 "world": "dark elf village deep in a black forest at night, giant trees, rope bridges between branches, glowing green and orange mushrooms, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 31 years old, tall, long legs, both eyes clearly visible, dark elf, dark skin, pointy ears, silver hair, metallic hair, long braid, red eyes, leather breastplate, loincloth, longbow, cold expression, large breasts, confident",
         "name": "the silver-braided dark elf huntress with a longbow"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, dark elf, dark skin, pointy ears, white hair, short hair, gold eyes, leather tunic, rope, eager grin",
          "name": "the white-haired dark elf apprentice with a coil of rope"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 27 years old, both eyes clearly visible, dark elf, dark skin, pointy ears, blonde hair, long hair, green eyes, green cloak, hanging herbs, curious smile, large breasts",
          "name": "the blonde dark elf herbalist in a green cloak"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 24 years old, both eyes clearly visible, dark elf, dark skin, pointy ears, red hair, wolf cut, amber eyes, fur collar, leather boots, collars on belt, smirk",
          "name": "the red-haired dark elf beast tamer with a fur collar"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 38 years old, tall, long legs, both eyes clearly visible, dark elf, dark skin, pointy ears, light purple hair, long hair, gold eyes, vine crown, black dress, tall, mature, serene, large breasts, confident",
            "name": "the lavender-haired dark elf chieftain with a vine crown"},
 },
 "places": {
   "trap": "trap site on an animal trail, fallen leaves, a soft hemp rope net hanging from branches, dusk light through the trees",
   "hollow": "hollow at the roots of a giant tree, thick moss floor, glowing green mushrooms, water drops",
   "bridge": "swaying rope bridge between giant trees, vine handrails, white mist far below",
   "hut": "huntress's treehouse, fur rug, bows hanging on the wall, round window between branches",
   "watch": "high lookout platform on a tree branch at night, dark forest below, wind",
   "range": "archery range, straw targets on wooden posts, packed earth",
   "apothecary": "herbalist's hut, bundles of dried herbs hanging from the ceiling, mortar, steaming earthen pot, wooden examination table",
   "smoke": "smokehouse, thin herbal smoke, low ceiling, furs on the floor, warm",
   "spring": "black forest spring, dark water reflecting orange mushroom light, flat cold stones",
   "stable": "beast stable, straw floor, leather collars hanging on a wooden post, hay",
   "hay": "pile of hay outside the beast stable at night, wooden fence, glowing mushrooms",
   "meadow": "moonlit meadow, full moon, dewy grass, tiny white flowers, open sky",
   "cradle": "woven vine cradle hanging from a branch, swaying, rustling leaves",
   "gate": "forest border gate of two mossy stone pillars, a road leading out of the forest, the last glowing mushrooms",
   "hall": "chieftain's hall carved inside a giant tree trunk, throne of living vines, mushroom candlesticks",
   "altar": "village altar, a flat stone wrapped in giant tree roots, ring of glowing mushrooms around it",
   "sap": "inner chamber with a pool of amber tree sap, warm wooden floor, sweet glow",
 },
 "atk": {
   "m1": ("range", "he stands with his back against a straw target post, the huntress stands before him flicking his nipple with a hard fingertip as if plucking a bowstring, her longbow in the other hand, glowing leaf-shaped marks on his pale chest"),
   "m2": ("hollow", "from behind, he is on all fours on thick moss, the huntress kneels behind him gripping his ankle, spreading his buttocks and licking his anus with a pointed tongue, anilingus, her long ears twitching, glowing mushrooms"),
   "m3": ("hut", "from side, he lies on his back on the fur rug with legs lifted, the huntress pegs his anus with her polished ebony strap-on tied with leather cords, anal, kissing him deeply, her long ear touching his cheek, his own penis separate", ST),
   "e1": ("trap", "he kneels on fallen leaves, the apprentice hugs him from behind wrapping soft hemp rope above and below his chest, pulling the knot tight so the rope rubs over his nipples, the apprentice's long ear at his nape"),
   "e2": ("apothecary", "he lies on his back on the wooden examination table with knees spread, the herbalist inserts two thin reed tubes, one into the tip of his penis and one into his anus, pushing green translucent jelly, tilting her long ear, observing"),
   "e3": ("stable", "he sits frozen on the straw wearing a soft leather collar, the tamer crouches beside him whispering into his ear, the toe of a leather boot stroking his penis, footjob, collars hanging on the post"),
   "boss": ("hall", "he is held in the air by living vines wrapped softly around his wrists and ankles, legs spread, a slick vine tip sliding into his anus, the chieftain bends over him licking his nipple, vine throne behind"),
 },
 "atk_desc": {
   "m1": "the huntress flicks his nipples like a bowstring.",
   "m2": "the huntress licks his anus with her hunter's tongue.",
   "m3": "the huntress inspects her prey with a kiss and her strap-on.",
   "e1": "the apprentice binds his chest with trap rope in a tight hug.",
   "e2": "the herbalist fills him with herbal jelly from front and back.",
   "e3": "the tamer collars him as a pet and rubs him with a boot.",
   "boss": "the chieftain's vines explore him while she licks his nipple.",
 },
 "lose": {
   "btl_m1": ("range", "he leans against the straw target post, the huntress kneels behind him spreading his buttocks and licking his anus, anilingus, one hand reaching around to flick his nipple, a spare bowstring on his wrist, cum on the post, dazed"),
   "onani_m1": ("trap", "on all fours alone inside a hanging hemp net, one fingertip flicking his own nipple, the other wet hand stroking his own anus, penis untouched, the huntress watches from the dark trees far away, red eyes glinting"),
   "inochi_m1": ("watch", "on the lookout platform at night, the huntress sits behind him hugging him against the wind, her hard fingertip flicking his nipple, the other finger drawing a glowing leaf mark on his chest, a horn at her belt"),
   "onedari_m1": ("meadow", "he kneels on the dewy grass under the full moon pushing his chest out, the huntress stands over him flicking his right nipple with a bowstring-hard fingertip, holding her longbow, white flowers around"),

   "btl_m2": ("hollow", "from behind, he is on all fours on the moss, the huntress kneels behind him spreading his buttocks, her pointed tongue inside his anus, anilingus, glowing leaf marks along his pale back, cum dripping onto the moss"),
   "onani_m2": ("spring", "on all fours alone on a flat stone by the black spring, reaching back with wet fingers stroking his own anus, penis untouched, the huntress stands far away across the water, watching"),
   "inochi_m2": ("hut", "he lies face down on the fur rug in the treehouse, the huntress kneels over his legs licking down his lower back to his anus, anilingus, glowing marks on his back, bows on the wall"),
   "onedari_m2": ("cradle", "he lies face down in the swaying vine cradle with hips raised, the huntress leans in from the side licking his anus, anilingus, one hand gripping the vine rope above, leaves rustling"),

   "btl_m3": ("hut", "from side, he lies on his back on the fur rug holding his knees, the huntress pegs his anus with her ebony strap-on, anal, kissing him deeply, glowing marks all over his pale body, his own penis separate, cum on his belly", ST),
   "onani_m3": ("bridge", "kneeling alone on the swaying rope bridge above white mist, sucking his own fingers, the other wet fingertip pressed at his own anus, penis untouched, the huntress stands at the far end of the bridge watching"),
   "inochi_m3": ("gate", "from side, he stands bent over with hands on a mossy stone pillar, the huntress behind him pegs his anus with her ebony strap-on, anal, turning his face to kiss him, the road beyond the gate, his own penis separate", ST),
   "onedari_m3": ("smoke", "from side, he lies on his back on furs holding his knees, herbal smoke drifting, the huntress pegs his anus with her ebony strap-on, anal, kissing him deeply, her long ears twitching, his own penis separate", ST),

   "btl_e1": ("trap", "he sits on fallen leaves, the apprentice hugs him from behind, soft hemp rope wound above and below his chest, pulling the third knot tight over his nipples, pink powder drifting from a bamboo blowpipe, cum on the leaves"),
   "onani_e1": ("range", "kneeling alone behind a straw target, a shirt cord wrapped around his own chest, pulling it so it rubs over his own nipples, penis untouched, the apprentice peeks from far behind the target posts, grinning"),
   "inochi_e1": ("bridge", "on the rope bridge above white mist, a lifeline rope tied around his waist and chest, the apprentice hugs him tightly from behind in the middle of the bridge, the rope rubbing his nipples, the bridge swaying"),
   "onedari_e1": ("spring", "he kneels at the edge of the black spring, hemp rope wound around his chest, the apprentice kneels behind him pulling the rope tight and blowing sweet powder on his neck from a bamboo blowpipe"),

   "btl_e2": ("apothecary", "from front, he lies on his back on the examination table holding his knees, reed tubes in the tip of his penis and in his anus, green jelly dripping, the herbalist leans close observing, steaming pot, cum on his belly"),
   "onani_e2": ("smoke", "sitting alone in the smoky hut with knees apart, pressing up on his own perineum with one hand, the other hand reaching back with a finger in his own anus, penis untouched, the herbalist watches from the doorway far away"),
   "inochi_e2": ("spring", "he lies on his back on a flat cold stone by the black spring, the herbalist kneels beside him with two fingers in his anus spreading ointment, fingering, a reed tube in the tip of his penis, green jelly"),
   "onedari_e2": ("hollow", "he lies on his back on thick moss holding his knees, the herbalist kneels between his legs pushing green jelly through a reed tube into his anus, a second tube in the tip of his penis, a measuring spoon in her hand"),

   "btl_e3": ("stable", "he sits frozen on the straw in a soft leather collar, the tamer stands over him stroking his penis with the top of a leather boot, footjob, calling a pet name, cum on the straw, collars on the post"),
   "onani_e3": ("cradle", "sitting alone in the swaying vine cradle, one hand at his own neck feeling for a collar, lips repeating a pet name, flushed, penis untouched, the tamer sits on a far branch looking down, smirking"),
   "inochi_e3": ("hay", "he kneels frozen on the pile of hay in a new soft leather collar, the tamer stands before him pressing the sole of a leather boot on his penis, footjob, holding an old collar in one hand"),
   "onedari_e3": ("watch", "on the lookout platform at night he sits in a leather collar, the tamer stands before him with a whistle at the lips, stroking his penis with the top of a leather boot, footjob, dark forest below"),

   "btl_boss": ("hall", "from side, he lies on his back before the vine throne, wrists and ankles held by living vines, legs spread, the chieftain pegs his anus with her pale birch-wood strap-on with a vine design, anal, a vine collar on his neck, his own penis separate", ST),
   "onani_boss": ("meadow", "kneeling alone on the moonlit grass, one wet finger stroking his own nipple, the other hand reaching back with fingers twisting into his own anus like a vine, penis untouched, the chieftain stands far away at the meadow's edge"),
   "inochi_boss": ("altar", "he lies on his back on the root-covered altar stone inside a ring of glowing mushrooms, vines holding his wrists, a slick vine tip sliding into his anus, the chieftain bends over him licking his nipple"),
   "onedari_boss": ("sap", "from side, he lies on his back on the warm wooden floor by the amber sap pool, vines around his wrists, the chieftain pegs his anus with her pale strap-on, anal, her lips on his nipple, his own penis separate", ST),
 },
 "lose_desc": "keeps him in the dark elf village forever as a collared forest servant covered in glowing hunter's marks.",
 "onanie": {
   "master": ("hollow", "on all fours on the moss like hunted prey, reaching back with wet fingers stroking his own anus in long licking motions, the other hand gripping the moss, penis untouched"),
   "e1": ("trap", "kneeling on fallen leaves, a cord wrapped around his own chest, pulling it tight so it rubs across his own nipples, biting his lip, penis untouched"),
   "e2": ("apothecary", "sitting on the examination table with knees apart, pressing up on his own perineum with one hand, the other reaching back with a finger in his own anus, penis untouched"),
   "e3": ("stable", "sitting on the straw, one hand on his own neck as if feeling a collar, murmuring a pet name to himself, the other hand resting on his thigh, penis untouched"),
   "boss": ("meadow", "kneeling on moonlit grass, one wet finger stroking his own nipple, the other hand reaching back with fingers twisting into his own anus like a vine, penis untouched"),
 },
}
