# N37 竜の宝物庫（Dragon）場面データ。登場人物は全員20歳以上（竜・竜人・精霊は年齢不詳の成人）。女性（竜の女王・古竜はふたなり）と男の娘の混合。
PEN = {"pen": "penis"}     # イグニス・アウルムはふたなり（設計メモどおり）
TOY = {"pen": "toy"}       # ジンの宝石の珠（アナルパール）
CG = {"cage": True}        # クロの金の輪（貞操帯）

DATA = {
 "code": "Dragon",
 "world": "dragon's treasure vault inside a volcano, mountains of gold coins and jewels, red glow of a lava river, hot air, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 34 years old, tall, long legs, both eyes clearly visible, dragon woman, humanoid dragon, black horns, red wings, dragon tail, red scales, red hair, long hair, gold eyes, slit pupils, gold jewelry, arrogant smile, tall, large breasts, confident",
         "name": "the red-haired dragon queen with black horns and red wings",
         "neg": "feral dragon, full dragon body, dragon head"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 23 years old, both eyes clearly visible, humanoid dragon, short horns, scaly tail, blonde hair, short hair, amber eyes, short vest, jeweled bracelets, smug",
          "name": "the blonde horned treasure guard with a scaly tail"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 25 years old, both eyes clearly visible, gem spirit, green hair, gemstones in hair, green eyes, crystalline skin patches, light green robe, gentle, medium breasts",
          "name": "the green-haired gem spirit with crystalline skin"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, humanoid dragon, short horns, black scaly tail, black hair, bob cut, red eyes, short attendant robe, gold anklets, expressionless",
          "name": "the black-bobbed dragon attendant with a black tail"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 40 years old, tall, long legs, both eyes clearly visible, dragon woman, humanoid dragon, large gold horns, white wings, platinum scales, white hair, long hair, gold eyes, white robe, layered gold necklaces, tall, mature, huge breasts, confident",
            "name": "the white-haired elder dragon with gold horns and white wings",
            "neg": "feral dragon, full dragon body, dragon head"},
 },
 "places": {
   "hall": "great treasure hall, mountains of gold coins and gems reaching the ceiling, red glow of a lava river, old crowns",
   "nest": "dragon's nest, a huge hollow filled with gold coins, a few red scales scattered, warm glow",
   "gemcave": "gem cave, walls studded with glowing green and red raw gemstones, cool stone, water drops",
   "polish": "polishing workshop, soft leather mat on the floor, water buckets, shelves of polished gems",
   "lava": "bank of a lava river, flowing red lava, black rocks, flying sparks, heat haze",
   "appraisal": "appraisal chamber, platinum pedestal, brass scales and magnifying glass, bright candlesticks",
   "chests": "long corridor lined with old treasure chests, iron locks, lamp light",
   "armory": "armory room, piles of old armor, swords and round shields, dull metal glow",
   "spring": "rock chamber with a shallow volcanic hot spring, steam, slick dark rocks",
   "crater": "rock ledge overlooking a glowing volcano crater at night, flying sparks, night sky",
   "chamber": "attendant's room behind black curtains, narrow bed, a stand of gold jewelry",
   "guardhouse": "guardhouse at the vault entrance, warning bell, key rings on the wall, wooden desk scattered with gems, narrow bed",
   "crown": "crown room, shelves of crowns and necklaces, large mirror, glittering gems in candlelight",
   "roost": "elder dragon's roost, the tallest mound of treasure, platinum pedestal at the top, scattered platinum scales",
 },
 "atk": {
   "m1": ("nest", "he lies on his back on the gold coins, the dragon queen leans over him with her red wings spread, blowing hot breath onto his neck and chest without touching him, heat haze from her lips, he trembles, dazed"),
   "m2": ("hall", "from behind, he lies face down on a mound of gold coins, his hips lifted by the dragon queen's thick tail, the dragon queen kneels behind him licking his anus with her long hot dragon tongue, the tongue sliding inside, anilingus, drool"),
   "m3": ("nest", "from side, he lies on his back on gold coins with legs lifted, the dragon queen penetrates his anus with her own large penis, anal, her thick tail coiled around his chest, the tail tip stroking his nipple, his own penis separate", PEN),
   "e1": ("guardhouse", "he lies face down on the wooden desk with hips raised, the guard stands behind him pushing a string of warm gemstone anal beads into his anus one by one, anal beads, the guard's scaly tail tip stroking his nipple", TOY),
   "e2": ("polish", "he lies on his back on the leather mat, the gem spirit kneels beside him polishing his nipple in slow circles with a fingertip coated in glittering polishing paste, his nipples shining, careful expression"),
   "e3": ("chamber", "he sits on the narrow bed with legs spread, his penis locked in a chastity cage, the attendant stands before him pressing a toe with a gold anklet against his perineum below the cage, the black tail brushing his thigh", CG),
   "boss": ("appraisal", "he lies on his back on the platinum pedestal with legs spread, the elder dragon bends over him licking his nipple, a thin gold rod inserted into the tip of his penis, her other fingers in his anus, fingering, magnifying glass on the stand"),
 },
 "atk_desc": {
   "m1": "the dragon queen melts his mind with hot breath.",
   "m2": "the dragon queen licks deep inside him with her long dragon tongue.",
   "m3": "the dragon queen takes him while her tail squeezes his chest.",
   "e1": "the guard pushes warm gemstone beads into him one by one.",
   "e2": "the gem spirit polishes his nipples until they shine.",
   "e3": "the attendant locks him in a gold ring and presses him with her toes.",
   "boss": "the elder dragon appraises him from the front, behind and chest at once.",
 },
 "lose": {
   "btl_m1": ("nest", "he lies on his back on the gold coins with legs open, half covered by the dragon queen's red wing, the dragon queen blows hot breath on his lower belly, a warm gold coin in his hand, heat haze, cum on his belly, dazed"),
   "onani_m1": ("guardhouse", "sitting alone on the narrow bed, breathing onto his own palm, the warmed fingers tracing his own neck and chest, the other wet hand reaching back to his own anus, penis untouched, the dragon queen peers from the doorway far away"),
   "inochi_m1": ("spring", "they sit side by side in the shallow hot spring, the dragon queen's tail wrapped around his waist pulling him close, her lips at his ear blowing hot breath, a thin gold chain and a red scale on his neck, steam"),
   "onedari_m1": ("crater", "he sits wrapped in the dragon queen's red wings on the rock ledge under the night sky, flying sparks, the dragon queen blows hot breath on his chest while he begs with his mouth open, heat haze"),

   "btl_m2": ("hall", "from behind, he lies face down on a mound of gold coins, his hips lifted by the dragon queen's thick tail, the dragon queen's long tongue deep in his anus, anilingus, coins spilling, a gold fang pendant on his neck, cum dripping"),
   "onani_m2": ("chests", "sitting alone on an old treasure chest, leaning back, reaching under himself with wet fingers stroking his own anus in long licking motions, penis untouched, the dragon queen stands far down the corridor watching"),
   "inochi_m2": ("polish", "he is on all fours on the leather mat, the dragon queen kneels behind him, her tail wrapped around his hips, her long tongue licking his anus, anilingus, drool, water buckets beside them"),
   "onedari_m2": ("crown", "he kneels on all fours before the large mirror, the dragon queen behind him with her long tongue deep in his anus, anilingus, his flushed face in the mirror, her horns and tail reflected, a ruby on his neck"),

   "btl_m3": ("nest", "from side, he lies on his back on the gold coins holding his knees, the dragon queen penetrates his anus with her own large penis, anal, her thick tail coiled around his chest, he presses his chest to the tail, his own penis separate, cum on his belly", PEN),
   "onani_m3": ("lava", "sitting alone on a black rock by the lava river, one wet finger in his own anus, the other arm wrapped tightly around his own chest as if coiled by a tail, penis untouched, the dragon queen watches from across the lava"),
   "inochi_m3": ("armory", "from side, he lies on his side beside piles of old armor, the dragon queen's tail wrapped around his chest, the dragon queen lies behind him penetrating his anus with her own penis, anal, her red wing over them, his own penis separate", PEN),
   "onedari_m3": ("spring", "at the edge of the shallow hot spring he lies back on a slick rock holding his knees, the dragon queen's tail coiled around his chest, the dragon queen penetrates his anus with her own penis, anal, steam, his own penis separate", PEN),

   "btl_e1": ("guardhouse", "from side, he lies face down on the wooden desk with hips raised, a string of gemstone anal beads half inside his anus, the guard stands behind him pushing the next bead in, counting, the scaly tail tip on his nipple", TOY),
   "onani_e1": ("chests", "kneeling alone on the corridor floor with hips raised, sinking one finger into his own anus and pulling it out, counting under his breath, penis untouched, the guard leans on a treasure chest far away watching, smug"),
   "inochi_e1": ("hall", "he sits on a lookout rock at the vault entrance, the gold ring of anal beads hanging from his anus, the guard stands beside him stroking his nipple with the scaly tail tip, smirking, gold coins below", TOY),
   "onedari_e1": ("gemcave", "he is on all fours before the glowing gem wall, the guard kneels behind him pushing an amber anal bead into his anus, garnet and topaz beads on the gold string, anal beads, the guard's tail curling", TOY),

   "btl_e2": ("polish", "he lies on his back on the leather mat, the gem spirit leans over him polishing both his nipples with paste-coated fingertips and kissing him with cool crystalline lips, his nipples shining, cum on his belly"),
   "onani_e2": ("gemcave", "sitting alone against the glowing gem wall, rubbing his own nipples in slow circles with his fingertips, counting, penis untouched, green light on his cheeks, the gem spirit stands far away watching"),
   "inochi_e2": ("spring", "they sit in the shallow hot spring, the gem spirit behind him spreading glittering polishing paste on his chest and rubbing his nipples in circles, her crystalline skin glowing faintly in the steam"),
   "onedari_e2": ("crown", "he sits before the large mirror with his chest out, the gem spirit kneels beside him polishing his right nipple with a fingertip, the left nipple already shining, both reflected in the mirror"),

   "btl_e3": ("chamber", "he sits on the narrow bed, his penis locked in a chastity cage, the attendant stands over him pressing a foot with a gold anklet on the cage and his perineum, the black scaly tail tracing his anus, trembling", CG),
   "onani_e3": ("nest", "sitting alone at the edge of the gold-filled hollow, his penis locked in a chastity cage, fingers pressing his own perineum and anus, trembling, the attendant stands far away watching expressionlessly", CG),
   "inochi_e3": ("chests", "he kneels before an open treasure chest full of old keys, his penis locked in a chastity cage, the attendant stands beside him pressing a bare foot with a gold anklet on the cage, expressionless", CG),
   "onedari_e3": ("armory", "he sits on an old round shield on the floor with legs spread, his penis locked in a chastity cage, the attendant presses a toe on his perineum, the black tail wrapped around his waist, a gold anklet on his own ankle", CG),

   "btl_boss": ("appraisal", "from side, he lies on his back on the platinum pedestal with legs lifted, the elder dragon penetrates his anus with her own large penis, anal, her white wings folding around them, his own penis separate, cum on his belly", PEN),
   "onani_boss": ("roost", "kneeling alone at the foot of the treasure mound, a finger in his own anus while his thumb presses his perineum, the other wet hand rubbing his own nipple, penis untouched, the elder dragon watches from the top of the mound"),
   "inochi_boss": ("hall", "he lies on his back on gold coins, a thin gold rod inserted into the tip of his penis, the elder dragon kneels beside him licking his nipple, two fingers in his anus, fingering, appraising him calmly"),
   "onedari_boss": ("roost", "at the top of the treasure mound he lies on the platinum pedestal holding his knees, the elder dragon penetrates his anus with her own penis, anal, platinum scales scattered, his own penis separate, a collar of platinum scales on his neck", PEN),
 },
 "lose_desc": "keeps him in the volcanic treasure vault forever as a treasure marked with golden scale seals.",
 "onanie": {
   "master": ("hall", "on all fours on the gold coins, reaching back with wet fingers stroking his own anus in long licking motions, the other hand braced on the coins, penis untouched"),
   "e1": ("chests", "kneeling with his hips raised, sinking one finger into his own anus and pulling it out again, counting as if they were beads, penis untouched"),
   "e2": ("polish", "sitting on the leather mat with his chest out, rubbing both his own nipples in slow careful circles with his fingertips as if polishing gems until they shine, penis untouched"),
   "e3": ("chamber", "sitting on the narrow bed, his penis locked in a chastity cage, pressing his own perineum with two fingers, the other hand reaching back to his own anus", CG),
   "boss": ("appraisal", "sitting on the pedestal, a finger in his own anus while his thumb presses his perineum, the other wet hand rubbing his own nipple, penis untouched"),
 },
}
