# N33 夢魔の揺りかご（Dream）場面データ。登場人物は全員20歳以上。責め手は女性（ソムニア・メリー・ネムリア）と男の娘（ムウ・ナイト）。光は紫〜桃（青くしない）。
DATA = {
 "code": "Dream",
 "world": "dream mansion floating in a lavender sky with clouds and stars, pink and purple light, soft glow, dreamy atmosphere, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 30 years old, tall, long legs, both eyes clearly visible, succubus, small bat wings, pink hair, very long hair, floating hair, purple eyes, lavender nightgown, star hair ornament, sleepy seductive smile, large breasts",
         "name": "the pink-haired succubus in a lavender nightgown",
         "neg": "blue theme, blue light"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 22 years old, both eyes clearly visible, tapir ears, small tail, white hair, fluffy short hair, black eyes, oversized pajamas, sleepy",
          "name": "the white-haired tapir-eared baku in oversized pajamas",
          "neg": "blue theme, blue light"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 26 years old, both eyes clearly visible, sheep horns, yellow hair, fluffy bob, brown eyes, woolly cape, wool dress, gentle smile, huge breasts",
          "name": "the sheep-horned shepherdess in a woolly cape",
          "neg": "blue theme, blue light"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 25 years old, black hair, long bangs, one eye visible, red eyes, gothic black outfit, shadow aura, gloomy smirk",
          "name": "the black-haired nightmare in a gothic black outfit",
          "neg": "blue theme, blue light"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 35 years old, tall, long legs, both eyes clearly visible, silver hair, metallic hair, long hair, gold eyes, starry night dress, crescent crown, serene, large breasts",
            "name": "the silver-haired dream queen in a starry night dress",
            "neg": "blue theme, blue light"},
 },
 "places": {
   "cradle": "antique wooden cradle-shaped bed overlapping a dim inn room, moonlight, creaking wood",
   "real": "small old inn bedroom blurred at the edges with pink haze, wooden ceiling, simple bed",
   "cloud": "corridor of soft pink clouds, cotton candy clouds, cloud hammocks floating",
   "stairs": "long staircase of starlight descending into darkness, glowing thread handrails, stars fading on each step",
   "bedroom": "lavender dream bedroom, huge canopy bed with purple gauze curtains, floating stars",
   "skylight": "attic under a skylight full of stars, piles of cushions, starlight only",
   "music": "lullaby music room, many music boxes, flickering candles, velvet couch",
   "mirror": "hall of mirrors, walls covered with tall mirrors, pink light, fogged glass",
   "moonbath": "moon bath, shallow milky white water glowing faintly, steam, pink light",
   "pillow": "baku's pillow room, pillows piled to the ceiling, floating feathers",
   "meadow": "night meadow with fluffy sheep, bells on their necks, starry sky",
   "hut": "wool hut on the pasture, fireplace, balls of yarn, hay, warm firelight",
   "corridor": "nightmare corridor, long dark shadows, pendulum clock, dim purple light",
   "closet": "cramped dark closet like the inside of a cupboard, heavy darkness, old cloth",
   "door": "white door with morning light leaking through the gap, the handle just out of reach",
   "throne": "starry sky throne room, crescent moon throne, floor covered with stars",
   "moon": "bottom of the dream stairs, huge crescent moon cradle rocking slowly, starry darkness",
 },
 "atk": {
   "m1": ("bedroom", "he lies on his side in the canopy bed, the succubus lies behind him wrapping his head in her bat wings, her lips at his ear whispering a lullaby, no hand on him, drowsy, hips twitching"),
   "m2": ("cloud", "he lies on his back sunk in soft pink clouds, the succubus on top of him kissing him deeply, tongues, saliva trail, her bat wings spread over them, her floating pink hair on his cheeks"),
   "m3": ("real", "from side, he lies on his back on the inn bed holding his knees, the succubus kneels between his legs penetrating his anus with her penis, anal, bending down licking his nipple, his own penis separate", {"pen": "penis"}),
   "e1": ("pillow", "he lies face down on the pile of pillows with his hips raised, the baku kneels behind him licking his anus with a long warm tongue, anilingus, tapir ears brushing his back, feathers floating"),
   "e2": ("meadow", "he sits in the shepherdess's lap wrapped in her woolly cape, the shepherdess strokes both of his nipples with tufts of white wool, sheep around them, bells, dazed"),
   "e3": ("corridor", "he lies face down on the floor unable to move, black shadow tentacles stretch from the nightmare's shadow into his anus, a thin shadow strand slipping into his urethra, the nightmare stands over him"),
   "boss": ("moon", "he lies on his back in the crescent moon cradle, a glowing pink womb tattoo on his lower belly, soft night-sky tentacles from the dream queen's dress hem entering his anus, the dream queen tracing the crest with her fingertip"),
 },
 "atk_desc": {
   "m1": "the succubus whispers a lullaby until he melts in his sleep.",
   "m2": "the succubus gives him a sweet dream kiss.",
   "m3": "the succubus takes him between dream and waking.",
   "e1": "the baku eats his bad dreams with a long tongue.",
   "e2": "the shepherdess strokes him with wool while counting sheep.",
   "e3": "the nightmare slides shadow tentacles into him.",
   "boss": "the dream queen draws her crest and sends her tentacles into him.",
 },
 "lose": {
   # m1 囁きの子守唄
   "btl_m1": ("bedroom", "he lies on his side deep in the canopy bed, the succubus lies behind him wrapping bat wings around his head, lips at his ear singing, her pink hair over his cheek, no hands on him, cum on the sheets"),
   "onani_m1": ("cradle", "lying alone on his back in the wooden cradle bed, hands resting at his sides, lips moving with a lullaby, hips twitching, penis untouched, the succubus sits far away on the windowsill watching"),
   "inochi_m1": ("door", "he kneels before the white door reaching for the far handle, the succubus kneels behind him wrapping her bat wings around him, singing into his ear, his hand frozen in the air, morning light from the gap"),
   "onedari_m1": ("music", "he lies on the velvet couch with his head in the succubus's lap, the succubus bends down under her wing singing into his right ear, music boxes and candles around, cum on his belly"),
   # m2 夢の口づけ
   "btl_m2": ("cloud", "he is pinned on his back in the soft clouds, the succubus lies on top kissing him deeply, tongues, saliva, her bat wings covering his eyes, cum on his belly, dazed"),
   "onani_m2": ("mirror", "kneeling alone before a tall mirror, licking his own lips slowly, hands clasped behind his back, his breath fogging the glass, penis untouched, the succubus stands far behind him in the hall watching"),
   "inochi_m2": ("moonbath", "they stand waist-deep in the milky moon bath, the succubus holds him and feeds him sweet nectar mouth to mouth, milky drops on his chin, his lips parted, steam"),
   "onedari_m2": ("stairs", "he sits on a step of the starlight stairs, the succubus stands one step above bending down kissing him deeply, tongue deep, stars fading around them, saliva trail"),
   # m3 夢と現の狭間で
   "btl_m3": ("real", "from side, he lies on his back on the inn bed, the succubus covers him penetrating his anus with her penis, anal, licking his nipple, her bat wings spread, his own penis separate, cum on his belly", {"pen": "penis"}),
   "onani_m3": ("skylight", "lying alone on the pile of cushions with his back arched and chest out, hands gripping the cushions away from his crotch, hips clenched, penis untouched, the succubus floats outside the skylight watching"),
   "inochi_m3": ("cloud", "from side, he lies on his back in a swaying cloud hammock, the succubus over him penetrating his anus with her penis, anal, licking his nipple, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("pillow", "from side, he sinks on his back into the pillows holding his knees, the succubus kneels between his legs penetrating his anus with her penis, anal, licking his nipple, feathers floating, his own penis separate", {"pen": "penis"}),
   # e1 ムウ
   "btl_e1": ("pillow", "he lies face down on the pillows with his hips raised, the baku kneels behind licking his anus with a long tongue, anilingus, the baku's tail tickling his calf, cum on the pillows"),
   "onani_e1": ("real", "lying alone on his side on the inn bed, one arm reaching behind with wet fingertips stroking around his own anus, penis untouched, the baku peeks in from the far doorway watching"),
   "inochi_e1": ("corridor", "he kneels on the floor with his hips raised and offered, the baku crouches behind him licking his anus with a long tongue, anilingus, the pendulum clock behind them"),
   "onedari_e1": ("moonbath", "he sits on the rim of the milky bath leaning back with his legs held up, the baku stands in the water licking his anus, the tongue tip slipping inside, anilingus, tail swaying"),
   # e2 メリー
   "btl_e2": ("meadow", "he sits in the shepherdess's lap wrapped in her woolly cape, the shepherdess strokes his nipples with tufts of wool, sheep and bells around them, cum on the grass, dazed"),
   "onani_e2": ("hut", "sitting alone before the fireplace, rubbing his own nipples with the soft edge of a blanket, penis untouched, balls of yarn around, the shepherdess stands in the far doorway watching"),
   "inochi_e2": ("cloud", "he lies on the clouds with his head in the shepherdess's lap, the shepherdess strokes his nipple with a tuft of wool while counting on her other fingers, his hips twitching"),
   "onedari_e2": ("mirror", "he kneels before the tall mirror, the shepherdess kneels behind him, stroking his right nipple with a tuft of wool and his left nipple with her fingertip, his reflection flushed"),
   # e3 ナイト
   "btl_e3": ("corridor", "he lies face down on the floor paralyzed, black shadow tentacles stretch from the nightmare's shadow into his anus, a thin shadow strand in his urethra, the pendulum clock, cum on the floor"),
   "onani_e3": ("closet", "lying face down alone in the dark closet, one arm reaching behind with fingers twisting into his own anus like shadows, penis untouched, the nightmare stands in the far darkness watching"),
   "inochi_e3": ("door", "he lies face down before the white door in the morning light, shadows wrapped around his ankles, black shadow tentacles entering his anus, the nightmare stands over him"),
   "onedari_e3": ("stairs", "on all fours on a dark landing of the stairs, three black shadow tentacles from the nightmare's feet deep in his anus, a thin shadow strand in his urethra, the nightmare crouches beside him"),
   # boss ネムリア
   "btl_boss": ("moon", "from side, he lies on his side in the crescent moon cradle, the dream queen lies behind him penetrating his anus with her penis, anal, a glowing pink womb tattoo on his lower belly, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("skylight", "lying alone on the cushions, one fingertip tracing a mark on his own lower belly, the other arm reaching behind with fingers in his own anus, penis untouched, the dream queen floats among the stars far away watching"),
   "inochi_boss": ("cradle", "he lies on his back in the wooden cradle bed, the dream queen's fingertip redrawing a glowing pink womb tattoo on his lower belly, night-sky tentacles from her dress hem entering his anus"),
   "onedari_boss": ("throne", "he kneels before the crescent moon throne, the dream queen seated above him, night-sky tentacles from her dress hem deep in his anus, a pink womb tattoo glowing on his lower belly"),
 },
 "lose_desc": "keeps him forever asleep in the dream mansion.",
 "onanie": {
   "master": ("bedroom", "lying alone on his back in the canopy bed, hands resting at his sides away from his body, lips moving with a lullaby, hips twitching, penis untouched"),
   "e1": ("pillow", "lying face down alone on the pillows, one arm reaching behind with wet fingertips stroking around his own anus like a licking tongue, hips raised, feathers floating, penis untouched"),
   "e2": ("hut", "sitting alone before the fireplace, rubbing his own nipples with the soft edge of a woolly blanket in slow rhythm as if counting sheep, the blanket around his shoulders, penis untouched"),
   "e3": ("closet", "lying face down alone in the heavy darkness, one arm reaching behind with fingers twisting into his own anus like shadow tentacles, body stiff as if paralyzed, penis untouched"),
   "boss": ("skylight", "lying alone on the cushions, one fingertip tracing a mark on his own lower belly, the other arm reaching behind with fingers in his own anus, penis untouched"),
 },
}
