# N53 星見堂の占い師（Fortune）場面データ。登場人物は全員20歳以上。女性（ティア・ミスズ・ノクス）とニューハーフ（マダム・ステラ・サラ）の混合。
DATA = {
 "code": "Fortune",
 "world": "mysterious fortune-telling house at the back of a shopping street at night, purple drapes, star-shaped lamps, glowing crystals, incense haze, detailed background",
 "chars": {
   "m":    {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 39 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, purple hair, long wavy hair, gold eyes, purple veil, dress with star embroidery, gold bracelets, large breasts",
            "name": "the purple-haired fortune teller in a purple veil and star-embroidered dress"},
   "e1":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, long legs, red hair, medium hair, green eyes, black cape, red dress, large breasts",
            "name": "the red-haired card reader in a black cape and red dress"},
   "e2":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 28 years old, adult proportions, beautiful detailed eyes, long legs, black hair, hime cut, red eyes, white kimono, purple hakama, modest breasts",
            "name": "the hime-cut palm reader in a white kimono and purple hakama"},
   "e3":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, pink hair, long hair, amber eyes, light pink sheer eastern robe, medium breasts",
            "name": "the pink-haired incense keeper in a light pink sheer robe"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 43 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long hair, red eyes, night-sky black and gold robe, star chart necklace, large breasts",
            "name": "the blonde grand astrologer in a black and gold night-sky robe"},
 },
 "places": {
   "reading":  "dim fortune-telling room, round table with a glowing crystal ball swirling purple and gold, tarot cards without text laid out, star-shaped lamps",
   "canopy":   "back room behind a heavy curtain, bed under a purple canopy, flickering candles, sandalwood smoke",
   "waiting":  "narrow waiting room, velvet couch, crystal ball glowing purple on a shelf, faint sandalwood smoke",
   "cardroom": "second-floor card reading room, round wooden table, low couch, window with shopping street night lights, scattered cards without text",
   "palm":     "tatami palm reading room, low wooden table, shoji screens glowing with street lights, incense stick smoke",
   "incense":  "cramped tatami incense room, floor cushions, incense burner, thick sweet white smoke drifting under the ceiling",
   "dome":     "domed star-viewing chamber at the top floor, starry dome ceiling, stone table carved with a star chart, huge glowing crystal in the center",
   "anteroom": "tatami anteroom with a folded blanket, sliding doors, dim light",
 },
 "atk": {
   "m1": ("reading", "he sits frozen upright in a chair, the fortune teller leans over his shoulder from behind whispering star names into his ear, her tongue at his earlobe, his nipples erect, precum dripping, no hands on him"),
   "m2": ("reading", "he lies back on a couch staring at the glowing crystal ball, the fortune teller holds the crystal ball above him, purple and gold light swirling, his hips jerking, cum on his belly, no hands on him"),
   "m3": ("canopy", "from side, he lies on his back on the canopy bed with legs wrapped around the fortune teller's waist, the fortune teller penetrates his anus while sucking his nipple, anal, his own penis separate", {"pen": "penis"}),
   "e1": ("cardroom", "he lies on his back on the round table with his chest bared, the card reader stands over him flicking the edges of two cards across both of his nipples, swollen red nipples, cards without text scattered"),
   "e2": ("palm", "from side, he is on all fours on the tatami, the palm reader kneels behind him tracing the inside of his anus with one finger, her other hand holding his open palm, his erection dripping onto the tatami"),
   "e3": ("incense", "he lies on his back on floor cushions, the incense keeper leans over him blowing a long stream of sweet white smoke onto his lips from her mouth, an incense burner on her lap, his mouth open inhaling, trembling"),
   "boss": ("dome", "from side, he lies on his back on the star-chart stone table holding his knees, the grand astrologer pinches his nipple with one hand and pushes a string of glowing crystal anal beads into his anus with the other, starlight", {"pen": "toy"}),
 },
 "atk_desc": {
   "m1": "the fortune teller whispers star names that rewrite his common sense.",
   "m2": "the fortune teller makes him climax just by staring into the crystal.",
   "m3": "the fortune teller sucks his nipple while penetrating him on her canopy bed.",
   "e1": "the card reader flicks his nipples with the edges of her cards.",
   "e2": "the palm reader traces the lines of his palm inside him.",
   "e3": "the incense keeper breathes sweet smoke into him.",
   "boss": "the grand astrologer ties his nipples and his anus into one constellation.",
 },
 "lose": {
   # マダム・ステラ 技1 星読みの囁き
   "btl_m1": ("reading", "he sits naked and frozen upright in the chair, the fortune teller behind him licking inside his ear, her long fingers pinching his nipple, twelve face-down cards without text on the table, cum on his thighs"),
   "onani_m1": ("waiting", "lying alone on the velvet couch staring at the glowing crystal ball on the shelf, both hands clutching the cushion, lips murmuring, hips twitching, penis untouched, the fortune teller watches from the far doorway"),
   "inochi_m1": ("reading", "he sits frozen in the fortune teller's arms, the fortune teller hugs his shoulders from the side and whispers into his ear, his mouth open begging for more, precum dripping, erect nipples, no hands on his crotch"),
   "onedari_m1": ("reading", "he sits on the couch, the fortune teller stands behind him bending down, her purple hair falling over his shoulders, her tongue licking his ear, her hands resting still on his shoulders, cum on his thighs, a card without text glowing on the table"),
   # 技2 水晶の暗示
   "btl_m2": ("reading", "he lies on his back on the couch, the fortune teller places the glowing crystal ball on his chest, purple and gold light shining through his skin, his hips jerking, cum on his belly, no hands on him"),
   "onani_m2": ("anteroom", "lying alone on the tatami wrapped in a blanket, clutching a glowing crystal bead in his fist, staring at it, hips twitching, penis untouched, the fortune teller watches from the far sliding door holding a large crystal ball"),
   "inochi_m2": ("reading", "he lies back on the couch with his bangs brushed aside, staring into the crystal ball the fortune teller holds before his face, swirling purple light, cum pooling on his belly, no hands on him, eyes not visible"),
   "onedari_m2": ("reading", "he kneels before the round table staring into the crystal ball, the fortune teller lifts the purple cloth from the glowing crystal ball, cum splashed on the table and floor, a card without text beside it, no hands on him"),
   # 技3 運命の夜
   "btl_m3": ("canopy", "from side, he lies on his back on the canopy bed with his legs wrapped around the fortune teller's waist, the fortune teller penetrates his anus deeply while sucking his nipple, anal, his own penis separate, candlelight", {"pen": "penis"}),
   "onani_m3": ("canopy", "lying alone on his back on the canopy bed staring at a glowing crystal on the pillow, fists clenched on the sheet, hips lifting, penis untouched, the fortune teller watches from the far curtain"),
   "inochi_m3": ("canopy", "from side, he lies on his back under the purple canopy facing the fortune teller, the fortune teller slowly pushes into his anus while licking his nipple, anal, his own penis separate, the canopy cloth swaying", {"pen": "penis"}),
   "onedari_m3": ("canopy", "from side, he sits in the fortune teller's lap facing her on the canopy bed, the fortune teller holds his hips and thrusts up into his anus, anal, her lips sucking his nipple, his own penis separate", {"pen": "penis"}),
   # e1 ティア カードの縁で
   "btl_e1": ("cardroom", "he sits on the low couch with his chest bared, the card reader kneels on the couch beside him flicking two cards alternately across both of his nipples, red swollen nipples, cum on his thighs, cards without text on the floor"),
   "onani_e1": ("cardroom", "sitting alone on the low couch holding the hem of his shirt in his teeth, scratching his own nipples with his fingernails like card edges, back arched, penis untouched, the card reader watches from the far doorway"),
   "inochi_e1": ("cardroom", "he lies on his back on the round table, the card reader stands over him fanning out a deck and dragging the fanned card edges across his nipple, a pile of cards without text beside him"),
   "onedari_e1": ("cardroom", "he kneels with his hands behind his back and his chest thrust out, the card reader bends down kissing him deeply while pressing card edges against both of his nipples, tongues, cards without text"),
   # e2 ミスズ 手相をなぞる
   "btl_e2": ("palm", "from side, he is on all fours on the tatami, the palm reader kneels behind him with one finger in his anus tracing a line, her other hand holding his open palm, precum dripping onto the tatami"),
   "onani_e2": ("palm", "lying alone on his side on the tatami staring at his own open left palm, the right arm reaching behind with oiled fingers in his own anus, penis untouched, the palm reader watches from the far shoji"),
   "inochi_e2": ("palm", "he lies on his back on the tatami with his knees raised, the palm reader kneels between his legs with her sleeves tied back, one finger in his anus, her bare sole resting on the underside of his erection"),
   "onedari_e2": ("palm", "he lies across the palm reader's lap on the tatami tracing his own lifeline with his finger, the palm reader's middle finger inside his anus following the same line, her other hand on his waist"),
   # e3 サラ 香の煙
   "btl_e3": ("incense", "he lies on his back on floor cushions in the smoke, the incense keeper leans over his face blowing sweet white smoke onto his lips, her oiled fingers in his anus, his mouth open exhaling"),
   "onani_e3": ("incense", "sitting alone on a floor cushion with eyes hidden by bangs, breathing in thick incense smoke, hands resting on his thighs, mouth open exhaling, penis untouched, the incense keeper watches from the far doorway"),
   "inochi_e3": ("incense", "he sits on a floor cushion leaning back against the incense keeper's chest, the incense keeper hugs him from behind and blows sweet smoke into his ear, the incense burner smoking beside them, cum on his thighs"),
   "onedari_e3": ("incense", "he lies on the cushion bed with his fingers laced with the incense keeper's, the incense keeper kisses him breathing sweet smoke into his mouth, her other oiled fingertips circling his anus"),
   # boss ノクス 星座を結ぶ
   "btl_boss": ("dome", "from side, he lies on his back on the star-chart stone table, the grand astrologer stands beside him pushing the last glowing crystal bead of a long string into his anus, her other hand pinching his nipple, his back arched", {"pen": "toy"}),
   "onani_boss": ("dome", "kneeling alone on the stone floor against the wall, pinching his own nipple, the other arm reaching behind with two fingers in his own anus, starlight through the dome, penis untouched, the grand astrologer watches from the far door"),
   "inochi_boss": ("dome", "from side, he lies face down on the star-chart stone table with his hips raised, the grand astrologer stands behind him pulling a silver string of glowing crystal anal beads from his anus, her other hand pinching his nipple", {"pen": "toy"}),
   "onedari_boss": ("dome", "from side, he lies on the stone floor holding his own knees, the grand astrologer kneels beside him holding a silver string of glowing crystal anal beads inserted in his anus, pinching his nipple, starlight", {"pen": "toy"}),
 },
 "lose_desc": "seals him asleep inside a huge crystal as his fated end.",
 "onanie": {
   "master": ("reading", "sitting alone at the round table staring into the glowing crystal ball, hands clutching the table edge, mouth open, hips twitching, penis untouched, lips parted, ragged breathing, knees shaking"),
   "e1": ("cardroom", "sitting on the low couch holding the hem of his shirt in his teeth, scratching his own nipples with his fingernails, back arched, penis untouched"),
   "e2": ("palm", "lying on his side on the tatami staring at his own open palm, the other arm reaching behind with oiled fingers in his own anus, penis untouched"),
   "e3": ("incense", "sitting on a floor cushion in thick incense smoke, head tilted back, mouth open inhaling the smoke, hands on his thighs, penis untouched, lips parted, ragged breathing, knees shaking"),
   "boss": ("dome", "kneeling on the stone floor, pinching his own nipple, the other arm reaching behind with two fingers in his own anus, starlight, penis untouched, lips parted, ragged breathing, knees shaking"),
 },
}
