# N50 霧の幽霊船（GhostShip）場面データ。登場人物は全員20歳以上。女性とニューハーフの混合（モルガナ・ジャッキー＝NH、セイレーン3人＝女性の人魚）。
MERMAID_NEG = "legs on the mermaid, feet on the mermaid, human legs on the mermaid, two legs on the mermaid"
DATA = {
 "code": "GhostShip",
 "world": "ghost pirate ship in a foggy sea at night, black tattered sails, glowing lanterns, wet wooden planks, drifting mist, detailed background",
 "chars": {
   "m":    {"type": "nh", "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, red hair, long wavy hair, gold eyes, black and gold captain coat, tricorne hat, open chest blouse, large breasts",
            "name": "the red-haired captain in a tricorne hat and black coat",
            "height_note": "she is much taller than him, a head taller"},
   "e1":   {"type": "woman", "tags": "adult woman, monster girl, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, pink hair, very long hair, purple eyes, mermaid, pink scaled fish tail, seashell and pearl chest ornament, large breasts",
            "name": "the pink-haired siren with a pink fish tail", "neg": MERMAID_NEG},
   "e2":   {"type": "nh", "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, blonde hair, dreadlocks in one ponytail, green eyes, striped shirt, short vest, rope over shoulder, medium breasts",
            "name": "the blonde dreadlocked boatswain in a striped shirt"},
   "e3":   {"type": "woman", "tags": "adult woman, monster girl, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, white hair, short curly hair, red eyes, mermaid, white and green scaled fish tail, seaweed hair ornament, medium breasts",
            "name": "the white-curled mermaid with a green fish tail", "neg": MERMAID_NEG},
   "boss": {"type": "woman", "tags": "adult woman, monster girl, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, black hair, very long hair with pearls, red eyes, mermaid queen, large black and gold scaled fish tail, coral crown, pearl necklace, very large breasts",
            "name": "the black-haired mermaid queen with a coral crown", "neg": MERMAID_NEG,
            "height_note": "she is much larger than him"},
 },
 "places": {
   "deck":     "foggy main deck of the ghost ship, black tattered sails, ship's wheel, glowing lanterns, wet planks",
   "hold":     "dark ship hold below deck, seawater pooled on the floor, barrels, a single hanging lantern",
   "cabin":    "cramped ship cabin, round porthole window with fog outside, narrow bunk bed with a blanket",
   "captain":  "captain's cabin at the stern, oil lamp, large wooden bed, sea chart table without text, brass compass",
   "mess":     "ship's mess hall at night, long wooden table, tankards, lantern light",
   "crow":     "crow's nest at the top of the mast, barrel-shaped lookout platform, strong wind, fog far below",
   "net":      "rope net stretched under the bowsprit just above the waves, sea spray",
   "stern":    "plank swing seat hung by ropes from the stern just above the moonlit water",
   "capstan":  "anchor capstan on the deck, thick ropes and chains, wet planks",
   "rigging":  "rope ladder rigging net slanting from the mast, coiled ropes on the deck",
   "tub":      "large wooden tub of seawater in the middle of the deck, lanterns around",
   "bilge":    "flooded bilge of the ship, knee-deep seawater, open trapdoor above, lantern light",
   "seagate":  "large sea gate opening in the ship's hull, moonlit dark water, seaweed drifting",
   "sternwin": "stern cabin with large stern windows, black night sea outside, moonlight",
   "reef":     "flat wet reef rock beside the ship in the moonlit sea, seaweed",
   "palace":   "undersea palace of coral and pearls, a bed of swaying seaweed, soft blue light, bubbles",
 },
 "atk": {
   "m1": ("deck", "he kneels on the wet deck with his knees buckling, the tall captain bends down from behind singing a sea shanty into his ear, her lips at his ear, one hand under his chin, trembling"),
   "m2": ("hold", "he sits on a barrel with his chin lifted, the tall captain leans down kissing him deeply, tongues, saliva trail, her palm resting over the tip of his erection"),
   "m3": ("captain", "from side, he lies on his side on the large wooden bed, the captain behind him penetrating his anus with her own penis, anal, her fingers pinching his nipple, his own penis separate, precum", {"pen": "penis"}),
   "e1": ("hold", "he lies on the wet steps half in the seawater, the siren floats beside him singing into his ear, a webbed fingertip touching his nipple, no other hands on him, back arched, dazed"),
   "e2": ("hold", "he stands with a rough rope wound around his chest, knots pressing on both of his nipples, the boatswain behind him pulling the rope tight, grinning, precum"),
   "e3": ("bilge", "he sits in the knee-deep seawater, the mermaid rises from the water licking his nipple with a foamy bubbling tongue, bubbles popping on his chest, her other hand pinching his nipple"),
   "boss": ("seagate", "he is held in the mermaid queen's arms in the water at the sea gate, the queen kisses him deeply, tongues, long seaweed tendrils coiling around his hips and slipping into his anus"),
 },
 "atk_desc": {
   "m1": "the captain sings a cursed sea shanty into his ear.",
   "m2": "the captain steals his breath with a pirate kiss.",
   "m3": "the captain takes him in her cabin bed.",
   "e1": "the siren's song melts his mind without a touch.",
   "e2": "the boatswain ties rope knots over his nipples.",
   "e3": "the mermaid licks his nipples with a bubbling tongue.",
   "boss": "the mermaid queen gives him the deep sea kiss.",
 },
 "lose": {
   # 船長 技1（呪いの舟唄）
   "btl_m1":     ("hold", "he leans back against the tall captain's chest, the captain sings into his ear with her lips at his ear, her hand wrapped around his penis, cum on her hand, trembling, footsteps above"),
   "onani_m1":   ("cabin", "kneeling alone on the bunk, one hand cupped behind his ear as if listening to a song, the other hand pinching his own nipple, hips twitching, penis untouched, the captain watches from the doorway"),
   "inochi_m1":  ("deck", "he kneels on the wet deck by the ship's wheel singing, a brass compass hanging from his neck, the captain behind him singing into his ear, her hand stroking his penis, cum flying into the fog"),
   "onedari_m1": ("mess", "he sits on the tall captain's lap at the long table, the captain licks inside his ear, her hand stroking his penis, tankards on the table, cum on her hand"),
   # 船長 技2（潮風の口づけ）
   "btl_m2":     ("hold", "he sits on a barrel with his chin lifted, the tall captain kisses him deeply, tongues, saliva trail, her palm over the tip of his penis, cum in her palm"),
   "onani_m2":   ("cabin", "sitting alone on the bunk wrapped in a blanket, sucking two of his own seawater-wet fingers deeply as if kissing, the other wet hand rubbing his own nipple, penis untouched, the captain watches from the doorway"),
   "inochi_m2":  ("deck", "he sits in a lifeboat hanging on chains, the captain kneels over him kissing him deeply, her bare thigh pressed against his penis, a brass compass clutched on his chest, cum on her thigh"),
   "onedari_m2": ("crow", "he clings to the tall captain inside the crow's nest, the captain holds the back of his head kissing him deeply, her thigh pressed against his penis, wind in their hair, cum"),
   # 船長 技3（船長室で・NH）
   "btl_m3":     ("captain", "from side, he lies on his back on the large bed holding his knees, the captain between his legs penetrating his anus with her own penis, anal, her thumbnail scratching his nipple, his own penis separate, cum leaking", {"pen": "penis"}),
   "onani_m3":   ("cabin", "on all fours alone on the bunk with his hips raised, one arm reaching behind with two of his own fingers in his own anus, the other hand pinching his nipple, penis untouched, the captain watches from the doorway"),
   "inochi_m3":  ("captain", "from side, he lies on his side under a blanket on the large bed, the captain behind him penetrating his anus with her own penis, anal, kissing his neck, pinching his nipple, his own penis separate, a brass compass on the blanket", {"pen": "penis"}),
   "onedari_m3": ("captain", "from side, he is bent over the chart table, the captain behind him penetrating his anus with her own penis, anal, pulling his nipple, his own penis separate, cum dripping down the table edge", {"pen": "penis"}),
   # セイレーン ローラ（セイレーンの歌）
   "btl_e1":     ("hold", "he lies on the wet steps at the water's edge, the siren floats beside him singing into his ear, one webbed fingertip poking his nipple, cum on his belly, back arched, dazed"),
   "onani_e1":   ("cabin", "lying alone on his back on the bunk, humming a song with his mouth open, hands gripping the sheets, back arched, penis untouched, the siren watches through the round porthole"),
   "inochi_e1":  ("net", "he lies on the rope net above the waves, the siren rises from the water singing into his ear, a webbed fingertip poking his nipple, a seashell compass in his hand, cum dripping through the net"),
   "onedari_e1": ("stern", "he sits on the plank swing seat above the water, the siren rises from the sea singing into his ear without touching him, his toes kicking the water, cum, moonlight"),
   # 甲板長 ジャッキー（もやい結び）
   "btl_e2":     ("hold", "he stands with a rough rope wound around his chest, knots biting into both of his nipples, the rope end looped loosely around the base of his penis, the boatswain pulls the rope, cum"),
   "onani_e2":   ("cabin", "sitting alone under the hammocks, a thin rope wrapped around his own chest with a knot over each nipple, pulling the rope end tight, penis untouched, the boatswain watches from the doorway"),
   "inochi_e2":  ("capstan", "he is tied with his back to the anchor capstan, rope knots on both of his nipples, a brass compass on his chest, the boatswain pinches his nipple through the knot, cum on the wet deck"),
   "onedari_e2": ("rigging", "he is tied spread against the rope ladder net, rope knots over both of his nipples, the boatswain pulls the rope back and forth, the rope end around the base of his penis, cum on the deck"),
   # セイレーン マリン（泡の舌）
   "btl_e3":     ("bilge", "he sits in the knee-deep seawater, the mermaid licks his nipple with a bubbling foamy tongue, pinching the other, her fish tail brushing his penis under the water, cum in the water"),
   "onani_e3":   ("cabin", "on all fours alone beside the open trapdoor, licking his own fingertips and rubbing both of his nipples fast, penis untouched, the mermaid watches from the water under the trapdoor"),
   "inochi_e3":  ("net", "he lies on a floating wooden board on the waves, the mermaid rises beside him sucking his nipple with a foamy tongue, bubbles popping, a spiral shell compass in his hand, cum on the board"),
   "onedari_e3": ("tub", "he sits in the large wooden tub of seawater, the mermaid in the tub sucks his nipples in turn with a foamy tongue, her fish tail rubbing his penis, bubbles, cum in the water"),
   # 女王 テティス（深海の口づけ）
   "btl_boss":   ("seagate", "he floats in the mermaid queen's arms at the sea gate, the queen kisses him deeply, seaweed tendrils coiling around his hips and inside his anus, one tendril around his penis, cum in the water"),
   "onani_boss": ("sternwin", "kneeling alone by the stern window, sucking two fingers of one hand deeply as if kissing, the other hand reaching behind with fingers in his own anus, penis untouched, the mermaid queen watches from the dark sea outside"),
   "inochi_boss":("reef", "he lies on the flat reef rock, the mermaid queen leans over him kissing him deeply, seaweed tendrils in his anus, pearls of her necklace rolling on his nipple, cum on the seaweed"),
   "onedari_boss":("deck", "he sits on the deck edge with his legs in the sea, the mermaid queen rises from the water kissing him, pulling a string of pearl anal beads from his anus, seaweed around his penis, cum", {"pen": "toy"}),
 },
 "lose_desc": "takes him down to the palace at the bottom of the sea to sleep peacefully forever.",
 "onanie": {
   "master": ("cabin", "kneeling on the bunk, sucking two of his own seawater-wet fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched"),
   "e1": ("cabin", "lying on his back on the bunk humming a song, hands gripping the sheets, back arched, dazed, penis untouched"),
   "e2": ("hold", "a rough rope wrapped around his own chest with knots over his nipples, pulling the rope end tight, penis untouched"),
   "e3": ("bilge", "sitting in the shallow seawater, licking his own fingertips and rubbing both of his nipples fast, bubbles around, penis untouched"),
   "boss": ("sternwin", "kneeling by the stern window, sucking his own fingers deeply, the other hand reaching behind with fingers in his own anus, penis untouched"),
 },
}
