# N34 禁書の図書館（Library）場面データ。登場人物は全員20歳以上。責め手は女性（ヘレナ・リーフ・オルガ）と男の娘（ルカ・セージ）。本・紙面には文字を描かない。
DATA = {
 "code": "Library",
 "world": "grand old library after closing time at night, towering bookshelves, lamplight, books without text, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 33 years old, tall, long legs, both eyes clearly visible, black hair, long hair, low bun, green eyes, glasses, white blouse, black long skirt, shawl, librarian, cold smile, large breasts",
         "name": "the black-haired head librarian in glasses"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, blonde hair, bob cut, green eyes, oversized cardigan, shorts, armband, friendly smile",
          "name": "the blonde apprentice in an oversized cardigan"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 27 years old, both eyes clearly visible, green hair, medium hair, brown eyes, rolled sleeves, white shirt, leather apron, ink-stained fingers",
          "name": "the green-haired scribe in a leather apron"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 25 years old, both eyes clearly visible, red hair, long hair, low ponytail, gold eyes, white gloves, work vest, loupe, fastidious",
          "name": "the red-haired restorer in a work vest"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 41 years old, tall, long legs, both eyes clearly visible, white hair, long hair, purple eyes, black robe suit, antique key necklace, mature, stern, large breasts",
            "name": "the white-haired director in a black robe suit"},
 },
 "places": {
   "hall": "great reading hall after closing, moonlight from tall windows, long wooden tables in rows",
   "spiral": "spiral stone staircase down to the basement, wall lamps, small landing with a bench",
   "gate": "heavy iron grille gate of the forbidden archive, big padlock",
   "maze": "maze of bookshelves reaching the ceiling, narrow aisle, book spines without text",
   "ladder": "top of a wooden library ladder against a tall bookshelf, ceiling close, warm lamp",
   "desk": "reading desk with a green-shaded banker's lamp, leather chair, open book without text",
   "reading": "small round reading room, velvet couch, echoing quiet",
   "stacks": "narrow closed stacks aisle, a single hanging lamp, dust, old leather books without text",
   "scriptorium": "scriptorium, desks with ink pots and feather quills, blank parchment",
   "bindery": "bookbinding room, book press, thread and needles, steaming pot of glue, leather",
   "restore": "restoration room, white worktable, magnifying loupe, tweezers, white gloves",
   "counter": "return counter, brass service bell, wooden box of blank lending cards, polished wood",
   "map": "map room, large globe, table covered with old maps without text, parchment",
   "office": "head librarian's office, heavy curtains, black couch, teacup, notebook without text",
   "study": "director's study, fireplace, deep leather armchair, ring of old keys",
   "special": "special collection room, crimson carpet, glass-fronted bookcases, hushed air",
   "hallway": "quiet stone hallway before the restoration room, lamplight on the wall",
   "anteroom": "anteroom of the director's study, small leather couch, lamplight",
 },
 "atk": {
   "m1": ("reading", "he sits on the velvet couch with his knees opening on their own, the head librarian stands behind him reading an open book without text into his ear, one hand resting on his shoulder, no hand on his penis"),
   "m2": ("map", "he lies on his back on the map table, the head librarian leans over him tracing circles around his nipple with the soft tip of a large white quill feather, reading aloud, his back arched"),
   "m3": ("stacks", "from side, he stands bent forward with his hands on a bookshelf, the head librarian behind him pegging his anus with her strap-on, anal, turning his head to kiss him, her skirt lifted, his own penis separate", {"pen": "strapon"}),
   "e1": ("counter", "he sits on the return counter, thin red silk bookmark ribbons tied loosely around both of his nipples, the apprentice stands beside him pulling the ribbons and whispering into his ear, brass bell"),
   "e2": ("bindery", "he lies face down on the worktable beside the steaming glue pot, the scribe pours warm clear glue from a brass-spouted bottle into his anus, glue glistening, her ink-stained fingers on his hip", {"pen": "toy"}),
   "e3": ("restore", "he is on all fours on the white worktable, the restorer with gloves removed has two bare fingers in his anus, a loupe in the other hand, a soft hemp cord wound around the base of his penis"),
   "boss": ("special", "he stands on the crimson carpet trembling, the director presses a blank brass seal to his chest while pushing his nipple in with one finger, his head thrown back, glass bookcases behind"),
 },
 "atk_desc": {
   "m1": "the head librarian reads him and his body obeys every line.",
   "m2": "the head librarian writes on his chest with a white quill.",
   "m3": "the head librarian takes him in the closed stacks.",
   "e1": "the apprentice ties bookmark ribbons to his chest.",
   "e2": "the scribe fills him with warm binding glue.",
   "e3": "the restorer inspects him inside with bare fingers.",
   "boss": "the director stamps him with her ownership seal.",
 },
 "lose": {
   # m1 朗読
   "btl_m1": ("reading", "he sits on the velvet couch with his knees spread wide, the head librarian stands behind him reading an open book without text into his ear, her hand on his shoulder, no hand on his penis, cum on his belly"),
   "onani_m1": ("desk", "sitting alone at the reading desk under the green lamp, reading aloud from an open book without text, hands flat on the desk, hips trembling, penis untouched, the head librarian stands far behind among the shelves"),
   "inochi_m1": ("gate", "he stands with his back against the iron grille gate reading aloud from a document without text in his trembling hands, the head librarian beside him reading the next line into his ear"),
   "onedari_m1": ("office", "he sits on the black couch, the head librarian sits beside him writing in a notebook without text and reading it back into his ear, his knees parting, a teacup on the side table"),
   # m2 羽ペン
   "btl_m2": ("map", "he lies on his back on old maps without text, the head librarian traces the white quill feather around his nipple, reading aloud from an open book without text, cum on his belly"),
   "onani_m2": ("ladder", "alone at the top of the library ladder, one hand gripping the rail, the other fingertip circling his own nipple, lips murmuring, penis untouched, the head librarian looks up from the floor far below"),
   "inochi_m2": ("counter", "he sits on the return counter with his chest bare, the head librarian writes on his chest with the back of a dry quill nib, no ink, reading the line aloud, his nipples stiff, brass bell"),
   "onedari_m2": ("maze", "he leans back against a bookshelf, the head librarian strokes his right nipple with the feather of the white quill and his left with the back of the nib, reading aloud, flushed"),
   # m3 閉架の奥で
   "btl_m3": ("stacks", "from side, he is bent forward with his hands on a bookshelf, the head librarian behind him pegging his anus with her strap-on, anal, kissing him over his shoulder, skirt lifted, his own penis separate, cum on the floor", {"pen": "strapon"}),
   "onani_m3": ("spiral", "sitting alone on the landing bench, licking his own lips, hands gripping the edge of the bench, hips clenched, penis untouched, the head librarian descends the stairs far above watching"),
   "inochi_m3": ("hall", "from side, he lies on his back on a long reading table with his legs lifted, the head librarian pegging his anus with her strap-on, anal, bending to kiss him, an open book without text beside him, his own penis separate", {"pen": "strapon"}),
   "onedari_m3": ("scriptorium", "from side, he lies on his back on the scriptorium desk holding his knees, the head librarian between his legs pegging his anus with her strap-on, anal, ink pots and quills around, his own penis separate", {"pen": "strapon"}),
   # e1 ルカ
   "btl_e1": ("counter", "he sits on the return counter, red silk ribbons tied to both nipples, the apprentice pulls the ribbons taut while whispering into his ear, cum on the counter, brass bell beside him"),
   "onani_e1": ("desk", "sitting alone at the reading desk, a thin cord looped around his own nipples, pulling it with one hand, penis untouched, the apprentice stands by the far shelves hugging books and watching"),
   "inochi_e1": ("map", "he sits on the map table, red, green and yellow silk ribbons tied to his nipples, the apprentice holds all the ribbon ends and pulls them gently, the globe behind them"),
   "onedari_e1": ("hall", "he sits at the end of a long reading table, a red ribbon on his right nipple and a green ribbon on his left, the apprentice stands beside him pulling both, moonlight"),
   # e2 リーフ
   "btl_e2": ("bindery", "he lies face down on the worktable beside the steaming glue pot, the scribe pours warm clear glue from a brass-spouted bottle into his anus, glue dripping down his thighs, cum on the table", {"pen": "toy"}),
   "onani_e2": ("scriptorium", "bent over a scriptorium desk alone, one arm reaching behind with oiled fingers in his own anus, oil dripping, a glass bottle of oil beside him, penis untouched, the scribe watches from the far door"),
   "inochi_e2": ("hallway", "he stands bent forward with his hands on the wall, the scribe behind him pouring more warm glue from a brass-spouted bottle into his anus, glue dripping, her other hand on his hip", {"pen": "toy"}),
   "onedari_e2": ("reading", "he is on all fours on the velvet couch, the scribe kneels beside him pouring warm glue from a brass-spouted bottle into his anus, turning his chin to kiss him, ink-stained fingers", {"pen": "toy"}),
   # e3 セージ
   "btl_e3": ("restore", "he is on all fours on the white worktable, the restorer's bare fingers deep in his anus, a loupe in the other hand, a hemp cord braided around the base of his penis, precum leaking"),
   "onani_e3": ("maze", "crouching alone in the shadow of the shelves, one arm reaching behind with two fingers in his own anus pressing carefully, penis untouched, the restorer stands at the end of the aisle watching"),
   "inochi_e3": ("spiral", "he is bent over the stone steps, the restorer one step below with bare fingers in his anus, a soft hemp cord wound around the base of his penis, lamplight"),
   "onedari_e3": ("anteroom", "he lies on his back on the leather couch of the anteroom holding his legs up, the restorer kneels beside him with bare fingers deep in his anus, a hemp cord braided around his penis"),
   # boss オルガ
   "btl_boss": ("special", "from side, he is on all fours on the crimson carpet, the director kneels behind him pegging his anus with her strap-on, anal, a brass seal in her hand, his own penis separate, cum on the carpet", {"pen": "strapon"}),
   "onani_boss": ("study", "kneeling alone on the rug before the fireplace, pushing his own nipples in with his fingertips, lips murmuring, penis untouched, the director sits in the leather armchair far away watching"),
   "inochi_boss": ("gate", "he stands with his back against the iron grille gate, the director presses a blank brass seal to his chest while pushing his nipple in with one finger, his head thrown back, cum on his belly"),
   "onedari_boss": ("maze", "from side, at the deepest end of the shelf maze, he is bent forward with his hands on the shelves, the director behind him pegging his anus with her strap-on, anal, his own penis separate", {"pen": "strapon"}),
 },
 "lose_desc": "shelves him forever as a bound book of the library.",
 "onanie": {
   "master": ("reading", "sitting alone on the velvet couch, reading aloud from an open book without text on his knees, hands on the pages, hips trembling, knees opening on their own, penis untouched"),
   "e1": ("counter", "sitting alone on the return counter, a thin cord looped around his own nipples, pulling it tight and loosening it with one hand, penis untouched"),
   "e2": ("bindery", "bent over the worktable alone, one arm reaching behind with fingers dripping with oil slowly filling his own anus, a glass bottle of oil beside him, penis untouched"),
   "e3": ("restore", "on all fours alone on the white worktable, one arm reaching behind with two fingers in his own anus pressing point by point, penis untouched"),
   "boss": ("special", "kneeling alone on the crimson carpet before the glass bookcases, pushing his own nipples in with his fingertips, lips murmuring the same word, head tilted back, penis untouched"),
 },
}
