# N56 月の女神の神殿（Luna）場面データ。登場人物は全員20歳以上（女性＋ニューハーフ：カグヤ・ルナリア）。
DATA = {
 "code": "Luna",
 "world": "white greek style temple on a hill under a huge full moon, marble pillars, moonlight, white night-blooming flowers, stars, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, mature face, sharp adult features, 34 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, very long glowing hair, red eyes, white greek goddess robe, gold crescent crown, moonlight shawl, goddess, large breasts, very tall",
         "name": "the blonde moon goddess in a white greek robe and crescent crown"},
   "e1": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, long legs, black hair, very long straight hair, red eyes, miko, white kosode, red hakama, chihaya, medium breasts",
          "name": "the black-haired miko in a red hakama"},
   "e2": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, pink hair, long hair, gold eyes, white and gold priest robe, moon hair ornament, medium breasts",
          "name": "the pink-haired priestess in a white and gold robe"},
   "e3": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, long legs, green hair, long hair with white flowers, gold eyes, white petal dress, flower spirit, large breasts",
          "name": "the green-haired flower spirit in a white petal dress"},
   "boss": {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 36 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, silver hair, long hair, metallic sheen, gold eyes, silver priest long robe, moon staff, large breasts",
            "name": "the silver-haired high priestess in a long silver robe"},
 },
 "places": {
   "skylight": "white marble temple floor directly under a round skylight, full moon seen through the skylight, pale moonbeam",
   "altar":    "innermost altar hall, white stone altar covered with a white cloth, candlesticks with blue flames, carved moon phases on the wall without text",
   "stairs":   "round hall at the top of white stairs, white pillars, night wind, huge moon very close, white feather robe spread on the floor",
   "guest":    "temple guest room, window seat with moonlight streaming in, silver water basin reflecting the moon",
   "bedroom":  "temple bedchamber, white canopy bed, silver water basin on the bedside table, moonlight from the window",
   "archive":  "temple archive room, long desk with an unrolled scroll of golden moon phase drawings without text, chaise longue, candles",
   "spring":   "purification spring behind the temple, rocks and clear spring water reflecting the full moon, white cloth on a flat rock, wooden bucket",
   "shrine":   "shrine worship hall, polished wooden floor, kagura bells, paper lanterns, silver water basin",
   "corridor": "temple colonnade corridor, arched window with the full moon, marble bench",
   "terrace":  "moon viewing terrace, marble floor, silver water basin in the center, night sky full of stars",
   "garden":   "temple courtyard filled with blooming white night-blooming cereus flowers, stone table, moonlight",
   "gazebo":   "white gazebo wrapped in vines of night-blooming cereus, bed of white petals, moonlight",
   "bath":     "moonlit temple bathhouse, steam, marble bath, bottle of fragrant oil, silver water basin",
   "roundhall":"roofless round hall on the top floor, silver rings of moon phases drawn on the floor, glowing, full moon directly above",
   "pool":     "moon pool with rocks at the water's edge, rippling silver water reflecting the full moon",
   "moonbed":  "white palace of the moon city, large white bed with silver sheets, earth seen in the dark sky through the window",
   "balcony":  "temple balcony at night, white lounge chair, night breeze, full moon",
 },
 "atk": {
   "m1": ("skylight", "he lies on his back on the marble floor under the skylight, the moon goddess kneels by his head resting one cold fingertip on his forehead, faint glowing moon drops on his chest, back arched, precum, no other touch"),
   "m2": ("stairs", "he stands with his back against a white pillar, the moon goddess bends down holding his chin up and kisses him deeply, tongues, saliva trail, a glowing moon drop on his lower lip, his knees trembling"),
   "m3": ("altar", "from side, he lies on his back on the white altar holding his knees, the moon goddess stands between his legs pegging his anus with a glowing moonlight strap-on, anal, bending down licking his nipple, his own penis separate", {"pen": "strapon"}),
   "e1": ("spring", "from side, he is on all fours on the white cloth on a flat rock by the spring, the miko kneels behind him with two wet fingers in his anus pressing his prostate, kagura bells in her other hand"),
   "e2": ("corridor", "he sits on the marble bench leaning back limp, the priestess sits beside him with her lips at his ear whispering, one finger on her lips, his mouth open, drool, hips twitching, no hands on him"),
   "e3": ("garden", "from side, he lies on his side among the white flowers, the flower spirit hugs him from behind, her fingers in his anus dripping golden honey jelly, golden honey dripping down his thighs"),
   "boss": ("roundhall", "he lies on his back on silver cloth in the center of the glowing rings with legs spread, the high priestess kneels between his legs, a thin glowing thread of light inserted into his urethra, her two fingers in his anus"),
 },
 "atk_desc": {
   "m1": "the moon goddess fills his head with moonlight until he climaxes without being touched.",
   "m2": "the moon goddess gives him the moonlight kiss.",
   "m3": "the moon goddess takes him on the altar with a strap-on made of moonlight.",
   "e1": "the miko purifies him inside with her fingers.",
   "e2": "the priestess rewrites his common sense with moon words.",
   "e3": "the flower spirit fills him with flower honey.",
   "boss": "the high priestess draws the tide out of him through urethra and anus.",
 },
 "lose": {
   # m1 満ち欠けの（脳イキ）
   "btl_m1": ("skylight", "he lies on his back on the marble floor limbs thrown out, the moon goddess kneels by his head with one fingertip on his forehead, twelve glowing moon drops in a circle on his chest, cum on his belly, dazed"),
   "onani_m1": ("guest", "sitting alone on the window seat, sucking two of his own fingers, the other hand on his chest, gazing up at the full moon, hips twitching, penis untouched, a silver water basin glowing, the moon goddess stands far across the room watching"),
   "inochi_m1": ("skylight", "he lies with his head on the kneeling moon goddess's lap, the moon goddess brushes his wet bangs aside with one fingertip on his forehead, the full moon in the skylight above, cum on his belly, trembling"),
   "onedari_m1": ("archive", "he lies on the chaise longue arching his back, the moon goddess sits beside him with a fingertip on his forehead and a golden brush in her other hand, the unrolled moon calendar scroll on the desk, cum on his chest"),
   # m2 月光の口づけ
   "btl_m2": ("stairs", "he lies on his back on the white feather robe, the moon goddess lies over him kissing him deeply and sucking his tongue, both her hands pinching his nipples, saliva trail, huge moon behind the pillars"),
   "onani_m2": ("bedroom", "lying alone on his back on the canopy bed, sucking two of his own fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched, the moon goddess watches from the moonlit window far away"),
   "inochi_m2": ("balcony", "he lies on the white lounge chair, the moon goddess kneels beside it kissing him deeply, pinching both of his nipples, a thin glowing thread from his lips to the full moon, saliva, night breeze"),
   "onedari_m2": ("bedroom", "he sits on the bed with his mouth open and tongue out begging, the moon goddess holds his face and sucks his tongue, a round silver plate with five carved moon phases without text hangs on the bedpost"),
   # m3 祭壇の上で（ペニバン）
   "btl_m3": ("altar", "from side, he lies on his back on the altar holding his knees, the moon goddess stands between his legs pegging his anus with a glowing moonlight strap-on, anal, licking his nipple, his own penis separate, cum on his belly, blue candle flames", {"pen": "strapon"}),
   "onani_m3": ("altar", "sitting alone in the shadow of the altar, one arm reaching behind with two of his own fingers in his own anus, the other hand pinching his own nipple, penis untouched, the moon goddess sits far away on the altar watching"),
   "inochi_m3": ("altar", "from side, he lies on the edge of the altar with knees up, the moon goddess stands at the altar pegging his anus with a glowing moonlight strap-on, anal, sucking his nipple, his own penis separate, full moon in the skylight", {"pen": "strapon"}),
   "onedari_m3": ("altar", "from side, he kneels on the white bedding on the altar with his chest down and hips raised, the moon goddess kneels behind him pegging his anus with a glowing moonlight strap-on, anal, her hand pinching his nipple, his own penis separate, moon calendar carved on the wall without text", {"pen": "strapon"}),
   # e1 禊の指
   "btl_e1": ("spring", "from side, he is on all fours on the flat rock by the spring with hips raised, the miko kneels behind him with two wet fingers deep in his anus, kagura bells ringing in her other hand, cum on the rock"),
   "onani_e1": ("shrine", "on all fours alone on the wooden veranda, one arm reaching behind with two of his own wet fingers in his own anus, penis untouched, a stone water basin beside him, the miko watches from the far end of the veranda"),
   "inochi_e1": ("shrine", "from side, he kneels face down on the wooden floor with hips raised, the miko kneels behind him with two fingers in his anus, wiping his back with a wet cloth, a wooden bucket, silver basin reflecting the full moon"),
   "onedari_e1": ("spring", "dawn, he lies on a cypress board by the spring with his hips raised begging, the miko kneels beside him with two fingers in his anus, an open japanese notebook without text on her knees"),
   # e2 月読みの囁き（NH・白玉）
   "btl_e2": ("corridor", "from side, he kneels on the marble bench with hips raised, the priestess sits close with her lips at his ear whispering, a string of white anal beads inserted in his anus, the string in her fingers, drool, trembling", {"pen": "toy"}),
   "onani_e2": ("terrace", "kneeling alone on the terrace floor, both hands cupped over his own ears, mouthing words, back arched, drool, hips twitching, penis untouched, the priestess sits far away by the silver basin watching"),
   "inochi_e2": ("bedroom", "he lies curled on the bed, the priestess sits on the edge of the bed singing softly into his ear, not touching him, hands folded in her lap, his hips twitching, cum on the sheets"),
   "onedari_e2": ("corridor", "he lies on his side on the marble bench, the priestess whispers into his ear while slowly pulling a string of white anal beads out of his anus, a scroll of moon letters without text on the wall", {"pen": "toy"}),
   # e3 花の蜜
   "btl_e3": ("garden", "from side, he lies on his back among the white flowers with legs spread, the flower spirit kneels beside him with fingers in his anus, golden honey jelly dripping from his anus, her other hand wrapping his penis in white petals"),
   "onani_e3": ("bath", "sitting alone on the marble edge of the bath, one arm reaching behind with oily fingers in his own anus, golden oil dripping down his thighs, a bottle of fragrant oil beside him, penis untouched, the flower spirit watches through the steam far away"),
   "inochi_e3": ("garden", "he lies curled among the blooming white flowers, the flower spirit hugs him from behind wrapping him in white petals, golden honey jelly leaking from his anus, dawn light"),
   "onedari_e3": ("gazebo", "he lies on the bed of white petals with legs spread, the flower spirit kneels beside him with fingers in his anus, golden honey overflowing, five white flowers blooming on the pillar"),
   # boss 月の潮汐（NH・指＋尿道の光の糸）
   "btl_boss": ("roundhall", "he lies on his back on silver cloth in the glowing rings, the high priestess kneels between his legs with two fingers in his anus, pulling a glowing thread of light out of his urethra, cum spurting upward"),
   "onani_boss": ("pool", "crouching alone behind a rock at the moon pool, one hand pressing his own perineum, the other arm reaching behind with two fingers in his own anus, penis untouched, the high priestess watches from across the water"),
   "inochi_boss": ("roundhall", "he lies curled on his side on silver cloth, the high priestess lies behind him with two fingers in his anus, a thin glowing thread of light in his urethra, cum spurting, the glowing rings around them"),
   "onedari_boss": ("roundhall", "he sits on a silver seat with his legs spread, the high priestess kneels before him with two fingers in his anus pulling a glowing thread of light from his urethra, a silver calendar plate on the wall without text, cum spurting"),
 },
 "lose_desc": "makes him the moon bride, drenched in twelve glowing moon drops.",
 "onanie": {
   "master": ("skylight", "kneeling upright under the skylight, sucking two of his own fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched"),
   "e1": ("spring", "on all fours on the flat rock with hips raised, one arm reaching behind with two of his own wet fingers in his own anus, penis untouched"),
   "e2": ("corridor", "sitting on the marble bench, both hands cupped over his own ears, mouthing words, drool, back arched, hands far from his crotch, penis untouched"),
   "e3": ("garden", "lying on his side among the white flowers, one arm reaching behind with fingers in his own anus, golden honey dripping down his thighs, penis untouched"),
   "boss": ("pool", "sitting on a rock at the water's edge with knees apart, one hand pressing his own perineum, the other arm reaching behind with two fingers in his own anus, penis untouched"),
 },
}
