# N52 古城の仮面舞踏会（Masque）場面データ。登場人物は全員20歳以上。女性（ヴェロニカ・ポーラ）とニューハーフ（エトワール・セシル・ドミナ）の混合。
DATA = {
 "code": "Masque",
 "world": "old castle in a dark forest hosting a masquerade ball at night, hundreds of candles, polished marble floor, velvet curtains, detailed background",
 "chars": {
   "m":    {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, long legs, black hair, updo, red eyes, deep red ball gown, black lace half mask with eyes visible, large breasts",
            "name": "the black-haired countess in a deep red ball gown and black lace half mask"},
   "e1":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, blonde hair, long hair, green eyes, gold slit dress, gold half mask with eyes visible, long slender legs, medium breasts",
            "name": "the blonde dancer in a gold slit dress and gold half mask"},
   "e2":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, chignon, amber eyes, black maid-like serving dress, white half mask with eyes visible, medium breasts",
            "name": "the brown-chignon server in a black serving dress and white half mask"},
   "e3":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, grey hair, long hair, purple eyes, grey feminine tailcoat dress with cinched waist, grey half mask with eyes visible, medium breasts",
            "name": "the grey-haired violinist in a grey tailcoat dress"},
   "boss": {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 42 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, silver hair, long hair, metallic sheen, gold eyes, silver and black gown, silver half mask with eyes visible, large breasts",
            "name": "the silver-haired hostess in a silver and black gown and silver half mask"},
 },
 "places": {
   "ballroom":  "grand ballroom of the castle, crystal chandeliers, hundreds of candles reflected on the polished floor, orchestra stage in the far back",
   "dais":      "raised dais at the head of the ballroom, silver throne-like chair, candelabras, velvet steps",
   "balcony":   "stone balcony of the castle at night, cold stone balustrade, full moon over a black forest, glass doors glowing behind",
   "anteroom":  "anteroom beside the ballroom, velvet chaise longue, tall mirror, single candelabra, velvet curtain",
   "alcove":    "wall alcove of the ballroom half hidden by a velvet drape, velvet sofa, dim light",
   "gallery":   "portrait gallery corridor, gilded frames with dark portraits, candle sconces, red carpet",
   "stairs":    "grand staircase landing, marble steps, red carpet runner, gilded banister",
   "pantry":    "serving pantry behind the ballroom, shelves full of silver trays and champagne glasses, wooden stool",
   "box":       "dim theater box above the ballroom, velvet balustrade, music stand, candlelit ballroom below",
   "instr":     "instrument storeroom, old cellos and harps under cloth covers, smell of rosin and wood",
   "stage":     "orchestra stage of the ballroom, velvet cushion on the boards, music stands, blank chalkboard without text",
   "bedroom":   "castle bedchamber, canopy bed with dark velvet curtains, candlelight, silver mask on the nightstand",
 },
 "atk": {
   "m1": ("ballroom", "he stands stiff in the middle of the ballroom floor, the countess bends from behind and whispers into his ear through her lace mask, her lips at his ear, his knees trembling, precum dripping, no hands on his crotch"),
   "m2": ("ballroom", "they dance a waltz, the countess hugs him tightly against her gown, his bare chest pressed into her breasts, her gloved fingertips pinching his nipple, his back arched, his feet unsteady"),
   "m3": ("balcony", "from side, he stands with his back against the stone balustrade, one of his legs held up by the countess, the countess kisses him deeply while pegging his anus with a black strap-on, anal, tongues, his own penis separate", {"pen": "strapon"}),
   "e1": ("ballroom", "he sits on the floor with his legs spread, the dancer stands over him barefoot with gold toenails and a thin gold anklet, the dancer rubs his erection with the sole of her foot, precum on her toes"),
   "e2": ("alcove", "he lies back on the velvet sofa with his chest out, the server kneels before him pouring champagne from a flute onto his nipple and sucking it, foam bubbles on his chest, his other nipple wet and red"),
   "e3": ("box", "he sits on a chair in the theater box with his chest out, wooden violin bridge clips on both of his nipples vibrating, the violinist stands beside him drawing her bow across the violin strings, sound wave lines, trembling"),
   "boss": ("dais", "from side, he sits in the hostess's lap facing her on the silver chair, the hostess holds his hips and thrusts up into his anus, anal, her fingers pinching both of his nipples, his own penis separate, candlelight", {"pen": "penis"}),
 },
 "atk_desc": {
   "m1": "the countess whispers commands through her lace mask.",
   "m2": "the countess crushes his nipples in her waltz embrace.",
   "m3": "the countess kisses him and pegs him on the moonlit balcony.",
   "e1": "the dancer steps on him with bare feet in waltz time.",
   "e2": "the server licks champagne bubbles off his nipples.",
   "e3": "the violinist makes his nipples vibrate with her strings.",
   "boss": "the hostess penetrates him in the last waltz while pinching his nipples.",
 },
 "lose": {
   # ヴェロニカ 技1 仮面越しの囁き
   "btl_m1": ("ballroom", "he is frozen on his knees in the middle of the ballroom floor, the countess stands behind him bending down, her lips at his ear whispering through the lace mask, tears wetting his bangs, cum on the floor, no hands on him"),
   "onani_m1": ("anteroom", "sitting alone on the velvet chaise longue, pinching both of his own nipples, lips moving counting one two three, flushed, penis untouched, the countess watches from the far doorway holding a closed fan"),
   "inochi_m1": ("gallery", "he stands with his back to the wall of the portrait gallery, arms hanging still, the countess leans in whispering into his ear, her gloved fingertip barely tracing the air near his erection, precum dripping, frozen"),
   "onedari_m1": ("stage", "he kneels frozen on the orchestra stage, the countess stands behind him bending her masked face to his ear, her breath on his ear, his erection throbbing untouched, a blank chalkboard without text behind"),
   # 技2 ワルツの抱擁
   "btl_m2": ("ballroom", "they dance a waltz in the middle of the ballroom, the countess hugs him tightly, his bare chest crushed into her breasts, her gloved fingers pinching his nipple, his face buried in her cleavage, cum on his thighs"),
   "onani_m2": ("anteroom", "kneeling alone on the chaise longue pressing his chest into the soft backrest, pinching his own nipples, rocking in waltz time, penis untouched, the countess watches from the far doorway with a fan"),
   "inochi_m2": ("balcony", "under the moonlight on the balcony, the countess hugs him tightly, his bare chest pressed into her breasts, her gloved fingers between their chests pinching his nipples, his knees buckling"),
   "onedari_m2": ("ballroom", "they waltz across the ballroom floor, the countess holds him tightly against her gown, both of his nipples pinched by her gloved fingers, his nipples red and swollen, precum dripping, his feet barely touching the floor"),
   # 技3 バルコニーで
   "btl_m3": ("balcony", "from side, he stands bent over the cold stone balustrade, the countess behind him pegging his anus with a black strap-on, anal, her head turned kissing him deeply, her gloved hand wrapped around his erection without moving, his own penis separate", {"pen": "strapon"}),
   "onani_m3": ("anteroom", "crouching alone behind the velvet curtain, pinching his own nipple with one hand, the other arm reaching behind with two fingers in his own anus, penis untouched, the countess watches from the far doorway holding a candelabra"),
   "inochi_m3": ("balcony", "from side, he stands with his back against the stone balustrade, one leg held up on the countess's arm, the countess pegs his anus with a black strap-on from the front while kissing him deeply, anal, his own penis separate, moonlight", {"pen": "strapon"}),
   "onedari_m3": ("balcony", "from side, he kneels on a velvet cushion clinging to the stone balustrade, the countess kneels behind him pegging his anus with a black strap-on, anal, his chest pressed to the cold stone, his own penis separate, moonlit forest", {"pen": "strapon"}),
   # e1 エトワール ステップの足
   "btl_e1": ("ballroom", "he sits on the polished floor with his legs spread, the dancer stands over him barefoot, her gold-nailed toes pressing his perineum below his balls, a thin gold anklet, his erection dripping precum"),
   "onani_e1": ("ballroom", "lying face down alone on the carpet at the edge of the ballroom, rubbing his chest against the carpet, hands pressing the floor, hips raised, penis untouched, the dancer watches from far across the floor"),
   "inochi_e1": ("stairs", "he sits on the marble stairs with his legs spread, the dancer sits two steps above him, both of her bare soles sandwiching his erection, gold toenails, a thin gold anklet, precum on her feet"),
   "onedari_e1": ("stage", "he stands at the edge of the orchestra stage thrusting his hips forward, the dancer sits on the stage above him pressing the sole of her bare foot on his erection, gold anklet, a blank chalkboard without text"),
   # e2 ポーラ シャンパンの泡
   "btl_e2": ("alcove", "he lies back on the velvet sofa with his shirt opened, the server kneels before him pouring champagne drop by drop onto his nipple and sucking it, bubbles on his chest, both nipples red and wet"),
   "onani_e2": ("anteroom", "sitting alone on the chaise longue, dripping cold champagne from a flute onto his own nipple, fingertips flicking the wet nipple, penis untouched, the server watches from the far doorway holding a silver tray"),
   "inochi_e2": ("pantry", "he sits on a wooden stool among shelves of glasses, arching his back and offering his chest, the server bends down sucking his nipple, champagne bubbles on his chest, her fingers pinching his other nipple"),
   "onedari_e2": ("ballroom", "he stands holding a silver tray of champagne flutes level with both hands, chest out, the server bends down licking champagne off his nipple, bubbles running down his chest, precum dripping"),
   # e3 セシル 弦の振動
   "btl_e3": ("box", "he lies on his back on the floor of the theater box, wooden violin bridge clips vibrating on both of his nipples, the violinist kneels between his legs with one finger in his anus pressing his prostate, cum on his belly"),
   "onani_e3": ("box", "sitting alone on a chair in the theater box, fingertips trembling rapidly on both of his own nipples like a vibrato, head tilted back, penis untouched, the violinist watches from the far corner holding her violin"),
   "inochi_e3": ("instr", "he stands bent over clinging to a cloth-covered harp, a humming tuning fork clipped against his nipple, the violinist behind him with one oiled finger in his anus, her other hand plucking a violin string"),
   "onedari_e3": ("stage", "he lies on his back on the orchestra stage, the violinist kneels by his head resting her violin body on his chest and bowing, his chest vibrating, sound wave lines, his erection untouched and throbbing"),
   # boss ドミナ 最後のワルツ
   "btl_boss": ("dais", "from side, he sits in the hostess's lap facing her on the silver chair, the hostess pulls his hips down and thrusts up into his anus, anal, pinching his nipple with her other hand, his own penis separate, candlelight", {"pen": "penis"}),
   "onani_boss": ("anteroom", "kneeling alone on the chaise longue, pinching his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched, the hostess watches from the far doorway"),
   "inochi_boss": ("bedroom", "from side, he lies on his back on the canopy bed with legs spread, the hostess on top of him penetrating his anus, anal, pinching his nipple, cum splashed on his chest, his own penis separate", {"pen": "penis"}),
   "onedari_boss": ("dais", "from side, he sits in the hostess's lap facing her on the silver chair, the hostess hugs him tightly penetrating his anus from below, anal, his nipples crushed against her breasts, her fingers pinching one, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "makes him a masked servant of the endless masquerade.",
 "onanie": {
   "master": ("ballroom", "standing alone hugging himself tightly, arms crossed over his chest, fingertips pinching his own nipples, swaying in waltz time, penis untouched, lips parted, ragged breathing, knees shaking"),
   "e1": ("ballroom", "lying face down on the carpet, rubbing his chest against it in waltz rhythm, one arm reaching back pressing his own perineum, penis untouched, lips parted, ragged breathing, knees shaking"),
   "e2": ("alcove", "sitting on the velvet sofa, dripping champagne from a flute onto his own nipple, fingertip flicking the wet nipple, penis untouched, lips parted, ragged breathing, knees shaking"),
   "e3": ("box", "sitting on a chair in the theater box, fingertips trembling rapidly on both of his own nipples like a vibrato, penis untouched, lips parted, ragged breathing, knees shaking"),
   "boss": ("dais", "kneeling on the velvet steps, pinching his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched, lips parted, ragged breathing, knees shaking"),
 },
}
