# N44 宝箱の迷宮（Mimic）場面データ。登場人物は全員20歳以上（年齢不詳の成人）。ラビリス・パンドラはふたなり、ツボミ・カラは男の娘。ミミ・ツボミ・パンドラは箱／壺から上半身を出したまま。
DATA = {
 "code": "Mimic",
 "world": "underground stone labyrinth, torchlight, treasure chests and ceramic pots, glinting gold coins, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 30 years old, tall, long legs, both eyes clearly visible, purple hair, long hair, braided, gold eyes, black and gold dress, key ring, tentacles from treasure chest behind, playful smile, large breasts",
         "name": "the purple-braided labyrinth mistress in a black and gold dress with a treasure chest behind her"},
   "e1": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 23 years old, both eyes clearly visible, mimic, woman emerging from treasure chest, lower body inside the chest, blonde hair, twintails, red eyes, chest lid, fang decorations on the chest rim, tentacles inside chest, cheerful, large breasts",
          "name": "the blonde twintailed mimic emerging from an old treasure chest",
          "neg": "legs on the mimic, the mimic out of the chest"},
   "e2": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 22 years old, both eyes clearly visible, mimic, adult otoko no ko emerging from large ceramic pot, lower body inside the pot, green hair, bob cut, amber eyes, slime dripping from pot, sleepy smile",
          "name": "the green-bob pot mimic emerging from a large ceramic pot",
          "neg": "legs on the pot mimic, the pot mimic out of the pot"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 25 years old, both eyes clearly visible, living armor, grey hair, long hair, red eyes, empty full armor, helmet removed, slender, stern",
          "name": "the grey-haired living armor in full plate with the helmet removed",
          "neg": "armor on the navy-haired man"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 36 years old, tall, long legs, both eyes clearly visible, mimic, woman emerging from golden treasure chest, lower body inside the chest, red hair, long wavy hair, gold eyes, tentacles inside lid, motherly smile, huge breasts",
            "name": "the red-haired mimic emerging from a huge golden treasure chest",
            "neg": "legs on the golden chest mimic"},
 },
 "places": {
   "entrance": "damp stone corridor at the labyrinth entrance, torches, dripping water, iron-bound door",
   "maze":     "winding stone maze corridor, identical corners, gold studs on the walls, an old treasure chest at the corner",
   "deadend":  "dead-end chamber, moss on the stones, one old treasure chest against the wall",
   "vault":    "treasure vault, torchlight, rows of treasure chests and pots, piles of gold coins",
   "coins":    "mountain of gold coins, shimmering torchlight, spilled jewels",
   "mimiroom": "chamber with an old fanged treasure chest, amber gems scattered on the floor",
   "pots":     "room of ceramic pots of many sizes, humid air, sweet clear slime dripping",
   "potrest":  "resting nook at the back of the pot room, straw on the floor, large ceramic pots",
   "armory":   "armory lined with empty suits of full plate armor, iron racks, oil lamps",
   "keys":     "room with countless keys hanging on the walls, brass glint",
   "appraise": "appraisal room, stone appraisal table, brass scales, oil lamp",
   "pit":      "bottom of a pit trap, soft moss floor, thin light from far above",
   "spring":   "underground spring chamber, ankle-deep clear water, glowing moss",
   "shelf":    "gallery corridor lined with empty treasure chests with open lids",
   "bedroom":  "mistress's bedroom, purple canopy bed, thick carpet, a large open treasure chest lined with velvet beside the bed",
   "inbox":    "inside a large treasure chest lined with purple velvet, the lid nearly closed, thin warm light through the gap",
   "hidden":   "cramped hidden storeroom behind a swinging bookshelf, dim lamp",
   "guard":    "guard post with torches, a spear rack and a wooden bench",
   "altar":    "deepest altar chamber, huge golden treasure chest lined with velvet, golden glow",
 },
 "atk": {
   "m1": ("maze", "he stands bent forward with his hands on the rim of the treasure chest at the corner, the labyrinth mistress hugs him from behind whispering into his ear and nibbling his earlobe, a long tongue stretching from her treasure chest licking his anus, anilingus"),
   "m2": ("vault", "he kneels on all fours inside a large empty treasure chest, the lid half open over his back, the labyrinth mistress stands beside it stroking his chest with her key-ring hand, a long warm tongue from her treasure chest licking his anus, anilingus"),
   "m3": ("inbox", "from side, he lies on his side on the velvet inside the chest, the labyrinth mistress lies behind him penetrating his anus with her penis, anal, slick tentacles sucking on both his nipples, his own penis separate", {"pen": "penis"}),
   "e1": ("mimiroom", "he is pulled chest-first against the rim of the fanged treasure chest, the chest mimic leans out of her chest licking his nipple upward with a long tongue, tentacles from the chest wrapped around his waist and arms"),
   "e2": ("pots", "he leans his belly over the rim of the large ceramic pot, the pot mimic leans out of the pot holding his waist, slime-covered fingers pushing warm clear slime into his anus, slime dripping down his thighs"),
   "e3": ("armory", "he is held from behind in the living armor's steel arms, rounded gauntlet fingers slick with oil pushed into his anus, fingering, the other gauntlet pinching his nipple, rows of empty armor"),
   "boss": ("altar", "he lies on his back on velvet inside the huge golden treasure chest, the golden chest mimic holds him in her arms, a hair-thin tentacle entering his urethra, another tentacle in his anus, sounding, tentacles from the lid"),
 },
 "atk_desc": {
   "m1": "the labyrinth mistress whispers wrong directions into his ear.",
   "m2": "the labyrinth mistress's treasure chest licks him deep inside.",
   "m3": "the labyrinth mistress shuts the lid and takes him in the dark.",
   "e1": "the chest mimic licks his nipples from inside her chest.",
   "e2": "the pot mimic fills him with warm slime.",
   "e3": "the living armor inspects him with steel fingers.",
   "boss": "the golden chest mimic fills him front and back with tentacles.",
 },
 "lose": {
   # m1 迷いの囁き
   "btl_m1": ("maze", "he stands bent forward with his hands on the rim of a treasure chest at a maze corner, the labyrinth mistress hugs him from behind whispering into his ear, a long tongue from her treasure chest licking his anus, anilingus, cum dripping"),
   "onani_m1": ("vault", "curled alone inside an empty treasure chest in the corner of the vault, lips moving as if murmuring, reaching behind to stroke his own anus with a wet finger, penis untouched, the labyrinth mistress stands far away among the chests watching"),
   "inochi_m1": ("bedroom", "he kneels before the open velvet-lined treasure chest beside the canopy bed holding a key with a purple tassel, the labyrinth mistress whispers into his ear from behind, a long tongue from her chest licking his anus, anilingus"),
   "onedari_m1": ("keys", "he kneels bent forward among walls of hanging keys, the labyrinth mistress holds his head and whispers into his ear, a long tongue from her chest licking his anus, anilingus, a gold key earring on his ear"),
   # m2 宝箱の舌
   "btl_m2": ("vault", "he kneels on all fours inside a large empty treasure chest, the lid half open over his back, a long warm tongue from the labyrinth mistress's chest pushing deep into his anus, anilingus, her key-ring hand stroking his nipple, cum dripping"),
   "onani_m2": ("shelf", "sitting alone on the lid of an empty treasure chest in a row of open chests, one oily finger circling his own anus, the other hand gripping the chest rim, penis untouched, the labyrinth mistress stands far down the gallery watching"),
   "inochi_m2": ("pit", "he hangs lifted in the air by tentacles from her chest with his legs spread, the labyrinth mistress stands on the moss below, a long tongue from her chest licking his anus, anilingus, a key on a string around his neck"),
   "onedari_m2": ("appraise", "he lies face down on the stone appraisal table with his hips raised, the labyrinth mistress stands behind him reading a blank tag without text, a long tongue from her chest licking deep into his anus, anilingus"),
   # m3 蓋を閉じて
   "btl_m3": ("inbox", "from side, he lies on his side on the velvet lining inside the chest, the labyrinth mistress lies behind him penetrating his anus with her penis, anal, slick tentacles sucking both his nipples, his own penis separate, cum on the velvet", {"pen": "penis"}),
   "onani_m3": ("hidden", "curled alone on the floor of the cramped hidden room, one hand behind stroking his own anus, the other hand pinching his own nipple, penis untouched, the labyrinth mistress stands far away in the opened bookshelf doorway watching"),
   "inochi_m3": ("bedroom", "from side, he lies on his side inside the open velvet-lined chest beside the canopy bed, the labyrinth mistress lies behind him penetrating his anus with her penis, anal, tentacles sucking his nipples, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("inbox", "from above, he lies on his back on the velvet with his legs raised, the labyrinth mistress kneels between his legs penetrating his anus with her penis, anal, tentacles sucking his nipples, a row of gold clasps on the lid, his own penis separate", {"pen": "penis"}),
   # e1 ミミ
   "btl_e1": ("mimiroom", "he is pulled against the rim of the fanged treasure chest, the chest mimic leans out licking his nipple with a long tongue, tentacles holding his waist, a thin tentacle pushed into his anus, anal tentacle, his own penis separate"),
   "onani_e1": ("vault", "sitting alone on the lid of a treasure chest, rubbing his own nipple upward with a saliva-wet finger as if licking, chest pushed out, penis untouched, the chest mimic leans out of another chest far away watching"),
   "inochi_e1": ("deadend", "he leans over the old treasure chest reaching inside for a key, the chest mimic leans out licking his nipple with a long tongue, tentacles curling around his reaching arm, moss"),
   "onedari_e1": ("spring", "he kneels in the ankle-deep spring water resting his chest on the rim of the chest, the chest mimic leans out sucking and licking his nipple, tentacles wrapped around his arms, glowing moss"),
   # e2 ツボミ
   "btl_e2": ("pots", "he lies with his belly over the rim of the large ceramic pot, the pot mimic leans out of the pot holding him, pushing slime-covered fingers into his anus and filling him with warm clear slime, slime dripping, kissing his cheek"),
   "onani_e2": ("potrest", "leaning alone against a large ceramic pot with his hips pushed back, reaching behind with lotion-soaked fingers into his own anus, lotion dripping, penis untouched, the pot mimic dozes in another pot far away watching"),
   "inochi_e2": ("spring", "his arm is sunk to the elbow in the ceramic pot, slime clinging, the pot mimic leans out kissing him deeply, the pot mimic's other slimy hand fingering his anus, glowing moss"),
   "onedari_e2": ("vault", "he kneels bent over beside the ceramic pot in the corner of the vault, the pot mimic leans out filling his anus with warm slime from slimy fingers, slime overflowing, kissing him slowly"),
   # e3 カラ
   "btl_e3": ("armory", "he is held from behind in the living armor's steel arms among the empty armor suits, rounded gauntlet fingers pushed deep into his anus, fingering, the other gauntlet pinching his nipple, cum dripping"),
   "onani_e3": ("appraise", "kneeling alone on the cold stone floor, reaching behind with two fingers in his own anus pressing upward, penis untouched, the living armor stands far away beside the appraisal table holding the helmet, watching"),
   "inochi_e3": ("entrance", "he stands braced against the stone wall by the iron-bound door, the living armor stands behind him pushing gauntlet fingers into his anus, fingering, the other steel arm around his chest, torches"),
   "onedari_e3": ("guard", "he lies on his back on the wooden bench holding his knees, the living armor kneels pushing two rounded gauntlet fingers into his anus, fingering, the other gauntlet pinching his nipple, spear rack"),
   # boss パンドラ
   "btl_boss": ("altar", "from side, he lies on his side on velvet inside the huge golden treasure chest, the golden chest mimic hugs him from behind penetrating his anus with her penis, anal, a hair-thin tentacle in his urethra, tentacles from the lid, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("shelf", "sitting alone on the lid of a treasure chest at the end of the gallery, one hand pushing up on his own perineum, the other hand behind him with fingers in his own anus, penis untouched, the golden chest mimic watches far away"),
   "inochi_boss": ("vault", "he lies on velvet inside the golden treasure chest, the golden chest mimic hugs him, a hair-thin tentacle entering his urethra, another tentacle in his anus, sounding, a key in the keyhole on the inside of the lid"),
   "onedari_boss": ("altar", "from side, he lies on his back on the velvet inside the golden chest with his legs raised, the golden chest mimic leans over him penetrating his anus with her penis, anal, a thin tentacle in his urethra, sounding, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "keeps him curled up asleep inside a velvet-lined treasure chest as her treasure.",
 "onanie": {
   "master": ("vault", "sitting on the lid of a treasure chest, one oily finger circling his own anus from behind, the other hand gripping the chest rim, penis untouched"),
   "e1": ("mimiroom", "kneeling alone by the fanged treasure chest with his chest pushed out, rubbing his own nipple upward with a saliva-wet finger as if licking, penis untouched"),
   "e2": ("pots", "leaning against a large ceramic pot with his hips pushed back, reaching behind with lotion-soaked fingers into his own anus as if filling himself with slime, lotion dripping, penis untouched"),
   "e3": ("armory", "kneeling on the cold stone floor among the empty armor, reaching behind with two cold fingers in his own anus, pressing upward step by step, penis untouched"),
   "boss": ("altar", "sitting with his legs apart, one hand pushing up on his own perineum, the other hand behind him with fingers in his own anus, penis untouched"),
 },
}
