# N41 猫又の屋敷（Nekomata）場面データ。登場人物は全員20歳以上（猫又は年齢不詳の成人）。タマキ・オウカはふたなり、スミ・チャイは男の娘。
DATA = {
 "code": "Nekomata",
 "world": "old samurai mansion deep in the mountains, tatami rooms, shoji screens, zabuton cushions everywhere, small bells, warm lantern light, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 30 years old, tall, long legs, both eyes clearly visible, nekomata, cat ears, two tails, white hair, long hair, gold eyes, loose kimono, bell pattern, lazy seductive smile, large breasts",
         "name": "the white-haired nekomata in a bell-pattern kimono",
         "neg": "realistic cat, feral, quadruped animal"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, cat ears, black cat tail, black hair, short hair, gold eyes, short black kimono, paw gloves, shy",
          "name": "the black-haired cat otoko no ko in a short black kimono and paw gloves",
          "neg": "realistic cat, feral, quadruped animal"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 24 years old, both eyes clearly visible, calico cat ears, calico tail, multicolored hair, green eyes, calico kimono, tasuki, caring smile, medium breasts",
          "name": "the calico-haired cat woman in a calico kimono and tasuki",
          "neg": "realistic cat, feral, quadruped animal"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 22 years old, both eyes clearly visible, cat ears, orange tabby tail, orange hair, messy hair, amber eyes, jinbei, barefoot, grin",
          "name": "the orange-haired tabby otoko no ko in a jinbei",
          "neg": "realistic cat, feral, quadruped animal"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 37 years old, tall, long legs, both eyes clearly visible, nekomata, cat ears, two tails, blonde hair, long hair, red eyes, black uchikake, gold embroidery, large bell collar, tall, mature, large breasts",
            "name": "the blonde nekomata chief in a black uchikake with a large bell collar",
            "neg": "realistic cat, feral, quadruped animal"},
 },
 "places": {
   "gate":      "roofed gate of the old mansion in the rain, wet stone pavement, moss, raindrops falling from the tiled eaves",
   "engawa":    "polished dark wooden veranda, warm sunset light through shoji screens, sunny spot",
   "engawa_n":  "dark wooden veranda at night, moonlit garden, paper lantern",
   "zashiki":   "eight-tatami front room, hanging scroll in the alcove, many zabuton cushions",
   "nedoko":    "room piled high with zabuton and futons, round hollows like cat beds, warm sunlight",
   "irori":     "sunken hearth room, iron kettle hanging over glowing charcoal, orange firelight",
   "doma":      "earthen-floored kitchen, kamado stove, wooden buckets, cool dirt floor",
   "kura":      "dim storehouse, old wicker trunks, bundles of dried silver vine hanging from the beams",
   "yudono":    "small hinoki wood bath room, wooden bath pail, wet wooden floor, steam",
   "ike":       "garden pond at night, stone lantern with a small flame, flat stones, koi",
   "yaneura":   "attic with thick beams, hay, moonlight through gaps in the boards",
   "nando":     "dark cramped storeroom closet, folded futons, wicker trunks, a sliver of light from the open sliding door",
   "suzu":      "long wooden corridor with many small bells hanging from the ceiling",
   "tsukimi":   "wooden moon-viewing deck jutting over the garden, full moon, pampas grass",
   "chashitsu": "small detached tea room, sunken hearth with an iron kettle, tatami",
   "osa":       "chief's hall, gold folding screen, incense smoke, a black uchikake on a kimono rack, a large bell",
 },
 "atk": {
   "m1": ("engawa", "he lies on his back with his head on the white nekomata's lap, the nekomata bends down licking his nipple upward with her rough cat tongue, her two white tails stroking his sides, erect nipples, saliva"),
   "m2": ("zashiki", "from side, he is on all fours on a zabuton, the white nekomata kneels behind him, one of her white tails slick with oil pushed into his anus, anal, the other tail wrapped around his waist spreading his legs, his own penis separate"),
   "m3": ("nedoko", "from side, he lies curled on his side in the pile of futons, the white nekomata lies behind him penetrating his anus with her penis, anal, she turns his face and kisses him deeply while purring, tongues, his own penis separate", {"pen": "penis"}),
   "e1": ("nando", "he sits on the floor, the black cat hugs him from behind, both paw-gloved hands pressing and kneading his chest, his nipples caught between the paw pads, the black cat whispering into his ear, black tail wrapped around his leg"),
   "e2": ("yudono", "he is on all fours on the wet wooden floor, the calico cat woman kneels behind him holding his hips and licking his anus with her rough tongue as if grooming, anilingus, saliva, steam"),
   "e3": ("engawa", "he lies on his back on the veranda, the tabby sits beside him pressing his thigh down with one bare foot, holding his penis and pushing the thin oiled tip of the orange tail into his urethra, urethral insertion, sounding"),
   "boss": ("osa", "he lies with his head on the nekomata chief's lap, the chief bends over licking his nipple with her rough tongue while her oiled fingers reach down into his anus, fingering, her two golden tails wrapped around his wrists"),
 },
 "atk_desc": {
   "m1": "the white nekomata grooms his nipples with her rough tongue.",
   "m2": "the white nekomata opens him with her two tails.",
   "m3": "the white nekomata purrs into his mouth while taking him from behind.",
   "e1": "the black cat kneads his chest with soft paw pads.",
   "e2": "the calico cat woman grooms him with her rough tongue.",
   "e3": "the tabby slides the thin tip of his tail inside him.",
   "boss": "the nekomata chief grooms him on her lap.",
 },
 "lose": {
   # m1 ざらつく舌
   "btl_m1": ("engawa", "he lies on his back with his head on the white nekomata's lap in the sunlight, the nekomata licks his nipple upward with her rough tongue, a pink paw-print mark on the center of his chest, her two tails stroking his sides, cum on his belly"),
   "onani_m1": ("nedoko", "kneeling alone in a hollow in the pile of futons, rubbing his own nipples upward with two saliva-wet fingertips as if licking, chest pushed out, tongue out, penis untouched, the white nekomata lies on the futon pile far away watching"),
   "inochi_m1": ("irori", "he sits on the white nekomata's lap by the sunken hearth, the nekomata holds him from behind and licks his neck and nipple with her rough tongue as if wiping him, a paw print pressed into the hearth ash, dazed"),
   "onedari_m1": ("tsukimi", "he kneels on the moon-viewing deck under the full moon with his chest pushed out begging, the white nekomata bends down licking one nipple with the flat of her rough tongue, counting on her fingers, a brass bell hanging from the pillar"),
   # m2 二股の尻尾
   "btl_m2": ("zashiki", "from side, he is on all fours on a zabuton, the white nekomata kneels beside his head licking his nipple from below, one of her white tails pushed into his anus, the other tail wrapped around his waist spreading his legs, his own penis separate, cum dripping"),
   "onani_m2": ("kura", "kneeling alone among hanging bundles of dried silver vine, one wet fingertip rubbing his own nipple, the other hand reaching behind circling his own anus with a finger, penis untouched, the white nekomata stands far away at the storehouse door watching"),
   "inochi_m2": ("yudono", "he sits in the hinoki bath with the water at his waist, the white nekomata kneels on the bath edge beside him licking his nipple, one white tail wrapped around his waist spreading his legs, the other tail pushed into his anus, steam"),
   "onedari_m2": ("yaneura", "he lies on his back on the hay holding his own knees apart, begging, the white nekomata kneels beside him licking his nipple, one white tail pushed into his anus, the other tail coiled around his waist, a bell rope hanging from a beam, moonlight"),
   # m3 喉を鳴らしながら
   "btl_m3": ("nedoko", "from side, he lies curled on his side in the pile of futons, the white nekomata lies behind him penetrating his anus with her penis, anal, she kisses him deeply while purring, her hand on his nipple, his own penis separate, cum on the futon", {"pen": "penis"}),
   "onani_m3": ("nando", "curled alone on an old zabuton in the dark closet, sucking the fingers of one hand, the other hand reaching behind to his own anus, knees drawn up, penis untouched, the white nekomata stands far away at the open sliding door watching"),
   "inochi_m3": ("suzu", "from side, he stands with both hands on the corridor wall, bent forward, the white nekomata stands behind him penetrating his anus with her penis, anal, she kisses the back of his neck while purring, rows of bells swaying above, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("ike", "from side, he is on all fours on the flat stones by the pond, the white nekomata kneels behind him penetrating his anus with her penis, anal, she leans over and turns his face to kiss him deeply, the stone lantern glowing, his own penis separate", {"pen": "penis"}),
   # e1 スミ
   "btl_e1": ("nando", "he sits on the floor of the dark closet, the black cat hugs him tightly from behind, paw-gloved hands kneading both of his nipples, the black tail coiled around his leg, a red string tied from the black tail to his wrist, whispering into his ear"),
   "onani_e1": ("nedoko", "sitting alone in a corner of the futon room, arms crossed over his chest as if hugging himself, both palms pressing and releasing his own nipples in a kneading rhythm, penis untouched, the black cat sits far away watching silently"),
   "inochi_e1": ("yaneura", "he lies on his side on the hay pretending to sleep, the black cat lies hugging him from behind, one paw-gloved hand kneading his nipple, lips at his ear whispering, moonlight through the boards"),
   "onedari_e1": ("engawa_n", "he sits on the veranda at night whispering a request, the black cat hugs him from behind pressing both paw-gloved hands on his chest, kneading his nipples, a thin black cord around his neck"),
   # e2 ミケ
   "btl_e2": ("yudono", "he is on all fours on the wet floor after the bath, the calico cat woman kneels behind him licking his anus with her rough tongue, anilingus, the tongue tip pushing in shallowly, saliva, a strip of her tasuki tied on his wrist, steam"),
   "onani_e2": ("doma", "kneeling alone on the cool earthen floor with his hips raised, reaching behind and stroking around his own anus with a wet finger in slow careful strokes as if grooming, penis untouched, the calico cat woman stands far away by the stove watching"),
   "inochi_e2": ("kura", "he lies face down on a straw mat, dazed, a bundle of dried silver vine by his face, the calico cat woman kneels over his legs spreading his buttocks and licking his anus with her rough tongue, anilingus"),
   "onedari_e2": ("tsukimi", "under the full moon, he is on all fours on the deck, the calico cat woman kneels behind him licking his anus with her rough tongue, anilingus, a boxwood comb in her hand, pampas grass swaying"),
   # e3 チャイ
   "btl_e3": ("engawa", "he lies on his back on the veranda, the tabby sits beside him pressing his thigh down with a bare foot, holding his penis and pushing the thin oiled tip of the orange tail into his urethra, urethral insertion, sounding, trembling"),
   "onani_e3": ("ike", "lying alone on a flat stone by the pond at night with his legs apart, one fingertip tracing upward along his own perineum, the other hand gripping the stone, penis untouched, the tabby squats far away on a rock watching, grinning"),
   "inochi_e3": ("doma", "he sits on a straw mat in front of the kamado stove, the tabby sits facing him holding his penis between both bare soles, footjob, the thin tip of the orange tail entering his urethra, sounding"),
   "onedari_e3": ("suzu", "he lies on his back on the bell corridor floor, the tabby stands over him treading on his lower belly with one bare foot, the thin orange tail tip inserted into his urethra, a bell tied to the tail, sounding"),
   # boss オウカ
   "btl_boss": ("osa", "from side, he lies on his side on the tatami before the gold folding screen, the nekomata chief lies behind him penetrating his anus with her penis, anal, her two golden tails wrapped around his wrists, a golden paw-print mark on his throat, his own penis separate", {"pen": "penis"}),
   "onani_boss": ("chashitsu", "curled alone on his side on the tatami of the tea room, one wet finger stroking his own nipple, the other hand reaching behind with two fingers in his own anus, penis untouched, the nekomata chief kneels far away by the hearth watching"),
   "inochi_boss": ("gate", "under the rainy eaves, he lies with his head on the nekomata chief's lap, a red collar with a gold bell and a blank tag without text on his neck, the chief licks his nipple while her oiled fingers push into his anus, fingering"),
   "onedari_boss": ("zashiki", "from side, he lies on his side on the hem of the black uchikake spread over the tatami, the nekomata chief lies behind him penetrating his anus with her penis, anal, licking his neck with her rough tongue, his own penis separate", {"pen": "penis"}),
 },
 "lose_desc": "keeps him as the mansion's pet, a red collar with a small gold bell on his neck.",
 "onanie": {
   "master": ("engawa", "sitting alone on the veranda with his chest pushed out, rubbing his own nipples upward with two saliva-wet fingertips as if licking, tongue out, penis untouched"),
   "e1": ("nedoko", "kneeling alone on a futon, arms crossed over his chest, both palms pressing and releasing his own nipples in a slow kneading rhythm like paws, penis untouched"),
   "e2": ("yudono", "on all fours on the wet bath floor with his hips raised, reaching back and stroking around his own anus with a wet finger in slow careful strokes, penis untouched"),
   "e3": ("engawa", "lying on his back on the veranda with his legs apart, one fingertip tracing up his own perineum, the other hand gripping the floor, penis untouched"),
   "boss": ("chashitsu", "curled on his side on the tatami, one wet finger stroking his own nipple, the other hand reaching behind with a finger in his own anus, penis untouched"),
 },
}
