# N31 湯守の宿（Onsen）場面データ。登場人物は全員20歳以上。責め手は女性（ミヤコ・ツバキ・セツ）と男の娘（ハル・コウ）。
DATA = {
 "code": "Onsen",
 "world": "old japanese hot spring inn in the mountains at night, rising steam, paper lanterns without text, wooden architecture, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 34 years old, tall, long legs, both eyes clearly visible, black hair, updo, red eyes, wisteria kimono, white apron, okami, gentle dominant smile, large breasts",
         "name": "the black-haired okami in a wisteria kimono"},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 22 years old, both eyes clearly visible, brown hair, short bob, amber eyes, green kimono, tasuki, nakai, cheerful",
          "name": "the brown-bob nakai in a green kimono"},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 29 years old, both eyes clearly visible, pink hair, tied back, green eyes, white samue, long fingers, expressionless",
          "name": "the pink-haired masseuse in a white samue"},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 24 years old, both eyes clearly visible, blonde hair, short hair, tenugui headband, brown eyes, grey happi coat, barefoot, smirk",
          "name": "the blonde bath attendant in a grey happi coat"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 38 years old, tall, long legs, both eyes clearly visible, white hair, long hair, updo, gold eyes, black tomesode kimono, gold obi, mature, large breasts",
            "name": "the white-haired grand okami in a black tomesode"},
 },
 "places": {
   "roten": "rocky open-air hot spring, flat rock at the edge of the bath, river and red maple leaves, thick steam",
   "uchiyu": "indoor hinoki cypress bath, wooden walls, wooden buckets, warm steam, lantern light",
   "arai": "washing area, wooden bath stool, wooden bucket, soap foam, steamed-up mirror, wet tiles",
   "datsui": "changing room, rattan baskets on shelves, tall standing mirror, wooden floorboards",
   "guest": "eight-tatami guest room, futon, andon paper lamp, shoji window with steam outside",
   "okami_room": "okami's private room, wisteria-patterned fusuma, lacquered dresser with mirror, futon, andon lamp",
   "anma": "dim massage room, single futon, incense smoke, low lamp",
   "bandai": "bath entrance rest area, high wooden bandai counter, round paper fans, glass of barley tea, zabuton cushions",
   "choba": "inn front desk, open guest ledger without text, abacus, pendulum wall clock",
   "rouka": "covered wooden corridor between bathhouse and main building, paper lanterns without text, night",
   "mushi": "stone steam room, thick white steam, stone bench, small hourglass",
   "kazoku": "small private hinoki family bath, wooden key tag without text",
   "yubatake": "hot spring field, long wooden troughs with yellow-white yunohana deposits, sulfur steam at night",
   "koya": "small wooden hut at the hot spring source, bubbling source water, hanging happi coat, iron key on a nail",
   "hanare": "grand okami's annex, small indoor bath of golden-tinted water, black tomesode on a kimono rack",
   "hanare_rouka": "polished wooden corridor of the annex, sliding doors, lantern light",
   "engawa": "wooden veranda of the annex at night, moonlit japanese garden, zabuton cushion",
 },
 "atk": {
   "m1": ("roten", "he sits in the hot water leaning back against the rock, the okami kneels behind him in the water, her lips at his ear singing softly, hands on his shoulders, his mouth open, trembling, steam"),
   "m2": ("uchiyu", "he sits between the okami's knees in the hinoki bath, twisted around, the okami holds his chin and kisses him deeply, tongues, saliva trail, her other hand on his chest, flushed"),
   "m3": ("roten", "from side, he is bent forward over the flat rock at the edge of the bath, the okami stands behind him in the water pegging his anus with her strap-on, anal, her hand reaching around rubbing his nipple, his own penis separate", {"pen": "strapon"}),
   "e1": ("arai", "he sits on the wooden bath stool leaning forward, soap foam all over his body, the nakai kneels behind him with two foamy fingers in his anus, anal fingering, the other foamy hand rubbing his nipple"),
   "e2": ("anma", "he lies on his back on the futon, the masseuse kneels beside him pressing one fingertip into his lower belly and one into his inner thigh, acupressure, no hand on his penis, his back arched"),
   "e3": ("yubatake", "he sits on the edge of a wooden trough with legs apart, the bath attendant crouches between his knees feeding milky white jelly into his urethra through a thin bamboo tube, urethral insertion, a ceramic pot of jelly on the trough"),
   "boss": ("hanare", "they stand waist-deep in the golden bath, the grand okami embraces him tightly and kisses him deeply, tongues, her fingers pinching both of his nipples, his arms limp, steam"),
 },
 "atk_desc": {
   "m1": "the okami sings a thousand-night bath song into his ear.",
   "m2": "the okami kisses him long in the bath.",
   "m3": "the okami strokes his chest in the water while taking him from behind.",
   "e1": "the nakai washes him inside with soapy fingers.",
   "e2": "the masseuse presses the hidden points until he melts.",
   "e3": "the bath attendant fills him with warm yunohana jelly.",
   "boss": "the grand okami seals his mouth and chest in one embrace.",
 },
 "lose": {
   # m1 千夜の湯歌
   "btl_m1": ("roten", "he sits in the water up to his chest, the okami hugs him from behind singing into his ear, he turns his head and the okami kisses him, her fingertips circling his nipples, a tiny silver bell tied on his wrist, cum floating in the water"),
   "onani_m1": ("datsui", "kneeling alone on the floorboards before the tall mirror, sucking two of his own fingers, the other wet hand circling his own nipple, humming, penis untouched, the okami stands in the far doorway watching, a wisteria towel in a basket"),
   "inochi_m1": ("okami_room", "morning light, he lies in the futon in the okami's room, the okami lies beside him singing a lullaby into his ear, her hand stroking his chest, an open guest ledger without text on the dresser, his knees trembling"),
   "onedari_m1": ("guest", "he lies on the futon with his head in the okami's lap, the okami bends down singing into his right ear, one finger rubbing his nipple, andon lamp glowing, cum on his belly, dazed"),
   # m2 湯船の口づけ
   "btl_m2": ("uchiyu", "he sits between the okami's knees in the hinoki bath, twisted around, the okami holds his face and kisses him deeply, tongues, saliva dripping into the water, red lipstick smudged on his lips, cum floating"),
   "onani_m2": ("guest", "kneeling alone before a lacquered dresser mirror, sucking his own fingers deeply as if kissing, the other hand tracing his own nipple, penis untouched, a red lip brush on the dresser, the okami watches from the fusuma"),
   "inochi_m2": ("choba", "he kneels on the tatami beside the front desk offering his lips, the okami bends down kissing him deeply, open guest ledger without text and abacus beside them, the pendulum clock behind, flushed"),
   "onedari_m2": ("kazoku", "they sit facing each other in the cozy family bath, he holds a wooden key tag without text to his chest, the okami kisses him with her tongue deep in his mouth, saliva dripping, steam"),
   # m3 湯の中で胸を撫でながら
   "btl_m3": ("okami_room", "from side, he lies on his back on the futon holding his knees, the okami kneels between his legs pegging his anus with her strap-on, anal, kissing him, her fingers pinching his nipple, his own penis separate, cum on his belly", {"pen": "strapon"}),
   "onani_m3": ("mushi", "sitting alone on the stone bench in thick steam, sucking two of his own fingers, one arm reaching behind with a finger in his own anus, penis untouched, the okami stands in the steamy doorway watching, hourglass"),
   "inochi_m3": ("guest", "from side, he lies on his side on the futon on top of an opened indigo yukata, the okami lies behind him pegging his anus with her strap-on, anal, her hand slipped around rubbing his nipple, his own penis separate", {"pen": "strapon"}),
   "onedari_m3": ("roten", "from side, he kneels in the shallow water with his hands on the flat rock, the okami stands behind him pegging his anus deep with her strap-on, anal, reaching around pinching his nipple, his own penis separate, steam", {"pen": "strapon"}),
   # e1 ハル
   "btl_e1": ("arai", "he sits on the wooden bath stool bent forward, soap foam over his body, the nakai kneels behind him with two foamy fingers deep in his anus, the other hand washing his nipple, cum on the wet tiles"),
   "onani_e1": ("datsui", "bent over a washbasin in the changing room alone, one arm reaching behind with soapy fingers in his own anus, foam dripping, penis untouched, the nakai watches from the far doorway holding a green towel"),
   "inochi_e1": ("bandai", "he lies with his head on the nakai's lap on the zabuton, the nakai fans him with a round fan while the other hand reaches down with fingers in his anus, a glass of barley tea beside them"),
   "onedari_e1": ("arai", "he is on all fours on the wet tiles before the steamed-up mirror, the nakai kneels beside him with two soapy fingers deep in his anus, foam everywhere, sleeves tied back with the tasuki, drooling"),
   # e2 ツバキ
   "btl_e2": ("anma", "he lies on his back on the futon, the masseuse kneels beside him pressing one fingertip on his perineum and another on his lower belly, no hand on his penis, cum on his belly, a wooden massage ball on the futon"),
   "onani_e2": ("guest", "lying alone on the futon, his fingertips pressing into his own lower belly and inner thigh like acupressure, penis untouched, back arched, the masseuse sits in the far corner watching"),
   "inochi_e2": ("anma", "he lies on his back on the futon, the masseuse sits at the foot of the futon, the sole of her bare foot pressing his penis against his belly, footjob, her hands kneading his calf, cum on his belly"),
   "onedari_e2": ("engawa", "he lies on his back on a cushion on the moonlit veranda, the masseuse kneels beside him pressing her thumb into his inner thigh point, a cord with three knots in her other hand, no hand on his penis"),
   # e3 コウ
   "btl_e3": ("yubatake", "he sits on the edge of a wooden trough in the steam with legs spread, the bath attendant crouches in front feeding milky jelly into his urethra through a thin bamboo tube, urethral insertion, jelly dripping, a ceramic pot beside him"),
   "onani_e3": ("koya", "sitting alone on the wooden floor of the source hut with his knees up, two fingers pressing his own perineum upward, penis untouched, the bath attendant leans in the doorway watching, a bamboo tube in hand"),
   "inochi_e3": ("bandai", "he sits on the high bandai seat with legs apart, the bath attendant stands beside him slipping a thin bamboo tube into his urethra, urethral insertion, milky jelly leaking, looking toward the corridor"),
   "onedari_e3": ("roten", "he sits on the flat rock at the edge of the bath, the bath attendant stands in the water licking his nipple while holding a thin bamboo tube in his urethra, urethral insertion, milky jelly overflowing"),
   # boss セツ
   "btl_boss": ("hanare", "from side, he lies back on the wooden rim of the golden bath with legs lifted, the grand okami stands in the water between his legs pegging his anus with her strap-on, anal, kissing him, pinching his nipple, his own penis separate", {"pen": "strapon"}),
   "onani_boss": ("hanare_rouka", "kneeling alone on the polished corridor floor, sucking two of his own fingers deeply, the other hand pinching his own nipple, penis untouched, the grand okami watches from the far end of the corridor"),
   "inochi_boss": ("choba", "the grand okami sits behind the front desk holding him on her lap facing her, embracing him and kissing him deeply, her fingers pinching his nipples, open guest ledger without text on the desk"),
   "onedari_boss": ("koya", "from side, he is on all fours on a straw mat in the source hut, the grand okami kneels behind him pegging his anus with her strap-on, anal, one hand on his nipple, a white happi coat hanging on the wall, his own penis separate", {"pen": "strapon"}),
 },
 "lose_desc": "keeps him at the inn forever as the live-in yumori husband.",
 "onanie": {
   "master": ("roten", "kneeling alone in the shallow water of the rocky bath, sucking two of his own fingers deeply as if kissing, tongue on his fingers, the other wet hand rubbing his own nipple, penis untouched"),
   "e1": ("arai", "sitting on the wooden bath stool leaning forward, one arm reaching behind with soapy fingers in his own anus, foam on his skin, penis untouched"),
   "e2": ("anma", "lying alone on his back on the futon in the dim room, one fingertip pressing into his own lower belly and the other into his inner thigh like acupressure, hips lifting, penis untouched"),
   "e3": ("koya", "sitting alone with his knees up on the wooden floor of the source hut, two fingers pressing his own perineum upward, the other hand gripping his knee, penis untouched"),
   "boss": ("hanare", "kneeling alone beside the golden bath, sucking two of his own fingers deeply as if kissed, the other hand pinching his own nipple hard, hugging himself, penis untouched"),
 },
}
