# N57 深夜の取調室（Police）場面データ。登場人物は全員20歳以上（女性＋ニューハーフ：クレア・ジュン・アヤセ）。架空の署・紋章なし。
DATA = {
 "code": "Police",
 "world": "fictional police station at midnight, no emblems, fluorescent light, papers without text, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, mature face, sharp adult features, 37 years old, adult proportions, beautiful detailed eyes, long legs, black hair, long straight hair, red eyes, black suit, white shirt, handcuffs on belt, large breasts",
         "name": "the black-haired inspector in a black suit"},
   "e1": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, bob cut, brown eyes, black uniform without emblem, uniform cap without emblem, pumps, large breasts, white latex gloves",
          "name": "the brown-bob patrol officer in a black uniform and cap"},
   "e2": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, blonde hair, short bob, green eyes, white forensic coveralls, gloves, cotton swab case, medium breasts",
          "name": "the blonde forensic technician in white coveralls"},
   "e3": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 29 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, red hair, long hair in one ponytail, amber eyes, leather jacket, tight skirt, boots, medium breasts",
          "name": "the red-ponytailed detective in a leather jacket"},
   "boss": {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 41 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, purple hair, long wavy hair, gold eyes, black formal skirt suit, white gloves, large breasts",
            "name": "the purple-haired police chief in a black skirt suit and white gloves"},
 },
 "places": {
   "interrog": "interrogation room, plain grey steel desk and two chairs, single desk lamp, large one-way mirror, stack of papers without text, red ballpoint pen",
   "cell":     "holding cell, narrow bed with a grey blanket, one wall is a large mirror, iron bars, dim light",
   "exam":     "white examination room, white examination table, smell of disinfectant, clipboard without text, box of latex gloves",
   "lab":      "basement forensics lab, silver shelves of bottles and boxes, steel work table, magnifying lamp, glass vials",
   "chief":    "police chief's office on the top floor, thick carpet, dark leather sofa, large wooden desk, window with distant city lights at night",
   "window":   "police chief's office, large window glass with distant city lights at night, thick carpet",
   "hall":     "night corridor of the police station, grey doors, fluorescent light",
   "keep":     "custody room with a bed and a washstand, case of cotton swabs on the shelf",
 },
 "atk": {
   "m1": ("interrog", "he sits on the chair with his hands cuffed behind the chair back, the inspector stands behind him flicking both of his nipples with her fingernails, jingling the handcuff chain, erect nipples"),
   "m2": ("interrog", "he sits on the chair, the inspector leans over the desk holding his chin and kisses him deeply, tongues, saliva trail, a red ballpoint pen in her other hand"),
   "m3": ("interrog", "from side, he lies face down on the grey desk with hips raised, the inspector stands behind him pegging his anus with a black strap-on, anal, reading a report without text in her other hand, his own penis separate", {"pen": "strapon"}),
   "e1": ("exam", "from side, he lies on his back on the examination table with his knees up, the patrol officer stands at the table with two gloved fingers in his anus pressing his prostate, her pumps foot resting on his penis"),
   "e2": ("lab", "he lies on his back on the steel work table with legs spread, the forensic technician bends over him under the magnifying lamp slowly inserting a thin cotton swab into his urethra, gloved fingers, precum"),
   "e3": ("interrog", "he sits on the floor in the shadow of the desk, the detective sits behind him hugging him with her lips at his ear whispering, licking his ear, his mouth open repeating words, drool, hips twitching"),
   "boss": ("chief", "from side, he lies on his back on the leather sofa with his legs held up, the police chief kneels between his legs penetrating his anus with her own penis, anal, pink rotors taped on both of his nipples, his own penis separate", {"pen": "penis"}),
 },
 "atk_desc": {
   "m1": "the inspector trains his nipples to the sound of handcuffs.",
   "m2": "the inspector kisses a confession out of him.",
   "m3": "the inspector pegs him while reading his report aloud.",
   "e1": "the patrol officer performs a body search inside him.",
   "e2": "the forensic technician takes a sample with a cotton swab.",
   "e3": "the detective whispers his confession into his ear.",
   "boss": "the police chief finishes him with nipple rotors and her own body.",
 },
 "lose": {
   # m1 手錠の指先（乳首）
   "btl_m1": ("interrog", "he sits on the chair with his hands cuffed loosely behind it, chest thrust forward, the inspector stands behind him flicking both of his nipples with her fingernails, handcuff chain jingling, cum on his thighs"),
   "onani_m1": ("cell", "sitting alone on the narrow bed facing the mirror wall, sucking two of his own fingers, the other wet fingertip rubbing his own nipple, penis untouched, the inspector stands outside the iron bars watching"),
   "inochi_m1": ("interrog", "he sits cuffed on the chair thrusting his chest forward, the inspector behind him presses both nipples with a key and her fingertip, a signed paper without text on the desk, cum on his thighs"),
   "onedari_m1": ("interrog", "he sits on the chair with his hands cuffed behind it, mouth open begging, the inspector stands behind him pinching one nipple and flicking the other, a red pen and papers without text on the desk"),
   # m2 自白の口づけ
   "btl_m2": ("interrog", "he sits on the chair clutching the lapels of the inspector's suit, the inspector holds his face in both hands and kisses him deeply, tongues, saliva trail, cup of coffee on the desk"),
   "onani_m2": ("cell", "sitting alone on the narrow bed in front of the mirror wall, sucking two of his own fingers deeply as if kissing, the other hand rubbing his own nipple, penis untouched, the inspector stands far outside the bars watching"),
   "inochi_m2": ("interrog", "he sits on the inspector's lap on the chair, the inspector kisses him deeply, tongues, saliva, his mouth still half open, a signed paper without text on the desk"),
   "onedari_m2": ("interrog", "he stands with his hands against the one-way mirror, the inspector presses him from behind and kisses him deeply over his shoulder, tongues, saliva trail, his fingers sliding on the glass"),
   # m3 調書を読み上げながら（ペニバン）
   "btl_m3": ("interrog", "from side, he lies face down on the grey desk with hips raised, the inspector stands behind him pegging his anus with a black strap-on, anal, reading a report without text, his own penis separate, cum dripping on the floor", {"pen": "strapon"}),
   "onani_m3": ("cell", "lying alone on his back on the narrow bed with knees apart, one hand reaching down with two of his own fingers in his own anus, sucking fingers of the other hand, penis untouched, the inspector watches from outside the bars"),
   "inochi_m3": ("interrog", "from side, he lies on his side on the grey desk, the inspector holds one of his legs up and pegs his anus with a black strap-on, anal, reading a paper without text, his own penis separate, his cheek on the desk", {"pen": "strapon"}),
   "onedari_m3": ("interrog", "from side, he is on all fours on top of the grey desk, the inspector stands behind him pegging his anus with a black strap-on, anal, her long black hair falling over his back, his own penis separate, cum on the desk", {"pen": "strapon"}),
   # e1 身体検査の指
   "btl_e1": ("exam", "from side, he lies on his back on the examination table with knees up, the patrol officer with two gloved fingers in his anus, the sole of her pumps resting on his penis, counting on a clipboard without text, cum"),
   "onani_e1": ("cell", "kneeling alone on the narrow bed with his hands on the mirror wall and hips pushed back, one arm reaching behind with two of his own wet fingers in his own anus, penis untouched, the patrol officer watches from outside the bars"),
   "inochi_e1": ("exam", "from side, he lies on his side on the examination table hugging his knees to his chest, the patrol officer stands behind him with two gloved fingers in his anus, clipboard without text, cum on the table"),
   "onedari_e1": ("exam", "he sits on the patrol officer's lap on a round stool, legs spread, the patrol officer has two gloved fingers in his anus from below, his head thrown back, cum"),
   # e2 綿棒（尿道）
   "btl_e2": ("lab", "he lies on his back on the steel work table with legs spread, the forensic technician bends over him tapping the end of a thin cotton swab inserted in his urethra, gloved fingers, toes curled"),
   "onani_e2": ("cell", "sitting alone on the narrow bed with legs spread, one fingertip tracing his own perineum upward, the other hand gripping the blanket, penis untouched, the forensic technician watches from outside the bars"),
   "inochi_e2": ("lab", "he lies on the steel work table, his own trembling fingers pulling a thin cotton swab out of his urethra, the forensic technician stands beside him guiding his hand, glass vials, cum on his chest"),
   "onedari_e2": ("lab", "he lies on his back on the steel work table under the magnifying lamp, the forensic technician slowly pulls a thin cotton swab out of his urethra, cum spurting toward the lens, glass vials"),
   # e3 取り調べの囁き
   "btl_e3": ("interrog", "he sits on the floor in the shadow of the desk leaning back against the detective, the detective hugs him from behind whispering into his ear and biting his earlobe, his mouth open repeating words, cum on his thighs"),
   "onani_e3": ("cell", "sitting alone on the narrow bed hugging his knees, mouthing words to himself, trembling, drool, hands far from his crotch, penis untouched, the detective watches from outside the bars"),
   "inochi_e3": ("interrog", "he sits between the detective's legs on the floor holding a paper without text, the detective whispers into his ear from behind, her lips on his ear, his mouth open, drool, cum"),
   "onedari_e3": ("interrog", "he sits facing the detective on the chair, his face on her shoulder, the detective licks the rim of his ear and whispers, his mouth open, drool, trembling, cum on his thighs"),
   # boss 総仕上げ（NH逆アナル＋乳首ローター）・保釈の条件（貞操帯）
   "btl_boss": ("chief", "from side, he lies on his back on the leather sofa with legs lifted, the police chief kneels between his legs penetrating his anus with her own penis, anal, pink rotors taped on his nipples, his own penis separate, cum on his belly", {"pen": "penis"}),
   "onani_boss": ("cell", "on all fours alone on the narrow bed, one arm reaching behind with two of his own wet fingers in his own anus, the other hand pressing a fingertip to his own nipple, penis untouched, the police chief watches from outside the bars"),
   "inochi_boss": ("chief", "from side, he sits on the police chief's lap facing her on the leather sofa, the police chief penetrates his anus from below with her own penis, anal, pink rotors on his nipples, clear fluid dripping from the cage", {"pen": "penis", "cage": True}),
   "onedari_boss": ("window", "from side, he stands bent forward with both hands on the window glass, the police chief stands behind him penetrating his anus with her own penis, anal, pink rotors on his nipples, his own penis separate, glass fogged by his breath", {"pen": "penis"}),
 },
 "lose_desc": "keeps him in custody at the station forever.",
 "onanie": {
   "master": ("interrog", "sitting on the chair with his hands behind his back as if cuffed, then one wet fingertip rubbing his right nipple, the other hand pinching his left nipple hard, penis untouched"),
   "e1": ("exam", "kneeling on the examination table with hips raised, one arm reaching behind with two of his own wet fingers in his own anus, penis untouched"),
   "e2": ("lab", "sitting on the steel table with legs spread, one fingertip tracing his own perineum upward, the other hand gripping the table edge, penis untouched"),
   "e3": ("interrog", "sitting on the floor in the shadow of the desk hugging his knees, mouthing words to himself, drool, hands far from his crotch, penis untouched"),
   "boss": ("chief", "on all fours on the thick carpet, one arm reaching behind with two of his own fingers in his own anus, the other fingertip trembling on his own nipple, penis untouched"),
 },
}
