# N54 白薔薇歌劇団（Revue）場面データ。登場人物は全員20歳以上。女性（ミユ・ココ・オデット）とニューハーフ（ルシア・レオナ）の混合。主人公は全場面で白い娘役ドレス。
DRESS = "a white frilly dress with a fitted waist, white rose embroidery on the hem, white stockings and a white headdress"
DRESS_OPEN = "a white frilly dress with an open neckline, white stockings and a white headdress"
DATA = {
 "code": "Revue",
 "world": "old grand theater of an all-female revue troupe, red velvet seats, gilded balconies, stage lights, white roses, detailed background",
 "chars": {
   "m":    {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 33 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, blonde hair, long wavy hair, red eyes, gold and red stage dress, feather ornaments, medium breasts",
            "name": "the blonde top star in a gold and red stage dress"},
   "e1":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 23 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, long hair, brown eyes, black practice clothes, practice skirt, modest breasts",
            "name": "the pink-haired actress in black practice clothes",
            "height_note": "she is about the same height as him"},
   "e2":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 28 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, red hair, ponytail, gold eyes, black leotard, wrap skirt, long slender legs, medium breasts",
            "name": "the red-ponytailed choreographer in a black leotard"},
   "e3":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, hair bun, green eyes, black smock, makeup tool belt, medium breasts",
            "name": "the brown-bun makeup artist in a black smock",
            "height_note": "she is about the same height as him"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 45 years old, adult proportions, beautiful detailed eyes, long legs, white hair, long hair tied up, purple eyes, black dress, white rose corsage, large breasts",
            "name": "the white-haired troupe director in a black dress with a white rose corsage"},
 },
 "places": {
   "stage":    "center of the grand stage under a white spotlight, red curtain raised, dark auditorium with rows of red seats",
   "wings":    "dark stage wings, ropes and sandbags, heavy black curtains, light spilling from the stage",
   "costume":  "costume room, walls of hanging feathered and silk dresses, tall standing mirror, old fabric",
   "naraku":   "dark trap room under the stage, old stage props, rolled curtains, wooden pillar, dim lamp light, old standing mirror",
   "rehearsal": "second-floor rehearsal room, wall-length mirrors, wooden floor, costume basket",
   "studio":   "basement dance studio, wooden floor, long ballet barre on the wall, mirrors",
   "bigdress": "large shared dressing room, rows of vanity tables with three-way mirrors, powder tins and puffs",
   "gakuya":   "private dressing room, vanity mirror framed with bright bulbs, velvet chaise longue, costume rack",
   "box":      "theater box seat, red velvet armchair and balustrade, view of the lit stage below",
 },
 "atk": {
   "m1": ("stage", "he stands under the white spotlight in the white dress, the top star stands behind him whispering into his ear, her lips at his ear, his knees trembling, his skirt front wet, no hands on him", {"hero_outfit": DRESS}),
   "m2": ("costume", "he stands before the tall mirror, the top star stands behind him tightening the laces of the white dress on his back, her fingertip tracing his spine, he clutches the skirt, flushed, trembling", {"hero_outfit": DRESS}),
   "m3": ("naraku", "from side, he lies on his back on a costume trunk with the white skirt lifted, the top star leans over him kissing him deeply while penetrating his anus, anal, tongues, his own penis separate", {"pen": "penis", "hero_outfit": DRESS}),
   "e1": ("rehearsal", "he stands before the mirror wall, the actress buttons up the back of his white dress one button at a time, her fingertips on his spine, her other hand smoothing the skirt over his crotch, flushed", {"hero_outfit": DRESS}),
   "e2": ("studio", "from side, he sits in a wide split on the wooden floor bent forward, the choreographer presses her chest on his back and slides two oiled fingers into his anus under the lifted skirt, trembling", {"hero_outfit": DRESS}),
   "e3": ("bigdress", "he sits before the three-way mirror with his chest bared by the open neckline, the makeup artist pats both of his nipples with soft powder puffs, white powder in the air, his nipples erect", {"hero_outfit": DRESS_OPEN}),
   "boss": ("stage", "from behind, he bows deeply on stage holding up the white skirt, the troupe director stands behind him pulling a string of white anal beads from his anus one by one, his mouth open, dazed", {"pen": "toy", "hero_outfit": DRESS}),
 },
 "atk_desc": {
   "m1": "the top star whispers under the spotlight until his mind melts.",
   "m2": "the top star dresses him as her leading lady, and the silk caresses him.",
   "m3": "the top star kisses him and penetrates him in the trap room under the stage.",
   "e1": "the actress dresses him button by button with her pleasure-giving hands.",
   "e2": "the choreographer stretches his body and his prostate open.",
   "e3": "the makeup artist powders his nipples with a soft puff.",
   "boss": "the director pulls anal beads out of him with every round of applause.",
 },
 "lose": {
   # ルシア 技1 スポットライトの囁き
   "btl_m1": ("stage", "he stands frozen under the white spotlight in the white dress, the top star behind him whispering into his ear, her breath in his ear, his knees buckling, cum dripping from under the skirt, no hands on him", {"hero_outfit": DRESS}),
   "onani_m1": ("gakuya", "standing alone before the bulb-lit mirror in the white dress, stroking his own thighs and buttocks over the skirt with both palms, chin raised into the light, penis untouched, the top star watches from the far doorway", {"hero_outfit": DRESS}),
   "inochi_m1": ("stage", "he stands under the spotlight in the white dress holding an open script without text, the top star behind him licking inside his ear, her palm pressing his lower belly over the skirt, his knees trembling", {"hero_outfit": DRESS}),
   "onedari_m1": ("wings", "he stands in the dark stage wings in the white dress, the top star bends from behind licking his ear, her palm resting on his lower belly, his other ear wet and flushed, precum wetting the skirt", {"hero_outfit": DRESS}),
   # 技2 娘役の衣装
   "btl_m2": ("costume", "he kneels in a deep curtsy before the tall mirror in the white dress and long white silk gloves, the top star stands behind him tightening the corset laces, his body trembling, a wet stain on the skirt front", {"hero_outfit": DRESS + ", long white silk gloves"}),
   "onani_m2": ("gakuya", "standing alone before the mirror in the white dress with knees together, stroking his own inner thighs and buttocks over the silk skirt, flushed, penis untouched, the top star watches from the far doorway", {"hero_outfit": DRESS}),
   "inochi_m2": ("costume", "he stands before the tall mirror in the white dress clutching the skirt, the top star behind him holding his shoulders, the petticoat moving by itself around his crotch, a wet stain spreading on the skirt, flushed", {"hero_outfit": DRESS}),
   "onedari_m2": ("stage", "he stands center stage in the white dress hugging himself, the top star behind him pulls the laces tight, the dress hugging his whole body, the skirt front wet, an open script without text on the floor", {"hero_outfit": DRESS}),
   # 技3 奈落で
   "btl_m3": ("naraku", "from side, he lies on his back on a costume trunk with the white skirt lifted and legs raised, the top star leans over him kissing him deeply and penetrating his anus, anal, his own penis separate, cum dripping on the floor", {"pen": "penis", "hero_outfit": DRESS}),
   "onani_m3": ("gakuya", "kneeling alone on the chaise longue in the white dress, the skirt lifted at the back, one arm reaching behind with two fingers in his own anus, sucking two fingers of the other hand, penis untouched, the top star watches from the far doorway", {"hero_outfit": DRESS}),
   "inochi_m3": ("naraku", "from side, he lies on his side on rolled curtains in the white dress, the top star lies behind him hugging him, penetrating his anus from behind, anal, turning his face for a deep kiss, his own penis separate", {"pen": "penis", "hero_outfit": DRESS}),
   "onedari_m3": ("naraku", "from side, he stands clinging to the wooden pillar in the white dress with the skirt lifted, the top star behind him penetrating his anus while kissing his nape, her hand in his neckline rolling his nipple, anal, his own penis separate", {"pen": "penis", "hero_outfit": DRESS}),
   # e1 ミユ 着付けの手
   "btl_e1": ("rehearsal", "he stands before the mirror wall in the white dress, the actress hugs him from behind, retying the ribbon at his waist, her fingers sliding along his inner thigh under the ruffles, the skirt wet, flushed", {"hero_outfit": DRESS}),
   "onani_e1": ("gakuya", "standing alone before the mirror in the white dress, stroking his own nipples through the chest ruffles with his fingertips, flushed, penis untouched, the actress watches from the far doorway", {"hero_outfit": DRESS}),
   "inochi_e1": ("rehearsal", "he stands before the mirror wall in the white dress, the actress lifts his chin with one finger and kisses him, her other hand fastening the back buttons, a white corset laced tight on his waist", {"hero_outfit": DRESS + ", white corset"}),
   "onedari_e1": ("stage", "he stands on stage in the white dress, the actress hugs him from behind with her chin on his shoulder, her hand stroking his lower belly over the petticoat, turning his face to kiss him, tongues", {"hero_outfit": DRESS}),
   # e2 レオナ ストレッチ
   "btl_e2": ("studio", "from side, he sits in a wide split on the wooden floor bent forward, the choreographer presses her chest on his back and pushes two oiled fingers into his anus under the lifted skirt, white skirt spread on the floor", {"hero_outfit": DRESS}),
   "onani_e2": ("gakuya", "sitting alone on the floor in the white dress in a wide split, the skirt lifted, one arm reaching down behind with two fingers in his own anus, penis untouched, the choreographer watches from the far doorway with arms folded", {"hero_outfit": DRESS}),
   "inochi_e2": ("studio", "from side, he stands with one leg raised on the ballet barre in the white dress, the choreographer stands behind him holding his waist with two oiled fingers in his anus under the lifted skirt, the mirror behind", {"hero_outfit": DRESS}),
   "onedari_e2": ("stage", "he sits on the stage floor in the white dress with the soles of his feet together and knees spread, the choreographer crouches before him pressing his knees down, her toe shoe tip tracing his inner thigh, one finger in his anus", {"hero_outfit": DRESS}),
   # e3 ココ パフの
   "btl_e3": ("bigdress", "he sits before the three-way mirror with the dress neckline open, the makeup artist pats both of his nipples with soft powder puffs, white powder drifting, a wet stain on the white petticoat", {"hero_outfit": DRESS_OPEN}),
   "onani_e3": ("bigdress", "sitting alone before the vanity with the dress neckline open, patting his own nipple with a soft powder puff, white powder on his chest, penis untouched, the makeup artist watches from the far doorway", {"hero_outfit": DRESS_OPEN}),
   "inochi_e3": ("bigdress", "he sits before the three-way mirror with the neckline open, his chest white with powder, the makeup artist taps the tip of his nipple with a thumb-sized puff, his back arched, knees trembling", {"hero_outfit": DRESS_OPEN}),
   "onedari_e3": ("stage", "he sits on a chair before a standing mirror on stage with the neckline open, chest thrust out, the makeup artist rests a soft puff on his nipple and waits, powder in the air, trembling", {"hero_outfit": DRESS_OPEN}),
   # boss オデット カーテンコール
   "btl_boss": ("stage", "from side, he bows deeply on stage holding up the white skirt, the troupe director stands behind him pulling a string of white anal beads from his anus, cum dripping from under the skirt, dazed", {"pen": "toy", "hero_outfit": DRESS + ", a white rose"}),
   "onani_boss": ("gakuya", "lying face down alone on the chaise longue in the white dress, the skirt lifted, one arm reaching behind with two fingers in his own anus, penis untouched, the troupe director watches from the far doorway", {"hero_outfit": DRESS}),
   "inochi_boss": ("box", "he lies face down across the troupe director's lap in the velvet box seat, the white skirt spread like a flower, the troupe director pushes a white bead of an anal bead string into his anus, stage lights below", {"pen": "toy", "hero_outfit": DRESS}),
   "onedari_boss": ("stage", "from side, he kneels at the edge of the stage in the white dress bowing deeply, the troupe director stands behind him slowly pulling a string of white anal beads from his anus, oil running down his stockings", {"pen": "toy", "hero_outfit": DRESS + ", a white rose"}),
 },
 "lose_desc": "keeps him on the stage forever as the troupe's leading lady in a white dress.",
 "onanie": {
   "master": ("gakuya", "standing before the mirror in the white dress, knees together, stroking his own thighs and buttocks over the silk skirt, clutching the ruffles, penis untouched", {"hero_outfit": DRESS}),
   "e1": ("rehearsal", "standing before the mirror wall in the white dress, fingertips stroking his own nipples through the chest ruffles, penis untouched, lips parted, ragged breathing, knees shaking", {"hero_outfit": DRESS}),
   "e2": ("studio", "sitting in a wide split on the wooden floor in the white dress, one arm reaching behind with two fingers in his own anus, penis untouched", {"hero_outfit": DRESS}),
   "e3": ("bigdress", "sitting before the vanity with the dress neckline open, patting his own nipple with a soft powder puff, penis untouched, lips parted, ragged breathing, knees shaking", {"hero_outfit": DRESS_OPEN}),
   "boss": ("stage", "bowing on stage in the white dress, one arm reaching behind under the skirt with two fingers in his own anus, penis untouched, lips parted, ragged breathing, knees shaking", {"hero_outfit": DRESS}),
 },
}
