# N46 夜蝶のショーパブ（ShowPub）場面データ。登場人物は全員20歳以上。女性とニューハーフの混合（ママ・アンナ・カオル＝NH）。
DATA = {
 "code": "ShowPub",
 "world": "underground show pub nightclub at night, red lighting, mirror ball sparkles, velvet and gold decor, detailed background",
 "chars": {
   "m":    {"type": "nh", "tags": "adult woman, mature female, mature face, sharp adult features, 38 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, black hair, long wavy hair, red eyes, red lipstick, crimson slit evening dress, fur stole, large breasts",
            "name": "the black-haired mama in a crimson evening dress"},
   "e1":   {"type": "woman", "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, high ponytail, green eyes, silver sequin showgirl costume, high heels, long slender legs, large breasts",
            "name": "the blonde dancer in a silver sequin costume"},
   "e2":   {"type": "nh", "tags": "adult woman, mature female, mature face, sharp adult features, 22 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, pink hair, bob cut, amber eyes, white mini dress, soft body, medium breasts",
            "name": "the pink-bob hostess in a white mini dress"},
   "e3":   {"type": "nh", "tags": "adult woman, mature female, mature face, sharp adult features, 27 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, purple hair, short bob, gold eyes, black vest, white shirt, thin necktie, slim-fitting, medium breasts",
            "name": "the purple-haired bartender in a black vest"},
   "boss": {"type": "woman", "tags": "adult woman, mature female, mature face, sharp adult features, 44 years old, adult proportions, beautiful detailed eyes, long legs, white hair, elegant updo, gold eyes, white china dress with gold embroidery, very large breasts, voluptuous",
            "name": "the white-haired owner in a white china dress"},
 },
 "places": {
   "stage":    "show pub stage under a white spotlight, red velvet curtain, dark audience seats with champagne glasses in the background",
   "pole":     "show stage with a tall silver dance pole, mirror ball light spots on the floor, spotlight",
   "dressing": "backstage dressing room, large vanity mirror framed with light bulbs, makeup table, sequin costumes on a rack, soft carpet",
   "box":      "private box seat behind a red velvet curtain, red velvet sofa, low glass table with bottles and a card game",
   "sofa":     "club sofa seat, red velvet sofa, carpet floor, glass table with champagne glasses",
   "counter":  "long bar counter with high stools, silver cocktail shaker, cocktail glasses, ice bucket, backbar lights",
   "behind":   "inside behind the bar counter, shelves of keep bottles with blank tags without text, backbar mirror, dim warm light, cushion on the floor",
   "stairs":   "narrow staircase leading down to the club entrance, red lights, perfume haze",
   "wings":    "dark stage wings behind the curtain, stage lights spilling in, low raised platform",
   "breakroom":"staff break room, silver basin of steaming white hand towels, narrow sofa, soap bottles",
   "owner":    "owner's office, white marble desk, champagne tower of coupe glasses, gold accents",
   "closed":   "closed empty club after hours, dim lights, empty audience seats, stage with a white cloth-covered table",
 },
 "atk": {
   "m1": ("stage", "he stands on the stage under the spotlight with his knees buckling, the mama holds him from behind, her red lips at his ear whispering, tongue licking his ear, one fingertip tracing his erection, trembling"),
   "m2": ("stage", "he sits on a round stool on the stage with his chin lifted, the mama bends over him kissing him deeply, tongues, saliva trail, her thigh from the dress slit pressed between his legs"),
   "m3": ("behind", "from side, he stands bent forward gripping the edge of the bar counter, the mama behind him penetrating his anus with her own penis, anal, her fingers pinching his nipple from behind, his own penis separate, precum", {"pen": "penis"}),
   "e1": ("pole", "he lies on his back on the stage floor at the foot of the silver pole, the dancer leans against the pole with one leg raised high, her high-heeled sole pressing his erection, footjob, fishnet stockings"),
   "e2": ("sofa", "he kneels on the red sofa with his hips raised, the hostess kneels behind him with two fingers in his anus, fingering, her other hand holding a steaming white hand towel, blush, trembling"),
   "e3": ("counter", "he sits on a bar stool, pink nipple rotors taped to both of his nipples, the bartender stands behind the counter shaking a silver cocktail shaker, the rotor remote on the counter, back arched, precum"),
   "boss": ("closed", "from side, he lies on his back on the white cloth-covered table, the owner leans over him sucking his nipple, her hand holding a slim vibrator in his anus, champagne dripping on his chest", {"pen": "toy"}),
 },
 "atk_desc": {
   "m1": "the mama whispers his new stage name into his ear.",
   "m2": "the mama gives him the stage kiss under the spotlight.",
   "m3": "the mama takes him behind the bar counter.",
   "e1": "the dancer steps on him with her pole-dance leg.",
   "e2": "the hostess serves him with warm towel fingers.",
   "e3": "the bartender shakes the shaker and the rotors buzz on his nipples.",
   "boss": "the owner pours the champagne tower from his chest to his hips.",
 },
 "lose": {
   # ママ 技1（耳元の源氏名）
   "btl_m1":     ("stage", "he sits collapsed on the stage floor in the spotlight, the mama kneels behind him hugging him, her lips at his ear whispering his stage name, one fingertip tracing his penis, cum on the floor, dazed"),
   "onani_m1":   ("dressing", "kneeling alone before the light-bulb mirror, his head tilted as if listening, both hands pinching his own nipples, knees trembling, penis untouched, the mama stands in the doorway watching, fur stole"),
   "inochi_m1":  ("box", "he kneels on the carpet beside the red sofa, a blank bottle tag without text hanging from his neck, the mama crouches behind him whispering into his ear, her fingertip tracing his penis, cum dripping"),
   "onedari_m1": ("sofa", "he sits on the carpet in front of the sofa with his knees giving way, the mama hugs him from behind, tongue in his ear, fingers flicking his nipple, cum on his belly, flushed"),
   # ママ 技2（ステージの口づけ）
   "btl_m2":     ("stage", "he sits slumped on a round stool on the stage, the mama bends down kissing him deeply, tongues, saliva trail, her bare thigh from the dress slit pressed against his crotch, cum on his thigh, spotlight"),
   "onani_m2":   ("dressing", "sitting alone before the light-bulb mirror, sucking two of his own fingers deeply as if kissing, the other wet hand rubbing his own nipple, penis untouched, the mama watches from the doorway"),
   "inochi_m2":  ("stairs", "he sits on the red-lit stairs with his chin lifted, the mama leans down kissing him deeply as a farewell kiss, tongues, saliva trail, her thigh between his legs, cum dripping"),
   "onedari_m2": ("stage", "he kneels on the stage with his mouth open begging, the mama tilts his chin up and lets a drop of saliva fall onto his tongue, then kisses him, tongues, spotlight"),
   # ママ 技3（カウンターの裏で・NH）
   "btl_m3":     ("behind", "from side, he stands bent forward gripping the bar counter, the mama behind him penetrating his anus with her own penis, anal, her hand pinching his nipple, his own penis separate, cum dripping onto the floor", {"pen": "penis"}),
   "onani_m3":   ("dressing", "on all fours on the carpet before the light-bulb mirror with his hips raised, one arm reaching behind with two of his own fingers in his own anus, the other hand pinching his nipple, penis untouched, the mama watches from the doorway"),
   "inochi_m3":  ("behind", "from side, he lies on his back on the cushion behind the bar counter holding his knees up, the mama kneels between his legs penetrating his anus with her own penis, anal, both hands pinching his nipples, his own penis separate, cum on his belly", {"pen": "penis"}),
   "onedari_m3": ("behind", "from side, he lies on a mat behind the bar counter with his legs spread begging, the mama leans over him penetrating his anus with her own penis, anal, pinching his nipple, his own penis separate, cum leaking, keep bottles on the shelf", {"pen": "penis"}),
   # ダンサー ミラ（ポールの脚）
   "btl_e1":     ("pole", "he lies on his back at the foot of the silver pole, the dancer barefoot with one heel shoe kicked off, her soles pressing his penis between both feet, footjob, fishnet stockings, a white feather fan brushing his nipple, cum on his belly"),
   "onani_e1":   ("dressing", "lying face down alone on the soft carpet with his shirt open, rubbing his chest against the floor, hips twitching, hands far away, penis untouched, the dancer watches from the doorway with arms crossed"),
   "inochi_e1":  ("pole", "he sits on the stage floor leaning back against the silver pole with his knees open, a red thumbprint on his thumb, the dancer stands over him pressing his penis with both fishnet soles, footjob, cum dripping"),
   "onedari_e1": ("pole", "he lies on the stage floor lifting his hips begging, pushing his erection against the dancer's fishnet sole, the dancer stands still with one hand on the pole, footjob, precum"),
   # 新人キャスト アンナ（おしぼりの指）
   "btl_e2":     ("stage", "he kneels on all fours on the stage, the hostess kneels behind him with two fingers in his anus, fingering, her other hand wrapping his penis in a steaming white hand towel, cum in the towel, trembling"),
   "onani_e2":   ("dressing", "on all fours alone before the light-bulb mirror, a steaming white hand towel over his wrist, two of his own fingers in his own anus, penis untouched, the hostess watches from the doorway holding a towel tray"),
   "inochi_e2":  ("breakroom", "he lies on the narrow sofa with a white hand towel covering his face, legs open, the hostess kneels beside him with two fingers in his anus, fingering, her other hand wiping his penis with a warm towel, steam"),
   "onedari_e2": ("sofa", "he leans back on the red sofa with his legs open, the hostess kneels between his knees with two fingers in his anus, her other hand wrapping his penis in a warm white towel, cum in the towel, flushed"),
   # バーテンダー カオル（シェイカーの振動）
   "btl_e3":     ("counter", "he sits on a bar stool with his back arched, pink nipple rotors taped to both of his nipples, the bartender behind the counter shakes the silver shaker, toes curled, trembling, precum"),
   "onani_e3":   ("dressing", "sitting alone on a chair before the light-bulb mirror, fingertips trembling fast on both of his own nipples as if vibrating, penis untouched, the bartender watches from the doorway holding a silver shaker"),
   "inochi_e3":  ("counter", "he leans on the bar counter drinking a cocktail from a glass, a pink rotor pressed to his nipple, the bartender holds his hand over the rotor while raising the silver shaker, cum dripping down his thigh"),
   "onedari_e3": ("counter", "he sits on a bar stool, pink rotors taped to both of his nipples, a blank white recipe card without text hanging from a bottle on the counter, the bartender shakes the silver shaker hard, back arched, precum"),
   # オーナー ハクラン（シャンパンタワー）
   "btl_boss":   ("closed", "from side, he lies on his back on the white cloth-covered table on the empty stage, the owner leans over him sucking his nipple, her hand holding a slim vibrator in his anus, champagne on his chest, cum on his belly", {"pen": "toy"}),
   "onani_boss": ("dressing", "kneeling alone before the light-bulb mirror, one wet finger rubbing his own nipple, the other arm reaching behind with trembling fingers in his own anus, penis untouched, the owner watches from the doorway holding a champagne glass"),
   "inochi_boss":("owner", "from side, he lies on his back on the white marble desk, the owner bends over him sucking his nipple and pinching the other, her hand holding a slim vibrator in his anus, champagne and cum on the marble", {"pen": "toy"}),
   "onedari_boss":("stage", "he kneels upright between the knees of the owner seated on a white chair, the owner bends forward sucking his nipple, her hand holding a slim vibrator in his anus, cum on the hem of her dress", {"pen": "toy"}),
 },
 "lose_desc": "keeps him in the show pub every night, twelve keep bottles lined up on the shelf.",
 "onanie": {
   "master": ("dressing", "kneeling before the light-bulb mirror, sucking two of his own fingers deeply as if kissing, the other wet hand rubbing his own nipple, penis untouched"),
   "e1": ("pole", "lying face down on the stage floor by the silver pole with his shirt open, rubbing his chest on the floor, hips raised, penis untouched"),
   "e2": ("dressing", "on all fours on the carpet, a warm white hand towel over his wrist, two of his own fingers in his own anus, penis untouched"),
   "e3": ("counter", "sitting on a bar stool, fingertips trembling fast on both of his own nipples as if vibrating, back arched, penis untouched"),
   "boss": ("dressing", "kneeling on the carpet, one wet finger rubbing his own nipple, the other hand reaching behind with fingers in his own anus, penis untouched"),
 },
}
