# N42 雪女の氷城（Snow）場面データ。登場人物は全員20歳以上（雪女たちは年齢不詳の成人）。シラネ・フリージアはふたなり、ユキ・シズリは男の娘。光は白と薄紫（青くしない）。
NB = "blue theme, blue light, frostbite, freezing pain"
DATA = {
 "code": "Snow",
 "world": "ice castle on a snowy mountain peak, walls of clear ice, white and pale purple light, frost flowers, drifting snowflakes, white breath, detailed background",
 "chars": {
   "m": {"type": "woman",
         "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 32 years old, tall, long legs, both eyes clearly visible, yuki-onna, pure white hair, long hair, purple eyes, pale skin, white kimono, light purple obi, cold breath, snowflakes, gentle cold smile, large breasts",
         "name": "the white-haired yuki-onna in a white kimono with a light purple obi", "neg": NB},
   "e1": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 21 years old, both eyes clearly visible, black hair, bob cut, red eyes, white padded jacket, red hood, innocent smile",
          "name": "the black-bob yukinko in a white padded jacket and red hood", "neg": NB},
   "e2": {"type": "woman",
          "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 26 years old, both eyes clearly visible, ice spirit, light purple hair, long straight hair, icy hair tips, silver eyes, ice crystal hair ornament, slim light purple dress, sharp expression, medium breasts",
          "name": "the lilac-haired ice spirit in a slim light purple dress", "neg": NB},
   "e3": {"type": "otoko",
          "tags": "adult male, otoko no ko, trap, very feminine, beautiful feminine face, pretty face, long eyelashes, soft jawline, light makeup, glossy lips, narrow shoulders, slender, elegant adult beauty, adult proportions, long legs, androgynous, delicate features, slim waist, flat chest, no breasts, 23 years old, both eyes clearly visible, rabbit ears, white rabbit ears, pink hair, short hair, red eyes, white fluffy jacket, short pants, sweet smile",
          "name": "the pink-haired snow rabbit with long white rabbit ears in a fluffy white jacket", "neg": NB},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, beautiful detailed eyes, adult proportions, 39 years old, tall, long legs, both eyes clearly visible, ice queen, silver hair, metallic hair, long hair, gold eyes, ice crown, silver dress, white fur cape, tall, mature, stern, large breasts",
            "name": "the silver-haired ice empress with an ice crown and white fur cape", "neg": NB},
 },
 "places": {
   "gate":     "blizzard on a mountain path before a huge gate of ice, white-out, swirling snow",
   "hall":     "great ice hall, chandelier of icicles, high ceiling, polished ice floor",
   "bed":      "bed of clear ice covered with thick white fur",
   "kairo":    "long corridor of frost flowers, pillars carved from ice, empty pedestals",
   "roudai":   "open ice balcony under the stars, snow falling silently, icicles hanging from the eaves",
   "himuro":   "ice storeroom, stacked blocks of ice, pale purple lamp, ice bench covered with white fur",
   "cave":     "underground hot spring cave, steam mixing with cold mist, flat stone at the edge of the water",
   "kamakura": "inside a snow hut, candlelight, warm glow on white snow walls, fur rug",
   "danro":    "room with the castle's only fireplace, white birch logs burning, orange firelight, white cushions",
   "mirror":   "hall of polished ice walls reflecting like mirrors, white fur rug",
   "garden":   "ice garden, flowers made of ice, snow-covered trees, moonlight",
   "rabbit":   "snow rabbit's burrow, soft hollow lined with cotton-like snow",
   "sled":     "fur-lined sled on a snowfield in the castle yard at night, sled bells",
   "throne":   "throne room, silver throne draped with white fur, high ceiling, glittering ice",
 },
 "atk": {
   "m1": ("bed", "he lies on his back on the white fur, the yuki-onna leans over him blowing a thin stream of cold white breath onto his nipple, her fingertip stroking the other erect nipple, frost flower marks on his chest"),
   "m2": ("hall", "he stands held tightly in the yuki-onna's arms under the icicle chandelier, she lifts his chin and kisses him deeply, tongues, saliva trail, white breath between their lips, his knees giving way"),
   "m3": ("kairo", "from side, he stands with both hands on an ice pillar, bent forward, the yuki-onna stands behind him whispering into his ear while penetrating his anus with her penis, anal, white breath, his own penis separate", {"pen": "penis"}),
   "e1": ("kamakura", "he is on all fours on the fur rug in the snow hut, the yukinko kneels behind him pushing a string of clear round ice beads into his anus one by one, anal beads, meltwater dripping, candlelight"),
   "e2": ("himuro", "he sits on the fur-covered ice bench with his legs apart, the ice spirit stands pressing his inner thigh with a cold bare foot, holding his penis and inserting a thin round-tipped icicle into his urethra, sounding, meltwater"),
   "e3": ("rabbit", "he lies face down in the soft snow hollow with his hips raised, the snow rabbit kneels behind him in the fluffy white jacket licking his anus, anilingus, long white rabbit ears brushing his back, saliva"),
   "boss": ("throne", "he sits on the ice empress's lap on the silver throne, the ice empress holds him and licks his nipple with her cold tongue, his penis locked in a chastity cage glistening with frost, frost flower marks on his skin", {"cage": True}),
 },
 "atk_desc": {
   "m1": "the yuki-onna blows icy breath on his nipples.",
   "m2": "the yuki-onna gives him a freezing kiss that turns hot.",
   "m3": "the yuki-onna whispers a blizzard into his ear while taking him from behind.",
   "e1": "the yukinko counts ice beads into him one by one.",
   "e2": "the ice spirit slides a thin icicle inside him.",
   "e3": "the snow rabbit licks him with a tongue that melts from cold to warm.",
   "boss": "the ice empress locks him in an ice cage and licks his nipples.",
 },
 "lose": {
   # m1 氷の吐息
   "btl_m1": ("bed", "he lies on his back on the white fur, the yuki-onna leans over him blowing cold white breath on his nipple, then kisses him deeply, frost flowers blooming around both nipples, cum on his belly, trembling"),
   "onani_m1": ("danro", "kneeling alone before the fireplace, sucking two of his own cold wet fingers, blowing on his own chest and tracing his nipple with a cold fingertip, penis untouched, the yuki-onna stands far behind in the doorway watching"),
   "inochi_m1": ("gate", "in the blizzard he kneels in the snow before the huge ice gate, the yuki-onna stands holding him and kisses him deeply, her cold breath on his bare chest, snowflakes swirling, erect nipples"),
   "onedari_m1": ("roudai", "under the stars he sits on the balcony with his chest pushed out begging, the yuki-onna bends down blowing a long thin cold breath onto his nipple, an ice wind chime hanging from the eaves"),
   # m2 凍える口づけ
   "btl_m2": ("hall", "under the icicle chandelier he is held tightly in the yuki-onna's arms, knees giving way, she kisses him deeply, tongues, a string of saliva, white breath, her cold fingers on his nipple, cum on his thighs"),
   "onani_m2": ("mirror", "kneeling alone before a wall of ice mirrors, sucking two of his own fingers deeply as if kissing, the other cold fingertip tracing his nipple, penis untouched, the yuki-onna stands far behind him, reflected in the ice, watching"),
   "inochi_m2": ("himuro", "he sits on the fur-covered ice bench raising his face to offer his lips, the yuki-onna bends down and kisses him deeply, tongues, white breath, his hands resting on his own knees, pale purple light"),
   "onedari_m2": ("cave", "he sits on the flat stone at the edge of the hot spring, the yuki-onna stands beside him lifting his chin and kissing him deeply, cold saliva dripping into his open mouth, steam and cold mist"),
   # m3 吹雪の囁き
   "btl_m3": ("kairo", "from side, he stands with both hands on an ice pillar, bent forward, the yuki-onna stands behind him penetrating his anus with her penis, anal, she turns his face and kisses him deeply, white breath, his own penis separate, cum dripping", {"pen": "penis"}),
   "onani_m3": ("garden", "kneeling alone in the ice garden, sucking the fingers of one hand, the other hand reaching behind to his own anus, head tilted as if listening to the wind, penis untouched, the yuki-onna stands far away among the ice flowers watching"),
   "inochi_m3": ("bed", "from side, he lies on his side on the white fur, the yuki-onna lies behind him whispering into his ear while penetrating his anus with her penis, anal, a light purple sash tied around his wrist, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("sled", "from side, he lies on his side wrapped in furs on the sled, the yuki-onna lies behind him penetrating his anus with her penis, anal, she kisses him deeply, sled bells, snowfield at night, his own penis separate", {"pen": "penis"}),
   # e1 ユキ
   "btl_e1": ("kamakura", "he is on all fours on the fur rug in the snow hut, the yukinko kneels beside him pushing clear round ice beads into his anus one by one, anal beads, the other cold hand pinching his nipple, meltwater running down his thighs, candlelight"),
   "onani_e1": ("himuro", "kneeling alone on the ice floor with his hips raised, reaching behind with one cold finger pushed into his own anus, counting on the fingers of the other hand, penis untouched, the yukinko sits on an ice stool far away watching"),
   "inochi_e1": ("danro", "he sits on the yukinko's lap before the fireplace, the end of a string of clear ice beads hanging from his anus, meltwater dripping, the yukinko's cold fingers pinching his nipple from behind, orange firelight"),
   "onedari_e1": ("garden", "he is on all fours in the moonlit ice garden, the yukinko kneels behind him pushing a string of seven clear round ice beads into his anus, anal beads, an ice box beside them, meltwater"),
   # e2 ツララ
   "btl_e2": ("himuro", "he sits on the fur-covered ice block with his legs apart, the ice spirit stands with one cold bare foot on his inner thigh, holding his penis and pushing a thin round-tipped icicle deep into his urethra, sounding, meltwater, trembling"),
   "onani_e2": ("mirror", "sitting alone on the white fur with his legs apart, one cold fingertip tracing thinly up his own perineum, the other hand behind him on the floor, penis untouched, the ice spirit stands far away by the ice mirror watching"),
   "inochi_e2": ("kairo", "he sits against an ice pillar in the frost corridor, the ice spirit sits facing him holding his penis between her cold bare soles, footjob, a thin icicle held in her hand"),
   "onedari_e2": ("roudai", "under the stars he sits on the balcony bench with his legs apart, the ice spirit kneels holding his penis and inserting a thin clear icicle into his urethra, sounding, meltwater dripping"),
   # e3 シズリ
   "btl_e3": ("rabbit", "he lies face down in the soft snow hollow with his hips raised, the snow rabbit hugs his waist from behind in the fluffy white jacket and licks his anus, anilingus, long white rabbit ears brushing his back, saliva"),
   "onani_e3": ("bed", "lying alone face down on the white fur with his hips raised, reaching behind and stroking his own anus with a wet finger as if licking, penis untouched, the snow rabbit sits far away on a white blanket watching"),
   "inochi_e3": ("cave", "he sits at the edge of the hot spring hugged from behind by the snow rabbit in the fluffy white jacket, the snow rabbit's hands stroking his nipples, rabbit ears against his cheek, steam, drowsy"),
   "onedari_e3": ("sled", "he lies face down on the furs in the sled with his hips raised, the snow rabbit kneels behind him licking his anus, anilingus, a white fur lap blanket, sled bells, snowfield at night"),
   # boss フリージア
   "btl_boss": ("throne", "from side, he lies on the white fur before the silver throne with his legs raised, the ice empress kneels between his legs penetrating his anus with her penis, anal, licking his nipple, his penis locked in a chastity cage glistening with frost", {"pen": "penis", "cage": True}),
   "onani_boss": ("kairo", "kneeling alone in the frost corridor, one wet finger stroking his own nipple, the other hand pressing his own perineum, penis untouched, the ice empress stands far away beside an empty pedestal watching"),
   "inochi_boss": ("danro", "he is wrapped together with the ice empress in her white fur cape before the fireplace, she holds him on her lap and licks his nipple, his penis locked in a frosty chastity cage, orange firelight", {"cage": True}),
   "onedari_boss": ("mirror", "from side, he is on all fours facing the ice mirror, the ice empress kneels behind him penetrating his anus with her penis, anal, his penis locked in a chastity cage glistening with frost, a crown of frost flowers on his forehead", {"pen": "penis", "cage": True}),
 },
 "lose_desc": "keeps him in the ice castle forever, frost flowers blooming all over his skin.",
 "onanie": {
   "master": ("hall", "kneeling alone on the ice floor, sucking two of his own fingers deeply as if kissing, the other cold fingertip tracing his own nipple, white breath, penis untouched"),
   "e1": ("kamakura", "kneeling on the fur rug with his hips raised, reaching behind with a cold finger pushed into his own anus, counting on the fingers of the other hand, penis untouched"),
   "e2": ("himuro", "sitting on the fur-covered ice bench with his legs apart, one cold fingertip tracing thinly up his own perineum, the other hand gripping the bench, penis untouched"),
   "e3": ("rabbit", "lying face down in the soft snow hollow with his hips raised, reaching behind and stroking his own anus with a wet finger as if licking, penis untouched"),
   "boss": ("throne", "kneeling on the white fur before the silver throne, one wet finger stroking his own nipple, the other hand pressing his own perineum, penis untouched"),
 },
}
