# N60 恒星間航行船（Starship）場面データ。登場人物は全員20歳以上（女性＋ニューハーフ：艦長アストレア・リゲル）。冷凍睡眠は眠っているだけ、画面・計器に文字なし。
DATA = {
 "code": "Starship",
 "world": "interior of an interstellar starship, white and gold panels and screens without text, stars and nebula through the viewport, detailed background",
 "chars": {
   "m": {"type": "nh",
         "tags": "adult woman, mature female, mature face, sharp adult features, 37 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, silver hair, long hair, metallic sheen, gold eyes, white and gold captain uniform, long cape, large breasts",
         "name": "the silver-haired captain in a white and gold uniform and cape"},
   "e1": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 29 years old, adult proportions, beautiful detailed eyes, long legs, pink hair, bob cut, green eyes, white medical uniform, white gloves, large breasts",
          "name": "the pink-bob medical officer in a white medical uniform"},
   "e2": {"type": "nh",
          "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, orange hair, side ponytail, purple eyes, orange and white pilot suit, medium breasts",
          "name": "the orange-haired navigator in an orange and white pilot suit"},
   "e3": {"type": "woman",
          "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, long legs, light purple hair, long hair, glowing red eyes, android, white artificial skin with seam lines, white and silver bodysuit, thin mechanical arms from back, medium breasts",
          "name": "the light-purple-haired android in a white and silver bodysuit"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, long legs, black hair, long hair in high ponytail, gold eyes, black and gold military style uniform, black gloves, large breasts",
            "name": "the black-ponytailed first officer in a black and gold uniform"},
 },
 "places": {
   "observe":  "observation deck at the bow, huge window with slowly streaming stars, zero gravity, floating",
   "bridge":   "starship bridge, captain's chair, rows of consoles without text, large front window with blue warp light",
   "quarters": "captain's quarters, large bed with white sheets, desk with a holographic star chart without text, window with a nebula",
   "cabin":    "narrow passenger cabin, bed, tiny black camera lens on the ceiling, dim night light",
   "hangar":   "hangar with a white egg-shaped escape pod with a transparent lid, soft blue light inside",
   "medbay":   "white medical bay, examination chair with leg rests, medical probe machine arm, monitors without text",
   "navroom":  "round navigation room, blue star chart projected over the whole ceiling, lines of light between stars",
   "cockpit":  "pilot seat before a huge window full of stars, control stick and instruments without text",
   "maint":    "maintenance area, low ceiling with pipes, charging pedestals along the wall, cold metal",
   "cryo":     "cryosleep bay, rows of transparent-lid cryo pods glowing pale blue, control panel on the wall without text",
   "officer":  "first officer's room, plain desk, wall of control panels without text",
 },
 "atk": {
   "m1": ("observe", "zero gravity, he floats limp, the captain floats behind him wrapping him in her cape and arms, her fingers pinching both of his nipples, her breasts against his back, stars streaming outside"),
   "m2": ("bridge", "he sits in the captain's chair with his mouth open, the captain leans over him from behind with her lips at his ear giving orders, his back arching by itself, drool, no hands on him"),
   "m3": ("quarters", "from side, he lies on his back on the large bed holding his knees, the captain kneels between his legs penetrating his anus with her own penis, anal, kissing him deeply, tongues, his own penis separate", {"pen": "penis"}),
   "e1": ("medbay", "from side, he lies on the examination chair with his legs on the leg rests, a slim white vibrating medical probe from the machine arm inserted in his anus, the medical officer holds a tablet without text, her gloved hand on his lower belly", {"pen": "toy"}),
   "e2": ("navroom", "he lies on his back under the ceiling star chart, the navigator kneels beside him tracing lines between points of light on his chest with her fingertip, pressing his nipple like a star"),
   "e3": ("maint", "he sits on a charging pedestal with his chest out, the android stands behind him, her thin mechanical arms attaching transparent suction cups to both of his nipples, nipples sucked and stretched"),
   "boss": ("cryo", "he kneels on the floor with his hands on the edge of an open pod, pink rotors taped on both of his nipples, a vibrator inserted in his anus, the first officer stands beside him with one gloved hand on the control panel", {"pen": "toy"}),
 },
 "atk_desc": {
   "m1": "the captain holds him in zero gravity.",
   "m2": "the captain rewrites his common sense with orders.",
   "m3": "the captain kisses him and takes him in her quarters.",
   "e1": "the medical officer examines him with a probe.",
   "e2": "the navigator draws a star chart on his chest.",
   "e3": "the android sucks his nipples with her arms.",
   "boss": "the first officer shakes him with each warp jump.",
 },
 "lose": {
   # m1 無重力の抱擁
   "btl_m1": ("observe", "zero gravity, he floats limp in the captain's arms wrapped in her cape, his cheek on her breasts, her fingers twisting his nipple, cum floating in droplets, unfamiliar stars outside"),
   "onani_m1": ("cabin", "zero gravity, floating alone above the narrow bed hugging himself, one fingertip rubbing his own nipple, the other hand pinching his other nipple, penis untouched, the captain watches from the open door far away"),
   "inochi_m1": ("hangar", "zero gravity, he floats beside the open escape pod, the captain hugs him from behind with her palms over his chest and his nipples between her fingers, cum floating in droplets"),
   "onedari_m1": ("observe", "zero gravity, he floats with his arms reaching out begging, the captain hugs him tightly, his face in her breasts, her fingers pinching his nipples, a log screen without text"),
   # m2 艦長命令
   "btl_m2": ("bridge", "he sits in the captain's chair with his back arched and chest out, the captain leans over from behind with her lips at his ear, no hands on him, cum on his belly, blue warp light in the window"),
   "onani_m2": ("cabin", "kneeling alone upright on the narrow bed in seiza, mouthing orders to himself, back straight, hands far from his crotch, penis untouched, a tiny speaker by the pillow, the captain watches from the open door far away"),
   "inochi_m2": ("hangar", "he stands beside the open escape pod with his chest thrust out and legs apart, the captain stands behind him giving orders into his ear, no hands on him, cum dripping"),
   "onedari_m2": ("quarters", "he stands naked with his chest thrust out in front of the desk, the captain stands close whispering orders into his ear, no hands on him, knees buckling, cum on his thighs"),
   # m3 艦長室で（NH逆アナル＋キス）
   "btl_m3": ("quarters", "from side, he lies on his back on the large bed with legs lifted, the captain penetrates his anus with her own penis, anal, kissing him deeply, her silver hair falling around him, cum leaking, his own penis separate", {"pen": "penis"}),
   "onani_m3": ("cabin", "lying alone on his back on the narrow bed with his mouth open, one arm reaching down with two of his own fingers in his own anus, penis untouched, a camera lens on the ceiling, the captain watches from the open door far away"),
   "inochi_m3": ("quarters", "from side, he lies on his side on the large bed, the captain lies behind him penetrating his anus with her own penis, anal, turning his face to kiss him, her fingers on his nipple, white escape pod in the corner, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("quarters", "from side, he lies on his back on the large bed hugging the captain, the captain penetrates his anus with her own penis, anal, kissing him deeply, a log screen without text on the desk, his own penis separate", {"pen": "penis"}),
   # e1 診察プローブ
   "btl_e1": ("medbay", "from side, he lies on the examination chair with his legs spread on the leg rests, a white vibrating probe from the machine arm in his anus, the medical officer presses his lower belly with her gloved hand, cum on his belly", {"pen": "toy"}),
   "onani_e1": ("cabin", "lying alone on his side on the narrow bed with knees drawn up, one arm reaching behind with two of his own fingers in his own anus, tapping rhythmically, penis untouched, the medical officer watches from the open door far away"),
   "inochi_e1": ("hangar", "he lies inside the open escape pod with his legs spread, a white vibrating probe in his anus, pink rotors on his nipples, the medical officer stands at the pod holding a tablet without text", {"pen": "toy"}),
   "onedari_e1": ("medbay", "from side, he lies on his side on the examination chair hugging his knees, a white vibrating probe from the machine arm in his anus, the medical officer presses his lower belly with her gloved hand, cum on the chair", {"pen": "toy"}),
   # e2 星図をなぞる指
   "btl_e2": ("navroom", "he lies on his back on the floor under the ceiling star chart, the navigator kneels over him pinching and rolling both of his nipples, glowing star lines drawn on his chest, cum on his belly"),
   "onani_e2": ("cabin", "lying alone on the narrow bed with his pajama top rolled up, tracing lines between points on his own chest with a fingertip, the other hand rolling his own nipple, penis untouched, the navigator watches from the open door"),
   "inochi_e2": ("hangar", "he lies beside the navigator inside a two-person pod under a glowing star chart on the glass lid, the navigator presses and rolls his nipple with her fingertip, glowing lines on his chest"),
   "onedari_e2": ("cockpit", "he sits on the navigator's lap in the pilot seat, the navigator pinches both of his nipples from behind, two bright stars in the window, glowing star lines on his chest, cum on his thighs"),
   # e3 吸引アーム
   "btl_e3": ("maint", "he sits on a charging pedestal, the android's four thin mechanical arms surround his chest, two transparent suction cups pulling his nipples, two mechanical fingertips tapping around them, cum on his thighs"),
   "onani_e3": ("cabin", "sitting alone on the narrow bed with his pajama top open, pinching his own nipples and pulling them outward, penis untouched, the android watches from the open door far away"),
   "inochi_e3": ("maint", "he lies in an open white pod with cables, the android's thin mechanical arms reach in from the wall, transparent suction cups pulling both of his nipples, cum on his belly"),
   "onedari_e3": ("maint", "he stands in front of a charging pedestal with his shirt open and chest out begging, the android behind him with transparent suction cups on both of his nipples on thin mechanical arms, nipples stretched"),
   # boss ワープの衝撃（ローター＋アナルバイブ）→冷凍睡眠
   "btl_boss": ("cryo", "he lies peacefully asleep inside an open cryo pod glowing soft blue, faint marks of tape on his nipples, the first officer stands beside the pod touching the transparent lid with one gloved fingertip, calm sleeping face", {"flaccid": True}),
   "onani_boss": ("cabin", "lying alone on his side on the narrow bed, one trembling fingertip on his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched, the first officer watches from the open door far away"),
   "inochi_boss": ("cryo", "he lies in an open pod with the lid half closed, rotors taped on his nipples, a vibrator in his anus, the first officer leans over the pod with her hand on the control panel, cum on his belly", {"pen": "toy"}),
   "onedari_boss": ("officer", "he kneels on the floor in front of the desk with his chest out, rotors taped on both of his nipples, a vibrator in his anus, the first officer holds him up from behind with one arm, cum on the floor", {"pen": "toy"}),
 },
 "lose_desc": "lays him to sleep peacefully in a cryosleep pod on the endless voyage.",
 "onanie": {
   "master": ("observe", "zero gravity, floating and hugging himself, one wet fingertip rubbing his right nipple, the other hand pinching his left nipple, penis untouched"),
   "e1": ("medbay", "lying on his side on the examination chair with knees drawn up, one arm reaching behind with two of his own fingers in his own anus, penis untouched"),
   "e2": ("navroom", "lying on his back under the star chart, tracing lines on his own chest with a fingertip, the other hand rolling his own nipple, penis untouched"),
   "e3": ("maint", "sitting on a charging pedestal with his chest out, pinching both of his own nipples and pulling them outward, penis untouched"),
   "boss": ("cryo", "kneeling beside the pods, one trembling fingertip on his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched"),
 },
}
