# N55 深夜の撮影スタジオ（Studio）場面データ。登場人物は全員20歳以上。女性（ミカ・エマ・ロザリー）とニューハーフ（キリエ・アカリ）の混合。
DATA = {
 "code": "Studio",
 "world": "rental photo studio in the suburbs late at night, bright softbox lights, light stands, black cables on the floor, cameras on tripods, detailed background",
 "chars": {
   "m":    {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 35 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, black hair, long hair swept to one side, gold eyes, black shirt dress, long boots, camera hanging from neck, medium breasts",
            "name": "the black-haired photographer in a black shirt dress and long boots"},
   "e1":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 26 years old, adult proportions, beautiful detailed eyes, long legs, brown hair, layered bob, green eyes, white shirt, apron-style tool pouch, large breasts",
            "name": "the brown-bob stylist in a white shirt"},
   "e2":   {"type": "nh",
            "tags": "adult woman, mature female, mature face, sharp adult features, 24 years old, adult proportions, beautiful detailed eyes, tall, elegant, feminine body, long legs, orange hair, short bob, amber eyes, tank top, cargo skirt, work gloves, medium breasts",
            "name": "the orange-haired lighting technician in a tank top and work gloves"},
   "e3":   {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 25 years old, adult proportions, beautiful detailed eyes, long legs, blonde hair, long hair, red eyes, white bathrobe over a photo costume, long legs, large breasts",
            "name": "the blonde senior model in a white bathrobe"},
   "boss": {"type": "woman",
            "tags": "adult woman, mature female, mature face, sharp adult features, 44 years old, adult proportions, beautiful detailed eyes, long legs, red hair, short hair, purple eyes, black pant suit, sunglasses on head, large breasts",
            "name": "the red-haired editor in chief in a black pant suit"},
 },
 "places": {
   "white":    "white seamless backdrop paper under bright studio lights, tape cross mark on the floor, camera on a tripod",
   "stool":    "center of the studio, round stool under a softbox light, camera tripod, dim edges",
   "bedset":   "bedroom film set in the studio, white bed with crisp sheets, only walls, soft morning-like lighting, tripod camera with a red lamp",
   "makeup":   "makeup room, vanity mirror framed with light bulbs, photos clipped on the mirror frame without text, oil bottles and brushes, narrow massage bed",
   "reflector": "dark corner behind a large white reflector board, blanket on the floor, a thin line of light leaking from the board edge",
   "equip":    "narrow equipment room, folded reflector boards leaning on the wall, light stands, cables",
   "sofa":     "studio lounge with a sofa and a high stool on white backdrop paper, cameras around",
   "rest":     "models' waiting room, white fluffy rug on the floor, sofa, clothes rack",
   "props":    "dim prop room, old chairs and picture frames piled up, a single bare light bulb, dusty old couch",
   "editor":   "glass-walled editing room on the second floor, large desk with proof pages without text, leather armchair, glowing light table, night studio lights beyond the glass",
 },
 "atk": {
   "m1": ("white", "he stands on the tape mark before the white backdrop pinching his own nipples with his hands behind his head posing, the photographer bends to his ear whispering pose orders, her tongue at his ear, precum dripping"),
   "m2": ("stool", "he sits on the round stool with his chest out, the photographer aims the camera lens close at his nipple, flash light, his nipples erect, his hips twitching, cum on his thighs, no hands on him"),
   "m3": ("bedset", "from side, he lies on his back on the white bed with legs spread, the photographer on top of him penetrating his anus, anal, pinching both of his nipples, his own penis separate", {"pen": "penis"}),
   "e1": ("makeup", "he sits before the bulb-lit mirror with his chest glistening with oil, the stylist hugs him from behind rubbing oil onto his chest, her fingertips rolling his nipples, oil dripping down his belly"),
   "e2": ("reflector", "from side, he kneels on all fours on the blanket behind the reflector board, the lighting technician kneels behind him with two gloved fingers in his anus pressing his prostate, a line of light across his hips"),
   "e3": ("sofa", "he lies on his back on the white backdrop paper, the senior model sits on the sofa above him with crossed legs, rubbing his erection with the sole of her bare foot, her other foot resting on his cheek"),
   "boss": ("editor", "he sits in the leather armchair with legs spread, a purple vibrator inserted in his anus, the editor in chief stands beside him holding the remote control and a silver key, cool expression", {"pen": "toy", "cage": True}),
 },
 "atk_desc": {
   "m1": "the photographer whispers pose orders that his body obeys.",
   "m2": "the photographer makes him climax just by aiming her lens at him.",
   "m3": "the photographer pinches his nipples while penetrating him on the bed set.",
   "e1": "the stylist massages oil into his nipples.",
   "e2": "the lighting technician opens up his prostate in the shadow of the reflector.",
   "e3": "the senior model steps on him with her bare feet for the pose.",
   "boss": "the editor in chief seals him in a chastity cage with a vibrator inside.",
 },
 "lose": {
   # キリエ 技1 ポーズの指示
   "btl_m1": ("white", "he stands frozen on the tape mark before the white backdrop pinching his own nipples, the photographer bends to his ear licking inside it, cum splattered on the backdrop paper, his knees trembling"),
   "onani_m1": ("sofa", "sitting alone on the sofa with knees trembling, both hands gripping his own knees, head tilted back, mouth half open, lips counting, penis untouched, the photographer watches from the far doorway holding her camera"),
   "inochi_m1": ("white", "he squats with his knees wide apart on the white backdrop, frozen, pinching his own nipple, the photographer crouches behind him whispering into his ear, precum dripping onto the paper, a tripod camera in front"),
   "onedari_m1": ("white", "he stands with his hands clasped behind his head, the photographer behind him licking the rim of his ear, his chest pushed out, erect nipples, precum dripping, his knees trembling"),
   # 技2 レンズの視線
   "btl_m2": ("white", "from side, he is on all fours on the white backdrop with his hips lifted toward the camera, the photographer crouches behind him aiming the lens at his buttocks, flash, precum dripping, no hands on him"),
   "onani_m2": ("props", "sitting alone on the dusty couch under the bare bulb, hands clutching the couch edge, head tilted back, mouth open, hips twitching, penis untouched, the photographer watches from the far doorway aiming her camera"),
   "inochi_m2": ("stool", "he sits naked on a white chair holding a signed contract paper without text on his lap, the photographer aims the lens close at his chest, flash, his nipples erect, cum on his thighs, no hands on him"),
   "onedari_m2": ("stool", "he sits on the round stool staring into the camera lens held right in front of his face by the photographer, cum splashed on his belly, erect nipples, no hands on him"),
   # 技3 ベッドセットで
   "btl_m3": ("bedset", "from side, he lies on his back on the white bed with his shirt open and legs spread, the photographer on top of him penetrating his anus, anal, pinching both of his nipples, cum on his belly, his own penis separate", {"pen": "penis"}),
   "onani_m3": ("bedset", "lying alone on his side on the white bed, pinching his own nipple, the other arm reaching behind with two fingers in his own anus, penis untouched, the photographer watches from beside the tripod far away with arms folded"),
   "inochi_m3": ("bedset", "from side, he sits in the photographer's lap facing away on the white bed, the photographer leans on the headboard holding his knee up, penetrating his anus from below, anal, flicking his nipple, his own penis separate", {"pen": "penis"}),
   "onedari_m3": ("bedset", "from side, he lies face down on the white bed, the photographer lies on his back penetrating his anus from behind, anal, her hands under his chest pinching his nipples, her long black hair on his shoulders, his own penis separate", {"pen": "penis"}),
   # e1 ミカ オイルを塗る
   "btl_e1": ("makeup", "he sits in the chair before the bulb-lit mirror, the stylist leans over him from behind pouring oil on the middle of his chest, her fingertips rolling his oily nipples, oil running down to his belly"),
   "onani_e1": ("makeup", "sitting alone before the bulb-lit mirror, spreading oil over his own chest with both palms, rolling his own oily nipples with his fingertips, back arched, penis untouched, the stylist watches from the far doorway"),
   "inochi_e1": ("makeup", "he lies on his back on the narrow massage bed, the stylist lies on top of him hugging him, both of them glistening with oil, her chest pressed on his, kissing him deeply, tongues"),
   "onedari_e1": ("makeup", "he sits before the bulb-lit mirror, the stylist hugs him from behind and pulls his oily nipple with her fingertips while kissing him over his shoulder, oil trickling down his chest"),
   # e2 アカリ レフ板の陰で
   "btl_e2": ("reflector", "from side, he kneels on all fours on the blanket behind the reflector board, the lighting technician leans over his back with two gloved fingers in his anus, a line of white light across his hips, precum dripping"),
   "onani_e2": ("equip", "curled alone on the floor among folded reflector boards, one arm reaching behind with two fingers in his own anus, penis untouched, the lighting technician watches from the far doorway with a camera"),
   "inochi_e2": ("reflector", "he lies on his back on the blanket with his knees up, the lighting technician kneels between his legs with two fingers in his anus, her other palm pressing down on his lower belly"),
   "onedari_e2": ("reflector", "from side, he stands bent over gripping the leg of a reflector stand, the lighting technician behind him with two gloved fingers in his anus, pink rotors taped on his nipples, a line of light across his hips"),
   # e3 エマ 絡みのポーズ
   "btl_e3": ("sofa", "he lies on his back on the white backdrop paper, the senior model sits on the sofa above him with crossed legs, one bare sole rubbing his erection, the other foot pressing his cheek down, precum dripping"),
   "onani_e3": ("rest", "lying alone on his back on the white fluffy rug, both hands under his shirt pinching his own nipples, back arched, mouth open, penis untouched, the senior model watches from the far doorway in her bathrobe"),
   "inochi_e3": ("sofa", "he lies on his back on the white backdrop paper, the senior model sits on a high stool above him in black thigh-high stockings, both stockinged soles sandwiching his erection"),
   "onedari_e3": ("sofa", "he lies on his back on the floor under the senior model's legs, the senior model sits on the sofa pressing her heel down on the base of his erection, her toes pinching his nipple, red toenails"),
   # boss ロザリー 袋とじ
   "btl_boss": ("editor", "he sits in the leather armchair with his legs spread over the armrests, a purple vibrator buzzing in his anus, the editor in chief stands beside him writing in a notebook without text, a key in her breast pocket", {"pen": "toy", "cage": True}),
   "onani_boss": ("editor", "lying face down alone on the leather sofa, one arm reaching behind with two fingers in his own anus, the other hand pressing his own perineum below the cage, the editor in chief watches from the far glass door", {"cage": True}),
   "inochi_boss": ("editor", "from side, he stands with both palms and his forehead against the glass wall, the editor in chief stands behind him pushing a purple vibrator in and out of his anus with her gloved hand, a key clutched in his fist", {"pen": "toy", "cage": True}),
   "onedari_boss": ("editor", "from side, he kneels on all fours on the glowing light table, the editor in chief stands behind him thrusting a purple vibrator into his anus, a clear drop hanging from the cage, proof pages without text under his hands", {"pen": "toy", "cage": True}),
 },
 "lose_desc": "signs him as the studio's exclusive model forever.",
 "onanie": {
   "master": ("stool", "sitting on the round stool staring into a camera lens on a tripod, hands gripping his knees, head tilted, mouth open, hips twitching, penis untouched"),
   "e1": ("makeup", "sitting before the bulb-lit mirror, rubbing oil over his own chest, rolling his own oily nipples with his fingertips, penis untouched, lips parted, ragged breathing, knees shaking"),
   "e2": ("reflector", "kneeling on all fours on the blanket, one arm reaching behind with two fingers in his own anus, a line of light across his hips, penis untouched"),
   "e3": ("rest", "lying on his back on the white rug, both hands under his shirt pinching his own nipples, back arched, penis untouched, lips parted, ragged breathing, knees shaking"),
   "boss": ("editor", "kneeling on the leather armchair, one hand pressing his own perineum below the cage, the other arm reaching behind with two fingers in his own anus", {"cage": True}),
 },
}
